// Extension for Chrome Browser - Magic Actions for YouTube™ - CHROMEACTIONS.COM - Copyright 2013 Vlad and Serge Strukoff - All Rights Reserved
chrome.runtime.sendMessage("a",function(a){a&&a.ver&&(genID(),extURL=chrome.runtime.getURL(""),opt=a,applyTheme(),applyStyles(),opt.wide&&document.cookie&&(document.cookie="wide=1; max-age=22592000; path=/; domain=youtube.com"),fireEvent("fromMagic",{id:5,extURL:extURL,gid:ID[14]}),contentLoaded())});
var script=function(){function a(){if(window.sessionStorage&&window.sessionStorage.mafy){var a=parseInt(window.sessionStorage.mafy);g={};g.mwvc=a>>26&1;g.color="red LightPink orange lime GreenYellow yellow gold DodgerBlue aqua magenta DeepPink white".split(" ")[a>>22&15];g.mwvct=a>>21&1;g.mwvci=a>>19&3;g.gap=a>>14&31;g.hq=a>>13&1;g.hqi="highres hd1080 hd720 large medium small tiny".split(" ")[a>>10&7];g.pause=a>>9&1;g.plist=a>>8&1;g.buf=a>>7&1;g.buf1=a>>6&1;g.loop=a>>5&1;g.hide=a>>4&1;g.ha=a>>3&1;
g.anns=a>>2&1;g.pt=a>>1&1;g.pti=a&1;E=g.loop}}function b(){var b;b=new WebKitMutationObserver(function(c){for(var d=0,e=c.length;d<e;++d)for(var h=c[d],n=0,l=h.addedNodes.length;n<l;++n){var k=h.addedNodes[n];"video"==k.localName?z&&window.ytplayer&&g.pt&&!g.pti?(k.parentElement.removeChild(k),k=null,delete k,document.getElementById("player-api").innerHTML=""):b.disconnect():"embed"==k.localName&&"application/x-shockwave-flash"==k.type&&(g||a(),g&&(z&&window.ytplayer&&g.pt&&g.pti?setTimeout(function(){k.parentElement.removeChild(k);
k=null;delete k},0):(setTimeout(f,0,k),b.disconnect())))}});b.observe(document.documentElement,{childList:!0,subtree:!0})}function c(){var a=HTMLMediaElement.prototype.load;HTMLMediaElement.prototype.load=function(){(k=document.getElementById("movie_player")||document.querySelector(".html5-video-player"))&&s();a.apply(this,arguments);HTMLMediaElement.prototype.load=a};var b=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(){if(!g.pt||g.pti)d(this),b.apply(this,arguments),HTMLMediaElement.prototype.play=
b}}function d(a){k&&g.hq&&k.setPlaybackQuality(g.hqi);A&&setTimeout(function(){k.pauseVideo();A=!1},0);z&&(v&&(clearTimeout(v),v=0),v=setTimeout(x,3E3));a.addEventListener("ended",e);g.anns&&r&&setTimeout(function(){var a=document.querySelectorAll(".html5-video-controls .ytp-menu .ytp-button");if(a&&0<a.length)for(var b=0,K=a.length;b<K;b++)"OFF"===a[b].textContent&&a[b].click()},2E3)}function e(a){E&&k.playVideo()}function f(a){function b(){k.getPlayerState?(k.addEventListener("onStateChange","__670ps_"),
s(),z&&(v&&(clearTimeout(v),v=0),v=setTimeout(x,3E3))):setTimeout(b,50)}if(!(0>a.id.indexOf("player")))if(k=a,!z&&g.hide||g.ha||g.hq||g.anns||g.pause||g.buf){a.style.setProperty("visibility","hidden",q);a.style.setProperty("display","none",q);if(a.attributes&&a.attributes.flashvars){var c=t(a.attributes.flashvars.value);l(c);a.attributes.flashvars.value=p(c)}setTimeout(function(){a.removeAttribute("wmode");a.style.setProperty("display","block",q);a.style.setProperty("visibility","visible",q);b()},
0)}else b()}function l(a){H=a.list;g.ha&&(delete a.ad_module,delete a.ad2_module,delete a.ad3_module,delete a.ad_channel_code_instream,delete a.ad_channel_code_overlay,delete a.ad_device,delete a.ad_eurl,delete a.ad_flags,delete a.ad_host,delete a.ad_host_tier,delete a.ad_logging_flag,delete a.ad_preroll,delete a.ad_slots,delete a.ad_tag,delete a.ad_type,delete a.ad_video_pub_id,delete a.adsense_video_doc_id,delete a.aftv,delete a.afv,delete a.afv_ad_tag,delete a.afv_ad_tag_restricted_to_instream,
delete a.afv_inslate_ad_tag,delete a.afv_instream_max,delete a.afv_video_min_cpm,delete a.allowed_ads,delete a.as_launched_in_country,delete a.baseUrl,delete a.dynamic_allocation_ad_tag,delete a.max_dynamic_allocation_ad_tag_length,delete a.max_ad_duration,delete a.prefetch_ad_live_stream,delete a.use_meta_ad_player);g.hq&&(a.vq=g.hqi);g.hide&&(a.autohide=1);g.anns&&(a.iv_load_policy=3);g.buf?(a.autoplay=1,z&&delete a.dashmpd,a.tsp_buffer=569228273678,g.pause&&(A=!0)):g.pause&&(a.autoplay=0,r&&(a.is_html5_mobile_device=
!0));H&&g.plist&&(a.autoplay=1,A=!1,r&&(a.is_html5_mobile_device=!1))}function h(a){if(a.currentTarget==k.parentElement||a.currentTarget.top){var b;if("mousewheel"==a.type)b=k.getVolume(),b=0>a.wheelDelta?b-g.gap:b+g.gap;else if(3==a.which){b=k.getVolume();if(0<a.webkitMovementX)b+=g.gap;else if(0>a.webkitMovementX)b-=g.gap;else return!0;F=!0}else return!0;100<b?b=100:1>b&&(b=0);k.setVolume(b);if(g.mwvci){var c=document.getElementById("maVol5");c||(c=B());C!=g.mwvci&&(C=g.mwvci,n("onMagicVolume",
{id:C}));1==C?(c.style.setProperty("top",k.offsetTop+k.scrollHeight-120+"px",q),c.style.setProperty("left",k.offsetLeft+k.offsetWidth/2-100+"px",q),c.style.setProperty("width","236px",q),c.style.setProperty("height","18px",q)):2==C&&(c.style.setProperty("top",k.offsetTop+12+"px",q),c.style.setProperty("left",k.offsetLeft+18+"px",q),c.style.setProperty("width","96px",q),c.style.setProperty("height","48px",q));n("onMagicVolume",{vol:parseInt(b),color:g.color});D?(clearTimeout(D),D=0):c.style.setProperty("display",
"block",q);D=setTimeout(function(){c.style.setProperty("display","none",q);clearTimeout(D);D=0},700)}a.preventDefault();a.stopPropagation()}else return!0}function m(a){F&&(F=!1,a.stopPropagation(),a.preventDefault())}function s(){function a(b){k.parentElement[b]("mousemove",h,!1);document[b]("contextmenu",m,!1);if(r){var c=k.querySelector(".html5-video-container");if(c)c[b]("contextmenu",m,!1)}}a("removeEventListener");k.parentElement.removeEventListener("mousewheel",h,!1);g.mwvc&&(1==g.mwvct?a("addEventListener"):
k.parentElement.addEventListener("mousewheel",h,!1))}function B(){var a=document.createElement("iframe");a.id="maVol5";a.setAttribute("scrolling","no");a.setAttribute("frameborder",0);a.setAttribute("allowtransparency","true");a.style.setProperty("z-index",2147483648,q);a.style.setProperty("position","absolute",q);a.style.setProperty(" -webkit-user-select","none",q);a.style.setProperty("display","block",q);a.onload=function(){var a=this.contentDocument;a.open();a.write('<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><style type="text/css"> *{margin:0;padding:0;border:0;} body{font-family:Segoe UI,Helvetica,Arial,sans-serif}#txt{width:96px;height:48px;line-height:43px;font-size:48px;text-align:center;text-shadow:1px 1px 4px #000}#box{width:234px;height:16px;background-color:#000;border:solid 1px;cursor:default} #line{width:200px;height:16px;opacity:.75} #vol{width:34px;height:16px;position:absolute;top:0;right:2px;line-height:18px;font-size:14px;font-weight:700;text-align:center}</style><script type="text/javascript">window.parent.addEventListener("onMagicVolume",function(a){a=a.detail;var c=document.getElementById("box"),d=document.getElementById("vol"),e=document.getElementById("line"),b=document.getElementById("txt");1==a.id?(b.style.display="none",c.style.display="block"):2==a.id&&(c.style.display="none",b.style.display="block");b.textContent=d.textContent=a.vol;e.style.width=2*a.vol+"px";c.style.borderColor=e.style.backgroundColor=b.style.color=d.style.color=a.color},!1);document.addEventListener("contextmenu", function(e) { e.preventDefault(); }, !1);\x3c/script></head><body><div id="txt"></div><div id="box"><div id="line"></div><div id="vol"></div></div></body></html>');
a.close();n("onMagicVolume",{id:C})};k.parentElement.appendChild(a);return a}function y(a){a.stopPropagation();k.showVideoInfo&&(k.info?(k.info=0,k.hideVideoInfo()):(k.info=1,k.showVideoInfo()))}function x(){var a=document.getElementById(I);if(a&&(a.ev||(a.ev=1,a.addEventListener("click",y,!1)),k&&k.getVideoLoadedFraction)){var b=k.getVideoLoadedFraction(),b=0.99<b?100:parseInt(100*b);a.textContent=isNaN(b)?"":b+"%";100>b?v=setTimeout(x,3E3):g.buf&&g.buf1&&(new Audio(w+"notify.ogg")).play()}}function n(a,
b){var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!0,!0,b);window.dispatchEvent(c)}function t(a){a=a.split(/&|=/);for(var b={},c=a[0]?0:1,d=a.length;c<d;c+=2)b[a[c]]=a[c+1];return b}function p(a){var b="",c;for(c in a)b+=c+"="+a[c]+"&";return b}if(!location.pathname.match(/\/edit|\/editor|\/enhance|\/audio|\/my_videos_annotate|\/timedtext/)){var g,w,r,J,k,E,H,A,C,F,D,v,I,q="important",z="/watch"==location.pathname,G={},u;a();Object.defineProperties(window,{ytplayer:{get:function(){g&&
u&&u.config&&u.config.args?(J||(J=!0,r=u.config.html5,g.pt&&(g.pti&&!r?(r=u.config.html5=!0,delete u.config.args.ad_module,delete u.config.args.ad3_module):!g.pti&&r&&(r=u.config.html5=!1)),r&&c()),l(u.config.args)):a();return u},set:function(a){u=a}},ytspf:{get:function(){G.enabled=!1;return G},set:function(a){G=a}}});b();window.addEventListener("fromMagic",function(a){var b=a.detail;b&&5==b.id&&(b.upd?(g=b.opt,s(),E=g.loop):(w=a.detail.extURL,I=a.detail.gid))},!1);window.__670ps_=function(a){1==
a&&A?(A=!1,k.pauseVideo()):0==a&&E&&(k.seekTo(1),k.playVideo())}}},e_script=document.createElement("script");e_script.innerHTML="("+script.toString()+")();";document.documentElement.appendChild(e_script);document.documentElement.removeChild(e_script);var opt,extURL,html5,e_plr,movie_box1,movie_box2,e_zoom,tmZoom,tmZoomThread,cinema_visible,bExpanded,tmRatingsThread,impt="important",void_string="",filterID=0,ID;
chrome.runtime.onMessage.addListener(function(a,b,c){50==a.id&&(b=opt.align,opt=a.opt,applyTheme(),applyStyles(b!=opt.align),cinema_visible&&(a=e_plr.offsetWidth,a=opt.align?parseInt(($("page").offsetWidth-a)/2):parseInt((window.innerWidth-a)/2),movie_box1.style.setProperty("left",a+"px",impt)),(a=$(ID[0]))?a.style.setProperty("display",opt.a0&&opt.a4?"block":"none",impt):opt.a0&&opt.a4&&addThemeSwitch(),fireEvent("fromMagic",{id:5,upd:1,opt:opt}),postMessageToFrame({id:630,opt:opt}))});
function contentLoaded(){"complete"==document.readyState?onPageLoaded():setTimeout(contentLoaded,250)}function fireEvent(a,b){var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!0,!0,b);window.dispatchEvent(c)}function postMessageToFrame(a){var b=document.querySelector('iframe[src*="widget/render/comments"]');b&&b.contentWindow.postMessage(JSON.stringify(a),"*");return!1}
function applyTheme(){var a=document.getElementById(ID[3]);a||(a=document.createElement("link"),a.setAttribute("rel","stylesheet"),a.id=ID[3],document.documentElement.appendChild(a));a.setAttribute("href",extURL+"themes/"+(opt.ui?"night":"day")+"/theme.css?v=671")}function onThemeSwitch(a){opt.ui++;1<opt.ui&&(opt.ui=0);chrome.runtime.sendMessage('{"id":4,"name":"ui","value":'+opt.ui+"}")}
function addThemeSwitch(){if(!$(ID[0])){var a=document.createElement("div"),b=document.createElement("div");a.id=ID[0];a.appendChild(b);document.body.appendChild(a);a.addEventListener("click",onThemeSwitch,!1)}}
function applyStyles(a){var b=$(ID[1]),c=extURL+"themes/"+(opt.ui?"night/":"day/");if(b){var d=b.sheet.cssRules;d[1].style.setProperty("opacity",opt.ui,impt);d[2].style.setProperty("border-bottom","1px solid "+(opt.ui?"#2e2e2e":"#e6e6e6"),impt);d[2].style.setProperty("background",opt.ui?"#101010":"#f1f1f1",impt);for(b=0;9>b;++b)d[8+b].style.setProperty("background-image","url("+c+b+".png)",impt);d[17].style.setProperty("background-image","url("+c+"5a.png)",impt);d[18].style.setProperty("background-image",
"url("+c+"6a.png)",impt);d[19].style.setProperty("color",opt.ui?"#eee":"#111",impt);d[20].style.setProperty("display",opt.h0&&opt.h1?"none":"",impt);d[21].style.setProperty("display",opt.h0&&opt.h2?"none":"",impt);d[22].style.setProperty("display",opt.h0&&opt.h3?"none":"",impt);d[23].style.setProperty("display",opt.h0&&opt.h3?"none":"",impt);d[24].style.setProperty("display",opt.h0&&opt.h4?"none":"",impt);d[25].style.setProperty("display",opt.h0&&opt.h5?"none":"",impt);d[26].style.setProperty("display",
opt.h0&&opt.h6?"none":"",impt);d[27].style.setProperty("display",opt.hide?"bottom:0px":"",impt);d[28].style.setProperty("display",opt.hide?"none":"",impt);d[29].style.setProperty("display","block",impt);a&&(d[30].style.setProperty("text-align",opt.align?"center":"",impt),d[31].style.setProperty("display",opt.align?"inline-block":"",impt),d[31].style.setProperty("max-width",opt.align?"100%":"",impt),d[32].style.setProperty("max-width",opt.align?"1335px":"",impt),d[32].style.setProperty("margin",opt.align?
"auto":"",impt))}else{b=document.createElement("style");b.setAttribute("type","text/css");b.id=ID[1];document.head.appendChild(b);a=b.sheet;b="#"+ID[0];a.insertRule(b+"{display:block!important;position:absolute;z-index:2147483646;left:3px;top:7px;width:14px !important;height:34px;background:url('"+extURL+"i/sw.png');overflow:hidden}",0);a.insertRule(b+" div{opacity:"+opt.ui+";width:14px;height:34px;background:url('"+extURL+"i/sw.png') -14px 0;-webkit-transition:opacity .4s;transition:opacity .4s}",
1);b="#"+ID[2];a.insertRule(b+"{display:block!important;z-index:2147483648;margin-top:-33px;background:"+(opt.ui?"#101010":"#f1f1f1")+";position:relative;opacity:.8;width:638px;height:32px;border-bottom:1px solid "+(opt.ui?"#2e2e2e":"#e6e6e6")+";transition:opacity .3s}",2);a.insertRule("void_0{}",3);a.insertRule("#progress{display:none!important}",4);b="."+ID[4];a.insertRule(b+"{display:block!important;float:left;width:50px;height:32px;line-height:32px;background-repeat:no-repeat;background-position:50% 50%;cursor:pointer;-webkit-user-select:none;transition:.3s}",
5);a.insertRule(b+":hover{box-shadow:inset 0 1px 0 rgba(255,255,255,.2),inset 0 -5px 20px rgba(255,0,0,.2),inset 0 0 0 1px rgba(120,33,33,.2);transition:0s}",6);a.insertRule("#"+ID[15]+"{position:absolute;right:0;top:5px;height:20px;width:90px;overflow:hidden}",7);for(b=0;9>b;++b)a.insertRule("#"+ID[5+b]+"{background-image:url("+c+b+".png)}",8+b);a.insertRule("#"+ID[10]+"[on]{background-image:url("+c+"5a.png)}",17);a.insertRule("#"+ID[11]+"[on]{background-image:url("+c+"6a.png)}",18);a.insertRule("#"+
ID[14]+"{font-weight:bold;margin-left:7px;padding:0 4px;width:auto;color:#"+(opt.ui?"eee":"111")+"cursor:pointer}",19);a.insertRule("#yt-masthead-container{"+(opt.h0&&opt.h1?"display:none!important}":"}"),20);a.insertRule("#watch7-sidebar{"+(opt.h0&&opt.h2?"display:none!important}":"}"),21);a.insertRule("#watch7-secondary-actions{"+(opt.h0&&opt.h3?"display:none!important}":"}"),22);a.insertRule("#watch7-action-panels{"+(opt.h0&&opt.h3?"display:none!important}":"}"),23);a.insertRule("#watch-discussion{"+
(opt.h0&&opt.h4?"display:none!important}":"}"),24);a.insertRule("#guide{"+(opt.h0&&opt.h5?"display:none!important}":"}"),25);a.insertRule("#footer-container{"+(opt.h0&&opt.h6?"display:none!important}":"}"),26);a.insertRule(".html5-video-container{"+(opt.hide?"bottom:0px!important}":"}"),27);a.insertRule(".html5-video-controls{"+(opt.hide?"display:none!important}":"}"),28);a.insertRule("#movie_player:hover .html5-video-controls{display:block!important}",29);a.insertRule("html{"+(opt.align?"text-align:center!important}":
"}"),30);a.insertRule("body{"+(opt.align?"display:inline-block!important;max-width:100%!important}":"}"),31);a.insertRule("#masthead-expanded, #masthead-expanded-container{"+(opt.align?"max-width:1335px!important;margin:auto!important}":"}"),32)}}
function onPageLoaded(){if("/watch"==location.pathname){if(opt.h0&&opt.h4){var a=$("watch-discussion");a&&(a.parentElement.removeChild(a),delete null)}opt.pt?setTimeout(initWatchPage,1E3):initWatchPage(0)}ratingsProc();zoomProc();opt.a0&&opt.a4&&addThemeSwitch();chrome.runtime.sendMessage('{"id":1}')}
function initWatchPage(a){(e_plr=$("movie_player"))&&e_plr.parentElement?(html5="div"===e_plr.localName?1:0,movie_box1=e_plr.parentElement,movie_box2=e_plr.parentElement.parentElement,opt.hide&&(movie_box1.classList.add("magic-autohide"),(a=$("watch7-playlist-tray-container"))&&a.classList.add("magic-autohide2")),movie_box1.style.setProperty("box-shadow","none",impt),addYtBtns(),opt.cin&&(opt.cina&&showCinema(),movie_box2.addEventListener("click",function(a){a.target==movie_box2&&(a.stopPropagation(),
cinema_visible=!1,showCinema(a))},!1)),setTimeout(disablePlaylistAutoplay,1E3,1)):10>a&&setTimeout(initWatchPage,1E3,a+1)}function isPlaylist(){return"/watch"==location.pathname&&$("watch7-playlist-bar-autoplay-button")?!0:!1}function onBtnPlaylistAutoplay(a){this.getAttribute("data-ma")?this.removeAttribute("data-ma"):opt.loop&&(opt.loop=!1,(a=$(ID[10]))&&a.removeAttribute("on"),fireEvent("fromMagic",{id:5,opt:opt}))}
function disablePlaylistAutoplay(a){if(opt.loop){var b=$("watch7-playlist-bar-autoplay-button");b&&(b.classList.contains("yt-uix-button-toggled")&&(b.setAttribute("data-ma",!0),b.click()),a&&b.addEventListener("click",onBtnPlaylistAutoplay,!1))}}function showPlaylistBar(a){var b=a?void_string:"none";if(a=e_plr.parentElement)a=a.firstElementChild;a&&a!=e_plr&&a.style.setProperty("display",b,impt);(a=$("watch-video-extra"))&&a.style.setProperty("display",b,impt)}
function loadCinemaColors(a){req("GET",extURL+"colors.json?v="+(new Date).getTime(),null,"responseText",function(b){a.colors=b;a.custom=opt.cins;setCinemaColor(0,opt.cinc)})}function scrollColorsBox(a){a.preventDefault();a.stopPropagation();a=$(ID[24]);var b=a.offsetLeft;visible_width=a.parentElement.offsetWidth;step=this.left?visible_width-36:-visible_width-36;max=a.scrollWidth-visible_width;b-=step;b<-max&&(b=-max);0<b&&(b=0);a.style.setProperty("margin-left",b+"px",impt)}
function setCinemaColor(a,b){a&&a.stopPropagation();var c=$(ID[21]);if(c)if(99==b)c.style.setProperty("background",c.custom,impt),c.ind=99;else{var d=a?parseInt(this.ind):b,e=c.colors;try{e=JSON.parse(e)}catch(f){return}d>=e.items.length&&(d=0);c.ind=d;ss(c,e.items[d].cinema,1);ss(movie_box1,e.items[d].movie,1)}}
function showCustomColors(a){a.stopPropagation();a=$(ID[21]);var b=$(ID[25]);a.custom=a.custom?a.custom:"linear-gradient(skyblue,yellow)";a.ind=99;b.style.setProperty("display","block",impt);b.firstElementChild.value=a.custom;movie_box1.style.setProperty("box-shadow","none",impt);a.style.setProperty("background",a.custom,impt)}
function setCustomColor(a){a.stopPropagation();a=$(ID[21]);var b=a.style.getPropertyValue("background"),c;a.style.setProperty("background",this.value,impt);c=a.style.getPropertyValue("background");b!=c&&(a.custom=c)}
function showCinemaColors(a){a.preventDefault();a.stopPropagation();a=$(ID[21]);var b=$(ID[22]);if(b)0<b.offsetHeight?($(ID[25]).style.setProperty("display","none",impt),b.style.setProperty("display","none",impt),99==a.ind&&chrome.runtime.sendMessage(JSON.stringify({id:4,name:"cins",value:a.custom})),chrome.runtime.sendMessage(JSON.stringify({id:4,name:"cinc",value:parseInt(a.ind)}))):b.style.setProperty("display","block",impt);else{var c=a.colors;try{c=JSON.parse(c)}catch(d){return}b=document.createElement("div");
b.id=ID[22];ss(b,["position","absolute","top",0,"left",0,"width","100%","height","36px","line-height","36px","overflow","hidden"],1);b.addEventListener("click",function(a){a.preventDefault();a.stopPropagation()},!1);var e,f,l,h;e=document.createElement("button");e.textContent="MAGIC";ss(e,["position","absolute","top",0,"left",0,"width","95px","height","36px","background","red","color","#eee","padding","0 7px"],1);b.appendChild(e);e=document.createElement("button");e.title="Set your own CSS background";
ss(e,["position","absolute","top",0,"left","95px","width","36px","height","36px","background","#CCC url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAadEVYdFNvZnR3YXJlAFBhaW50Lk5FVCB2My41LjEwMPRyoQAAAEVJREFUOE9jAIL/FGKG/5KK/7FiBwcHsKL/2i+x4lEDqGkAhZgBbBM2DFOETQ6E4QYw/JfFimGK/t/FjkcNoKoBZGOG/wBEVfKgWsYg4QAAAABJRU5ErkJggg==) center center no-repeat"],1);b.appendChild(e);e.addEventListener("click",showCustomColors,
!1);e=document.createElement("div");e.id=ID[23];ss(e,["display","block","position","absolute","top",0,"left","131px","right","72px"],1);b.appendChild(e);f=document.createElement("button");f.textContent="<";f.left=1;ss(f,["position","absolute","top",0,"left",0,"width","36px","height","36px","background","#333","color","#eee"],1);e.appendChild(f);f.addEventListener("click",scrollColorsBox,!1);f=document.createElement("div");ss(f,["position","absolute","top",0,"left","36px","right","36px","height","36px",
"background","gray","overflow","hidden"],1);e.appendChild(f);l=document.createElement("div");l.id=ID[24];ss(l,["width",36*c.items.length+"px","transition","margin-left .3s"],1);f.appendChild(l);for(var m=0,s=c.items.length;m<s;m++)h=c.items[m],f=document.createElement("button"),f.title=m+1+". "+h.title,f.ind=m,ss(f,h.preview,1),ss(f,"float left width 30px height 30px margin 3px border-radius 2px".split(" "),1),l.appendChild(f),f.addEventListener("click",setCinemaColor,!1);f=document.createElement("button");
f.textContent=">";ss(f,["position","absolute","top",0,"right",0,"width","36px","height","36px","background","#333","color","#eee"],1);e.appendChild(f);f.addEventListener("click",scrollColorsBox,!1);e=document.createElement("div");e.id=ID[25];ss(e,["display","none","position","absolute","top",0,"left","95px","right","72px","height","36px","background","#777"],1);b.appendChild(e);f=document.createElement("input");f.type="text";ss(f,"position;absolute;top;4px;left;12px;right;12px;height;24px;padding;0 12px;font;16px Segoe UI,Frutiger,Tahoma,Helvetica,Helvetica Neue,Arial,sans-serif".split(";"),
1);e.appendChild(f);f.addEventListener("keyup",setCustomColor,!1);f.addEventListener("paste",setCustomColor,!1);f.addEventListener("cut",setCustomColor,!1);e=document.createElement("button");e.textContent="OK";ss(e,["position","absolute","top",0,"right",0,"width","72px","height","36px","background","red","color","#eee"],1);b.appendChild(e);e.addEventListener("click",showCinemaColors,!1);a.appendChild(b)}}
function addCinemaBtn(a,b){var c=document.createElement("a"),d=$(ID[16]);d&&(setAttrs(c,["href",a,"target","_blank","role","button","aria-pressed","false"]),ss(c,"display inline-block width 48px height 32px".split(" "),1),c.addEventListener("click",b?b:stopPropagation,!1),d.appendChild(c))}function onFullScreen(a){a.stopPropagation();a.preventDefault();opt.cinf&&!document.webkitIsFullScreen&&(document.removeEventListener("webkitfullscreenchange",onFullScreen,!1),hideCinema())}
function hideCinema(){if(!html5&&opt.cinf&&document.webkitIsFullScreen)document.webkitCancelFullScreen();else{var a,b=$(ID[21]);window.scrollTo(0,0);showPlaylistBar(1);(a=$(ID[25]))&&a.style.setProperty("display","none",impt);(a=$(ID[22]))&&a.style.setProperty("display","none",impt);ss(movie_box1,["z-index",void_string,"position",void_string,"left",void_string,"top",void_string,"height",void_string,"width",void_string],1);movie_box1.style.setProperty("box-shadow","none",impt);movie_box2.style.setProperty("height",
void_string);movie_box2.style.setProperty("padding-left",void_string);if(a=$("page-container")){a.style.setProperty("z-index",void_string);do(a=a.previousElementSibling)&&a.style.setProperty("display",void_string);while(a)}setStyle(["alerts","gb","guide","yt-hitchhiker-feedback","yt-uix-clickcard-card1","player-branded-banner","watch7-creator-bar",ID[0]],"display",void_string);(a=$("watch7-sidebar"))&&a.style.setProperty("margin-top",void_string);b.style.setProperty("display","none",impt);cinema_visible=
!1}}
function showCinema(a){a&&(a.preventDefault(),a.stopPropagation());if(!bExpanded)if(cinema_visible)hideCinema();else{showPlaylistBar(0);window.scrollTo(0,0);var b,c;e_plr.style.setProperty("box-shadow","none",impt);setStyle(["alerts","gb","guide","yt-hitchhiker-feedback","yt-uix-clickcard-card1","watch7-creator-bar",ID[0]],"display","none");if(c=$("page-container")){c.style.setProperty("z-index","auto",impt);do(c=c.previousElementSibling)&&c.style.setProperty("display","none",impt);while(c)}(c=$("watch7-sidebar"))&&
c.style.setProperty("margin-top",0,impt);resizePlayer(a);(b=$(ID[21]))?setCinemaColor(0,opt.cinc):(b=document.createElement("div"),b.id=ID[21],ss(b,["z-index",2147483648,"position","absolute","top",0,"left",0,"right",0,"bottom",0],1),document.body.insertBefore(b,document.body.firstElementChild),loadCinemaColors(b),b.addEventListener("click",hideCinema,!1),$(ID[16])||(c=document.createElement("div"),c.id=ID[16],ss(c,["position","absolute","top","4px","right","8px","background-image","url("+extURL+
"i/btns.png)","width","192px","height","32px","overflow","hidden"],1),b.appendChild(c),addCinemaBtn("http://www.chromeactions.com/"),addCinemaBtn("http://www.chromeactions.com/magic-actions-for-youtube-chrome-app.html"),addCinemaBtn("#",onCapture),addCinemaBtn("#",showCinemaColors)));b.style.setProperty("display","block",impt);opt.cinf&&a&&!html5&&document.documentElement.webkitRequestFullScreen&&(document.documentElement.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT),document.addEventListener("webkitfullscreenchange",
onFullScreen,!1));cinema_visible=!0}}
function resizePlayer(){var a,b,c,d,e;c=opt.cini;c=1==c?0.3:0==c?0.4:0.2;!html5&&opt.cinf?(a=screen.width-20,b=screen.height):(a=window.innerWidth-20,b=window.innerHeight);a>b?(d=b-parseInt(b*c),c=parseInt(1920*d/1080)):(c=a-parseInt(a*(c-0.1)),d=parseInt(1080*c/1920));opt.hide||(d+=30);e=parseInt((b-d)/2);50>e&&(e=50);ss($("page"),["-webkit-transition","none","transition","none"],1);ss(movie_box2,["-webkit-transition","none","transition","none","height",b+"px","padding-left",0],1);ss(movie_box1,
["top",e+"px","width",c+"px","height",d+"px","z-index",2147483648,"position","absolute"],1);a=opt.align?parseInt(($("page").offsetWidth-c)/2)+"px":parseInt((a-c)/2)+"px";movie_box1.style.setProperty("left",a);html5&&resizePlayer5()}
function resizePlayer5(){var a=document.querySelector(".html5-video-content");a&&(a.style.setProperty("width","100%",impt),a.style.setProperty("height","100%",impt));if(a=e_plr.querySelector("video"))a.style.setProperty("width","100%",impt),a.style.setProperty("height","100%",impt)}
function expandPlayer(a){a.stopPropagation();var b,c,d,e,f,l,h=$(ID[20]);h||(h=document.createElement("iframe"),setAttrs(h,["id",ID[20],"scrolling","no","frameborder",0]),ss(h,["display","block","z-index",2147483648,"bottom","17px","right","10px","width","22px","height","17px","position","fixed","background","url("+extURL+"i/col.png)"],1),document.body.appendChild(h),h.contentWindow.addEventListener("click",expandPlayer,!1));bExpanded?(l=e=f=d=a=b=c=pos=void_string,h.style.setProperty("display","none",
impt),bExpanded=!1):(a.preventDefault(),cinema_visible&&hideCinema(),window.scrollTo(0,0),a=window.innerWidth+"px",b=document.body.offsetHeight+26+"px",f=e=0,d=2147483648,pos="fixed",c="none",l="hidden",h.style.setProperty("display","block",impt),bExpanded=!0);setStyle(["footer","yt-hitchhiker-feedback","watch7-main-container","masthead-positioner"],"display",c,bExpanded);ss(movie_box1,["left",e,"top",f,"z-index",d,"position",pos,"width",a,"height",b],bExpanded);document.body.style.setProperty("overflow",
l);showPlaylistBar(!bExpanded);html5&&resizePlayer5()}function onBtnLoop(a){a.preventDefault();a.stopPropagation();opt.loop=!opt.loop;opt.loop?this.setAttribute("on",void_string):this.removeAttribute("on");disablePlaylistAutoplay();fireEvent("fromMagic",{id:5,upd:1,opt:opt})}function onBtnShowOpt(a){a.stopPropagation();chrome.runtime.sendMessage('{"id":7}')}
function onFilter(a){a.preventDefault();a.stopPropagation();a=html5?document.getElementsByTagName("video")[0]:e_plr;var b=";contrast(125%) brightness(125%);grayscale(20%) contrast(150%) brightness(150%);grayscale(1);sepia(1);invert(1);rotateY(180deg);rotateX(180deg)".split(";");filterID++;7<filterID&&(filterID=0);5<filterID?(a.style.setProperty("-webkit-filter","",impt),a.style.setProperty("-webkit-transform",b[filterID],impt)):(a.style.setProperty("-webkit-transform","",impt),a.style.setProperty("-webkit-filter",
b[filterID],impt));this.title="Apply Filter;High Contrast;S-High Contrast;Grayscale;Sepia;Invert;H-Flip;V-Flip".split(";")[filterID]}function getVideoId(){var a=document.body.querySelector('meta[itemprop="videoId"]');return a?a.getAttribute("content"):0}
function onCapture(a){a.preventDefault();a.stopPropagation();var b=$XY(e_plr);a=window.devicePixelRatio;var c=b[0]*a-window.pageXOffset,b=b[1]*a-window.pageYOffset,d=e_plr.scrollWidth*a,e=e_plr.scrollHeight*a,f=document.documentElement.offsetWidth*a,l=getVideoId(),h,m=$("eow-reuse");m&&(h=m.textContent);e-=40*a;0>b&&(e+=b,b=0);0>c&&(d+=c,c=0);c+d>f&&(d=f-c);chrome.runtime.sendMessage(JSON.stringify({id:6,v:[c,b,d,e,l,h,encodeURIComponent(document.title)]}))}
function share(a){a.stopPropagation();a.preventDefault();var b;a=this.maSh;1==a?b="https://chrome.google.com/webstore/detail/abjcfabbhafbcdfjoecdgepllmpfceif/reviews":2==a&&(b="http://youtube.com/subscription_center?add_user=StrukoffBrothers");chrome.runtime.sendMessage('{"id":2,"url":"'+b+'"}')}
function addYtBtns(){var a=$(ID[2]);if(!a){var b=$("watch7-main"),c=isPepper();if(b){a=document.createElement("div");a.id=ID[2];addYtBtn(a,ID[5],ID[4],0,0,0,0,"http://www.chromeactions.com/");addYtBtn(a,ID[6],ID[4],0,share,2);addYtBtn(a,ID[7],ID[4],"c2",onBtnShowOpt);opt.cin&&addYtBtn(a,ID[8],ID[4],"c0",showCinema);addYtBtn(a,ID[9],ID[4],"c1",expandPlayer);addYtBtn(a,ID[10],ID[4],"c5",onBtnLoop,0,opt.loop?"on":0);if(html5||c)addYtBtn(a,ID[12],ID[4],"c14",onCapture),opt.f0&&addYtBtn(a,ID[13],ID[4],
"c16",onFilter);addYtBtn(a,ID[14],ID[4],"c11");b.style.setProperty("padding-top","33px",impt);b.insertBefore(a,b.firstElementChild)}}}function addYtBtn(a,b,c,d,e,f,l,h){var m=document.createElement(h?"a":"div");m.id=b;c&&(m.className=c);d&&(m.title=chrome.i18n.getMessage(d));l&&m.setAttribute(l,void_string);f&&(m.maSh=f);a.appendChild(m);h?(m.href=h,m.target="_blank"):e&&m.addEventListener("click",e,!1)}
function zoomProc(){tmZoomThread&&(clearTimeout(tmZoomThread),tmZoomThread=0);(function b(){if(opt&&opt.a0&&opt.a2){for(var c=document.images,d,e=0,f=c.length;e<f;e++)d=c[e],d.prc||(d.prc=1,d.addEventListener("mouseover",onImgOver,!1),d.addEventListener("mouseout",onImgOut,!1));tmZoomThread=setTimeout(b,1E4)}else tmZoomThread=setTimeout(b,15E3)})()}
function zoomImg(a,b,c,d,e,f,l){var h,m;e_zoom?(h=e_zoom.firstElementChild,m=e_zoom.lastElementChild,f&&h.style.setProperty("top",f,impt)):(e_zoom=document.createElement("div"),h=document.createElement("div"),m=document.createElement("iframe"),e_zoom.className="magic-tip",setAttrs(m,["scrolling","no","frameborder",0]),e_zoom.appendChild(h),e_zoom.appendChild(m),document.body.appendChild(e_zoom));ss(e_zoom,["top",b+"px","left",a+"px","height",d+"px"],1);ss(m,["width",c+"px","height",d+"px","background",
l,"display","block"],1);e?(h.style.setProperty("display",void_string),h.className=e):h.style.setProperty("display","none",impt);e_zoom.style.setProperty("display","block",impt)}
function onImgOver(a){tmZoom&&(clearTimeout(tmZoom),tmZoom=0);var b=this,c=$XY(b),d=c[0],e=c[1],f=this.offsetWidth,l=this.offsetHeight;tmZoom=setTimeout(function(){var a="center",c,s,B=256,y=256,x,n,t=window.scrollY,p=b.getAttribute("data-thumb");p||(p=b.src);p=p.split("/");if(-1<p[5].indexOf("default."))p[5]="hq"+p[5].match(/default\.jpg|default\.webp/),B=480,y=270,a="-45px";else if("i"==p[3])p[5]="hq1.jpg";else if(9==p.length)p[7]="s200-c-k";else return;f==l&&(y=B=256,a="center");d<window.innerWidth/
2?(c=d+f+32,x="magic-tip-left"):(c=d-B-32,x="magic-tip-right");s=e-parseInt((y-l)/2)-5;n=parseInt(y/2);s<t&&(n-=t-s,s=t);0>n&&(n=5);p=p.join("/");zoomImg(c,s,B,y,x,n+"px","url("+p+") center "+a+"/100% auto no-repeat")},500);a.stopPropagation()}function onImgOut(a){tmZoom&&(clearTimeout(tmZoom),tmZoom=0);e_zoom&&e_zoom.style.setProperty("display","none",impt)}
function ratingsProc(){tmRatingsThread&&(clearTimeout(tmRatingsThread),tmRatingsThread=0);(function b(){if(opt&&opt.a0&&opt.a1){for(var c=document.getElementsByClassName("yt-thumb-default"),d,e,f=[],l,h=0,m=c.length;h<m;h++)d=c[h],l=0,100>d.offsetWidth&&(d.prc=2),d.prc||(e=d.getElementsByTagName("img"),0<e.length&&(e=e[0],l=e.getAttribute("data-thumb"),l||(l=e.src),l=l.split("/")[4],d.prc=1)),f.push(l);reqYTData(f,"videos",0,function(e){if(e)for(var h=0,l=f.length,m=0;h<l;h++){d=c[h];if(1==d.prc&&
f[h]){var n=e[m],t=d.parentElement,p=n.status&&n.status.code;e_div=document.createElement("div");e_div.className="magic-ratings";if("200"==p)if(n.accessControl3&&"allowed"==n.accessControl3.permission){e_div.style.setProperty("background-color","#CCC",impt);var p=n.rating&&n.rating.average||0,g=n.rating1&&n.rating1.numLikes||0,w=n.rating&&n.rating.numRaters||0,n=n.comments&&n.comments.feedLink&&n.comments.feedLink.countHint||0,r=document.createElement("div");r.className="magic-likes";p?(g=g?(100*
g/w).toFixed(1):0,r.style.setProperty("width",g*d.offsetWidth/100+"px",impt),t.title=(g?g+"% of likes from "+w+" votes":void_string)+(p?"\n"+parseFloat(p).toFixed(4)+" points out of 5":void_string)+(n?"\n"+n+" comments":void_string)):(r.style.setProperty("width",d.offsetWidth/2+"px",impt),t.title="Likes: 0\nDislikes: 0");e_div.appendChild(r)}else e_div.style.setProperty("background-color","#FFCCCC",impt),t.title="Rating is not allowed for this video";else e_div.style.setProperty("background-color",
"#D42",impt),w=n.status&&n.status.reason,t.title="Could't retrieve ratings info. YouTube server response: "+(p?p:"---")+" "+(w?w:" unknown");t.appendChild(e_div);m++}d.prc=2}tmRatingsThread=setTimeout(b,12E3)})}else tmRatingsThread=setTimeout(b,15E3)})()}
function reqYTData(a,b,c,d){function e(a,b){for(var c,d,f,h=0,l=a.childNodes.length;h<l;h++)if(c=a.childNodes[h],3==c.nodeType)b.t=c.textContent;else if(1==c.nodeType){d=c.localName;if(b[d]){for(f=1;b[d+f];)f++;d+=f}b[d]={};if(c.attributes)for(var g=0,m=c.attributes.length;g<m;g++)f=c.attributes[g],b[d][f.localName]=f.nodeValue;c.childNodes&&e(c,b[d])}}b="//gdata.youtube.com/feeds/api/"+b+"/";for(var f='<feed xmlns="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/" xmlns:batch="http://schemas.google.com/gdata/batch" xmlns:yt="http://gdata.youtube.com/schemas/2007"><batch:operation type="query"/>',
l=0,h=0,m=a.length;h<m;++h)a[h]&&(f+="<entry><id>"+b+a[h]+"</id></entry>",l++);1>l?d(0):(b+="batch?v=2",c&&(b+="&fields="+c),req("POST",b,f+"</feed>","responseXML",function(a){var b=[];if(a){a=a.getElementsByTagName("entry");for(var c=0,f=a.length;c<f;c++)item={},b.push(item),e(a[c],item);d(b)}else d(0)}))}function req(a,b,c,d,e){var f=new XMLHttpRequest;f.onload=function(a){200==this.status?e(this[d]):e()};f.onerror=e;f.onabort=e;f.open(a,b,!0);f.send(c)}
function isPepper(){var a=navigator.mimeTypes["application/x-shockwave-flash"];a&&(a=a?a.enabledPlugin.filename:null);return"pepflashplayer.dll"==a||"PepperFlashPlayer.plugin"==a||"libpepflashplayer.so"==a}function genID(){ID=[];rg=new Uint16Array(32);i=0;for(crypto.getRandomValues(rg);32>i;++i)ID.push("watch7-"+rg[i])}function stopPropagation(a){a.stopPropagation()}function $(a){return document.getElementById(a)}
function $XY(a){if(!a||void 0==a)return[0,0];var b=0,c=0;if(a.offsetParent){do b+=a.offsetLeft,c+=a.offsetTop;while(a=a.offsetParent)}return[b,c]}function setAttrs(a,b){for(var c=0,d=b.length;c<d;c+=2)a.setAttribute(b[c],b[c+1])}function ss(a,b,c){if(a){var d=0,e=b.length;for(c=c?impt:null;d<e;d+=2)a.style.setProperty(b[d],b[d+1],c)}}function setStyle(a,b,c,d){for(var e,f=0,l=a.length;f<l;f++)(e=$(a[f]))&&e.style.setProperty(b,c,d?impt:void_string)};
