/* Copyright 2011 Google Inc. All Rights Reserved. */ (function(){var f="\" ' ( ) , - . / 1 2 : ? a about and are as be but com for from have i in is it like may more my next not of on search that the this to was when with you your".split(" "),m=!1,p={},q={},r=0,s=-1,v=-1,w=function(a){a=a.replace(/<[^>]*>/g,"");return a=a.replace(/[<>]/g,"")},x=function(a){a=w(a);return a=a.substring(0,100).toLowerCase()},y=function(a){for(var c=0,b=f.length;c<b;c++)if(a==f[c])return!0;return!1},z=function(a,c,b){"initialize"==a.type&&b({instanceId:r++})},A=function(a,c,b){"options"==
a.type&&b({options:p})},E=function(a,c,b){if("fetch_raw"!=a.type&&"fetch_html"!=a.type)return!1;_gaq&&_gaq.push(["_trackEvent","lookup",a.type]);-1!=s&&v!=a.instanceId&&chrome.tabs.sendMessage(s,{type:"hide",instanceId:v});"fetch_raw"==a.type?(s=c.tab.id,v=a.instanceId):v=s=-1;var e=x(a.query);if(!m)return b({eventKey:a.eventKey,sanitizedQuery:e}),!1;var d={request:a,sanitizedQuery:e,dictRes:null,enDictRes:null,tranRes:null,tabLangTranRes:null,tabLangTranReqTimedOut:!1,tabLang:null,numResponses:0,
callback:b,incognito:!1};B(e,p.language,function(a){d.dictRes=a;C(d)});"en"!=p.language?B(e,"en",function(a){d.enDictRes=a;C(d)}):C(d);D(e,"auto",function(a){d.tranRes=a;C(d)});chrome.tabs.getSelected(null,function(a){d.incognito=a.incognito;var b=window.setTimeout(function(){console.assert(null==d.tabLangTranRes);d.tabLangTranReqTimedOut=!0;C(d)},800);chrome.tabs.detectLanguage(a.id,function(a){d.tabLangTranReqTimedOut||(window.clearTimeout(b),"und"!=a?(d.tabLang="he"==a?"iw":a,D(e,d.tabLang,function(a){d.tabLangTranRes=
a;C(d)})):C(d))})});return!0},B=function(a,c,b){a={path:"dictionaryextension/v1/knowledge/search",params:{term:a,language:c,app:"dictionaryextension"}};(c=window["gdx.LANG_TO_COUNTRY"][c])&&(a.params.country=c);gapi.client.request(a).execute(function(a){a=F(a,"dictionaryData[0]");if(!a)return b(null);var c=function(a){if(!a.senseFamilies)return 0;a=a.senseFamilies;for(var b=a.length,c=0;c<a.length;c++)a[c].senses&&(b+=0.1*a[c].senses.length);return b},l=function(a,b){return c(b)-c(a)};a.entries&&
(a.entries=a.entries.sort(l));a.webDefinitions&&(a.hasWebDefinitions=!0);b(a)})},D=function(a,c,b){var e=new XMLHttpRequest;e.open("GET","https://clients5.google.com/translate_a/t?client=dict-chrome-ex&sl="+c+"&tl="+p.language+"&q="+encodeURIComponent(a),!0);e.onreadystatechange=function(){if(4==e.readyState)if(200==e.status)try{return b(JSON.parse(e.responseText))}catch(a){return b(null)}else return b(null)};e.send()},C=function(a){a.numResponses++;if(4==a.numResponses){var c=G(a.dictRes),b=c;"en"!=
p.language&&(b=G(a.enDictRes));var e=H(a.tranRes,!0),d=H(a.tabLangTranRes,!0),l=p.language.toLowerCase(),h=!1,n=null,k=null;d&&a.tabLang!=l?(h=!0,n=a.tabLangTranRes,k=d):!c&&e&&(h=!0,n=a.tranRes,k=e);h&&b&&b.audio&&"en"==k.srcLang.toLowerCase()&&(k.audio=b.audio);b=h?"translation":"definition";c||k||(b="none");_gaq&&_gaq.push(["_trackEvent","lookup","type_"+b]);d=encodeURIComponent(a.sanitizedQuery);b="";h&&(b="http://translate.google.com/translate_t?source=dict-chrome-ex&sl="+k.srcLang+"&tl="+p.language+
"&q="+d);e="http://www.google.com/search?source=dict-chrome-ex&defl="+p.language+"&hl="+p.language+"&q="+d+"&tbo=1&tbs=dfn:1";"en"==p.language&&(e="http://www.google.com/search?q=define+"+d);if("fetch_html"==a.request.type)c="",c=h?I(n,k.audio,b):J(a.dictRes,e),h={eventKey:a.request.eventKey,sanitizedQuery:a.sanitizedQuery,html:c};else{var g=null,t=null;h?(g=k,g.moreUrl=b):c&&(g=c,g.moreUrl=e,g.srcLang=p.language);g&&"true"==p.storeHistory&&!a.incognito&&chrome.storage.local.get("word-history",function(b){t=
g.srcLang+"<"+p.language+"<"+a.sanitizedQuery;b["word-history"][t]=g.meaningText;chrome.storage.local.set(b)});g&&!g.prettyQuery&&(g.prettyQuery=a.sanitizedQuery);h=!1;("true"==p.popupDblclick&&"none"==p.popupDblclickKey||"true"==p.popupSelect&&"none"==p.popupSelectKey)&&y(a.sanitizedQuery)&&(h=!0);h={eventKey:a.request.eventKey,sanitizedQuery:a.sanitizedQuery,meaningObj:g,showOptionsTip:h}}a.callback(h)}},H=function(a,c){if(!a||a.sentences[0].orig.toLowerCase()==a.sentences[0].trans.toLowerCase())return null;
var b;b=a.sentences[0].orig.toLowerCase();var e=a.sentences[0].trans.toLowerCase(),d=e;if(c&&a.dict&&0<a.dict.length)for(var l=0,h=a.dict.length;l<h;l++)for(var n=a.dict[l],k=0,g=0,t=n.terms.length;g<t&&2>k;g++){var u=n.terms[g].toLowerCase();0<u.length&&u!=b&&u!=e&&(d+=", "+u,k++)}b=w(d);(e=window["gdx.LANG_TO_NAME"][a.src.toLowerCase()])||(e=a.src);return{type:"translation",meaningText:b,attribution:"Translated from "+e,srcLang:a.src}},F=function(a,c){for(var b=c.split("."),e=0;e<b.length;e++){var d=
b[e];console.assert(d);if("]"===d.charAt(d.length-1)){d=d.split("[");console.assert(2===d.length);var l=parseInt(d[1].slice(0,-1),10);a=a[d[0]];if(!a)return null;a=a[l]}else a=a[d];if(!a)return null}return a},K=function(a){return"//"==a.substr(0,2)?"https:"+a:a},G=function(a){if(!a||a.error)return null;var c=null,b=null;if(c=F(a,"entries[0]"))b={prettyQuery:c.headword,meaningText:F(c,"senseFamilies[0].senses[0].definition.text"),attribution:"",audio:F(c,"phonetics[0].drEyeAudio"),type:"licensedDef"},
b.meaningText?b.audio&&(b.audio=K(b.audio)):b=null;!b&&(c=F(a,"webDefinitions[0]"))&&(b=c.sourceUrl,b={meaningText:c.definition,attribution:'<a href="'+b+'">'+b+"</a>",type:"webDef"});if(!b)return null;c=b.meaningText;b.meaningText=c.charAt(0).toUpperCase()+c.slice(1);return b},I=function(a,c,b){var e=H(a,!1);if(!e)return"";c&&(e.audio=c);a.tranResSummary=e;a.moreUrl=b;a.hasDict=Boolean(a.dict)&&a.dict.length;return Mustache.render(q.browser_action_tran,a)},J=function(a,c){if(!a||a.error)return"";
a.moreUrl=c;a.maybePrependHttps=function(){return function(a,c){var d=c(a).replace(/&#x2F;/g,"/");return K(d)}};return Mustache.render(q.browser_action_dict,a)},L=function(a){var c={};c.language=a.language||"en";var b=function(a,b){return"true"==a||"false"==a?a:!0==a?"true":!1==a?"false":b};c.popupDblclick=b(a.popupDblclick,"true");c.popupSelect=b(a.popupSelect,"false");c.enableHttps=b(a.enableHttps,"true");c.popupDblclickKey=a.popupDblclickKey||"none";c.popupSelectKey=a.popupSelectKey||"ctrl";c.storeHistory=
b(a.storeHistory,"false");c.allowCrossExtensionHistory=b(a.allowCrossExtensionHistory,"false");"pt"==a.language&&(c.language="pt-BR");return c},M=function(a,c,b){if("false"==p.allowCrossExtensionHistory||"false"==p.storeHistory||null==a||null==a.getHistory)return!1;chrome.storage.local.get("word-history",function(a){b(a["word-history"])});return!0},N=function(a,c){var b=new XMLHttpRequest;b.open("GET",a);b.onreadystatechange=function(){if(4==b.readyState)return 200==b.status?c(b.responseText):c(null)};
b.send()},O=function(){var a=window.localStorage.options,c={};a&&(c=JSON.parse(a));p=L(c);window.localStorage.options=JSON.stringify(p);chrome.storage.local.get("word-history",function(a){null==a["word-history"]&&chrome.storage.local.set({"word-history":{}})});chrome.runtime.onMessage.addListener(z);chrome.runtime.onMessage.addListener(A);chrome.runtime.onMessage.addListener(E);chrome.runtime.onMessageExternal.addListener(M)};window["gdx.updateOptions"]=function(){p=JSON.parse(window.localStorage.options)};
window.initBackgroundPageAsync=function(a){var c=function(){2>Object.keys(q).length||(m=!0,a&&a())};N("templates/browser_action_dict.html",function(a){q.browser_action_dict=a;c()});N("templates/browser_action_tran.html",function(a){q.browser_action_tran=a;c()})};window.initBackgroundPage=O;var P=P||!1;"undefined"!=typeof P&&P||O();})();
