// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Models.Day = (function(_super) {

    __extends(Day, _super);

    function Day() {
      return Day.__super__.constructor.apply(this, arguments);
    }

    Day.include(BH.Modules.I18n);

    Day.include(BH.Modules.Url);

    Day.prototype.initialize = function(attrs, options) {
      this.chromeAPI = chrome;
      this.settings = options.settings;
      return this.set({
        id: this.get('date').id()
      });
    };

    Day.prototype.toHistory = function() {
      return {
        date: this.get('date')
      };
    };

    Day.prototype.toTemplate = function() {
      var date, properties, weekId;
      date = this.get('date');
      weekId = this.startingWeekDate().id();
      properties = {
        title: date.format('dddd'),
        formalDate: date.format('LLL'),
        weekUrl: this.urlFor('week', weekId)
      };
      return _.extend(properties, this.toJSON());
    };

    Day.prototype.startingWeekDate = function() {
      return moment(this.get('date')).past(this.settings.get('startingWeekDay'), 0);
    };

    return Day;

  })(Backbone.Model);

}).call(this);
