// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Models.GroupedVisit = (function(_super) {

    __extends(GroupedVisit, _super);

    function GroupedVisit() {
      return GroupedVisit.__super__.constructor.apply(this, arguments);
    }

    GroupedVisit.prototype.initialize = function(attr) {
      this.visits = new BH.Collections.GroupedVisits(attr);
      return this.set({
        host: this.visits.at(0).domain(),
        domain: this.visits.at(0).domain(),
        url: this.visits.at(0).get('url'),
        time: this.visits.at(0).get('time'),
        isGrouped: true,
        visits: this.visits
      });
    };

    GroupedVisit.prototype.toTemplate = function() {
      return _.extend(this.toJSON(), {
        groupedVisits: this.visits.toTemplate()
      });
    };

    return GroupedVisit;

  })(Backbone.Model);

}).call(this);
