// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Models.History = (function(_super) {

    __extends(History, _super);

    function History() {
      return History.__super__.constructor.apply(this, arguments);
    }

    History.prototype.defaults = {
      history: []
    };

    History.prototype.isNew = function() {
      return false;
    };

    History.prototype.isEmpty = function() {
      return this.get('history').length === 0;
    };

    return History;

  })(Backbone.Model);

}).call(this);
