//@ sourceMappingURL=mailing_list.map
// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Models.MailingList = (function(_super) {

    __extends(MailingList, _super);

    function MailingList() {
      return MailingList.__super__.constructor.apply(this, arguments);
    }

    MailingList.prototype.storeName = 'mailing_list';

    MailingList.prototype.initialize = function(attrs, options) {
      return this.chromeAPI = chrome;
    };

    MailingList.prototype.parse = function(data) {
      return JSON.parse(data);
    };

    return MailingList;

  })(Backbone.Model);

}).call(this);
