// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Models.WeekHistory = (function(_super) {

    __extends(WeekHistory, _super);

    function WeekHistory() {
      return WeekHistory.__super__.constructor.apply(this, arguments);
    }

    WeekHistory.include(BH.Modules.I18n);

    WeekHistory.include(BH.Modules.Worker);

    WeekHistory.prototype.initialize = function() {
      this.chromeAPI = chrome;
      return this.historyQuery = new BH.Lib.HistoryQuery(this.chromeAPI);
    };

    WeekHistory.prototype.sync = function(method, model, options) {
      var _this = this;
      switch (method) {
        case 'read':
          return this.historyQuery.run(this.toChrome(), function(results) {
            return _this.preparse(results, options.success);
          });
        case 'delete':
          return this.chromeAPI.history.deleteRange(this.toChrome(false), function() {
            return _this.set({
              history: {}
            });
          });
      }
    };

    WeekHistory.prototype.toChrome = function(reading) {
      var properties;
      if (reading == null) {
        reading = true;
      }
      properties = {
        startTime: this.sod(),
        endTime: this.eod()
      };
      if (reading) {
        properties.text = '';
      }
      return properties;
    };

    WeekHistory.prototype.toTemplate = function() {
      var day, visits;
      return {
        total: this.totalVisits(),
        days: (function() {
          var _ref, _results;
          _ref = this.get('history');
          _results = [];
          for (day in _ref) {
            visits = _ref[day];
            _results.push({
              count: visits.length,
              day: day,
              percentage: "" + (this.dayVisitPercentage(day)) + "%"
            });
          }
          return _results;
        }).call(this)
      };
    };

    WeekHistory.prototype.sod = function() {
      return new Date(this.get('startDate').sod()).getTime();
    };

    WeekHistory.prototype.eod = function() {
      return new Date(this.get('endDate').eod()).getTime();
    };

    WeekHistory.prototype.dayVisits = function() {
      var day, visits, _ref, _results;
      _ref = this.get('history');
      _results = [];
      for (day in _ref) {
        visits = _ref[day];
        if (visits != null) {
          _results.push(visits.length);
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    WeekHistory.prototype.totalVisits = function() {
      if (this.dayVisits().length === 0) {
        return 0;
      }
      return this.dayVisits().reduce(function(sum, num) {
        return sum + num;
      });
    };

    WeekHistory.prototype.dayVisitPercentage = function(day) {
      var largest;
      largest = Math.max.apply(Math, this.dayVisits()) || 0;
      if (largest === 0) {
        return 0;
      }
      return this.get('history')[day].length / largest * 100;
    };

    WeekHistory.prototype.preparse = function(results, callback) {
      return this.worker('dayGrouper', {
        visits: results
      }, function(history) {
        return callback(history);
      });
    };

    WeekHistory.prototype.parse = function(data) {
      return {
        history: data
      };
    };

    return WeekHistory;

  })(BH.Models.History);

}).call(this);
