//@ sourceMappingURL=intervals.map
// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Collections.Intervals = (function(_super) {

    __extends(Intervals, _super);

    function Intervals() {
      return Intervals.__super__.constructor.apply(this, arguments);
    }

    Intervals.prototype.model = BH.Models.Interval;

    Intervals.prototype.destroyAll = function() {
      var _results;
      _results = [];
      while (this.length > 0) {
        if (this.at(0)) {
          _results.push(this.at(0).destroy());
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    return Intervals;

  })(Backbone.Collection);

}).call(this);
