//@ sourceMappingURL=autocomplete_tags_view.map
// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Views.AutoCompleteView = (function(_super) {

    __extends(AutoCompleteView, _super);

    function AutoCompleteView() {
      return AutoCompleteView.__super__.constructor.apply(this, arguments);
    }

    AutoCompleteView.prototype.template = BH.Templates['autocomplete_tags'];

    AutoCompleteView.prototype.initialize = function() {};

    AutoCompleteView.prototype.render = function() {
      var html, properties;
      properties = {
        tags: this.model.tags()
      };
      properties.editable = this.options.editable;
      html = Mustache.to_html(this.template, properties);
      this.$el.html(html);
      return this;
    };

    return AutoCompleteView;

  })(Backbone.View);

}).call(this);
