// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Router = (function(_super) {

    __extends(Router, _super);

    function Router() {
      return Router.__super__.constructor.apply(this, arguments);
    }

    Router.prototype.routes = {
      '': 'reset',
      'tags': 'tags',
      'tags/:id': 'tag',
      'weeks/:id': 'week',
      'days/:id': 'day',
      'settings': 'settings',
      'search/*query(/p:page)': 'search',
      'search': 'search',
      'today': 'today'
    };

    Router.prototype.initialize = function(options) {
      var settings, tracker,
        _this = this;
      settings = options.settings;
      tracker = options.tracker;
      this.state = options.state;
      this.app = new BH.Views.AppView({
        el: $('.app'),
        collection: new BH.Collections.Weeks(null, {
          settings: settings
        }),
        settings: settings,
        state: this.state
      });
      this.app.render();
      this.on('route', function(route) {
        tracker.pageView(Backbone.history.getFragment());
        window.scroll(0, 0);
        if (settings.get('openLocation') === 'last_visit') {
          return _this.state.set({
            route: location.hash
          });
        }
      });
      if (location.hash === '') {
        return this.reset;
      }
    };

    Router.prototype.reset = function() {
      return this.navigate(this.state.get('route'), {
        trigger: true
      });
    };

    Router.prototype.tags = function() {
      var view;
      view = this.app.loadTags();
      view.select();
      return this._delay(function() {
        return view.collection.fetch();
      });
    };

    Router.prototype.tag = function(id) {
      var view;
      view = this.app.loadTag(id);
      view.select();
      return this._delay(function() {
        return view.model.fetch();
      });
    };

    Router.prototype.week = function(id) {
      var view;
      view = this.app.loadWeek(id);
      view.select();
      return this._delay(function() {
        return view.history.fetch();
      });
    };

    Router.prototype.day = function(id) {
      var view;
      view = this.app.loadDay(id);
      view.history.fetch();
      return view.select();
    };

    Router.prototype.today = function() {
      var view;
      view = this.app.loadDay(moment(new Date()).id());
      view.history.fetch();
      return view.select();
    };

    Router.prototype.settings = function() {
      var view;
      view = this.app.loadSettings();
      return view.select();
    };

    Router.prototype.search = function(query, page) {
      var view;
      if (query == null) {
        query = '';
      }
      view = this.app.loadSearch(query === '' || page ? {
        expired: true
      } : void 0);
      if (page != null) {
        view.page.set({
          page: parseInt(page, 10)
        }, {
          silent: true
        });
      }
      view.model.set({
        query: decodeURIComponent(query)
      });
      view.select();
      return this._delay(function() {
        if (view.model.validQuery()) {
          return view.history.fetch();
        }
      });
    };

    Router.prototype._delay = function(callback) {
      return setTimeout((function() {
        return callback();
      }), 250);
    };

    return Router;

  })(Backbone.Router);

}).call(this);
