//@ sourceMappingURL=share_tag_view.map
// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Views.ShareTagView = (function(_super) {

    __extends(ShareTagView, _super);

    function ShareTagView() {
      return ShareTagView.__super__.constructor.apply(this, arguments);
    }

    ShareTagView.include(BH.Modules.I18n);

    ShareTagView.prototype.className = 'share_tag_view';

    ShareTagView.prototype.template = BH.Templates['share_tag'];

    ShareTagView.prototype.events = {
      'click .done': 'doneClicked'
    };

    ShareTagView.prototype.initialize = function() {
      this.chromeAPI = chrome;
      this.tracker = this.options.tracker;
      return this.attachGeneralEvents();
    };

    ShareTagView.prototype.render = function() {
      var _this = this;
      this.$el.html(this.renderTemplate(this.getI18nValues()));
      this.model.share({
        success: function(data) {
          return _this.$('.url').text(data.url);
        },
        error: function() {
          return _this.$('.url').text('Oops. something went wrong :(');
        }
      });
      return this;
    };

    ShareTagView.prototype.doneClicked = function(ev) {
      ev.preventDefault();
      return this.close();
    };

    ShareTagView.prototype.getI18nValues = function() {
      var properties;
      properties = this.t(['share_tag_instructions', 'prompt_done_button']);
      properties['i18n_share_tag_title'] = this.t('share_tag_title', [this.model.get('name')]);
      return properties;
    };

    return ShareTagView;

  })(BH.Views.ModalView);

}).call(this);
