// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Models.Settings = (function(_super) {

    __extends(Settings, _super);

    function Settings() {
      return Settings.__super__.constructor.apply(this, arguments);
    }

    Settings.prototype.storeName = 'settings';

    Settings.prototype.defaults = function() {
      return {
        timeGrouping: 15,
        domainGrouping: true,
        searchByDomain: true,
        searchBySelection: true,
        openLocation: 'last_visit',
        startingWeekDay: 'Monday',
        weekDayOrder: 'ascending'
      };
    };

    return Settings;

  })(Backbone.Model);

}).call(this);
