// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Models.User = (function(_super) {

    __extends(User, _super);

    function User() {
      return User.__super__.constructor.apply(this, arguments);
    }

    User.prototype.storeName = 'user';

    User.prototype.initialize = function() {
      this.chromeAPI = chrome;
      return this.loggedIn = false;
    };

    User.prototype.fetch = function() {
      var _this = this;
      return this.chromeAPI.storage.sync.get('user', function(data) {
        var _ref;
        if (((_ref = data.user) != null ? _ref.authId : void 0) != null) {
          return _this.login(data.user);
        }
      });
    };

    User.prototype.save = function() {
      return this.chromeAPI.storage.sync.set({
        user: this.toJSON()
      });
    };

    User.prototype.login = function(data) {
      this.set(data);
      this.save();
      this.trigger('login');
      return this.loggedIn = true;
    };

    User.prototype.logout = function() {
      this.clear({
        silent: true
      });
      this.save();
      this.trigger('logout');
      return this.loggedIn = false;
    };

    User.prototype.isLoggedIn = function() {
      return this.loggedIn;
    };

    return User;

  })(Backbone.Model);

}).call(this);
