//@ sourceMappingURL=visit.map
// Generated by CoffeeScript 1.6.1
(function() {
  var getDomain,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Models.Visit = (function(_super) {

    __extends(Visit, _super);

    function Visit() {
      return Visit.__super__.constructor.apply(this, arguments);
    }

    Visit.prototype.defaults = {
      title: '(No Title)'
    };

    Visit.prototype.initialize = function() {
      this.chromeAPI = chrome;
      this.set({
        id: this.cid
      });
      if (this.get('title') === '') {
        this.set({
          title: this.defaults.title
        });
      }
      this.set({
        domain: getDomain(this.get('url'))
      });
      if (this.get('domain') != null) {
        return this.set({
          path: this.get('url').replace(this.get('domain'), '')
        });
      }
    };

    Visit.prototype.sync = function(method, model, options) {
      if (method === 'delete') {
        this.chromeAPI.history.deleteUrl({
          url: this.get('url')
        });
        return options.success(this);
      }
    };

    return Visit;

  })(Backbone.Model);

  getDomain = function(url) {
    var match;
    match = url.match(/\w+:\/\/(.*?)\//);
    if (match === null) {
      return null;
    } else {
      return match[0];
    }
  };

}).call(this);
