//@ sourceMappingURL=week.map
// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Models.Week = (function(_super) {

    __extends(Week, _super);

    function Week() {
      return Week.__super__.constructor.apply(this, arguments);
    }

    Week.prototype.initialize = function() {
      return this.set({
        id: moment(this.get('date')).id()
      });
    };

    return Week;

  })(Backbone.Model);

}).call(this);
