//@ sourceMappingURL=grouped_visits_presenter.map
// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Presenters.GroupedVisitsPresenter = (function(_super) {

    __extends(GroupedVisitsPresenter, _super);

    function GroupedVisitsPresenter(collection) {
      this.collection = collection;
    }

    GroupedVisitsPresenter.prototype.groupedVisits = function() {
      var model, presenter, _i, _len, _ref, _results;
      _ref = this.collection.models;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        model = _ref[_i];
        presenter = new BH.Presenters.GroupedVisitPresenter(model);
        _results.push(presenter.groupedVisit());
      }
      return _results;
    };

    return GroupedVisitsPresenter;

  })(BH.Presenters.Base);

}).call(this);
