//@ sourceMappingURL=intervals_presenter.map
// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Presenters.IntervalsPresenter = (function(_super) {

    __extends(IntervalsPresenter, _super);

    function IntervalsPresenter() {
      return IntervalsPresenter.__super__.constructor.apply(this, arguments);
    }

    IntervalsPresenter.prototype.intervals = function() {
      var intervals, model, presenter;
      intervals = (function() {
        var _i, _len, _ref, _results;
        _ref = this.models;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          model = _ref[_i];
          presenter = new BH.Presenters.IntervalPresenter(model);
          _results.push(presenter.interval());
        }
        return _results;
      }).call(this);
      return {
        intervals: intervals
      };
    };

    return IntervalsPresenter;

  })(BH.Presenters.Base);

}).call(this);
