//@ sourceMappingURL=visit_presenter.map
// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Presenters.VisitPresenter = (function(_super) {

    __extends(VisitPresenter, _super);

    function VisitPresenter(model) {
      this.model = model;
    }

    VisitPresenter.prototype.visit = function() {
      return _.extend({
        isGrouped: false,
        host: this.model.domain(),
        path: this.model.path()
      }, this.model.toJSON());
    };

    return VisitPresenter;

  })(BH.Presenters.Base);

}).call(this);
