// Generated by CoffeeScript 1.6.1
(function() {

  BH.Lib.Pagination = {
    RESULTS_PER_PAGE: 100,
    calculatePages: function(resultAmount) {
      return Math.ceil(resultAmount / this.RESULTS_PER_PAGE);
    },
    calculateBounds: function(page) {
      var end, start;
      start = page * this.RESULTS_PER_PAGE;
      end = page === 0 ? this.RESULTS_PER_PAGE : page * this.RESULTS_PER_PAGE + this.RESULTS_PER_PAGE;
      return [start, end];
    }
  };

}).call(this);
