// Generated by CoffeeScript 1.6.1
(function() {

  BH.Lib.Syncer = (function() {

    function Syncer() {}

    Syncer.prototype.updateIfNeeded = function(callback) {
      if (callback == null) {
        callback = function() {};
      }
      return persistence.remote().sitesHash(function(remoteData) {
        return persistence.tag().getSitesHash(function(localData) {
          if (remoteData.sitesHash !== localData.sitesHash) {
            return persistence.remote().getSites(function(sites) {
              var data, syncingTranslator;
              syncingTranslator = new BH.Lib.SyncingTranslator();
              data = syncingTranslator.forLocal(sites);
              return persistence.tag()["import"](data, function() {
                chrome.runtime.sendMessage({
                  action: 'calculate hash'
                });
                return callback();
              });
            });
          }
        });
      });
    };

    return Syncer;

  })();

}).call(this);
