//@ sourceMappingURL=tracking.map
// Generated by CoffeeScript 1.6.1
(function() {

  BH.Lib.Tracking = {
    pageView: function() {
      var url;
      url = Backbone.history.getFragment();
      return _gaq.push(['_trackPageview', "/" + url]);
    },
    weekClicked: function(date, distanceFromCurrentWeek) {
      return _gaq.push(['_trackEvent', 'Weeks', 'Clicked', date, distanceFromCurrentWeek]);
    }
  };

}).call(this);
