// Generated by CoffeeScript 1.6.1
(function() {

  BH.Lib.WeeksHistory = (function() {

    function WeeksHistory() {
      this.history = new BH.Chrome.History();
    }

    WeeksHistory.prototype.fetch = function(callback) {
      var options,
        _this = this;
      if (callback == null) {
        callback = function() {};
      }
      options = {
        startTime: 0,
        maxResults: 0,
        endTime: new Date().getTime(),
        text: ''
      };
      return this.history.query(options, function(history) {
        options = {
          visits: history,
          config: {
            startingWeekDay: settings.get('startingWeekDay')
          }
        };
        return BH.Modules.Worker.worker('weekGrouper', options, function(history) {
          return callback(history);
        });
      });
    };

    WeeksHistory.prototype.destroy = function(callback) {
      var _this = this;
      if (callback == null) {
        callback = function() {};
      }
      return this.history.deleteAll(function() {
        return callback();
      });
    };

    return WeeksHistory;

  })();

}).call(this);
