function clickIE6(){if(event.button==2)return!1}function clickNS4(g){if(document.layers||document.getElementById&&!document.all)if(g.which==2||g.which==3)return!1}if(document.layers)document.captureEvents(Event.MOUSEDOWN),document.onmousedown=clickNS4;else if(document.all&&!document.getElementById)document.onmousedown=clickIE6;document.oncontextmenu=new Function("return false");
function deepCopy(g){if(Object.prototype.toString.call(g)==="[object Array]"){for(var l=[],d=0,i=g.length;d<i;d++)l[d]=arguments.callee(g[d]);return l}if(typeof g==="object"){l={};for(d in g)l[d]=arguments.callee(g[d]);return l}return g}
function clientSideInclude(g,l){var d=!1;if(window.XMLHttpRequest)try{d=new XMLHttpRequest}catch(i){d=!1}else if(window.ActiveXObject)try{d=new ActiveXObject("Msxml2.XMLHTTP")}catch(p){try{d=new ActiveXObject("Microsoft.XMLHTTP")}catch(o){d=!1}}var n=document.getElementById(g);n?d?(d.open("GET",l,!1),d.send(null),n.innerHTML=d.responseText):n.innerHTML="Sorry, your browser does not support XMLHTTPRequest objects. This page requires Internet Explorer 5 or better for Windows, or Firefox for any system, or Safari. Other compatible browsers may also exist.":
alert("Bad id "+g+"passed to clientSideInclude.You need a div or span element with this id in your page.")}
function setScreenshotUrl(g){var l=chrome.extension.getBackgroundPage().getSelected(),d=document.getElementsByTagName("body")[0],i=document.createElement("table"),p=document.createElement("tbody"),o=parseInt(window.innerWidth/5.2),n=parseInt(o*0.7),q=0;chrome.windows.getAll({populate:!0},function(b){for(var a=0;a<b.length;a++){for(var c=0;c<b[a].tabs.length;c++)if(b[a].tabs[c].id!=g){if(q%4==0)var d=document.createElement("tr");var i=document.createElement("td");i.className+="specialBorder";i.id=
b[a].tabs[c].id+"cell";var j=document.createElement("div");j.style.position="relative";j.style.overflow="hidden";j.style.height=n+"px";j.style.width=o+"px";j.id=b[a].tabs[c].id+"div";var k=document.createElement("div");k.style.overflow="hidden";k.style.width=o*0.93+"px";k.style.height="17px";k.style.backgroundColor="transparent";if(window.localStorage.theme!=1&&window.localStorage.theme!=2)window.localStorage.theme=2,k.style.color="#606060";else if(window.localStorage.theme==1)k.style.color="black";
else if(window.localStorage.theme==2)k.style.color="#606060";k.className+="fixedfont";var f=b[a].tabs[c].favIconUrl,e=document.createElement("img");e.src=f?f:"favicon.png";e.width=12;e.height=12;f=b[a].tabs[c].url.search("exposeDisplay.html")>0?document.createTextNode("  Tab Expose Tab Selection Window"):document.createTextNode("  "+b[a].tabs[c].title);k.appendChild(e);k.appendChild(f);e=document.createElement("img");e.className+="myss";if(chrome.extension.getBackgroundPage().getSs(b[a].tabs[c].id))b[a].tabs[c].url.search("youtube.com/watch")>
0?(f=b[a].tabs[c].url.match("[\\?&]v=([^&#]*)"),e.src="http://img.youtube.com/vi/"+f[1]+"/0.jpg"):e.src=b[a].tabs[c].url.search("exposeDisplay.html")>0?"tabExpose.png":chrome.extension.getBackgroundPage().getSs(b[a].tabs[c].id);else if(b[a].tabs[c].url.search("youtube.com")>0){if(e.src="youtube.png",b[a].tabs[c].url.search("youtube.com/watch")>0)f=b[a].tabs[c].url.match("[\\?&]v=([^&#]*)"),e.src="http://img.youtube.com/vi/"+f[1]+"/0.jpg"}else if(b[a].tabs[c].url.search("chrome.google.com/extensions")>
0){if(e.src="chromeExtension.png",b[a].tabs[c].url.search("chrome.google.com/extensions/detail")>0)e.src="galleryDetail.png"}else if(b[a].tabs[c].url=="chrome://extensions/")e.src="extension.png";else if(b[a].tabs[c].url.search("exposeDisplay.html")>0)e.src="tabExpose.png";else if(b[a].tabs[c].url.search("chrome.google.com/webstore")>0){if(e.src="webStore.png",b[a].tabs[c].url.search("chrome.google.com/webstore/detail")>0)e.src="storeDetail.png"}else e.src=b[a].tabs[c].url.search("google.com/search?")>
0?"googleSearch.png":b[a].tabs[c].url.search("://newtab")>0?"newtab.png":"http://open.thumbshots.org/image.aspx?url="+b[a].tabs[c].url;e.width=o*0.95;e.height=n*0.78;e.style.zIndex="-1";f=document.createElement("div");f.style.position="absolute";f.style.top="0";f.style.left="0";f.style.height="100%";f.style.width="100%";f.style.zIndex="50";var m=document.createElement("div");m.style.position="absolute";m.style.top="1";m.style.right="0";m.style.height=12;m.style.width=12;m.style.zIndex="100";m.style.backgroundColor=
"transparent";var h=document.createElement("img");h.id=b[a].tabs[c].id;h.src="close.png";h.width=13;h.height=13;h.style.zIndex="100";h.style.cssFloat="right";m.appendChild(h);h.onmouseover=function(){this.src="close2.png"};h.onmouseout=function(){this.src="close.png"};h.onclick=function(){chrome.tabs.remove(parseInt(this.id));var a=document.getElementById(this.id+"cell");a.parentNode.removeChild(a)};f.id=b[a].tabs[c].id;f.onclick=function(){chrome.tabs.update(parseInt(this.id),{selected:!0});chrome.tabs.remove(g)};
if(b[a].tabs[c].id==l)myHereDiv=document.createElement("div"),myHereDiv.style.position="absolute",myHereDiv.style.bottom="15%",myHereDiv.style.left="50%",myHereDiv.style.marginLeft="-69px",myHereDiv.style.height=30,h=document.createElement("img"),h.src="here.png",h.height=30,myHereDiv.appendChild(h);j.appendChild(k);j.appendChild(e);j.appendChild(f);j.appendChild(m);b[a].tabs[c].id==l&&j.appendChild(myHereDiv);i.appendChild(j);d.appendChild(i);q++;q%4==0&&p.appendChild(d)}q%4!=0&&p.appendChild(d)}});
i.appendChild(p);d.appendChild(i);i.setAttribute("border","0");i.setAttribute("align","center");i.setAttribute("cellSpacing","20")}
function bgSet(){if(document.body)if(window.localStorage.theme!=1&&window.localStorage.theme!=2)window.localStorage.theme=2,document.body.background="bgM.bmp",document.body.style.backgroundAttachment="fixed";else if(window.localStorage.theme==1)document.body.background="bg.bmp",document.body.style.backgroundAttachment="";else if(window.localStorage.theme==2)document.body.background="bgM.bmp",document.body.style.backgroundAttachment="fixed"};