// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Presenters.AllWeeksPresenter = (function(_super) {

    __extends(AllWeeksPresenter, _super);

    function AllWeeksPresenter(collection) {
      this.collection = collection;
    }

    AllWeeksPresenter.prototype.allWeeks = function() {
      var model, out, weeks;
      weeks = (function() {
        var _i, _len, _ref, _results;
        _ref = this.collection.models;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          model = _ref[_i];
          _results.push(out = {
            shortTitle: moment(model.get('date')).format('L'),
            visitCount: model.get('visits').length,
            url: "#weeks/" + (moment(model.get('date')).id())
          });
        }
        return _results;
      }).call(this);
      return {
        weeks: weeks
      };
    };

    AllWeeksPresenter.prototype.totalVisits = function() {
      var model, out, _i, _len, _ref;
      out = 0;
      _ref = this.collection.models;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        model = _ref[_i];
        out += model.get('visits').length;
      }
      return out;
    };

    return AllWeeksPresenter;

  })(BH.Presenters.Base);

}).call(this);
