// Generated by CoffeeScript 1.6.1
(function() {
  var startingWeekDate;

  BH.Presenters.DayPresenter = (function() {

    function DayPresenter(day) {
      this.day = day;
    }

    DayPresenter.prototype.dayInfo = function() {
      var date, properties, weekId;
      date = moment(this.day.date);
      weekId = startingWeekDate(date).id();
      properties = {
        title: date.format('dddd'),
        formalDate: date.format('LLL'),
        weekUrl: "#weeks/" + weekId
      };
      return _.extend(properties, this.day);
    };

    return DayPresenter;

  })();

  startingWeekDate = function(date) {
    return moment(date).past(settings.get('startingWeekDay'), 0);
  };

}).call(this);
