//@ sourceMappingURL=grouped_visit_presenter.map
// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Presenters.GroupedVisitPresenter = (function(_super) {

    __extends(GroupedVisitPresenter, _super);

    function GroupedVisitPresenter(model) {
      this.model = model;
    }

    GroupedVisitPresenter.prototype.groupedVisit = function() {
      var presenter;
      presenter = new BH.Presenters.VisitsPresenter(this.model.visits);
      return _.extend(this.model.toJSON(), {
        groupedVisits: presenter.visits().visits
      });
    };

    return GroupedVisitPresenter;

  })(BH.Presenters.Base);

}).call(this);
