//@ sourceMappingURL=sites_presenter.map
// Generated by CoffeeScript 1.6.1
(function() {

  BH.Presenters.SitesPresenter = (function() {

    function SitesPresenter(collection) {
      this.collection = collection;
    }

    SitesPresenter.prototype.sitesWithSharedTags = function() {
      return {
        sites: this.collection.toJSON()
      };
    };

    return SitesPresenter;

  })();

}).call(this);
