// Generated by CoffeeScript 1.6.1
(function() {

  BH.Presenters.TagPresenter = (function() {

    function TagPresenter(model) {
      this.model = model;
    }

    TagPresenter.prototype.sites = function() {
      var sites;
      sites = this.model.get('sites').sort(function(a, b) {
        return b.datetime - a.datetime;
      });
      return {
        sites: sites
      };
    };

    return TagPresenter;

  })();

}).call(this);
