// Generated by CoffeeScript 1.6.1
(function() {
  var inflateDays,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Presenters.WeekPresenter = (function(_super) {

    __extends(WeekPresenter, _super);

    function WeekPresenter(week) {
      this.week = week;
    }

    WeekPresenter.prototype.inflatedWeek = function() {
      var copy, day, days, out;
      copy = {
        shortTitle: moment(this.week.date).format('L'),
        url: "#weeks/" + this.week.id,
        title: this.t('date_week_label', [moment(this.week.date).format('LL')])
      };
      days = (function() {
        var _i, _len, _ref, _results;
        _ref = inflateDays(this.week.date);
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          day = _ref[_i];
          _results.push(out = {
            day: moment(day.id()).lang('en').format('dddd'),
            title: day.format('dddd'),
            inFuture: moment() < day,
            url: "#days/" + (day.id())
          });
        }
        return _results;
      }).call(this);
      return _.extend(copy, this.week, {
        days: days
      });
    };

    return WeekPresenter;

  })(BH.Presenters.Base);

  inflateDays = function(date) {
    var days, i;
    days = (function() {
      var _i, _results;
      _results = [];
      for (i = _i = 0; _i <= 6; i = ++_i) {
        _results.push(moment(new Date(date)).add('days', i));
      }
      return _results;
    })();
    if (settings.get('weekDayOrder') === 'descending') {
      days.reverse();
    }
    return days;
  };

}).call(this);
