// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Presenters.WeeksPresenter = (function(_super) {

    __extends(WeeksPresenter, _super);

    function WeeksPresenter(collection) {
      this.collection = collection;
    }

    WeeksPresenter.prototype.weeks = function() {
      var model, out, weeks;
      weeks = (function() {
        var _i, _len, _ref, _results;
        _ref = this.collection.models;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          model = _ref[_i];
          _results.push(out = {
            id: model.id,
            url: "#weeks/" + model.id,
            shortTitle: model.get('date').format('L')
          });
        }
        return _results;
      }).call(this);
      return {
        weeks: weeks
      };
    };

    return WeeksPresenter;

  })(BH.Presenters.Base);

}).call(this);
