/*
 GNU Lesser General Public License, http://www.gnu.org/copyleft/lesser.html
 @author  Jan Odvarko, http://odvarko.cz
 @created 2008-06-15
 @updated 2012-07-06
 @link    http://jscolor.com
*/
var jscolor={dir:"",bindClass:"color",binding:!0,preloading:!0,install:function(){jscolor.addEvent(window,"load",jscolor.init)},init:function(){jscolor.binding&&jscolor.bind();jscolor.preloading&&jscolor.preload()},getDir:function(){if(!jscolor.dir){var a=jscolor.detectDir();jscolor.dir=a!==!1?a:"jscolor/"}return jscolor.dir},detectDir:function(){for(var a=location.href,f=document.getElementsByTagName("base"),b=0;b<f.length;b+=1)if(f[b].href)a=f[b].href;f=document.getElementsByTagName("script");for(b=
0;b<f.length;b+=1)if(f[b].src&&/(^|\/)jscolor\.js([?#].*)?$/i.test(f[b].src))return a=(new jscolor.URI(f[b].src)).toAbsolute(a),a.path=a.path.replace(/[^\/]+$/,""),a.query=null,a.fragment=null,a.toString();return!1},bind:function(){for(var a=RegExp("(^|\\s)("+jscolor.bindClass+")\\s*(\\{[^}]*\\})?","i"),f=document.getElementsByTagName("input"),b=0;b<f.length;b+=1){var l;if(!f[b].color&&f[b].className&&(l=f[b].className.match(a))){var o={};if(l[3])try{o=(new Function("return ("+l[3]+")"))()}catch(v){}f[b].color=
new jscolor.color(f[b],o)}}},preload:function(){for(var a in jscolor.imgRequire)jscolor.imgRequire.hasOwnProperty(a)&&jscolor.loadImage(a)},images:{pad:[181,101],sld:[16,101],cross:[15,15],arrow:[7,11]},imgRequire:{},imgLoaded:{},requireImage:function(a){jscolor.imgRequire[a]=!0},loadImage:function(a){if(!jscolor.imgLoaded[a])jscolor.imgLoaded[a]=new Image,jscolor.imgLoaded[a].src=jscolor.getDir()+a},fetchElement:function(a){return typeof a==="string"?document.getElementById(a):a},addEvent:function(a,
f,b){a.addEventListener?a.addEventListener(f,b,!1):a.attachEvent&&a.attachEvent("on"+f,b)},fireEvent:function(a,f){if(a)if(document.createEvent){var b=document.createEvent("HTMLEvents");b.initEvent(f,!0,!0);a.dispatchEvent(b)}else if(document.createEventObject)b=document.createEventObject(),a.fireEvent("on"+f,b);else if(a["on"+f])a["on"+f]()},getElementPos:function(a){var f=a,b=0,l=0;if(f.offsetParent){do b+=f.offsetLeft,l+=f.offsetTop;while(f=f.offsetParent)}for(;(a=a.parentNode)&&a.nodeName.toUpperCase()!==
"BODY";)b-=a.scrollLeft,l-=a.scrollTop;return[b,l]},getElementSize:function(a){return[a.offsetWidth,a.offsetHeight]},getRelMousePos:function(a){var f=0,b=0;if(!a)a=window.event;if(typeof a.offsetX==="number")f=a.offsetX,b=a.offsetY;else if(typeof a.layerX==="number")f=a.layerX,b=a.layerY;return{x:f,y:b}},getViewPos:function(){return typeof window.pageYOffset==="number"?[window.pageXOffset,window.pageYOffset]:document.body&&(document.body.scrollLeft||document.body.scrollTop)?[document.body.scrollLeft,
document.body.scrollTop]:document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop)?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[0,0]},getViewSize:function(){return typeof window.innerWidth==="number"?[window.innerWidth,window.innerHeight]:document.body&&(document.body.clientWidth||document.body.clientHeight)?[document.body.clientWidth,document.body.clientHeight]:document.documentElement&&(document.documentElement.clientWidth||
document.documentElement.clientHeight)?[document.documentElement.clientWidth,document.documentElement.clientHeight]:[0,0]},URI:function(a){function f(b){for(var a="";b;)if(b.substr(0,3)==="../"||b.substr(0,2)==="./")b=b.replace(/^\.+/,"").substr(1);else if(b.substr(0,3)==="/./"||b==="/.")b="/"+b.substr(3);else if(b.substr(0,4)==="/../"||b==="/..")b="/"+b.substr(4),a=a.replace(/\/?[^\/]*$/,"");else if(b==="."||b==="..")b="";else{var f=b.match(/^\/?[^\/]*/)[0],b=b.substr(f.length);a+=f}return a}this.authority=
this.scheme=null;this.path="";this.fragment=this.query=null;this.parse=function(b){b=b.match(/^(([A-Za-z][0-9A-Za-z+.-]*)(:))?((\/\/)([^\/?#]*))?([^?#]*)((\?)([^#]*))?((#)(.*))?/);this.scheme=b[3]?b[2]:null;this.authority=b[5]?b[6]:null;this.path=b[7];this.query=b[9]?b[10]:null;this.fragment=b[12]?b[13]:null;return this};this.toString=function(){var b="";this.scheme!==null&&(b=b+this.scheme+":");this.authority!==null&&(b=b+"//"+this.authority);this.path!==null&&(b+=this.path);this.query!==null&&(b=
b+"?"+this.query);this.fragment!==null&&(b=b+"#"+this.fragment);return b};this.toAbsolute=function(b){var b=new jscolor.URI(b),a=new jscolor.URI;if(b.scheme===null)return!1;if(this.scheme!==null&&this.scheme.toLowerCase()===b.scheme.toLowerCase())this.scheme=null;this.scheme!==null?(a.scheme=this.scheme,a.authority=this.authority,a.path=f(this.path),a.query=this.query):(this.authority!==null?(a.authority=this.authority,a.path=f(this.path),a.query=this.query):(this.path===""?(a.path=b.path,a.query=
this.query!==null?this.query:b.query):(this.path.substr(0,1)==="/"?a.path=f(this.path):(a.path=b.authority!==null&&b.path===""?"/"+this.path:b.path.replace(/[^\/]+$/,"")+this.path,a.path=f(a.path)),a.query=this.query),a.authority=b.authority),a.scheme=b.scheme);a.fragment=this.fragment;return a};a&&this.parse(a)},color:function(a,f){function b(c,a,b){if(c===null)return[b,b,b];var d=Math.floor(c),e=b*(1-a),c=b*(1-a*(d%2?c-d:1-(c-d)));switch(d){case 6:case 0:return[b,c,e];case 1:return[c,b,e];case 2:return[e,
b,c];case 3:return[e,c,b];case 4:return[c,e,b];case 5:return[b,e,c]}}function l(c,b){if(!jscolor.picker){jscolor.picker={box:document.createElement("div"),boxB:document.createElement("div"),pad:document.createElement("div"),padB:document.createElement("div"),padM:document.createElement("div"),sld:document.createElement("div"),sldB:document.createElement("div"),sldM:document.createElement("div"),btn:document.createElement("div"),btnS:document.createElement("span"),btnT:document.createTextNode(d.pickerCloseText)};
for(var k=0;k<jscolor.images.sld[1];k+=4){var f=document.createElement("div");f.style.height="4px";f.style.fontSize="1px";f.style.lineHeight="0";jscolor.picker.sld.appendChild(f)}jscolor.picker.sldB.appendChild(jscolor.picker.sld);jscolor.picker.box.appendChild(jscolor.picker.sldB);jscolor.picker.box.appendChild(jscolor.picker.sldM);jscolor.picker.padB.appendChild(jscolor.picker.pad);jscolor.picker.box.appendChild(jscolor.picker.padB);jscolor.picker.box.appendChild(jscolor.picker.padM);jscolor.picker.btnS.appendChild(jscolor.picker.btnT);
jscolor.picker.btn.appendChild(jscolor.picker.btnS);jscolor.picker.box.appendChild(jscolor.picker.btn);jscolor.picker.boxB.appendChild(jscolor.picker.box)}var e=jscolor.picker;e.box.onmouseup=e.box.onmouseout=function(){a.focus()};e.box.onmousedown=function(){p=!0};e.box.onmousemove=function(c){if(q||r)q&&z(c),r&&A(c),document.selection?document.selection.empty():window.getSelection&&window.getSelection().removeAllRanges(),t()};e.padM.onmouseup=e.padM.onmouseout=function(){q&&(q=!1,jscolor.fireEvent(i,
"change"))};e.padM.onmousedown=function(c){switch(m){case 0:d.hsv[2]===0&&d.fromHSV(null,null,1);break;case 1:d.hsv[1]===0&&d.fromHSV(null,1,null)}q=!0;z(c);t()};e.sldM.onmouseup=e.sldM.onmouseout=function(){r&&(r=!1,jscolor.fireEvent(i,"change"))};e.sldM.onmousedown=function(c){r=!0;A(c);t()};k=o(d);e.box.style.width=k[0]+"px";e.box.style.height=k[1]+"px";e.boxB.style.position="absolute";e.boxB.style.clear="both";e.boxB.style.left=c+"px";e.boxB.style.top=b+"px";e.boxB.style.zIndex=d.pickerZIndex;
e.boxB.style.border=d.pickerBorder+"px solid";e.boxB.style.borderColor=d.pickerBorderColor;e.boxB.style.background=d.pickerFaceColor;e.pad.style.width=jscolor.images.pad[0]+"px";e.pad.style.height=jscolor.images.pad[1]+"px";e.padB.style.position="absolute";e.padB.style.left=d.pickerFace+"px";e.padB.style.top=d.pickerFace+"px";e.padB.style.border=d.pickerInset+"px solid";e.padB.style.borderColor=d.pickerInsetColor;e.padM.style.position="absolute";e.padM.style.left="0";e.padM.style.top="0";e.padM.style.width=
d.pickerFace+2*d.pickerInset+jscolor.images.pad[0]+jscolor.images.arrow[0]+"px";e.padM.style.height=e.box.style.height;e.padM.style.cursor="crosshair";e.sld.style.overflow="hidden";e.sld.style.width=jscolor.images.sld[0]+"px";e.sld.style.height=jscolor.images.sld[1]+"px";e.sldB.style.display=d.slider?"block":"none";e.sldB.style.position="absolute";e.sldB.style.right=d.pickerFace+"px";e.sldB.style.top=d.pickerFace+"px";e.sldB.style.border=d.pickerInset+"px solid";e.sldB.style.borderColor=d.pickerInsetColor;
e.sldM.style.display=d.slider?"block":"none";e.sldM.style.position="absolute";e.sldM.style.right="0";e.sldM.style.top="0";e.sldM.style.width=jscolor.images.sld[0]+jscolor.images.arrow[0]+d.pickerFace+2*d.pickerInset+"px";e.sldM.style.height=e.box.style.height;try{e.sldM.style.cursor="pointer"}catch(j){e.sldM.style.cursor="hand"}e.btn.style.display=d.pickerClosable?"block":"none";e.btn.style.position="absolute";e.btn.style.left=d.pickerFace+"px";e.btn.style.bottom=d.pickerFace+"px";e.btn.style.padding=
"0 15px";e.btn.style.height="18px";e.btn.style.border=d.pickerInset+"px solid";(function(){var c=d.pickerInsetColor.split(/\s+/);e.btn.style.borderColor=c.length<2?c[0]:c[1]+" "+c[0]+" "+c[0]+" "+c[1]})();e.btn.style.color=d.pickerButtonColor;e.btn.style.font="12px sans-serif";e.btn.style.textAlign="center";try{e.btn.style.cursor="pointer"}catch(h){e.btn.style.cursor="hand"}e.btn.onmousedown=function(){d.hidePicker()};e.btnS.style.lineHeight=e.btn.style.height;switch(m){case 0:var g="hs.png";break;
case 1:g="hv.png"}e.padM.style.backgroundImage="url('"+jscolor.getDir()+"cross.gif')";e.padM.style.backgroundRepeat="no-repeat";e.sldM.style.backgroundImage="url('"+jscolor.getDir()+"arrow.gif')";e.sldM.style.backgroundRepeat="no-repeat";e.pad.style.backgroundImage="url('"+jscolor.getDir()+g+"')";e.pad.style.backgroundRepeat="no-repeat";e.pad.style.backgroundPosition="0 0";v();B();jscolor.picker.owner=d;document.getElementsByTagName("body")[0].appendChild(e.boxB)}function o(c){return[2*c.pickerInset+
2*c.pickerFace+jscolor.images.pad[0]+(c.slider?2*c.pickerInset+2*jscolor.images.arrow[0]+jscolor.images.sld[0]:0),c.pickerClosable?4*c.pickerInset+3*c.pickerFace+jscolor.images.pad[1]+c.pickerButtonHeight:2*c.pickerInset+2*c.pickerFace+jscolor.images.pad[1]]}function v(){switch(m){case 0:var c=1;break;case 1:c=2}jscolor.picker.padM.style.backgroundPosition=d.pickerFace+d.pickerInset+Math.round(d.hsv[0]/6*(jscolor.images.pad[0]-1))-Math.floor(jscolor.images.cross[0]/2)+"px "+(d.pickerFace+d.pickerInset+
Math.round((1-d.hsv[c])*(jscolor.images.pad[1]-1))-Math.floor(jscolor.images.cross[1]/2))+"px";c=jscolor.picker.sld.childNodes;switch(m){case 0:for(var a=b(d.hsv[0],d.hsv[1],1),k=0;k<c.length;k+=1)c[k].style.backgroundColor="rgb("+a[0]*(1-k/c.length)*100+"%,"+a[1]*(1-k/c.length)*100+"%,"+a[2]*(1-k/c.length)*100+"%)";break;case 1:var f,e=[d.hsv[2],0,0],k=Math.floor(d.hsv[0]),j=k%2?d.hsv[0]-k:1-(d.hsv[0]-k);switch(k){case 6:case 0:a=[0,1,2];break;case 1:a=[1,0,2];break;case 2:a=[2,0,1];break;case 3:a=
[2,1,0];break;case 4:a=[1,2,0];break;case 5:a=[0,2,1]}for(k=0;k<c.length;k+=1)f=1-1/(c.length-1)*k,e[1]=e[0]*(1-f*j),e[2]=e[0]*(1-f),c[k].style.backgroundColor="rgb("+e[a[0]]*100+"%,"+e[a[1]]*100+"%,"+e[a[2]]*100+"%)"}}function B(){switch(m){case 0:var c=2;break;case 1:c=1}jscolor.picker.sldM.style.backgroundPosition="0 "+(d.pickerFace+d.pickerInset+Math.round((1-d.hsv[c])*(jscolor.images.sld[1]-1))-Math.floor(jscolor.images.arrow[1]/2))+"px"}function u(){return jscolor.picker&&jscolor.picker.owner===
d}function C(){i!==a&&d.importColor()}function z(c){var a=jscolor.getRelMousePos(c),c=a.x-d.pickerFace-d.pickerInset,a=a.y-d.pickerFace-d.pickerInset;switch(m){case 0:d.fromHSV(c*(6/(jscolor.images.pad[0]-1)),1-a/(jscolor.images.pad[1]-1),null,w);break;case 1:d.fromHSV(c*(6/(jscolor.images.pad[0]-1)),null,1-a/(jscolor.images.pad[1]-1),w)}}function A(c){c=jscolor.getRelMousePos(c).y-d.pickerFace-d.pickerInset;switch(m){case 0:d.fromHSV(null,null,1-c/(jscolor.images.sld[1]-1),x);break;case 1:d.fromHSV(null,
1-c/(jscolor.images.sld[1]-1),null,x)}}function t(){d.onImmediateChange&&(typeof d.onImmediateChange==="string"?new Function(d.onImmediateChange):d.onImmediateChange).call(d)}this.adjust=this.required=!0;this.hash=!1;this.slider=this.caps=!0;this.styleElement=this.valueElement=a;this.onImmediateChange=null;this.hsv=[0,0,1];this.rgb=[1,1,1];this.minH=0;this.maxH=6;this.minS=0;this.maxS=1;this.minV=0;this.maxV=1;this.pickerOnfocus=!0;this.pickerMode="HSV";this.pickerPosition="bottom";this.pickerSmartPosition=
!0;this.pickerButtonHeight=20;this.pickerClosable=!1;this.pickerCloseText="Close";this.pickerButtonColor="ButtonText";this.pickerFace=10;this.pickerFaceColor="ThreeDFace";this.pickerBorder=1;this.pickerBorderColor="ThreeDHighlight ThreeDShadow ThreeDShadow ThreeDHighlight";this.pickerInset=1;this.pickerInsetColor="ThreeDShadow ThreeDHighlight ThreeDHighlight ThreeDShadow";this.pickerZIndex=1E4;for(var n in f)f.hasOwnProperty(n)&&(this[n]=f[n]);this.hidePicker=function(){u()&&(delete jscolor.picker.owner,
document.getElementsByTagName("body")[0].removeChild(jscolor.picker.boxB))};this.showPicker=function(){if(!u()){var c=jscolor.getElementPos(a),b=jscolor.getElementSize(a),d=jscolor.getViewPos(),f=jscolor.getViewSize(),e=o(this),j,h,g;switch(this.pickerPosition.toLowerCase()){case "left":j=1;h=0;g=-1;break;case "right":j=1;h=0;g=1;break;case "top":j=0;h=1;g=-1;break;default:j=0,g=h=1}var i=(b[h]+e[h])/2,c=this.pickerSmartPosition?[-d[j]+c[j]+e[j]>f[j]?-d[j]+c[j]+b[j]/2>f[j]/2&&c[j]+b[j]-e[j]>=0?c[j]+
b[j]-e[j]:c[j]:c[j],-d[h]+c[h]+b[h]+e[h]-i+i*g>f[h]?-d[h]+c[h]+b[h]/2>f[h]/2&&c[h]+b[h]-i-i*g>=0?c[h]+b[h]-i-i*g:c[h]+b[h]-i+i*g:c[h]+b[h]-i+i*g>=0?c[h]+b[h]-i+i*g:c[h]+b[h]-i-i*g]:[c[j],c[h]+b[h]-i+i*g];l(c[j],c[h])}};this.importColor=function(){if(i)if(this.adjust)!this.required&&/^\s*$/.test(i.value)?(i.value="",g.style.backgroundImage=g.jscStyle.backgroundImage,g.style.backgroundColor=g.jscStyle.backgroundColor,g.style.color=g.jscStyle.color,this.exportColor(s|y)):this.fromString(i.value)||this.exportColor();
else{if(!this.fromString(i.value,s))g.style.backgroundImage=g.jscStyle.backgroundImage,g.style.backgroundColor=g.jscStyle.backgroundColor,g.style.color=g.jscStyle.color,this.exportColor(s|y)}else this.exportColor()};this.exportColor=function(c){if(!(c&s)&&i){var b=this.toString();this.caps&&(b=b.toUpperCase());this.hash&&(b="#"+b);i.value=b}if(!(c&y)&&g)g.style.backgroundImage="none",g.style.backgroundColor="#"+this.toString(),g.style.color=0.213*this.rgb[0]+0.715*this.rgb[1]+0.072*this.rgb[2]<0.5?
"#FFF":"#000";!(c&x)&&u()&&v();!(c&w)&&u()&&B()};this.fromHSV=function(c,a,d,f){c!==null&&(c=Math.max(0,this.minH,Math.min(6,this.maxH,c)));a!==null&&(a=Math.max(0,this.minS,Math.min(1,this.maxS,a)));d!==null&&(d=Math.max(0,this.minV,Math.min(1,this.maxV,d)));this.rgb=b(c===null?this.hsv[0]:this.hsv[0]=c,a===null?this.hsv[1]:this.hsv[1]=a,d===null?this.hsv[2]:this.hsv[2]=d);this.exportColor(f)};this.fromRGB=function(c,a,d,f){c!==null&&(c=Math.max(0,Math.min(1,c)));a!==null&&(a=Math.max(0,Math.min(1,
a)));d!==null&&(d=Math.max(0,Math.min(1,d)));var c=c===null?this.rgb[0]:c,a=a===null?this.rgb[1]:a,e=d===null?this.rgb[2]:d,g=Math.min(Math.min(c,a),e),d=Math.max(Math.max(c,a),e),h=d-g;h===0?c=[null,0,d]:(c=c===g?3+(e-a)/h:a===g?5+(c-e)/h:1+(a-c)/h,c=[c===6?0:c,h/d,d]);c[0]!==null&&(this.hsv[0]=Math.max(0,this.minH,Math.min(6,this.maxH,c[0])));c[2]!==0&&(this.hsv[1]=c[1]===null?null:Math.max(0,this.minS,Math.min(1,this.maxS,c[1])));this.hsv[2]=c[2]===null?null:Math.max(0,this.minV,Math.min(1,this.maxV,
c[2]));c=b(this.hsv[0],this.hsv[1],this.hsv[2]);this.rgb[0]=c[0];this.rgb[1]=c[1];this.rgb[2]=c[2];this.exportColor(f)};this.fromString=function(a,b){var d=a.match(/^\W*([0-9A-F]{3}([0-9A-F]{3})?)\W*$/i);return d?(d[1].length===6?this.fromRGB(parseInt(d[1].substr(0,2),16)/255,parseInt(d[1].substr(2,2),16)/255,parseInt(d[1].substr(4,2),16)/255,b):this.fromRGB(parseInt(d[1].charAt(0)+d[1].charAt(0),16)/255,parseInt(d[1].charAt(1)+d[1].charAt(1),16)/255,parseInt(d[1].charAt(2)+d[1].charAt(2),16)/255,
b),!0):!1};this.toString=function(){return(256|Math.round(255*this.rgb[0])).toString(16).substr(1)+(256|Math.round(255*this.rgb[1])).toString(16).substr(1)+(256|Math.round(255*this.rgb[2])).toString(16).substr(1)};var d=this,m=this.pickerMode.toLowerCase()==="hvs"?1:0,p=!1,i=jscolor.fetchElement(this.valueElement),g=jscolor.fetchElement(this.styleElement),q=!1,r=!1,s=1,y=2,x=4,w=8;jscolor.addEvent(a,"focus",function(){d.pickerOnfocus&&d.showPicker()});jscolor.addEvent(a,"blur",function(){p?p=!1:window.setTimeout(function(){p||
(i===a&&d.importColor(),d.pickerOnfocus&&d.hidePicker());p=!1},0)});i&&(n=function(){d.fromString(i.value,s);t()},jscolor.addEvent(i,"keyup",n),jscolor.addEvent(i,"input",n),jscolor.addEvent(i,"blur",C),i.setAttribute("autocomplete","off"));if(g)g.jscStyle={backgroundImage:g.style.backgroundImage,backgroundColor:g.style.backgroundColor,color:g.style.color};switch(m){case 0:jscolor.requireImage("hs.png");break;case 1:jscolor.requireImage("hv.png")}jscolor.requireImage("cross.gif");jscolor.requireImage("arrow.gif");
this.importColor()}};jscolor.install();
