/* Copyright (C) Sergey Barbushin, 2013. All Rights Reserved.
 * This file can be used only within Google Chrome extension "PHP Console" installed from https://chrome.google.com/webstore/detail/php-console/nfhmhhlpfleoednkpnnnkolmclajemef
 * Unauthorized copying and using of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Sergey Barbushin <barbushin@gmail.com>, June 2013
 */
window.app=new function(){function h(a,b,c){p.getServer(b,function(l){var d={"php-console-client":p.protocol};(l=n.j(l))&&(l=l.o())&&(d.auth=l);e[0]!=f[2][0]&&(a=1);var k=g.f[b]||!1,r=(k?"https":"http")+"://"+b,h=btoa(JSON.stringify(d));chrome.cookies.get({url:r,name:s},function(b){!b||b.value!=h||k&&b.secure!=k?chrome.cookies.set({url:r,name:s,secure:k,value:h},function(){c?c(!0):chrome.tabs.reload(a,{bypassCache:!0})}):c()})})}function m(a,b,c){var f=v[b];p.getServer(g.a(f),function(l){q.l(f,{__PHP_Console:{eval:{data:a,
signature:n.j(l).p(a)},getBackData:{tabId:b}}},c,c)})}function x(a,b,c,f){e[2]!=u[0]&&(b=a);c!=p.protocol&&g.m({tabId:a,protocol:c});v[a]=b;b=g.a(b);var d=!1;w[b]||(w[b]=!0,q.addListener(b),d=!0);h(a,b,function(b){id=l++;k.e[a]=id;f(id,d||b)})}var k=this,v={},w={},y=!1,p=null,n=null,e=chrome.runtime,d=e.getManifest(),g=null,q=null,s="php-console-client",u="history",a=null,b=/^https:\/\//i,c=e.getURL("manifest.json"),f=["eval","console","notify"],l=0;this.e={};this.getOptions=function(){return p};
this.k=function(a,b){b._id=k.e[a];chrome.tabs.sendMessage(a,b)};this.getActiveTab=function(a){chrome.tabs.query({currentWindow:!0,active:!0},function(b){var c=b[0].id;a(c,g.a(g.h[c]?g.h[c]:b[0].url))})};chrome.extension.onMessage.addListener(function(a,c,f){if(a._getConsolePack){c=a.id;var l=g.i[c];if(l&&g.i[c])return delete g.i[c],f({pack:l}),!0}else{if(a._registerTab){var d=a.url;x(c.tab.id,d,a.protocol,function(a,c){f({id:a,url:g.f[g.a(d)]&&!b.exec(d)?d.replace("http://","https://"):c?d:""})});
return!0}if(a._setPassword)k.getActiveTab(function(b,c){n.s(c,a.password);h(b,c);chrome.tabs.reload(b)});else if(a._logout)k.getActiveTab(function(a,b){n.n(b);h(a,b);chrome.tabs.reload(a)});else if(a._evalCode)return p.evalClearConsole&&k.k(a.tabId,{_clearConsole:!0}),m(a.code,a.tabId,f),!0}});p=new A(function(b){e=e.id;n=new B(b);a=new C(b);g=new D(b,n,a,k);q=new E(g);c=c.substr(19);var f=parseFloat(/^\d+\.\d+/.exec(d.version)[0]);chrome.extension.inIncognitoContext||b.version==f||(b.version?2.9>=
b.version?(y=!0,chrome.tabs.onRemoved.addListener(function(){y&&(y=!1,b.version=f,a.d({type:"update",subject:"PHP Console MEGA Update",permanent:!0,data:"\u271a Dump any type variable\n\u271a Execute PHP code remotely\n\u271a Protect access by password\n\u271a Group console logs by request\n\u271a New communication protocol\n\u271a Jump to error file:line in your text editor",openUrlOnClose:"https://github.com/barbushin/php-console/wiki/PHP-Console-v3-Release-(November-2013)",buttons:[{title:"IMPORTANT: PHP Console server library must be updated",
url:"https://github.com/barbushin/php-console/wiki/PHP-Console-v3-Release-(November-2013)"},{title:"Changelog & server library update instructions",url:"https://github.com/barbushin/php-console/wiki/PHP-Console-v3-Release-(November-2013)",icon:"img/right.png"}]}))})):b.version=f:(a.d({type:"update",subject:d.name+" installed",permanent:!0,data:"To use PHP Console on your server you need to install PHP Console server library.",openUrlOnClose:"https://github.com/barbushin/php-console#php-console-server-library",
buttons:[{title:"PHP Console server library Installation & Usage Guide",url:"https://github.com/barbushin/php-console#php-console-server-library",icon:"img/right.png"}]}),b.version=f),c[1]!="force"[0]&&(b={}))})};document.addEventListener("DOMContentLoaded",window.app,!1);
function B(h){function m(x,k){h.updateServer(x,{auth:k},null,!0)}this.r=function(h){var k=h.auth;k&&m(h.domain,{publicKey:k.publicKey,isSuccess:k.isSuccess})};this.j=function(h){var k=h.auth;if(k.publicKey&&k.hash)return new F(h.domain,k.publicKey,k.hash)};this.s=function(h,k){m(h,{hash:window.CryptoJS.SHA256(k+"NeverChangeIt:)").toString()})};this.n=function(h){m(h,{hash:null})}}
function F(h,m,x){this.domain=h;this.b=m;this.hash=x;this.getAuthToken=function(){if(this.hash&&this.b)return window.CryptoJS.SHA256(this.hash+this.b).toString()};this.p=function(h){if(this.hash&&this.b)return window.CryptoJS.SHA256(this.hash+this.b+h).toString()};this.o=function(){var h=this.getAuthToken();if(h&&this.b)return{publicKey:this.b,token:h}}}
function E(h){function m(a,b){for(var c in a)if(a[c].name==b)return a[c].value;return null}function x(a,b,c,f,l){var d=a||!1;d||(a={tabId:0>=f?null:f,redirectUrl:w(c,l),url:c,domain:h.a(c)});if(b){n[a.domain]=a.url;b=JSON.parse(b);if(b.isPostponed){u.push(a);k(b.id,a);return}for(var e in b)a[e]=b[e];b.getBackData&&b.getBackData.tabId&&(a.tabId=+b.getBackData.tabId);a.sourcesBasePath&&(a.sourcesBasePath=h.c(a.sourcesBasePath));if(a.messages&&a.messages.length)for(e in a.messages)b=a.messages[e],b.redirectUrl=
a.redirectUrl,b.url=a.url,b.tabId=a.tabId,b.basePath=a.sourcesBasePath,b.isLocal=a.isLocal,b["class"]?b.tags=[b["class"]]:"debug"!=b.type||b.tags||(b.tags=["debug"]),b.file&&g.exec(b.file)&&(b.file="terminal")}a.tabId&&chrome.tabs.get(a.tabId,function(b){a.tabUrl=b.url;d||u.push(a);a.redirectUrl||(b=u.slice(0),u=[],h.q(b))})}function k(a,b){p.l(b.url,{__PHP_Console:{getPostponedResponse:a}},function(a){x(b,a)})}function v(a){var b=h.a(a.url),c=m(a.responseHeaders,e);c||(c=m(a.responseHeaders,d));
(n[b]==a.url||c)&&x(null,c,a.url,a.tabId,a.redirectUrl)}function w(a,b){b&&!q.exec(b)&&(b=(s.exec(a)||[a])[0]+b);return b}function y(a,b){var c=[],f;for(f in a){var l=b?b+"["+f+"]":f,d=a[f];c.push("object"==typeof d?y(d,l):encodeURIComponent(l)+"="+encodeURIComponent(d))}return c.join("&")}var p=this,n={},e="PHP-Console",d="PHP-Console-Postpone",g=/EvalProvider.php.*?eval/i,q=/^http/i,s=/^(.+[/\\])/,u=[];this.l=function(a,b,c,f){try{var l=new XMLHttpRequest;l.open("POST",a,!0);l.setRequestHeader("Content-type",
"application/x-www-form-urlencoded");l.onreadystatechange=function(){4==l.readyState&&200==l.status&&c&&c(l.responseText)};l.send(y(b))}catch(d){f&&f()}};this.addListener=function(a){a={urls:["*://"+a+"/*"],types:["main_frame","sub_frame","xmlhttprequest","other"]};chrome.webRequest.onCompleted.addListener(v,a,["responseHeaders"]);chrome.webRequest.onBeforeRedirect.addListener(v,a,["responseHeaders"])}}
function D(h,m,x,k){function v(a,c){var f=!1,l=setInterval(function(){chrome.tabs.get(a,function(d){"complete"==d.status&&!f&&k.e[a]&&(f=!0,clearInterval(l),c())})},100)}function w(a,c){var f=c.ignoreErrors,l=c.ignoreDebug,d={},e=[],g;for(g in a){var k=!1,t=a[g];if("debug"==t.type){if("object"==typeof t.tags)for(var n in t.tags){var r=t.tags[n];if("undefined"!=typeof l[r]){if(l[r]){k=!0;break}}else d[r]||(d[r]=!0)}}else"error"==t.type&&f[t["class"]]&&(k=!0);k||e.push(t)}f=Object.keys(d);if(f.length){f.sort();
d={};k=[];t=[];for(r in l)l[r]?k.push(r):t.push(r);for(g=0;20>g;g++)if(r=k.shift())d[r]=!0;else if(r=f.shift()||t.shift())d[r]=!1;else break;h.updateServer(c.domain,{ignoreDebug:d})}return e}function y(a){if("eval_result"==a.type){var c=[];a.output&&c.push(["%c output ","color: white; background: black",a.output]);c.push(["%c return ","color: white; background: black",a["return"]]);a.time&&h.evalShowTime&&c.push(["%c time ","color: white; background: black",a.time])}else if(c=["%c "+a.tags.join(".")+
" ","color: white; background: "+("debug"==a.type?"blue":"red"),a.data],a.path||a.trace)c.push("-"),a.path&&c.push(a.path+(a.line?":"+a.line:"")),a.trace&&c.push("\n"+a.trace);a.args=c}function p(a){if(a.trace){var c=[],f;for(f in a.trace){var d="#"+(+f+1)+" ",e=a.trace[f];e.file?(d+=n(a.basePath,e.file),e.line&&(d+=":"+e.line)):d+="[internal call]";e.call&&(d+=" - "+e.call);c.unshift(d)}a.trace=c.join("\n")}a.file&&(a.path=n(a.basePath,a.file))}function n(b,c){c=a.c(c);return b&&c.substr(0,b.length)==
b?c.substr(b.length):c}this.f={};this.h={};var e={},d={},g={},q=RegExp("\\\\","g"),s=/:\/\/([^:/]+)/,u=/^\w+:\/\/.*?(\/.*\.(js|htm|html))($|\?)/,a=this;this.c=function(a){return a.replace(q,"/")};this.m=function(a){var c=a.tabId;if(a.protocol){var f="logo_16.png",d="options/layout.html",e="PHP Console is active on server.";a.protocol!=h.protocol?(f="logo_16_fail.png",d="wrong_protocol.html",e="Wrong version of PHP Console server. Click on this icon to get update instructions."):a.auth&&(a.isEvalEnabled?
(f="terminal_16.png",e="PHP Console eval is enabled on server. Click on this icon to access eval & options form.",d="terminal/popup.html"):a.auth.isSuccess?(e="PHP Console is active on server protected by password. Click on this icon to see options.",d="logout/popup.html"):(f="key_16.png",e="PHP Console authorization required. Click on this icon to see authorization form.",d="auth/popup.html"));v(c,function(){chrome.pageAction.setTitle({tabId:c,title:e});chrome.pageAction.setIcon({tabId:c,path:"img/"+
f});chrome.pageAction.setPopup({tabId:c,popup:d});chrome.pageAction.show(c)})}else chrome.pageAction.hide(c)};a.q=function(b){var c=[],f=b[b.length-1];"undefined"!=typeof f.isSslOnlyMode&&(a.f[f.domain]=f.isSslOnlyMode);a.h[f.tabId]=f.url;a.m(f);f.protocol==h.protocol&&(m.r(f),f.docRoot&&(e[f.domain]=a.c(f.docRoot)),f.sourcesBasePath&&(d[f.domain]=a.c(f.sourcesBasePath)),f.isLocal&&(g[f.domain]=f.isLocal),h.getServer(f.domain,function(a){for(var d in b){var e=b[d];if(e.messages){var g=w(e.messages,
a),n=[],t=[],u=!1,r=!1,q;for(q in g){var m=g[q];p(m);var s="eval_result"==m.type,s=s|(h.consoleErrors&&"error"==m.type);if(s|=h.consoleDebug&&"debug"==m.type)"error"==m.type?u=!0:"eval_result"==m.type&&(r=!0),y(m),n.push(m);s=!1;s|=h.notifyErrors&&"error"==m.type;s|=h.notifyDebug&&"debug"==m.type;(s|="protocol_error"==m.type)&&t.push(m)}if(n.length){g=[];if(r)for(q in m=["debug","eval_result","error"],m)for(var z in n)n[z].type==m[q]&&g.push(n[z]);c.push({url:e.url,redirectUrl:e.redirectUrl,groupName:e.redirectUrl?
e.url+" --\x3e "+e.redirectUrl:e.url,collapse:!r&&!u&&(e.redirectUrl||h.consoleCollapseNoErrors),messages:g.length?g:n})}if(t.length&&!r){g=[];for(q in t)"error"==t[q].type&&(g.push(t[q]),delete t[q]);for(q in t)"error"!=t[q].type&&g.push(t[q]);x.g(g)}}}c.length&&v(f.tabId,function(){k.k(f.tabId,{_handleConsolePacks:!0,packs:c})})}))};chrome.extension.onMessage.addListener(function(b,c){if(b._handleJavascriptError){var f=b.text,l=b.url,k=b.line,m=c.tab.id;if(h.notifyJavaScriptErrors){if(f){var f=
f.replace(/^Uncaught /g,""),q=/(.+): *(.+)/.exec(f);if(q)var s="JavaScript "+q[1],f=q[2];else s="JavaScript error"}else f="... see details in JavaScript Console",s="JavaScript unknown error";var t=!1,p=l;if(p){var r=a.a(l);(q=u.exec(l))&&e[r]&&(l=e[r]+q[1],t=g[r],d[r]&&(p=n(d[r],l)))}x.d({tabId:m,type:"js_error",subject:s,data:f,file:l,line:k,path:p,isLocal:t},!0)}}});this.a=function(a){return s.exec(a)[1]}}
function C(h){function m(a,b){b=b||"";if("object"==typeof a&&null!==a){var c="",f;for(f in a){var d="";d="object"==typeof a[f]&&null!==a[f]?(d=m(a[f],b+"  "))?"\n"+d:-1!=f.indexOf(":")?"{}":"[]":a[f]+"\n";c=c+b+f+": "+d}return c}return b+a+"\n"}function x(a,b){if("debug"==b.type)return a.message;var c=a.title+": "+a.message;b.path&&(c+=" - "+b.path+(b.line?":"+b.line:""));b.trace&&(c+="\n"+b.trace);return c}function k(a,b){q++;var c="n"+q,d={type:"basic",buttons:[],priority:"error"==a.type?2:0,iconUrl:s[a.type]?
"img/"+s[a.type]:null,title:a.subject?a.subject:"debug"==a.type?a.tags.join("."):a["class"],message:m(a.data).trim()},e={isPermanent:a.permanent||!1,openUrlOnClose:a.openUrlOnClose||null,buttons:[]};if(a.path){var k=h.notifyJumpToFile&&a.isLocal&&"eval_result"!=a.type&&a.line,p=a.path+(a.line?" "+a.line:"");d.buttons.push({title:50>=p.length?p:"..."+p.substr(-47),iconUrl:k?"img/jump.png":"img/file.png"});e.buttons.push({type:"source",open:k,file:a.file,line:a.line,tabId:a.tabId})}!h.notifyCopyToClipboard||
"error"!=a.type&&"js_error"!=a.type&&"debug"!=a.type||(d.buttons.push({title:"Copy to clipboard",iconUrl:"img/clipboard.png"}),e.buttons.push({type:"copy",text:x(d,a)}));if(a.buttons)for(var u in a.buttons)k=a.buttons[u],d.buttons.push({title:k.title,iconUrl:k.icon||null}),e.buttons.push({type:"link",url:k.url});g[c]=e;e.isPermanent&&setTimeout(function(){g[c]&&(n(c),w(c,!0))},3E4);chrome.notifications.create(c,d,b)}function v(){!d&&h.notifyLifeTime&&(d=setTimeout(function(){w();d=null;Object.keys(g).length&&
v()},1E3*h.notifyLifeTime))}function w(a,b){if(!a)for(var c in g){a=c;break}!a||g[a].permanent&&!b||(delete g[a],chrome.notifications.clear(a,function(){}))}function y(a){var b=a.shift();b&&k(b,function(){y(a)})}function p(){var a=Object.keys(g);if(500<(new Date).getTime()-e)for(var b in a)w(a[b]);e=(new Date).getTime();d&&(clearTimeout(d),d=null)}function n(a){g[a].openUrlOnClose&&chrome.tabs.create({url:g[a].openUrlOnClose,active:!0})}var e=null,d=null,g={},q=1,s={update:"ok.png",js_error:"js_error.png",
error:"error.png",ahtung:"ahtung.png",debug:"info.png"},u=this;chrome.extension.onRequest.addListener(function(a){a.showNotifications?u.g(a.showNotifications):a.showNotification&&u.d(a.message)});u.g=function(a,b){b||p();y(a);v()};u.d=function(a,b){u.g([a],b)};chrome.notifications.onClosed.addListener(function(a,b){g[a]&&n(a);b&&p()});chrome.notifications.onClicked.addListener(function(a){g[a]&&(n(a),delete g[a])});chrome.notifications.onButtonClicked.addListener(function(a,b){if(g[a]){var c=g[a].buttons[b];
if("link"==c.type)chrome.tabs.create({url:c.url,active:!0});else if("source"==c.type)/:\/\//.exec(c.file)?chrome.tabs.create({url:"view-source:"+c.file,active:!0}):c.open&&document.getElementById("debug").setAttribute("src","editor://open/?file="+encodeURIComponent(c.file)+"&line="+encodeURIComponent(c.line));else if("copy"==c.type){var d=document.getElementById("textarea");d.value=c.text;d.select();document.execCommand("Copy",!1,null)}delete g[a]}})}
function A(h){function m(e,d){localStorage[e]="object"==typeof d?JSON.stringify(d):d}function x(e){return function(){return w[e]}}function k(e){return function(d){w[e]=d;m(e,d)}}var v=this;this.protocol=5;var w={version:null,consoleDebug:!0,consoleErrors:!0,consoleCollapseNoErrors:!1,notifyDebug:!0,notifyErrors:!0,notifyJavaScriptErrors:!0,notifyLifeTime:"",notifyCopyToClipboard:!1,notifyJumpToFile:!1,evalClearConsole:!0,evalShowTime:!0},y={auth:{},ignoreErrors:{},ignoreDebug:{}},p=null;this.getServer=
function(e,d,g){(g||p.transaction("servers","readwrite").objectStore("servers")).index("domain").get(e).onsuccess=function(g){g=g.target.result||{};g.domain=e;for(var h in y)"undefined"==typeof g[h]&&(g[h]=y[h]);d(g)}};this.updateServer=function(e,d,g,h){var k=p.transaction("servers","readwrite").objectStore("servers");v.getServer(e,function(e){for(var a in d)if(h&&e[a]&&"object"==typeof d[a])for(var b in d[a])e[a][b]=d[a][b];else e[a]=d[a];e=k.put(e);g&&(e.onsuccess=g)},k)};var n=indexedDB.open("php-console");
n.onupgradeneeded=function(){p=n.result;p.createObjectStore("servers",{keyPath:"domain",autoIncrement:!1}).createIndex("domain","domain",{unique:!0})};n.onsuccess=function(){p=n.result;if("undefined"==typeof localStorage.evalShowTime)for(var e in localStorage)"version"!=e&&delete localStorage[e];for(var d in w)e=localStorage.getItem(d),e="true"==e?!0:"false"==e?!1:null!==e&&"{"==e.charAt(0)&&"}"==e.charAt(e.length-1)?JSON.parse(e):e,null===e?(e=w[d],m(d,e)):w[d]=e,v.__defineGetter__(d,x(d)),v.__defineSetter__(d,
k(d));h(v)}};