/* Copyright 2011 Google Inc. All Rights Reserved. */ (function(){var k=RegExp("<[^>]*>","g"),m=RegExp("[<>]","g"),p="\" ' ( ) , - . / 1 2 2012 : ? a about and are as be but com for from have i in is it like may more my next not of on search that the this to was when with you your".split(" "),q={},t=0,u=-1,v=-1,w=function(a){a=a.replace(k,"");return a=a.replace(m,"")},x=function(a){a=w(a);return a=a.substring(0,100).toLowerCase()},y=function(){q=JSON.parse(window.localStorage.options)},z=function(a,b,c){"initialize"==a.type&&(a={instanceId:t++},c(a))},A=function(a,
b,c){"options"==a.type&&c({options:q})},D=function(a,b,c){if("fetch_raw"!=a.type&&"fetch_html"!=a.type)return!1;_gaq&&_gaq.push(["_trackEvent","lookup",a.type]);-1!=u&&v!=a.instanceId&&chrome.tabs.sendMessage(u,{type:"hide",instanceId:v});"fetch_raw"==a.type?(u=b.tab.id,v=a.instanceId):v=u=-1;var d=x(a.query),e={request:a,sanitizedQuery:d,dictResponse:null,enDictResponse:null,translateResponse:null,tabLangTranslateResponse:null,tabLang:null,numResponses:0,callback:c};b="pr,de";"fetch_html"==a.type&&
(b="pr,de,sy");google.language.define(d,q.language,q.language,function(a){e.dictResponse=a;B(e)},{restricts:b});"en"!=q.language&&google.language.define(d,"en","en",function(a){e.enDictResponse=a;B(e)},{restricts:b});C(d,"auto",function(a){e.translateResponse=a;B(e)});chrome.tabs.getSelected(null,function(a){var b=window.setTimeout(function(){e.tabLangTranslateResponse||(e.tabLangTranslateResponse=null,B(e))},800);chrome.tabs.detectLanguage(a.id,function(a){window.clearTimeout(b);"und"!=a&&(e.tabLang=
"he"==a?"iw":a,C(d,e.tabLang,function(a){e.tabLangTranslateResponse=a;B(e)}))})});return!0},C=function(a,b,c){var d=new XMLHttpRequest;d.open("GET","https://clients5.google.com/translate_a/t?client=dict-chrome-ex&sl="+b+"&tl="+q.language+"&q="+encodeURIComponent(a),!0);d.onreadystatechange=function(){if(4==d.readyState)try{c(JSON.parse(d.responseText))}catch(a){c(null)}};d.send()},B=function(a){var b=3;"en"!=q.language&&(b=4);a.numResponses++;if(a.numResponses==b){var c=b=E(a.dictResponse);"en"!=
q.language&&(c=E(a.enDictResponse));var d=F(a.translateResponse,!0),e=F(a.tabLangTranslateResponse,!0),l=q.language.toLowerCase(),g=!1,f=null,h=null;e&&a.tabLang!=l?(g=!0,f=a.tabLangTranslateResponse,h=e):!b&&d&&(g=!0,f=a.translateResponse,h=d);l=g?"translation":"definition";b||d||e||(l="none");_gaq&&_gaq.push(["_trackEvent","lookup","type_"+l]);l=encodeURIComponent(a.sanitizedQuery);d="";g&&(d="http://translate.google.com/translate_t?source=dict-chrome-ex&sl="+h.srcLang+"&tl="+q.language+"&q="+l);
e="http://www.google.com/search?source=dict-chrome-ex&defl="+q.language+"&hl="+q.language+"&q="+l+"&tbo=1&tbs=dfn:1";"en"==q.language&&(e="http://www.google.com/search?q=define+"+l);if("fetch_html"==a.request.type){if(g)if(b=f,c=d,g=F(b,!1)){g='<div class="translate-main">'+g.meaningText+'</div><div class="translate-attrib">('+g.attribution+")</div>";h="";if(b.dict&&0<b.dict.length)for(h='<h3 class="dct-tl">Translated definitions</h3>',f=0,d=b.dict.length;f<d;f++){for(var e=b.dict[f],h=h+("<b>"+e.pos+
"</b><ol>"),l=0,n=e.terms.length;l<n;l++){var r=e.terms[l];0<r.length&&(h+="<li>"+r+"</li>")}h+="</ol>"}b=g+h+('<br><div class="translate-powered">Powered by <a href="'+c+'" class="translate-link">Google Translate</a></div><br>')}else b="";else if(c=a.dictResponse,b=e,!c||c.error)b="";else{g=google.language.dictionary.createResultHtml(c);c=document.createElement("div");c.innerHTML=g;g=c.getElementsByTagName("a");for(h=g.length-1;0<=h;h--)f=g[h],"Google Dictionary"==f.innerText&&0==f.href.lastIndexOf("http://www.google.com/dictionary",
0)&&(f.href=b);b=c.innerHTML}b={eventKey:a.request.eventKey,sanitizedQuery:a.sanitizedQuery,html:b}}else{f=null;g?(f=h,f.moreUrl=d,c&&c.audio&&"en"==f.srcLang.toLowerCase()&&(f.audio=c.audio)):b&&(f=b,f.moreUrl=e);f&&!f.prettyQuery&&(f.prettyQuery=a.sanitizedQuery);b=!1;if(c="true"==q.popupDblclick&&"none"==q.popupDblclickKey||"true"==q.popupSelect&&"none"==q.popupSelectKey)e:{c=0;for(g=p.length;c<g;c++)if(a.sanitizedQuery==p[c]){c=!0;break e}c=!1}c&&(b=!0);b={eventKey:a.request.eventKey,sanitizedQuery:a.sanitizedQuery,
meaningObj:f,showOptionsTip:b}}a.callback(b)}},F=function(a,b){if(!a||a.sentences[0].orig.toLowerCase()==a.sentences[0].trans.toLowerCase())return null;var c;c=a.sentences[0].orig.toLowerCase();var d=a.sentences[0].trans.toLowerCase(),e=d;if(b&&a.dict&&0<a.dict.length)for(var l=0,g=a.dict.length;l<g;l++)for(var f=a.dict[l],h=0,n=0,r=f.terms.length;n<r&&2>h;n++){var s=f.terms[n].toLowerCase();0<s.length&&s!=c&&s!=d&&(e+=", "+s,h++)}c=w(e);(d=window["gdx.LANG_MAP"][a.src.toLowerCase()])||(d=a.src);
return{type:"translation",meaningText:c,attribution:"Translated from "+d,srcLang:a.src}},G=function(a,b){for(var c=0,d;d=a[c];c++)if(d.type&&d.type==b&&d.text)return d.text;return""},H=function(a){if(!a||0==a.length)return null;for(var b=0,c;c=a[b];b++)for(var d=0,e;e=c.entries[d];d++)if("meaning"==e.type&&e.terms&&0<e.terms.length){var l=G(e.terms,"text");if(l)return a=G(c.terms,"sound").replace("http://","https://"),{prettyQuery:G(c.terms,"text"),meaningText:l,audio:a,attribution:G(e.terms,"url")}}return null},
E=function(a){if(!a||a.error)return null;var b=H(a.primaries);b?(b.attribution="",b.type="licensedDef"):(b=H(a.webDefinitions))&&(b.type="webDef");return b},J=function(){var a=I,b={};b.language=a.language||"en";var c=function(a,b){return"true"==a||"false"==a?a:!0==a?"true":!1==a?"false":b};b.popupDblclick=c(a.popupDblclick,"true");b.popupSelect=c(a.popupSelect,"false");b.enableHttps=c(a.enableHttps,"true");b.popupDblclickKey=a.popupDblclickKey||"none";b.popupSelectKey=a.popupSelectKey||"ctrl";a.popupMode&&
("popup_disabled"==a.popupMode?b.popupDblclick="false":"popup_key_ctrl"==a.popupMode&&(b.popupDblclickKey="ctrl",b.popupSelect="true",b.popupSelectKey="ctrl"));return b},K=K||!1;
if("undefined"==typeof K||!K){dict_api.load("https://clients5.google.com?client=dict-chrome-ex","1","en");var L=window.localStorage.options,I={};L&&(I=JSON.parse(L));q=J();window.localStorage.options=JSON.stringify(q);chrome.extension.onMessage.addListener(z);chrome.extension.onMessage.addListener(A);chrome.extension.onMessage.addListener(D);window["gdx.updateOptions"]=y};})();
