//@ sourceMappingURL=prompt.map
// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Models.Prompt = (function(_super) {

    __extends(Prompt, _super);

    function Prompt() {
      return Prompt.__super__.constructor.apply(this, arguments);
    }

    return Prompt;

  })(Backbone.Model);

}).call(this);
