// Extension for Chrome Browser - Magic Actions for YouTube™ - CHROMEACTIONS.COM - Copyright 2013 Vlad and Serge Strukoff - All Rights Reserved
(function(){function r(){"complete"==document.readyState?(s(),w(),x()):setTimeout(r,250)}function y(){var a=document.getElementById("j782675h"),b;a||(a=document.createElement("style"),a.setAttribute("type","text/css"),a.id="j782675h",document.documentElement.appendChild(a),b=a.sheet,b.disabled=f.a0&&f.a4&&f.ui?!1:!0,b.insertRule("body *{color:#909090!important}",0),b.insertRule("div,div > span{background-color:#101010!important;border-color:#333!important}",1),b.insertRule("a{color:#555!important}",
2),b.insertRule("a:hover,a > span{color:#6783ab!important}",3),b.insertRule("[aria-label='Posting options']{background:url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAAS0lEQVQ4y2NgGAWjYIiD////t//HDqZRYijj////l6AZuPH////MlLqW7f///3uhBp74//8/F7WCgf/////b/v//Lz2aKEbBKMADAMppT6HBpHJKAAAAAElFTkSuQmCC') center no-repeat!important}",4),b.insertRule("span[role=listitem] *{color:#fff!important;background-color:transparent!important}",5),b.insertRule("[role=checkbox],[role=tooltip] div,.Mga,.Jea{border:0!important}",
6),b.insertRule("[role=checkbox] > div{border:1px solid #333!important}",7),b.insertRule("[aria-checked=true] > div{box-shadow:inset 0 0 0 3px #101010!important;background:#4e4e4e!important}",8),b.insertRule("span.r0,.g-h-f-p-Ov{background:none!important}",9));a.sheet.disabled=f.a0&&f.a4&&f.ui?!1:!0}function x(){document.documentElement.proc||(document.documentElement.proc=1,document.documentElement.addEventListener("click",function(a){setTimeout(s,1E3);setTimeout(w,1E3);setTimeout(x,1E3)},!1))}function w(){if(f.c0&&
(f.c2||f.c3))for(var a=document.querySelectorAll("a[oid]"),b=0,d=a.length;b<d;b++)a[b].proc||(a[b].proc=!0,a[b].addEventListener("mouseover",D,!1))}function D(a){2>this.proc&&(this.proc=2,E(this));a.stopPropagation()}function z(a,b){A("GET","//gdata.youtube.com/feeds/api/users/"+a+"?v=2&alt=json",null,"responseText",0,function(a){if(a){try{a=JSON.parse(a).entry}catch(l){return}var g,e,c=a.gd$feedLink;g=a.yt$location&&a.yt$location.$t?a.yt$location.$t:"Earth";a.yt$statistics&&a.yt$statistics.subscriberCount&&
(subscribers=a.yt$statistics.subscriberCount);a=0;for(var t=c.length;a<t;++a)c[a].rel.match(/uploads/)&&(e=c[a].countHint);if(f.c3){c=document.createElement("a");a=g;var t=g.length,B={AF:"Afghanistan",AX:"\u00c5land Islands",AL:"Albania",DZ:"Algeria",AS:"American Samoa",AD:"Andorra",AO:"Angola",AI:"Anguilla",AG:"Antigua and Barbuda",AR:"Argentina",AM:"Armenia",AW:"Aruba",AU:"Australia",AT:"Austria",AZ:"Azerbaijan",BS:"Bahamas",BH:"Bahrain",BD:"Bangladesh",BB:"Barbados",BY:"Belarus",BE:"Belgium",BZ:"Belize",
BJ:"Benin",BM:"Bermuda",BT:"Bhutan",BO:"Bolivia",BQ:"Bonaire",BA:"Bosnia and Herzegovina",BW:"Botswana",BR:"Brazil",IO:"British Indian Ocean Territory",BN:"Brunei Darussalam",BG:"Bulgaria",BF:"Burkina Faso",BI:"Burundi",KH:"Cambodia",CM:"Cameroon",CA:"Canada",CV:"Cape Verde",KY:"Cayman Islands",CF:"Central African Republic",TD:"Chad",CL:"Chile",ZH:"China",CN:"China",CX:"Christmas Island",CC:"Cocos Islands",CO:"Colombia",KM:"Comoros",CG:"Congo",CD:"Congo",CK:"Cook Islands",CR:"Costa Rica",CI:"C\u00f4te d'Ivoire",
HR:"Croatia",CU:"Cuba",CW:"Cura\u00e7ao",CY:"Cyprus",CZ:"Czech Republic",DK:"Denmark",DJ:"Djibouti",DM:"Dominica",DO:"Dominican Republic",EC:"Ecuador",EG:"Egypt",SV:"El Salvador",GQ:"Equatorial Guinea",ER:"Eritrea",EE:"Estonia",ET:"Ethiopia",FK:"Falkland Islands (Malvinas)",FO:"Faroe Islands",FJ:"Fiji",FI:"Finland",FR:"France",GF:"French Guiana",PF:"French Polynesia",TF:"French Southern Territories",GA:"Gabon",GM:"Gambia",GE:"Georgia",DE:"Germany",GH:"Ghana",GI:"Gibraltar",GR:"Greece",GL:"Greenland",
GD:"Grenada",GP:"Guadeloupe",GU:"Guam",GT:"Guatemala",GG:"Guernsey",GN:"Guinea",GW:"Guinea-Bissau",GY:"Guyana",HT:"Haiti",VA:"Vatican",HN:"Honduras",HK:"Hong Kong",HU:"Hungary",IS:"Iceland",IN:"India",ID:"Indonesia",IR:"Iran",IQ:"Iraq",IE:"Ireland",IM:"Isle of Man",IL:"Israel",IT:"Italy",JM:"Jamaica",JP:"Japan",JE:"Jersey",JO:"Jordan",KZ:"Kazakhstan",KE:"Kenya",KI:"Kiribati",KP:"North Korea",KR:"South Korea",KW:"Kuwait",KG:"Kyrgyzstan",LA:"Laos",LV:"Latvia",LB:"Lebanon",LS:"Lesotho",LR:"Liberia",
LY:"Libya",LI:"Liechtenstein",LT:"Lithuania",LU:"Luxembourg",MO:"Macao",MK:"Macedonia",MG:"Madagascar",MW:"Malawi",MY:"Malaysia",MV:"Maldives",ML:"Mali",MT:"Malta",MH:"Marshall Islands",MQ:"Martinique",MR:"Mauritania",MU:"Mauritius",YT:"Mayotte",MX:"Mexico",FM:"Micronesia",MD:"Moldova",MC:"Monaco",MN:"Mongolia",ME:"Montenegro",MS:"Montserrat",MA:"Morocco",MZ:"Mozambique",MM:"Myanmar",NA:"Namibia",NR:"Nauru",NP:"Nepal",NL:"Netherlands",NC:"New Caledonia",NZ:"New Zealand",NI:"Nicaragua",NE:"Niger",
NG:"Nigeria",NU:"Niue",NF:"Norfolk Island",MP:"Northern Mariana Islands",NO:"Norway",OM:"Oman",PK:"Pakistan",PW:"Palau",PS:"Palestinian Territory",PA:"Panama",PG:"Papua New Guinea",PY:"Paraguay",PE:"Peru",PH:"Philippines",PN:"Pitcairn",PL:"Poland",PT:"Portugal",PR:"Puerto Rico",QA:"Qatar",RE:"R\u00e9union",RO:"Romania",RU:"Russia",RW:"Rwanda",BL:"Saint Barth\u00e9lemy",SH:"Saint Helena",KN:"Saint Kitts and Nevis",LC:"Saint Lucia",MF:"Saint Martin",PM:"Saint Pierre and Miquelon",VC:"Saint Vincent and the Grenadines",
WS:"Samoa",SM:"San Marino",ST:"Sao Tome and Principe",SA:"Saudi Arabia",SN:"Senegal",RS:"Serbia",SC:"Seychelles",SL:"Sierra Leone",SG:"Singapore",SX:"Sint Maarten",SK:"Slovakia",SI:"Slovenia",SB:"Solomon Islands",SO:"Somalia",ZA:"South Africa",GS:"South Georgia and the South Sandwich Islands",SS:"South Sudan",ES:"Spain",LK:"Sri Lanka",SD:"Sudan",SR:"Suriname",SZ:"Swaziland",SE:"Sweden",CH:"Switzerland",SY:"Syria",TW:"Taiwan",TJ:"Tajikistan",TZ:"Tanzania",TH:"Thailand",TL:"Timor-Leste",TG:"Togo",TK:"Tokelau",
TO:"Tonga",TT:"Trinidad and Tobago",TN:"Tunisia",TR:"Turkey",TM:"Turkmenistan",TC:"Turks and Caicos Islands",TV:"Tuvalu",UG:"Uganda",UA:"Ukraine",AE:"United Arab Emirates",GB:"United Kingdom",US:"United States",UM:"U.S. Minor Outlying Islands",UY:"Uruguay",UZ:"Uzbekistan",VU:"Vanuatu",VE:"Venezuela",VN:"Viet Nam",VG:"Virgin Islands, British",VI:"Virgin Islands, U.S.",WF:"Wallis and Futuna",EH:"Western Sahara",YE:"Yemen",ZM:"Zambia",ZW:"Zimbabwe",EA:"Earth"};2<t&&(a="Earth"==g?"EA":g.slice(t-2));c.href=
"http://www.fastsatfinder.com/country-flags-geo-location.html?cc="+a;c.target="_blank";B[a]&&(c.title=B[a]);c.className="maFlag";c.style.setProperty("width","16px",h);c.style.setProperty("height","11px",h);c.style.setProperty("display","inline-block",h);c.style.setProperty("margin-left","5px",h);c.style.setProperty("cursor","pointer",h);c.style.setProperty("background","url("+F+"i/f/"+a+".png) no-repeat",h);g=b.parentElement;"h3"===g.localName&&(g=g.parentElement);g.appendChild(c)}f.c2&&(g=subscribers,
c=b.parentElement,a=document.createElement("span"),a.style.setProperty("color","#2793e6",h),a.style.setProperty("margin-left","7px",h),a.style.setProperty("cursor","default",h),a.title="This user uploaded "+e+" videos and have "+g+" subscribers",a.innerHTML=e+" / "+g,"h3"===c.localName&&(c=c.parentElement),c.appendChild(a))}})}function E(a){var b=a.getAttribute("oid"),d,l;b&&(0==b.indexOf("UC")?z(b.slice(2),a):A("GET","//www.youtube.com/profile_redirector/"+b,null,"response",1,function(b){b&&b.documentElement&&
(l=b.documentElement.querySelector("meta[itemprop=channelId]"))&&(d=l.getAttribute("content"))&&z(d.slice(2),a)}))}function s(){if(f.a0&&f.a2)for(var a=document.images,b,d=0,l=a.length;d<l;d++)b=a[d],b.prc||(b.prc=1,b.addEventListener("mouseover",G,!1),b.addEventListener("mouseout",H,!1))}function G(a){k&&(clearTimeout(k),k=0);var b=this,d=I(b),l=d[0],g=d[1],f=this.offsetWidth,c=this.offsetHeight;b.removeAttribute("title");k=setTimeout(function(){var a,d,k,m,u=b.src.replace(/s\d+-c-k/,"s256-c-k");
300>l?(a=l+f+20,k="magic-tip-left"):(a=l-256-20,k="magic-tip-right");d=g-parseInt((256-c)/2)-5;m=128;0>d&&(m+=d,d=0);m+="px";var u="url("+u+") center center/100% auto no-repeat",n,p;if(e)n=e.firstElementChild,p=e.lastElementChild;else{e=document.createElement("div");n=document.createElement("div");p=document.createElement("iframe");e.className="magic-tip";for(var r=p,v=["scrolling","no","frameborder",0],q=0,s=v.length;q<s;q+=2)r.setAttribute(v[q],v[q+1]);e.appendChild(n);e.appendChild(p);document.body.appendChild(e)}C(e,
["top",d+"px","left",a+"px","height","256px"],1);C(p,["width","256px","height","256px","background",u,"display","block"],1);k?(n.style.setProperty("display",""),n.className=k,m&&n.style.setProperty("top",m,h)):n.style.setProperty("display","none",h);e.style.setProperty("display","block",h)},500);a.stopPropagation()}function H(a){k&&(clearTimeout(k),k=0);e&&e.style.setProperty("display","none",h)}function A(a,b,d,f,g,e){var c=new XMLHttpRequest;c.onload=function(a){200==this.status?e(this[f]):e()};
c.onerror=e;c.onabort=e;c.open(a,b,!0);g&&(c.responseType="document");c.send(d)}function C(a,b,d){if(a){var e=0,f=b.length;for(d=d?h:null;e<f;e+=2)a.style.setProperty(b[e],b[e+1],d)}}function I(a){if(!a||void 0==a)return[0,0];var b=0,d=0;if(a.offsetParent){do b+=a.offsetLeft,d+=a.offsetTop;while(a=a.offsetParent)}return[b,d]}var f,F=chrome.runtime.getURL(""),e,k,h="important";chrome.runtime.sendMessage('{"id":0}',function(a){a&&a.ver&&(f=a,y(),a=document.getElementById("s773549"),a||(a=document.createElement("style"),
a.setAttribute("type","text/css"),a.id="s773549",document.documentElement.appendChild(a),a=a.sheet,a.insertRule(".magic-tip{z-index:2147483648;position:absolute;background-color:#333;border:7px solid #333;border-radius:7px}",0),a.insertRule(".magic-tip-right{position:absolute;top:50%;right:-17px;margin-top:-10px;width:0;height:0;border-style:solid;border-width:10px 0 10px 10px;border-color:transparent #333!important}",1),a.insertRule(".magic-tip-left{position:absolute;top:50%;left:-17px;margin-top:-10px;width:0;height:0;border-style:solid;border-width:10px 10px 10px 0;border-color:transparent #333!important}",
2)),r())});window.addEventListener("message",function(a){var b=0;try{b=JSON.parse(a.data)}catch(d){return}630==b.id&&(f=b.opt,y())},!1)})();
