// Extension for Chrome Browser - Magic Actions for YouTube™ - CHROMEACTIONS.COM - Copyright 2013 Vlad and Serge Strukoff - All Rights Reserved
window.addEventListener("load",ccMenu,!1);
function ccMenu(){function t(){var a=this.id;k!=a&&(k&&(document.getElementById(k).className="nav"),k=a,this.className="nav act",r(a))}function r(a){var b,c=document.getElementById("box");if("menu0"==a)b=[3,"orange","report.png",0,7,0,"help1.png",1,3,"blue","options.png",2,3,"violet","plugins.png",3,3,"violet","history.png",4,3,"violet","extensions.png",5,3,"violet","security.png",6,0,"fb","facebook32.png",7,0,"yt","youtube32.png",8,0,"gp","gplus32.png",9,0,"rt","rate32.png",10];else if("menu1"==
a){b=document.getElementById("donate");if(!b.hasAttribute("init")){for(var f=chrome.i18n.getMessage(a).split(";"),g=b.innerHTML,h=0,n;n=f[h];h++)g=g.replace("t"+(10+h),n);b.innerHTML=g;b.setAttribute("init",!0);u()}c.style.display="none";b.style.display="block";return}h=0;a=chrome.i18n.getMessage(a).split(";");for(var k=document.createDocumentFragment(),d,e,l,p,q,s,m=0;m<b.length;m+=4)p=m/4,d=b[m],l=b[m+1],q=b[m+2],2==d?(e=new Uint8Array(1),crypto.getRandomValues(e),e=e[0]%l.length,p="i"+(p+e),l=
l[e],q="i/menu/"+q[e],s=a[b[m+3]+e]):(p="i"+p,q="i/menu/"+q,s=a[b[m+3]]),7>d?(n=0,f=document.createElement("div"),g=document.createElement("div"),e=new Image,l="btn "+l,2<d&&(l+=" wide"),f.id=p,f.className=l,e.className="icn",g.className="txt0",e.dataset.url=e.src=q,g.textContent=s,f.appendChild(e),f.appendChild(g),k.appendChild(f)):(d=document.createElement("div"),l=document.createElement("div"),e=new Image,e.src=q,d.id=p,d.className="adt a"+n,e.className="icnm",l.className="txt1",l.textContent=
s,d.appendChild(e),f.insertBefore(d,g),f.insertBefore(l,g),n++),h++;c.innerHTML="";c.appendChild(k);c.style.display="";document.getElementById("donate").style.display=""}function v(a){var b=a.target.id?a.target:a.target.parentElement,c=b.id;"menu0"==k&&(c=parseInt(b.id.slice(1)),0==c?h("http://www.chromeactions.com/magic-actions-for-youtube-support.html"):1==c?h("http://www.chromeactions.com/magic-actions-for-youtube-help-and-tips.html"):2==c?chrome.runtime.sendMessage('{"id":7}'):3==c?h("chrome://plugins"):
4==c?h("http://www.youtube.com/my_history"):5==c?h("chrome://extensions"):6==c?h("http://www.hotcleaner.com/clickclean-app.html"):7==c?h("https://www.facebook.com/magicactions"):8==c?h("http://www.youtube.com/user/StrukoffBrothers/feed"):9==c?h("https://plus.google.com/110367533603365326399/posts"):10==c&&h("https://chrome.google.com/webstore/detail/magic-actions-for-youtube/abjcfabbhafbcdfjoecdgepllmpfceif/reviews"));a.stopPropagation()}function u(){var a=[{lang:"de es fi fr el es it nl pt_PT et lv lt cr bg ro sk sl sr".split(" "),
title:"Euro",sign:"\u20ac",currency_code:"EUR",min:5,max:50,step:5},{title:"British Pounds",lang:["en-GB"],sign:"\u00a3",currency_code:"GBP",min:5,max:50,step:5},{title:"Hungarian Forints",lang:["hu"],sign:"Ft.",currency_code:"HUF",min:1E3,max:1E4,step:500},{title:"Czech Korunas",lang:["cs"],sign:"K\u010d.",currency_code:"CZK",min:100,max:1E3,step:50},{title:"Japanese Yen",lang:["ja"],sign:"\u00a5",currency_code:"JPY",min:500,max:5E3,step:250},{title:"Swedish Kronas",lang:["sv"],sign:"Kr.",currency_code:"SEK",
min:50,max:500,step:25},{title:"Danish Krones",lang:["da"],sign:"Kr.",currency_code:"DKK",min:50,max:500,step:25},{title:"Polish Zloty",lang:["pl"],sign:"z\u0142",currency_code:"PLN",min:10,max:150,step:10},{title:"Norwegian Krones",lang:["nb"],sign:"Kr.",currency_code:"NOK",min:50,max:500,step:25},{title:"Brazilian Reals",lang:["pt-BR"],sign:"R$",currency_code:"BRL",min:10,max:100,step:10},{title:"Taiwan Dollars",lang:["zh-TW"],sign:"NT$",currency_code:"TWD",min:100,max:2E3,step:100}],b=document.getElementById("rng"),
c=document.getElementById("amnt"),f=document.getElementById("ctrb"),g="$",k="USD",n="&country=US",r=navigator.language;b.min=5;b.max=100;b.step=1;b.value=5;c.title="US Dollars";for(var d=0,e=a.length;d<e;d++)if(-1<a[d].lang.indexOf(r)){b.min=a[d].min;b.max=a[d].max;b.step=a[d].step;b.value=3*a[d].min;c.title=a[d].title;g=a[d].sign;k=a[d].currency_code;n="";break}c.textContent=g+" "+b.value;b.addEventListener("change",function(a){c.textContent=g+" "+b.value;a.stopPropagation()},!1);f.addEventListener("click",
function(){h("https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=webmaster@mixesoft.com&item_name=Donation for Magic Actions App&no_note=1&no_shipping=1"+n+"&currency_code="+k+"&amount="+b.value)},!1)}function h(a){chrome.tabs.create({url:a})}var k="menu0";(function(){var a=chrome.i18n.getMessage("menu").split(";"),b=document.createDocumentFragment(),c=document.getElementById("menu"),f;c.id="menu";for(var g=0;g<a.length;g++)f=document.createElement("div"),f.className="nav",f.id="menu"+
g,f.textContent=a[g],f.addEventListener("click",t,!1),b.appendChild(f);c.appendChild(b);document.getElementById(k).className="nav act";r(k);document.getElementById("box").addEventListener("click",v,!1)})()};
