// Extension for Chrome Browser - Magic Actions for YouTube™ - CHROMEACTIONS.COM - Copyright 2013 Vlad and Serge Strukoff - All Rights Reserved
var bLocalPage="chrome-extension:"===window.location.protocol?!0:!1;bLocalPage&&window.location.search!="?s=7"+(new Date).getDate()?window.location.href="options.html":magicOpt();
function magicOpt(){function F(){b("prf2")?J():setTimeout(F,200)}function J(){var u=b("prf"),G=b("prf2"),c;u&&chrome.runtime.sendMessage('{"id":0}',function(d){if(0<d.nv){if(c=b("m0"))c.textContent=chrome.i18n.getMessage("m1",[B,d.ver]),c.style.display="block";k("nv",0)}c=g("h3");c.textContent=B+" v"+d.ver+" "+a("m2");u.appendChild(c);c=g("p");c.id="m2";c.appendChild(document.createTextNode(chrome.i18n.getMessage("m3",B)));u.appendChild(c);c=g("ul");c.id="opt";u.appendChild(c);e(c,"mwvc",a("o8"),
d.mwvc,0,0,"http://www.chromeactions.com/magic-actions-for-youtube-volume-control.html");w=d.mwvct;var h=c,f=g("li");f.id="mwvct";f.className="sub";f.setAttribute("disabled",!b("mwvc").checked);h.appendChild(f);p(f,"vt0",a("o82"),H);p(f,"vt1",a("o83"),H);b("vt"+w).checked=!0;q=d.color;h=g("li");f=g("label");h.className="sub";h.setAttribute("disabled",!b("mwvc").checked);h.id="color";f.textContent=a("o9");h.appendChild(f);b("opt").appendChild(h);l("red");l("LightPink");l("orange");l("lime");l("GreenYellow");
l("yellow");l("gold");l("DodgerBlue");l("aqua");l("magenta");l("DeepPink");l("white");(f=b(q))||(q="lime");b(q).className="sel";x=d.mwvci;var h=c,f=g("li"),r=g("label");f.id="mwvci";f.className="sub";f.setAttribute("disabled",!b("mwvc").checked);r.textContent=a("o23");f.appendChild(r);h.appendChild(f);p(f,"vc1",a("o24"),C);p(f,"vc2",a("o25"),C);p(f,"vc0",a("o26"),C);b("vc"+x).checked=!0;var h=a("o27"),f=d.gap,r=!b("mwvc").checked,n=g("li"),v=g("label"),m=g("input");v.textContent=h;v.setAttribute("for",
"gap");m.type="range";m.min=1;m.max=25;m.step=1;m.value=f;m.id="gap";m.title="Range: 1-25";n.appendChild(v);n.appendChild(m);v=g("span");v.textContent=f;n.appendChild(v);n.className="sub";n.setAttribute("disabled",r);b("opt").appendChild(n);m.addEventListener("change",K,!1);e(c,"hq",a("o90"),d.hq,0,0,"http://www.chromeactions.com/magic-actions-for-youtube-autohd.html");s=d.hqi;h=g("li");h.id="hqi";h.className="sub";h.setAttribute("disabled",!b("hq").checked);b("opt").appendChild(h);t("highres",a("o91"));
t("hd1080",a("o92"));t("hd720",a("o93"));t("large",a("o94"));t("medium",a("o95"));t("small",a("o96"));t("tiny",a("o97"));(h=b(s))||(s="highres");b(s).checked=!0;G&&(c=g("ul"),c.id="opt2",G.appendChild(c));e(c,"ha",a("o20"),d.ha);e(c,"wide",a("o28"),d.wide);e(c,"align",a("o80"),d.align);e(c,"cin",a("o29"),d.cin,0,0,"http://www.chromeactions.com/magic-actions-for-youtube-cinema.html");y=d.cini;h=c;f=g("li");r=g("label");f.id="cini";f.className="sub";f.setAttribute("disabled",!b("cin").checked);r.textContent=
a("o32");f.appendChild(r);h.appendChild(f);p(f,"ca0",a("o33"),D);p(f,"ca1",a("o34"),D);p(f,"ca2",a("o35"),D);b("ca"+y).checked=!0;e(c,"cina",a("o30"),d.cina,1,!b("cin").checked);e(c,"cinf",a("o31"),d.cinf,1,!b("cin").checked);e(c,"pt",a("o65"),d.pt);E("pt");z=d.pti;h=c;f=g("li");f.id="pti";f.className="sub";f.setAttribute("disabled",!b("pt").checked);h.appendChild(f);p(f,"pt0",a("o66"),I);p(f,"pt1",a("o67"),I);b("pt"+z).checked=!0;e(c,"pause",a("o17"),d.pause);e(c,"plist",a("o19"),d.plist,1,!b("pause").checked);
e(c,"buf",a("o18"),d.buf);e(c,"buf1",a("o63"),d.buf1,1,!b("buf").checked);e(c,"loop",a("o40"),d.loop);e(c,"hide",a("o41"),d.hide);e(c,"c0",a("o70"),d.c0,0,0,"http://www.chromeactions.com/magic-actions-for-youtube-comments.html");e(c,"c2",a("o72"),d.c2,1,!b("c0").checked);e(c,"c3",a("o73"),d.c3,1,!b("c0").checked);e(c,"anns",a("o42"),d.anns);e(c,"f0",a("o43"),d.f0);b("f0").parentElement.title="Show/Hide the Filters button so you can apply a filter (grayscale, flip, high contrast etc.) to any video";
E("f0");e(c,"h0",a("o50"),d.h0);e(c,"h1",a("o51"),d.h1,1,!b("h0").checked);e(c,"h2",a("o52"),d.h2,1,!b("h0").checked);e(c,"h3",a("o53"),d.h3,1,!b("h0").checked);e(c,"h4",a("o54"),d.h4,1,!b("h0").checked);e(c,"h5",a("o55"),d.h5,1,!b("h0").checked);e(c,"h6",a("o64"),d.h6,1,!b("h0").checked);e(c,"a0",a("o60"),d.a0,0,0,"http://www.chromeactions.com/magic-actions-for-youtube-themes.html");e(c,"a1",a("o61"),d.a1,1,!b("a0").checked);e(c,"a2",a("o62"),d.a2,1,!b("a0").checked);e(c,"a3",a("o71"),d.a3,1,!b("a0").checked);
E("a3");e(c,"a4",a("o81"),d.a4,1,!b("a0").checked)})}function k(a,b){chrome.runtime.sendMessage(JSON.stringify({id:4,name:a,value:b}))}function E(u){var e=g("sup");e.textContent=a("m4");e.style.color="red";e.style.verticalAlign="top";b(u).nextElementSibling.appendChild(e)}function L(a){b(q).className="";q=this.id;this.className="sel";k("color",q)}function H(a){b("vt"+w).checked=!1;w=parseInt(this.id.charAt(2));this.checked=!0;k("mwvct",w)}function C(a){b("vc"+x).checked=!1;x=parseInt(this.id.charAt(2));
this.checked=!0;k("mwvci",x)}function D(a){b("ca"+y).checked=!1;y=parseInt(this.id.charAt(2));this.checked=!0;k("cini",y)}function I(a){b("pt"+z).checked=!1;z=parseInt(this.id.charAt(2));this.checked=!0;k("pti",z)}function M(a){b(s).checked=!1;s=this.id;this.checked=!0;k("hqi",s)}function N(a){"cinf"==this.id?(b("cina").checked=!1,k("cina",!1)):"cina"==this.id&&(b("cinf").checked=!1,k("cinf",!1));k(this.id,this.checked);a=this.parentElement;if("sub"!=a.className)for(a=a.nextElementSibling;a&&"sub"==
a.className;)a.setAttribute("disabled",!this.checked),a=a.nextElementSibling}function O(a){k(a.id,parseInt(a.value))}function K(a){A&&(clearTimeout(A),A=0);this.nextElementSibling.textContent=this.value;A=setTimeout(O,1E3,this)}function l(a){var e=g("button");e.id=a;e.style.backgroundColor=a;b("color").appendChild(e);e.addEventListener("click",L,!1)}function p(a,b,c,d){var e=g("label"),f=g("input");f.type="radio";f.id=b;a.appendChild(f);e.textContent=c;e.setAttribute("for",b);a.appendChild(e);f.addEventListener("click",
d,!1)}function t(a,e){var c=b("hqi"),d=g("label"),h=g("input");h.type="radio";h.id=a;c.appendChild(h);d.textContent=e;d.setAttribute("for",a);c.appendChild(d);h.addEventListener("click",M,!1)}function e(a,b,c,d,e,f,l){var n=g("li"),k=g("label"),m=g("input");k.textContent=c;k.setAttribute("for",b);m.type="checkbox";m.id=b;m.checked=d;n.appendChild(m);n.appendChild(k);e?(n.className="sub",n.setAttribute("disabled",f)):n.className="opt";l&&(b=g("a"),b.href=l,b.setAttribute("target","_blank"),b.className=
"help",n.appendChild(b));a.appendChild(n);m.addEventListener("click",N,!1)}function b(a){return document.getElementById(a)}function g(a){return document.createElement(a)}function a(a){return chrome.i18n.getMessage(a)}var q,s,w,x,y,z,A=0,B=chrome.i18n.getMessage("extName");F()};
