// Generated by CoffeeScript 1.6.1
(function() {

  BH.Trackers.ErrorTracker = (function() {

    ErrorTracker.prototype.key = "eb2245d5729a3c65d7e429f4e7690a62";

    ErrorTracker.prototype.version = "2.4.1";

    ErrorTracker.prototype.environment = "production";

    function ErrorTracker(tracker) {
      this.tracker = tracker;
      this.tracker.setContext({
        version: this.version
      });
      this.tracker.configure({
        api_key: this.key,
        environment: this.environment,
        onerror: true
      });
    }

    ErrorTracker.prototype.report = function(e, data) {
      if (data == null) {
        data = {};
      }
      return this.tracker.notify(e, {
        context: data
      });
    };

    return ErrorTracker;

  })();

}).call(this);
