//@ sourceMappingURL=mailing_list_view.map
// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Views.MailingListView = (function(_super) {

    __extends(MailingListView, _super);

    function MailingListView() {
      return MailingListView.__super__.constructor.apply(this, arguments);
    }

    MailingListView.include(BH.Modules.I18n);

    MailingListView.prototype.className = 'sign_up_view';

    MailingListView.prototype.template = BH.Templates['sign_up'];

    MailingListView.prototype.events = {
      'click .close': 'closeClicked'
    };

    MailingListView.prototype.initialize = function() {
      this.chromeAPI = chrome;
      return this.attachGeneralEvents();
    };

    MailingListView.prototype.render = function() {
      this.$el.html(this.renderTemplate(this.getI18nValues()));
      return this;
    };

    MailingListView.prototype.closeClicked = function(ev) {
      ev.preventDefault();
      return this.close();
    };

    MailingListView.prototype.openClicked = function(ev) {
      ev.preventDefault();
      return this.open();
    };

    MailingListView.prototype.getI18nValues = function() {
      return this.t(['close_button', 'mailing_list_title', 'mailing_list_description', 'mailing_list_link', 'mailing_list_promise', 'leave_a_review']);
    };

    return MailingListView;

  })(BH.Views.ModalView);

}).call(this);
