// Generated by CoffeeScript 1.6.1
(function() {

  this.BH = {
    Views: {},
    Modals: {},
    Models: {},
    Collections: {},
    Lib: {
      ContextMenus: {}
    },
    Modules: {},
    Templates: {},
    Trackers: {},
    Presenters: {},
    Persistence: {},
    Migrations: {},
    Init: {},
    Chrome: {},
    Base: function() {}
  };

  if (typeof onServer !== "undefined" && onServer !== null) {
    module.exports = this.BH;
  }

}).call(this);
