/*
 MIT License (c) copyright 2011-2013 original author or authors */
define("background/incomingCache",[],function(){return{streamsCache:[],filesToOpen:[]}});
define("background/cache",[],function(){var l=function(){var e=window.localStorage.getItem("qo_background_cache");try{e=e?JSON.parse(e):{}}catch(c){e={},console.warn("Failed to parse background cache so resetting it to be empty: "+c)}return e},h=function(e){if(e){try{e=JSON.stringify(e)}catch(c){e={},console.warn("Failed to stringify background cache so resetting it to be empty: "+c)}window.localStorage.setItem("qo_background_cache",e)}};return{overwriteEntry:function(e,c,n){if(e){var k=l();k[e]=
{tab:c,srcPath:n};h(k)}},containsTabId:function(e){var c=!1;if(e){var n=l(),k;for(k in n)if(n[k].tab===e){c=!0;break}}return c},removeAllTabIds:function(){var e=l(),c;for(c in e)e[c].tab=void 0;h(e)},deleteOrphans:function(e){for(var c=[],n=l(),k=e.length,g=0;g<k;g++){var p=e[g];if(!p.isDirectory){var p=p.fullPath,s=n[p];if(!s||!s.tab)c.push(p),delete n[p]}}h(n);return c},getCache:function(){return l()}}});
define("qowtRoot/utils/typeUtils",[],function(){function l(c,n,k){if(k.types.every(function(c){var g=e[c];if(!g)throw Error("Bad config to checkArgTypes: unknown type: "+c);return!g(k.value)})){var g=1===k.types.length?k.types[0]:"["+k.types.join(",")+"]";throw Error("Argument "+n+" passed to function "+c+" was supposed to be of type "+g+" but had value "+k.value);}}var h={checkArgTypes:function(c,e){for(var k in e){var g={value:e[k][0],types:e[k].slice(1)};l(c,k,g)}},isObject:function(c){return"object"===
typeof c&&null!==c},isPromise:function(c){return Promise.cast(c)===c},isPromiseLike:function(c){return!(!c||!h.isFunction(c.then))},isList:function(c){return"[object Array]"===Object.prototype.toString.call(c)},isNumber:function(c){return"number"===typeof c&&!isNaN(c)},isInteger:function(c){return"number"===typeof c&&parseInt(c,10)===c},isFunction:function(c){return"function"===typeof c},isString:function(c){return"[object String]"===Object.prototype.toString.call(c)},isRegex:function(c){return"[object RegExp]"===
Object.prototype.toString.call(c)},isNode:function(c){return c instanceof Node},isNull:function(c){return null===c},isUndefined:function(c){return void 0===c},isBoolean:function(c){return"boolean"===typeof c},isArgumentsObjectOrList:function(c){return c instanceof Object&&c.hasOwnProperty("length")},extend:function(c,e){for(var k in e)e.hasOwnProperty(k)&&(c[k]=e[k])},createNewType:function(c){var h=function(){},k={isOfType:function(c){return void 0!==c&&null!==c&&c.constructor===h},markAsType:function(c){Object.defineProperty(c,
"constructor",{value:h,configurable:!1,writable:!1,enumerable:!1});return c}};if(c){if(e[c])throw Error("Already registered type "+c);e[c]=k.isOfType}return k}},e={string:h.isString,object:h.isObject,promise:h.isPromise,promiseLike:h.isPromiseLike,node:h.isNode,regex:h.isRegex,"function":h.isFunction,number:h.isNumber,list:h.isList,"boolean":h.isBoolean,"null":h.isNull,undefined:h.isUndefined};return h});
(function(l,h){l("third_party/when/when",["require"],function(e){function c(a,d,b,f){return(a instanceof n?a:k(a)).then(d,b,f)}function n(a,d){this._message=a;this.inspect=d}function k(a){return g(function(d){d(a)})}function g(d){return p(d,a.PromiseStatus&&a.PromiseStatus())}function p(a,b){function f(a){if(h){var m=h;h=d;v(function(){k=G(g,a);b&&q(k,b);l(m,k)})}}function c(a){f(t(a))}function e(a){if(h){var d=h;v(function(){l(d,H(a))})}}var g,k,h=[];g=new n(function(a,d,m,b){function f(T){T._message(a,
d,m,b)}h?h.push(f):v(function(){f(k)})},function(){return k?k.inspect():{state:"pending"}});g._status=b;try{a(f,c,e)}catch(p){c(p)}return g}function l(a,d){for(var b=0;b<a.length;b++)a[b](d)}function z(a){return A(new w(a),function(){return r(a)})}function t(a){return A(new B(a),function(){return M(a)})}function A(a,d){return new n(function(d,b,f){try{f(a[d].apply(a,b))}catch(T){f(t(T))}},d)}function H(a){return new n(function(d,b,f,c){d=b[2];try{c("function"===typeof d?d(a):a)}catch(e){c(e)}})}function G(a,
d){if(d===a)return t(new TypeError);if(d instanceof n)return d;try{var b=d===Object(d)&&d.then;return"function"===typeof b?C(b,d):z(d)}catch(f){return t(f)}}function C(a,d){return g(function(b,f){N(a,d,b,f)})}function w(a){this.value=a}function B(a){this.reason=a}function q(a,d){a.then(function(){d.fulfilled()},function(a){d.rejected(a)})}function O(a){return a&&"function"===typeof a.then}function R(a,d,b,f,e){return c(a,function(a){return g(function(b,f,m){function L(a){l(a)}function y(a){Q(a)}var e,
g,k,h,Q,l,p,q;p=a.length>>>0;e=Math.max(0,Math.min(d,p));k=[];g=p-e+1;h=[];if(e){l=function(a){h.push(a);--g||(Q=l=D,f(h))};Q=function(a){k.push(a);--e||(Q=l=D,b(k))};for(q=0;q<p;++q)q in a&&c(a[q],y,L,m)}else b(k)}).then(b,f,e)})}function I(a,d,f,c){return b(a,D).then(d,f,c)}function b(a,d,b){return c(a,function(a){return p(function(f,m,e){function k(a,y){c(a,d,b).then(function(a){g[y]=a;--q||f(g)},m,e)}var g,h,q,l;q=h=a.length>>>0;g=[];if(q)for(l=0;l<h;l++)l in a?k(a[l],l):--q;else f(g)})})}function r(a){return{state:"fulfilled",
value:a}}function M(a){return{state:"rejected",reason:a}}function v(a){1===x.push(a)&&E(J)}function J(){l(x);x=[]}function D(a){return a}function P(d){"function"===typeof a.reportUnhandled?a.reportUnhandled():v(function(){throw d;});throw d;}c.promise=g;c.resolve=k;c.reject=function(a){return c(a,t)};c.defer=function(){var a,b,f;a={promise:d,resolve:d,reject:d,notify:d,resolver:{resolve:d,reject:d,notify:d}};a.promise=b=g(function(d,c,e){a.resolve=a.resolver.resolve=function(a){if(f)return k(a);f=
!0;d(a);return b};a.reject=a.resolver.reject=function(a){if(f)return k(t(a));f=!0;c(a);return b};a.notify=a.resolver.notify=function(a){e(a);return a}});return a};c.join=function(){return b(arguments,D)};c.all=I;c.map=function(a,d){return b(a,d)};c.reduce=function(a,d){var b=N(u,arguments,1);return c(a,function(a){var f;f=a.length;b[0]=function(a,b,m){return c(a,function(a){return c(b,function(b){return d(a,b,m,f)})})};return K.apply(a,b)})};c.settle=function(a){return b(a,r,M)};c.any=function(a,
d,b,f){return R(a,1,function(a){return d?d(a[0]):a[0]},b,f)};c.some=R;c.isPromise=O;c.isPromiseLike=O;n.prototype={then:function(a,d,b){var f,c;f=arguments;c=this._message;return p(function(a,d,b){c("when",f,a,b)},this._status&&this._status.observed())},otherwise:function(a){return this.then(d,a)},ensure:function(a){function d(){return k(a())}return"function"===typeof a?this.then(d,d).yield(this):this},done:function(a,d){this.then(a,d).otherwise(P)},yield:function(a){return this.then(function(){return a})},
tap:function(a){return this.then(a).yield(this)},spread:function(a){return this.then(function(b){return I(b,function(b){return a.apply(d,b)})})},always:function(a,d){return this.then(a,a,d)}};w.prototype.when=function(a){return"function"===typeof a?a(this.value):this.value};B.prototype.when=function(a,d){if("function"===typeof d)return d(this.reason);throw this.reason;};var K,u,N,E,x,S,F,a,d;x=[];S=h.setTimeout;a="undefined"!==typeof console?console:c;if("object"===typeof process&&process.nextTick)E=
process.nextTick;else if(F=h.MutationObserver||h.WebKitMutationObserver)E=function(a,d,b){var f=a.createElement("div");(new d(b)).observe(f,{attributes:!0});return function(){f.setAttribute("x","x")}}(document,F,J);else try{E=e("vertx").runOnLoop||e("vertx").runOnContext}catch(f){E=function(a){S(a,0)}}e=Function.prototype;F=e.call;N=e.bind?F.bind(F):function(a,d){return a.apply(d,u.call(arguments,2))};e=[];u=e.slice;K=e.reduce||function(a){var d,b,f,c,e;e=0;d=Object(this);c=d.length>>>0;b=arguments;
if(1>=b.length)for(;;){if(e in d){f=d[e++];break}if(++e>=c)throw new TypeError;}else f=b[1];for(;e<c;++e)e in d&&(f=a(f,d[e],e,d));return f};return c})})("function"===typeof define&&define.amd?define:function(l){module.exports=l(require)},this);
(function(){var l=this,h=l._,e={},c=Array.prototype,n=Object.prototype,k=c.push,g=c.slice,p=c.concat,s=n.toString,z=n.hasOwnProperty,t=c.forEach,A=c.map,H=c.reduce,G=c.reduceRight,C=c.filter,w=c.every,B=c.some,q=c.indexOf,O=c.lastIndexOf,n=Array.isArray,R=Object.keys,I=Function.prototype.bind,b=function(a){return a instanceof b?a:this instanceof b?(this._wrapped=a,void 0):new b(a)};"undefined"!=typeof exports?("undefined"!=typeof module&&module.exports&&(exports=module.exports=b),exports._=b):l._=
b;b.VERSION="1.5.2";var r=b.each=b.forEach=function(a,d,f){if(null!=a)if(t&&a.forEach===t)a.forEach(d,f);else if(a.length===+a.length)for(var m=0,c=a.length;c>m&&d.call(f,a[m],m,a)!==e;m++);else for(var L=b.keys(a),m=0,c=L.length;c>m&&d.call(f,a[L[m]],L[m],a)!==e;m++);};b.map=b.collect=function(a,d,b){var m=[];return null==a?m:A&&a.map===A?a.map(d,b):(r(a,function(a,c,e){m.push(d.call(b,a,c,e))}),m)};b.reduce=b.foldl=b.inject=function(a,d,f,m){var c=2<arguments.length;if(null==a&&(a=[]),H&&a.reduce===
H)return m&&(d=b.bind(d,m)),c?a.reduce(d,f):a.reduce(d);if(r(a,function(a,b,e){c?f=d.call(m,f,a,b,e):(f=a,c=!0)}),!c)throw new TypeError("Reduce of empty array with no initial value");return f};b.reduceRight=b.foldr=function(a,d,f,m){var c=2<arguments.length;if(null==a&&(a=[]),G&&a.reduceRight===G)return m&&(d=b.bind(d,m)),c?a.reduceRight(d,f):a.reduceRight(d);var e=a.length;if(e!==+e)var y=b.keys(a),e=y.length;if(r(a,function(b,g,k){g=y?y[--e]:--e;c?f=d.call(m,f,a[g],g,k):(f=a[g],c=!0)}),!c)throw new TypeError("Reduce of empty array with no initial value");
return f};b.find=b.detect=function(a,d,b){var m;return M(a,function(a,c,e){return d.call(b,a,c,e)?(m=a,!0):void 0}),m};b.filter=b.select=function(a,d,b){var m=[];return null==a?m:C&&a.filter===C?a.filter(d,b):(r(a,function(a,c,e){d.call(b,a,c,e)&&m.push(a)}),m)};b.reject=function(a,d,f){return b.filter(a,function(a,b,c){return!d.call(f,a,b,c)},f)};b.every=b.all=function(a,d,f){d||(d=b.identity);var c=!0;return null==a?c:w&&a.every===w?a.every(d,f):(r(a,function(a,b,g){return(c=c&&d.call(f,a,b,g))?
void 0:e}),!!c)};var M=b.some=b.any=function(a,d,f){d||(d=b.identity);var c=!1;return null==a?c:B&&a.some===B?a.some(d,f):(r(a,function(a,b,g){return c||(c=d.call(f,a,b,g))?e:void 0}),!!c)};b.contains=b.include=function(a,d){return null==a?!1:q&&a.indexOf===q?-1!=a.indexOf(d):M(a,function(a){return a===d})};b.invoke=function(a,d){var f=g.call(arguments,2),c=b.isFunction(d);return b.map(a,function(a){return(c?d:a[d]).apply(a,f)})};b.pluck=function(a,d){return b.map(a,function(a){return a[d]})};b.where=
function(a,d,f){return b.isEmpty(d)?f?void 0:[]:b[f?"find":"filter"](a,function(a){for(var b in d)if(d[b]!==a[b])return!1;return!0})};b.findWhere=function(a,d){return b.where(a,d,!0)};b.max=function(a,d,f){if(!d&&b.isArray(a)&&a[0]===+a[0]&&65535>a.length)return Math.max.apply(Math,a);if(!d&&b.isEmpty(a))return-1/0;var c={computed:-1/0,value:-1/0};return r(a,function(a,b,e){b=d?d.call(f,a,b,e):a;b>c.computed&&(c={value:a,computed:b})}),c.value};b.min=function(a,d,f){if(!d&&b.isArray(a)&&a[0]===+a[0]&&
65535>a.length)return Math.min.apply(Math,a);if(!d&&b.isEmpty(a))return 1/0;var c={computed:1/0,value:1/0};return r(a,function(a,b,e){b=d?d.call(f,a,b,e):a;b<c.computed&&(c={value:a,computed:b})}),c.value};b.shuffle=function(a){var d,f=0,c=[];return r(a,function(a){d=b.random(f++);c[f-1]=c[d];c[d]=a}),c};b.sample=function(a,d,f){return 2>arguments.length||f?a[b.random(a.length-1)]:b.shuffle(a).slice(0,Math.max(0,d))};var v=function(a){return b.isFunction(a)?a:function(d){return d[a]}};b.sortBy=function(a,
d,f){var c=v(d);return b.pluck(b.map(a,function(a,d,b){return{value:a,index:d,criteria:c.call(f,a,d,b)}}).sort(function(a,d){var b=a.criteria,f=d.criteria;if(b!==f){if(b>f||void 0===b)return 1;if(f>b||void 0===f)return-1}return a.index-d.index}),"value")};var J=function(a){return function(d,f,c){var e={},g=null==f?b.identity:v(f);return r(d,function(b,f){var k=g.call(c,b,f,d);a(e,k,b)}),e}};b.groupBy=J(function(a,d,f){(b.has(a,d)?a[d]:a[d]=[]).push(f)});b.indexBy=J(function(a,d,b){a[d]=b});b.countBy=
J(function(a,d){b.has(a,d)?a[d]++:a[d]=1});b.sortedIndex=function(a,d,f,c){f=null==f?b.identity:v(f);d=f.call(c,d);for(var e=0,g=a.length;g>e;){var k=e+g>>>1;f.call(c,a[k])<d?e=k+1:g=k}return e};b.toArray=function(a){return a?b.isArray(a)?g.call(a):a.length===+a.length?b.map(a,b.identity):b.values(a):[]};b.size=function(a){return null==a?0:a.length===+a.length?a.length:b.keys(a).length};b.first=b.head=b.take=function(a,d,b){return null==a?void 0:null==d||b?a[0]:g.call(a,0,d)};b.initial=function(a,
d,b){return g.call(a,0,a.length-(null==d||b?1:d))};b.last=function(a,d,b){return null==a?void 0:null==d||b?a[a.length-1]:g.call(a,Math.max(a.length-d,0))};b.rest=b.tail=b.drop=function(a,d,b){return g.call(a,null==d||b?1:d)};b.compact=function(a){return b.filter(a,b.identity)};var D=function(a,d,f){return d&&b.every(a,b.isArray)?p.apply(f,a):(r(a,function(a){b.isArray(a)||b.isArguments(a)?d?k.apply(f,a):D(a,d,f):f.push(a)}),f)};b.flatten=function(a,d){return D(a,d,[])};b.without=function(a){return b.difference(a,
g.call(arguments,1))};b.uniq=b.unique=function(a,d,f,c){b.isFunction(d)&&(c=f,f=d,d=!1);f=f?b.map(a,f,c):a;var e=[],g=[];return r(f,function(f,c){(d?c&&g[g.length-1]===f:b.contains(g,f))||(g.push(f),e.push(a[c]))}),e};b.union=function(){return b.uniq(b.flatten(arguments,!0))};b.intersection=function(a){var d=g.call(arguments,1);return b.filter(b.uniq(a),function(a){return b.every(d,function(d){return 0<=b.indexOf(d,a)})})};b.difference=function(a){var d=p.apply(c,g.call(arguments,1));return b.filter(a,
function(a){return!b.contains(d,a)})};b.zip=function(){for(var a=b.max(b.pluck(arguments,"length").concat(0)),d=Array(a),f=0;a>f;f++)d[f]=b.pluck(arguments,""+f);return d};b.object=function(a,d){if(null==a)return{};for(var b={},c=0,e=a.length;e>c;c++)d?b[a[c]]=d[c]:b[a[c][0]]=a[c][1];return b};b.indexOf=function(a,d,f){if(null==a)return-1;var c=0,e=a.length;if(f){if("number"!=typeof f)return c=b.sortedIndex(a,d),a[c]===d?c:-1;c=0>f?Math.max(0,e+f):f}if(q&&a.indexOf===q)return a.indexOf(d,f);for(;e>
c;c++)if(a[c]===d)return c;return-1};b.lastIndexOf=function(a,d,b){if(null==a)return-1;var c=null!=b;if(O&&a.lastIndexOf===O)return c?a.lastIndexOf(d,b):a.lastIndexOf(d);for(b=c?b:a.length;b--;)if(a[b]===d)return b;return-1};b.range=function(a,d,b){1>=arguments.length&&(d=a||0,a=0);b=arguments[2]||1;for(var c=Math.max(Math.ceil((d-a)/b),0),e=0,g=Array(c);c>e;)g[e++]=a,a+=b;return g};var P=function(){};b.bind=function(a,d){var f,c;if(I&&a.bind===I)return I.apply(a,g.call(arguments,1));if(!b.isFunction(a))throw new TypeError;
return f=g.call(arguments,2),c=function(){if(!(this instanceof c))return a.apply(d,f.concat(g.call(arguments)));P.prototype=a.prototype;var b=new P;P.prototype=null;var e=a.apply(b,f.concat(g.call(arguments)));return Object(e)===e?e:b}};b.partial=function(a){var d=g.call(arguments,1);return function(){return a.apply(this,d.concat(g.call(arguments)))}};b.bindAll=function(a){var d=g.call(arguments,1);if(0===d.length)throw Error("bindAll must be passed function names");return r(d,function(d){a[d]=b.bind(a[d],
a)}),a};b.memoize=function(a,d){var c={};return d||(d=b.identity),function(){var e=d.apply(this,arguments);return b.has(c,e)?c[e]:c[e]=a.apply(this,arguments)}};b.delay=function(a,d){var b=g.call(arguments,2);return setTimeout(function(){return a.apply(null,b)},d)};b.defer=function(a){return b.delay.apply(b,[a,1].concat(g.call(arguments,1)))};b.throttle=function(a,d,b){var c,e,g,k=null,h=0;b||(b={});var l=function(){h=!1===b.leading?0:new Date;k=null;g=a.apply(c,e)};return function(){var q=new Date;
h||!1!==b.leading||(h=q);var p=d-(q-h);return c=this,e=arguments,0>=p?(clearTimeout(k),k=null,h=q,g=a.apply(c,e)):k||!1===b.trailing||(k=setTimeout(l,p)),g}};b.debounce=function(a,d,b){var c,e,g,k,h;return function(){g=this;e=arguments;k=new Date;var q=function(){var l=new Date-k;d>l?c=setTimeout(q,d-l):(c=null,b||(h=a.apply(g,e)))},l=b&&!c;return c||(c=setTimeout(q,d)),l&&(h=a.apply(g,e)),h}};b.once=function(a){var d,b=!1;return function(){return b?d:(b=!0,d=a.apply(this,arguments),a=null,d)}};b.wrap=
function(a,b){return function(){var c=[a];return k.apply(c,arguments),b.apply(this,c)}};b.compose=function(){var a=arguments;return function(){for(var b=arguments,c=a.length-1;0<=c;c--)b=[a[c].apply(this,b)];return b[0]}};b.after=function(a,b){return function(){return 1>--a?b.apply(this,arguments):void 0}};b.keys=R||function(a){if(a!==Object(a))throw new TypeError("Invalid object");var d=[],c;for(c in a)b.has(a,c)&&d.push(c);return d};b.values=function(a){for(var d=b.keys(a),c=d.length,e=Array(c),
g=0;c>g;g++)e[g]=a[d[g]];return e};b.pairs=function(a){for(var d=b.keys(a),c=d.length,e=Array(c),g=0;c>g;g++)e[g]=[d[g],a[d[g]]];return e};b.invert=function(a){for(var d={},c=b.keys(a),e=0,g=c.length;g>e;e++)d[a[c[e]]]=c[e];return d};b.functions=b.methods=function(a){var d=[],c;for(c in a)b.isFunction(a[c])&&d.push(c);return d.sort()};b.extend=function(a){return r(g.call(arguments,1),function(b){if(b)for(var c in b)a[c]=b[c]}),a};b.pick=function(a){var b={},f=p.apply(c,g.call(arguments,1));return r(f,
function(c){c in a&&(b[c]=a[c])}),b};b.omit=function(a){var d={},f=p.apply(c,g.call(arguments,1)),e;for(e in a)b.contains(f,e)||(d[e]=a[e]);return d};b.defaults=function(a){return r(g.call(arguments,1),function(b){if(b)for(var c in b)void 0===a[c]&&(a[c]=b[c])}),a};b.clone=function(a){return b.isObject(a)?b.isArray(a)?a.slice():b.extend({},a):a};b.tap=function(a,b){return b(a),a};var K=function(a,d,c,e){if(a===d)return 0!==a||1/a==1/d;if(null==a||null==d)return a===d;a instanceof b&&(a=a._wrapped);
d instanceof b&&(d=d._wrapped);var g=s.call(a);if(g!=s.call(d))return!1;switch(g){case "[object String]":return a==String(d);case "[object Number]":return a!=+a?d!=+d:0==a?1/a==1/d:a==+d;case "[object Date]":case "[object Boolean]":return+a==+d;case "[object RegExp]":return a.source==d.source&&a.global==d.global&&a.multiline==d.multiline&&a.ignoreCase==d.ignoreCase}if("object"!=typeof a||"object"!=typeof d)return!1;for(var k=c.length;k--;)if(c[k]==a)return e[k]==d;var k=a.constructor,h=d.constructor;
if(k!==h&&(!b.isFunction(k)||!(k instanceof k&&b.isFunction(h)&&h instanceof h)))return!1;c.push(a);e.push(d);k=0;h=!0;if("[object Array]"==g){if(k=a.length,h=k==d.length)for(;k--&&(h=K(a[k],d[k],c,e)););}else{for(var l in a)if(b.has(a,l)&&(k++,!(h=b.has(d,l)&&K(a[l],d[l],c,e))))break;if(h){for(l in d)if(b.has(d,l)&&!k--)break;h=!k}}return c.pop(),e.pop(),h};b.isEqual=function(a,b){return K(a,b,[],[])};b.isEmpty=function(a){if(null==a)return!0;if(b.isArray(a)||b.isString(a))return 0===a.length;for(var d in a)if(b.has(a,
d))return!1;return!0};b.isElement=function(a){return!(!a||1!==a.nodeType)};b.isArray=n||function(a){return"[object Array]"==s.call(a)};b.isObject=function(a){return a===Object(a)};r("Arguments Function String Number Date RegExp".split(" "),function(a){b["is"+a]=function(b){return s.call(b)=="[object "+a+"]"}});b.isArguments(arguments)||(b.isArguments=function(a){return!(!a||!b.has(a,"callee"))});"function"!=typeof/./&&(b.isFunction=function(a){return"function"==typeof a});b.isFinite=function(a){return isFinite(a)&&
!isNaN(parseFloat(a))};b.isNaN=function(a){return b.isNumber(a)&&a!=+a};b.isBoolean=function(a){return!0===a||!1===a||"[object Boolean]"==s.call(a)};b.isNull=function(a){return null===a};b.isUndefined=function(a){return void 0===a};b.has=function(a,b){return z.call(a,b)};b.noConflict=function(){return l._=h,this};b.identity=function(a){return a};b.times=function(a,b,c){for(var e=Array(Math.max(0,a)),g=0;a>g;g++)e[g]=b.call(c,g);return e};b.random=function(a,b){return null==b&&(b=a,a=0),a+Math.floor(Math.random()*
(b-a+1))};var u={escape:{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#x27;"}};u.unescape=b.invert(u.escape);var N={escape:RegExp("["+b.keys(u.escape).join("")+"]","g"),unescape:RegExp("("+b.keys(u.unescape).join("|")+")","g")};b.each(["escape","unescape"],function(a){b[a]=function(b){return null==b?"":(""+b).replace(N[a],function(b){return u[a][b]})}});b.result=function(a,d){if(null!=a){var c=a[d];return b.isFunction(c)?c.call(a):c}};b.mixin=function(a){r(b.functions(a),function(d){var c=
b[d]=a[d];b.prototype[d]=function(){var a=[this._wrapped];k.apply(a,arguments);a=c.apply(b,a);return this._chain?b(a).chain():a}})};var E=0;b.uniqueId=function(a){var b=++E+"";return a?a+b:b};b.templateSettings={evaluate:/<%([\s\S]+?)%>/g,interpolate:/<%=([\s\S]+?)%>/g,escape:/<%-([\s\S]+?)%>/g};var x=/(.)^/,S={"'":"'","\\":"\\","\r":"r","\n":"n","\t":"t","\u2028":"u2028","\u2029":"u2029"},F=/\\|'|\r|\n|\t|\u2028|\u2029/g;b.template=function(a,d,c){var e;c=b.defaults({},c,b.templateSettings);var g=
RegExp([(c.escape||x).source,(c.interpolate||x).source,(c.evaluate||x).source].join("|")+"|$","g"),k=0,h="__p+='";a.replace(g,function(b,d,c,e,f){return h+=a.slice(k,f).replace(F,function(a){return"\\"+S[a]}),d&&(h+="'+\n((__t=("+d+"))==null?'':_.escape(__t))+\n'"),c&&(h+="'+\n((__t=("+c+"))==null?'':__t)+\n'"),e&&(h+="';\n"+e+"\n__p+='"),k=f+b.length,b});h+="';\n";c.variable||(h="with(obj||{}){\n"+h+"}\n");h="var __t,__p='',__j=Array.prototype.join,print=function(){__p+=__j.call(arguments,'');};\n"+
h+"return __p;\n";try{e=new Function(c.variable||"obj","_",h)}catch(l){throw l.source=h,l;}if(d)return e(d,b);d=function(a){return e.call(this,a,b)};return d.source="function("+(c.variable||"obj")+"){\n"+h+"}",d};b.chain=function(a){return b(a).chain()};b.mixin(b);r("pop push reverse shift sort splice unshift".split(" "),function(a){var d=c[a];b.prototype[a]=function(){var c=this._wrapped;return d.apply(c,arguments),"shift"!=a&&"splice"!=a||0!==c.length||delete c[0],this._chain?b(c).chain():c}});
r(["concat","join","slice"],function(a){var d=c[a];b.prototype[a]=function(){var a=d.apply(this._wrapped,arguments);return this._chain?b(a).chain():a}});b.extend(b.prototype,{chain:function(){return this._chain=!0,this},value:function(){return this._wrapped}})}).call(this);define("qowtRoot/third_party/underscore/underscore-min",function(){});
define("background/fileReaper",["background/cache","qowtRoot/utils/typeUtils","third_party/when/when","qowtRoot/third_party/underscore/underscore-min"],function(l,h,e){var c={init:function(){e(z()).then(t)},cacheOpenedFile:function(c,e,g){l.overwriteEntry(c,e,g)},addLock:function(c){p.push(c)},removeLock:function(c){c=p.indexOf(c);-1!==c&&p.splice(c,1)}},n,k=!1,g=[],p=[],s=0,z=function(){var c;return function(){var g=e.defer();c?g.resolve(c):window.webkitRequestFileSystem(window.TEMPORARY,1048576,
function(e){c=e;g.resolve(c)},function(){g.reject(Error("File Reaper failed to access the file system"))});return g.promise}}(),t=function(){var e=_.throttle(A,3E4);chrome.tabs.onRemoved.addListener(function(g,k){c.removeLock(g);l.containsTabId(g)&&e()})},A=function(){!s&&!(0<p.length)&&(l.removeAllTabIds(),k=!1,n=window.setTimeout(G,3E5),chrome.windows.getAll({populate:!0},function(c){for(var e=c.length,g=0;g<e;g++)c[g].tabs.forEach(function(c){s++;chrome.tabs.sendMessage(c.id,"reaperCheck",H.bind(this,
c.id))})}))},H=function(c,e){k?h.isObject(e)&&e.hasOwnProperty("privatePath")&&console.warn("Reaper received a belated Quickoffice tab response - this may result in its private temp file being incorrectly deleted"):(h.isObject(e)&&e.hasOwnProperty("privatePath")&&l.overwriteEntry(e.privatePath,c,e.srcPath),1===s?(window.clearTimeout(n),0<p.length?s=0:C()):s--)},G=function(){k=!0;0<p.length?s=0:C()},C=function(){e(z()).then(function(c){g=[];var e=c.root.createReader(),k=function(){e.readEntries(function(c){0<
c.length?(c.forEach(function(b){g.push(b)}),k()):w(g)},w)};k()})},w=function(c){!(0<p.length)&&h.isList(c)&&l.deleteOrphans(c).forEach(function(c){B(c)});s=0},B=function(c){c&&e(z()).then(function(e){e.root.getFile(c,{create:!1},function(e){e.remove(function(){console.log("File Reaper has deleted file "+c)})})})};return c});
define("background/pageAPI",["background/incomingCache","background/fileReaper"],function(l,h){window.getFileToOpen=function(){if(0<l.filesToOpen.length)return l.filesToOpen.pop()};window.getStreamDetails=function(){if(0<l.streamsCache.length)return l.streamsCache.pop()};window.addReaperLock=function(e){h.addLock(e)};window.removeReaperLock=function(e){h.removeLock(e)};window.cacheOpenedFile=function(e,c,l){h.cacheOpenedFile(e,c,l)};window.isReady=!0;return{}});
define("background/chromeHandler",["background/pageAPI","background/incomingCache","background/fileReaper"],function(l,h,e){function c(c){chrome.windows.create({type:"normal",focused:!0},function(e){chrome.tabs.update(e.tabs[0].id,{active:!0,url:"../views/app.html"});for(var l=0;l<c.length;l++)h.filesToOpen.push(c[l]),n(e.id)})}function n(c){chrome.tabs.create({windowId:c,active:!0,url:"../views/app.html"})}return{handleConnection:function(c){var e=chrome&&chrome.app&&chrome.app.getDetails?chrome.app.getDetails().version:
"loading";c.postMessage({qo_version:e})},handleStream:function(c,e,l,n){h.streamsCache.push({mimeType:c,originalURL:e,streamURL:l});n?chrome.tabs.update(n,{url:"../views/app.html"}):chrome.tabs.create({url:"../views/app.html"})},handleChromeOSFile:function(e,g){if("qoview"===e){h.filesToOpen.push(g.entries[0]);var l=g.entries.slice(1);chrome.windows.getAll({populate:!1},function(e){if(!e||1>e.length)c(l);else if((e=e[0])&&e.id){n(e.id);for(var g=0;g<l.length;g++)h.filesToOpen.push(l[g]),n(e.id)}else c(l)})}}}});
(function(){function l(e){console.error(e.stack?e.stack:e)}var h=(new Promise(function(e,c){require(["background/chromeHandler"],e)})).catch(l);(function(){var e=chrome&&chrome.runtime&&chrome.runtime.onConnectExternal&&chrome.runtime.onConnectExternal.addListener;e||console.warn("Missing Chrome Connect API... drive integration wont work");return e})()&&chrome.runtime.onConnectExternal.addListener(function(e){e.onDisconnect.addListener(function(){});h.then(function(c){c.handleConnection(e)}).catch(l)});
(function(){var e=chrome&&chrome.streamsPrivate&&chrome.streamsPrivate.onExecuteMimeTypeHandler&&chrome.streamsPrivate.onExecuteMimeTypeHandler.addListener;e||console.warn("Missing Chrome Streams API... blue links wont work");return e})()&&chrome.streamsPrivate.onExecuteMimeTypeHandler.addListener(function(e,c,n,k){h.then(function(g){g.handleStream(e,c,n,k)}).catch(l)});(function(){var e=chrome&&chrome.fileBrowserHandler&&chrome.fileBrowserHandler.onExecute&&chrome.fileBrowserHandler.onExecute.addListener;
e||console.warn("Missing ChromeOS FileBrowser API... files app integration wont work");return e})()&&chrome.fileBrowserHandler.onExecute.addListener(function(e,c){h.then(function(h){h.handleChromeOSFile(e,c)}).catch(l)})})();define("background/backgroundMain",function(){});
