// Generated by CoffeeScript 1.6.1
(function() {

  BH.Modules.I18n = {
    t: function(key, replacements) {
      var keys, lookup, _i, _len;
      if (replacements == null) {
        replacements = [];
      }
      if (key instanceof Array) {
        keys = key;
        lookup = {};
        for (_i = 0, _len = keys.length; _i < _len; _i++) {
          key = keys[_i];
          lookup["i18n_" + key] = this.chromeAPI.i18n.getMessage(key.toString());
        }
        return lookup;
      } else {
        return this.chromeAPI.i18n.getMessage(key, replacements);
      }
    }
  };

}).call(this);
