//@ sourceMappingURL=devices.map
// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Collections.Devices = (function(_super) {

    __extends(Devices, _super);

    function Devices() {
      return Devices.__super__.constructor.apply(this, arguments);
    }

    Devices.prototype.fetch = function() {
      var _this = this;
      return chrome.sessions.getRecentlyClosed(function(devices) {
        return console.log(devices);
      });
    };

    return Devices;

  })(Backbone.Collection);

}).call(this);
