//@ sourceMappingURL=grouped_visits.map
// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Collections.GroupedVisits = (function(_super) {

    __extends(GroupedVisits, _super);

    function GroupedVisits() {
      return GroupedVisits.__super__.constructor.apply(this, arguments);
    }

    GroupedVisits.prototype.model = BH.Models.Visit;

    return GroupedVisits;

  })(Backbone.Collection);

}).call(this);
