// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Modals.AuthErrorModal = (function(_super) {

    __extends(AuthErrorModal, _super);

    function AuthErrorModal() {
      return AuthErrorModal.__super__.constructor.apply(this, arguments);
    }

    AuthErrorModal.include(BH.Modules.I18n);

    AuthErrorModal.prototype.className = 'auth_error_view';

    AuthErrorModal.prototype.template = BH.Templates['auth_error'];

    AuthErrorModal.prototype.events = {
      'click .cancel': 'cancelClicked',
      'click .login': 'loginClicked'
    };

    AuthErrorModal.prototype.initialize = function() {
      this.chromeAPI = chrome;
      this.tracker = this.options.tracker;
      return this.attachGeneralEvents();
    };

    AuthErrorModal.prototype.render = function() {
      this.$el.html(this.renderTemplate(this.getI18nValues()));
      return this;
    };

    AuthErrorModal.prototype.cancelClicked = function(ev) {
      ev.preventDefault();
      this.close();
      return user.logout();
    };

    AuthErrorModal.prototype.loginClicked = function(ev) {
      var userProcessor;
      ev.preventDefault();
      this.close();
      user.logout();
      userProcessor = new BH.Lib.UserProcessor();
      return userProcessor.start();
    };

    AuthErrorModal.prototype.getI18nValues = function() {
      return this.t(['login_again_button', 'prompt_cancel_button', 'auth_error_title', 'auth_error_description']);
    };

    return AuthErrorModal;

  })(BH.Modals.Base);

}).call(this);
