// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Modals.MailingListModal = (function(_super) {

    __extends(MailingListModal, _super);

    function MailingListModal() {
      return MailingListModal.__super__.constructor.apply(this, arguments);
    }

    MailingListModal.include(BH.Modules.I18n);

    MailingListModal.prototype.className = 'mailing_list_view';

    MailingListModal.prototype.template = BH.Templates['mailing_list'];

    MailingListModal.prototype.events = {
      'click .close': 'closeClicked',
      'click #join_mailing_list': 'joinMailingListClicked'
    };

    MailingListModal.prototype.initialize = function() {
      this.chromeAPI = chrome;
      return this.attachGeneralEvents();
    };

    MailingListModal.prototype.render = function() {
      this.$el.html(this.renderTemplate(this.getI18nValues()));
      return this;
    };

    MailingListModal.prototype.closeClicked = function(ev) {
      ev.preventDefault();
      return this.close();
    };

    MailingListModal.prototype.joinMailingListClicked = function() {
      return this.close();
    };

    MailingListModal.prototype.getI18nValues = function() {
      return this.t(['close_button', 'mailing_list_title', 'mailing_list_description', 'mailing_list_link', 'mailing_list_promise', 'leave_a_review']);
    };

    return MailingListModal;

  })(BH.Modals.Base);

}).call(this);
