//@ sourceMappingURL=day.map
// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Models.Day = (function(_super) {

    __extends(Day, _super);

    function Day() {
      return Day.__super__.constructor.apply(this, arguments);
    }

    Day.prototype.initialize = function() {
      return this.set({
        id: moment(this.get('date')).id()
      });
    };

    Day.prototype.parseAndSet = function(data) {
      var interval, intervals, visit, visits, _i, _j, _len, _len1, _ref;
      intervals = new BH.Collections.Intervals();
      for (_i = 0, _len = data.length; _i < _len; _i++) {
        interval = data[_i];
        visits = new BH.Collections.Visits();
        _ref = interval.visits;
        for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
          visit = _ref[_j];
          if (_.isArray(visit)) {
            visits.add(new BH.Models.GroupedVisit(visit));
          } else {
            visits.add(new BH.Models.Visit(visit));
          }
        }
        intervals.add({
          id: interval.id,
          datetime: interval.datetime,
          visits: visits
        });
      }
      return this.set({
        history: intervals
      });
    };

    return Day;

  })(Backbone.Model);

}).call(this);
