//@ sourceMappingURL=interval.map
// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Models.Interval = (function(_super) {

    __extends(Interval, _super);

    function Interval() {
      return Interval.__super__.constructor.apply(this, arguments);
    }

    Interval.prototype.findVisitById = function(id) {
      var foundVisit,
        _this = this;
      foundVisit = this.get('visits').get(id);
      if (foundVisit != null) {
        return foundVisit;
      }
      this.get('visits').find(function(visit) {
        if (visit.get('visits') != null) {
          foundVisit = visit.get('visits').get(id);
          if (foundVisit != null) {
            return true;
          }
        }
      });
      return foundVisit;
    };

    return Interval;

  })(Backbone.Model);

}).call(this);
