var extInfoStorage=null,extInfoStorage_inprogress=!1,failureTimeout=null,requestTimeout=1E4,getExtendedInfoTimer,historyList=[],historyTrack=[],extList=[],idleState=null,idleStateTimer=null,changesDelay=500,changesTimeout=null,mainListener=function(a,b,c){if(a&&a.type)switch(a.type){case "notify":notify(a);break;case "settings":settings.load();resetSettings();break;case "getExtInfo":loadExtInfo(c);break;case "getHistory":loadHistory(c);break;case "uninstall":doUninstall(a.extInfo);break;case "onChanged":if(a.webstore){listenerOnWebStore(a.extInfo,
a.webstore);break}case "version":a.manifest&&(a.manifest.version&&a.kernel&&a.kernel.version)&&versionUpgrade(a.manifest.version,a.kernel.version)}};
function init(){thisExtensionId=chrome.runtime?chrome.runtime.id:chrome.i18n.getMessage("@@extension_id");settings.load();fixUpdateExtInfoInterval();chrome.runtime.onSuspend.addListener(function(){finalize()});isChromeBrowser=-1<navigator.userAgent.toLowerCase().indexOf("gecko) chrome");historyList=localStorage.historyList?JSON.parse(localStorage.historyList):[];loadExtInfo();apiOnMessage.addListener(mainListener);chrome.management.onUninstalled.addListener(listenerOnUninstall);chrome.management.onInstalled.addListener(listenerOnInstall);
chrome.management.onEnabled.addListener(listenerOnToggle);chrome.management.onDisabled.addListener(listenerOnToggle);resetSettings();wsSession()}function versionUpgrade(){}function fixUpdateExtInfoInterval(){var a=tryIntParse(settings.getValue("updateExtInfoInterval"));0<a&&settings.setValue("updateExtInfoInterval",(0).toString())}function idleCheckState(){chrome.idle.queryState(15,function(a){idleState=a})}
function setExtendedInfoTimer(){getExtendedInfoTimer&&clearTimeout(getExtendedInfoTimer);getExtendedInfoTimer=null;var a=tryIntParse(settings.getValue("updateExtInfoInterval"));0!==a&&(getExtendedInfoTimer=window.setInterval(function(){getExtendedInfo()},6E4*a))}function resetSettings(){}function finalize(){for(var a=chrome.extension.getViews({type:"notification"}),b=0;b<a.length;b++)a[b].close();getExtendedInfoTimer&&clearTimeout(getExtendedInfoTimer)}
function doUninstall(a){window.confirm("Are you sure you want to uninstall "+displayName(a)+"?")&&chrome.management.uninstall(a.id)}function notifySimple(a,b){if(window.webkitNotifications)try{var c=parseInt(settings.getValue("notifyTimeout"));void 0===a&&(a="");void 0===b&&(b="");iconUrl="icons/logo-32.png";var d=webkitNotifications.createNotification(iconUrl,a,b);d.show();d.ondisplay=function(){!isNaN(c)&&0<c&&setTimeout(function(){d.cancel();d=null},1E3*c)}}catch(e){console.error(e)}}
function notify(a){var b=chrome.extension.getURL("icons/logo-32.png");if(window.webkitNotifications)var c=parseInt(settings.getValue("notifyTimeout"));var d,e=a&&a.extInfo?getExtInfoItem(a.extInfo.id):null;if(d=webkitNotifications.createNotification(e?e.webstore&&e.webstore.logo?e.webstore.logo:getIconUrl(e.icons,48):b,a.title,a.message))d.ondisplay=function(){!isNaN(c)&&0<c&&setTimeout(function(){d.cancel();d=null},1E3*c)},d.show()}
function loadHistory(a){historyList=localStorage.historyList?JSON.parse(localStorage.historyList):[];a&&a()}
function loadExtInfoAdditive(){extList=localStorage.extList?JSON.parse(localStorage.extList):[];for(var a=extInfoStorage.length-1;0<=a;a--){for(var b=!1,c=extList.length-1;0<=c;c--)if(extInfoStorage[a].id===extList[c].id){addObject(extInfoStorage[a],extList[c]);b=!0;break}b||(extList.push({id:extInfoStorage[a].id,_version:extInfoStorage[a].version}),extInfoStorage[a]._version=extInfoStorage[a].version);extInfoStorage[a]._version&&extInfoStorage[a]._version!==extInfoStorage[a].version&&listenerOnInstall(extInfoStorage[a])}}
function updateExtInfoAdditive(a,b){var c;for(c=extList.length-1;0<=c&&extList[c].id!==a.id;c--);0>c&&(c=extList.push({id:a.id,_version:a.version})-1);b&&(a.webstore=b);a.webstore&&(extList[c].webstore=a.webstore);a._version&&(extList[c]._version=a._version);localStorage.extList=JSON.stringify(extList)}
function loadExtInfo(a){if(void 0===extInfoStorage||!extInfoStorage){failureTimeout&&clearTimeout(failureTimeout);failureTimeout=setTimeout(bind(function(a){notify({message:"Sorry, timeout failure on loading extensions information. Please, try again later or restart browser."});a&&a({extInfoArray:null})},this,a),12E3);var b=bind(function(b,d){extInfoStorage=d;extInfoStorage.sort(ordinalSort);extInfoStorage_inprogress=!1;loadExtInfoAdditive();failureTimeout&&(clearTimeout(failureTimeout),failureTimeout=
null);a&&a({extInfoArray:null},!0)},this,a);chrome.management.getAll(b)}else a&&a({extInfoArray:null})}function autoDisableThemes(a){if(a&&a.enabled&&extInfoStorage&&settings.getValue("autoDisableTheme")&&getUnitKind(a)===unitKind.theme)for(var b=extInfoStorage.length-1;0<=b;b--)getUnitKind(extInfoStorage[b])===unitKind.theme&&extInfoStorage[b].enabled&&a.id!==extInfoStorage[b].id&&chrome.management.setEnabled(extInfoStorage[b].id,!1)}
function monitorChanges(){changesTimeout&&clearTimeout(changesTimeout);changesTimeout=setTimeout(function(){apiSendMessage({type:"onChanges"})},changesDelay)}function listenerOnWebStore(){}
function listenerOnUninstall(a){if(extInfoStorage){for(var b=extInfoStorage.length-1;0<=b;b--)if(extInfoStorage[b].id===a){settings.getValue("showInstallNotification")&&notify({title:displayName(extInfoStorage[b]),message:" have been uninstalled at "+displayCurrentTime(),extInfo:extInfoStorage[b]});extInfoStorage.splice(b,1);removeHistory(a);break}apiSendMessage({type:"onUninstalled",id:a});monitorChanges()}}
function listenerOnInstall(a){var b=!1;if(extInfoStorage){for(var c=extInfoStorage.length-1;0<=c;c--)if(extInfoStorage[c].id==a.id){b=!0;settings.getValue("showUpdatesNotification")&&notify({title:displayName(a),message:" has been updated to version "+a.version+(extInfoStorage[c]._version?" from "+extInfoStorage[c]._version:""),extInfo:a,forceUpdate:!0});extInfoStorage[c]._version=a.version;updateObject(extInfoStorage[c],a);settings.getValue("actionAutoEnableInstalled")&&!a.enabled&&chrome.management.setEnabled(a.id,
!0);apiSendMessage({type:"onChanged",id:a.id,version:a.version,extInfo:a});break}b||(extInfoStorage.push(a),apiSendMessage({type:"onInstalled",id:a.id,extInfo:a}),settings.getValue("showInstallNotification")&&notify({title:displayName(a),message:" has been installed at "+displayCurrentTime(),extInfo:a,forceUpdate:!0}));updateHistory(a.id,b?historyEventKind.Updated:historyEventKind.Installed);wsExtension(a);monitorChanges()}}
function listenerOnToggle(a){if(extInfoStorage){for(var b=!1,c=extInfoStorage.length-1;0<=c;c--)if(extInfoStorage[c].id===a.id){extInfoStorage[c].enabled=a.enabled;extInfoStorage[c].notified&&(b=!0,--extInfoStorage[c].notified);break}settings.getValue("showToggleNotification")&&(b||notify({title:displayName(a),message:" has been "+(a.enabled?"enabled":"disabled")+" at "+displayCurrentTime(),extInfo:a}));apiSendMessage({type:"onChanged",id:a.id,enabled:a.enabled});updateHistory(a.id,a.enabled?historyEventKind.Enabled:
historyEventKind.Disabled);autoDisableThemes(a);monitorChanges()}}var updateObject=function(a,b){if(a&&b)for(var c in b)a[c]=b[c];return a};function removeHistory(){}function eqHistoryType(a,b){return a===b||(a===historyEventKind.Installed||a===historyEventKind.Updated)&&(b===historyEventKind.Installed||b===historyEventKind.Updated)||(a===historyEventKind.Enabled||a===historyEventKind.Disabled)&&(b===historyEventKind.Enabled||b===historyEventKind.Disabled)}
function updateHistory(a,b){var c=new Date,d=-1;if(historyList&&historyList.length)for(var e=historyList.length-1;0<=e;e--)if(historyList[e].id==a&&eqHistoryType(b,historyList[e].type)){historyList[e].type=b;historyList[e].time=c;d=e;break}0>d&&(historyList.push({id:a,type:b,time:c}),d=historyList.length-1);localStorage.historyList=JSON.stringify(historyList);return d}
function publicationNoify(a,b){var c=parseInt(settings.getValue("publicationNotifyTimeout"));try{var d="<b>"+displayName(a)+"<br>published a new version ";b&&b.version&&(d+=b.version+"</b><br>"+b.date);var e=webkitNotifications.createHTMLNotification(chrome.extension.getURL("notify.html")+"?"+encodeURIComponent(JSON.stringify({extInfo:a,message:d,forceUpdate:!0,homepage:!0})));e.show();!isNaN(c)&&0<c&&setTimeout(function(){e.cancel()},1E3*c)}catch(f){console.error(f)}}
function getExtInfoItem(a){for(var b=extInfoStorage.length-1;0<=b;b--)if(extInfoStorage[b].id===a)return extInfoStorage[b];return null}function getExtInfoItemInd(a){for(var b=extInfoStorage.length-1;0<=b;b--)if(extInfoStorage[b].id===a)return b;return-1}function skipNotify(a,b){for(var c=!1,d=extInfoStorage.length-1;0<=d;d--)if(extInfoStorage[d].id===a){c=extInfoStorage[d];if(void 0===typeof b||c.enabled!==b)c.notified||(c.notified=0),++c.notified;c=!!c.notified}return c}$ready(init);