var dragKind={Link:0,Move:1},dragImages=null,historyTrack=[],separator="\u00a0",currentAction=actionKind.All,popListener=function(a){if(a&&a.type)switch(a.type){case "onChanges":calcGroupStatistics();break;case "onChanged":a.webstore||doAction(currentAction);if(a.lastVersion){updateLastVersion(a.id,a.lastVersion,a.extInfo);break}if(a.version){updateVersion(a.id,a.version,a.extInfo);break}break;case "groupDuplicate":groupDuplicateEnvelope(a.src,a.dst);break;case "addNewGroup":actionAddGroup(groupAdd(actionKind.Group,
"NEW GROUP"));setDropActive();break;case "moveGroup":setDropActive()}};
function initialize(){prepareDragIcon();historyTrack=apiBackground.historyTrack;settings.load();chrome.management.onUninstalled.addListener(listenerOnUninstall);chrome.management.onEnabled.addListener(listenerOnToggled);chrome.management.onDisabled.addListener(listenerOnToggled);var a=settings.getValue("popupWidth");document.body.style.width=(a?a:"700")+"px";$id("panel").style.width=(a?a:"700")+"px";$id("loading").setAttribute("style","visibility:hidden; display:none;");initAction();settings.getValue("actionValue");
a=settings.getValue("filterValue");settings.getValue("saveFilter")&&($id("filter").value=a,changedFilter(a));apiOnMessage.addListener(popListener);doAction(getRelativeAct())}function finalize(){saveSettings()}
function getRelativeAct(){var a=actionKind.All,e=settings.getValue("actionValue"),f=settings.getValue("startAction");!f||/memorizedAction/i.test(f)?a=parseInt(e):/extensionAction/i.test(f)?a=actionKind.Extensions:/applicationsAction/i.test(f)?a=actionKind.Applications:/themesAction/i.test(f)?a=actionKind.Themes:/enabledAction/i.test(f)?a=actionKind.Enabled:/disabledAction/i.test(f)?a=actionKind.Disabled:/outdatedAction/i.test(f)&&(a=actionKind.Outdated);a=parseInt(a);return isNaN(a)?actionKind.All:
a}function saveSettings(){var a=$id("filter");a&&settings.setValue("filterValue",a.value);(a=document.getElementsByClassName("actionSelected"))&&0<a.length&&settings.setValue("actionValue",a[0].dataset.action);settings.save()}function listenerOnInstall(){doAction(currentAction)}function listenerOnUninstall(a){a=document.querySelectorAll('[data-id="'+a+'"]');for(var e=0;e<a.length;e++)removeWithChilds(a[e])}
function listenerOnToggled(a){var e=document.getElementById("toggle#"+a.id),f=document.getElementById("imageOptions#"+a.id);e&&(e.checked=a.enabled);f&&a.optionsUrl&&f.setAttribute("src",a.enabled?"icons/options.png":"icons/optionsOff.png")}function updateLastVersion(a,e,f){if((a=document.getElementById("ver#"+a))&&f.webstore)removeChilds(a),a.appendChild(document.createTextNode(separator+"v."+f.version+"(last v."+f.webstore.version+")"))}
function updateVersion(a,e,f){if(a=document.getElementById("ver#"+a))removeChilds(a),a.appendChild(document.createTextNode(separator+"v."+f.version))}var extInfoStorage=null,extInfoStorage_inprogress=!1,failureTimeout=null;function loadExtInfo(a,e,f){apiBackground.loadExtInfo(function(){a(apiBackground.extInfoStorage,e,f)})}
function initAction(){var a=document.getElementById("actions"),e=document.createElement("div");e.classList.add("actionButtons");c=document.createElement("span");d=document.createElement("a");d.addEventListener("click",function(a){stopEvent(a);switchOn()},!1);d.setAttribute("href","#");b=document.createElement("img");b.setAttribute("width","16");b.setAttribute("src",chrome.extension.getURL("icons/swon.png"));d.appendChild(b);c.appendChild(d);dfn(c,"Switch ON");e.appendChild(c);c=document.createElement("span");
d=document.createElement("a");d.addEventListener("click",function(a){stopEvent(a);switchOff()},!1);d.setAttribute("href","#");b=document.createElement("img");b.setAttribute("width","16");b.setAttribute("src",chrome.extension.getURL("icons/swoff.png"));d.appendChild(b);c.appendChild(d);dfn(c,"Switch OFF");e.appendChild(c);c=document.createElement("span");d=document.createElement("a");d.addEventListener("click",function(a){stopEvent(a);switchUndo()},!1);d.setAttribute("href","#");b=document.createElement("img");
b.setAttribute("width","16");b.setAttribute("src",chrome.extension.getURL("icons/undo.png"));d.appendChild(b);c.appendChild(d);dfn(c,"Nothing to UNDO.","undoSwitch");e.appendChild(c);c=document.createElement("span");d=document.createElement("a");d.addEventListener("click",function(a){stopEvent(a);chrome.tabs.create({url:chrome.extension.getURL(settings.manifest.options_page),selected:!0})},!1);d.setAttribute("href","#");b=document.createElement("img");b.setAttribute("width","16");b.setAttribute("src",
chrome.extension.getURL("icons/config.png"));d.appendChild(b);c.appendChild(d);e.appendChild(c);dfn(c,"Options");c=document.createElement("span");d=document.createElement("a");d.addEventListener("click",function(a){stopEvent(a);window.close()},!1);d.setAttribute("href","#");b=document.createElement("img");b.setAttribute("width","16");b.setAttribute("src",chrome.extension.getURL("icons/close.png"));d.appendChild(b);c.appendChild(d);e.appendChild(c);dfn(c,"Close");a.appendChild(e);var e=document.createElement("span"),
f=document.createElement("a");f.setAttribute("href","#");f.innerText=" All ";e.dataset.action=actionKind.All;f.addEventListener("click",bind(function(a,e){stopEvent(e);doAction(a,e)},this,actionKind.All),!1);e.appendChild(f);attachDragHandlers(e,{type:"group",id:actionKind.All});a.appendChild(e);dfn(e,null,e.dataset.action);settings.getValue("showExtension")&&(e=document.createElement("span"),f=document.createElement("a"),f.setAttribute("href","#"),f.innerText=" Extensions ",e.dataset.action=actionKind.Extensions,
f.addEventListener("click",bind(function(a,e){stopEvent(e);doAction(a,e)},this,actionKind.Extensions),!1),a.appendChild(f),e.appendChild(f),attachDragHandlers(e,{type:"group",id:actionKind.Extensions}),a.appendChild(e),dfn(e,null,e.dataset.action));settings.getValue("showApp")&&(e=document.createElement("span"),f=document.createElement("a"),f.setAttribute("href","#"),f.innerText=" Applications ",e.dataset.action=actionKind.Applications,f.addEventListener("click",bind(function(a,e){stopEvent(e);doAction(a,
e)},this,actionKind.Applications),!1),e.appendChild(f),attachDragHandlers(e,{type:"group",id:actionKind.Applications}),a.appendChild(e),dfn(e,null,e.dataset.action));settings.getValue("showThemes")&&(e=document.createElement("span"),f=document.createElement("a"),f.setAttribute("href","#"),f.innerText=" Themes ",e.dataset.action=actionKind.Themes,f.addEventListener("click",bind(function(a,e){stopEvent(e);doAction(a,e)},this,actionKind.Themes),!1),e.appendChild(f),attachDragHandlers(e,{type:"group",
id:actionKind.Themes}),a.appendChild(e));settings.getValue("showEnabledView")&&(e=document.createElement("span"),f=document.createElement("a"),f.setAttribute("href","#"),f.innerText=" Enabled  ",e.dataset.action=actionKind.Enabled,f.addEventListener("click",bind(function(a,e){stopEvent(e);doAction(a,e)},this,actionKind.Enabled),!1),e.appendChild(f),attachDragHandlers(e,{type:"group",id:actionKind.Enabled}),a.appendChild(e));settings.getValue("showDisabledView")&&(e=document.createElement("span"),
f=document.createElement("a"),f.setAttribute("href","#"),f.innerText=" Disabled  ",e.dataset.action=actionKind.Disabled,f.addEventListener("click",bind(function(a,e){stopEvent(e);doAction(a,e)},this,actionKind.Disabled),!1),e.appendChild(f),attachDragHandlers(e,{type:"group",id:actionKind.Disabled}),a.appendChild(e));settings.getValue("showRecentlyView")&&(e=document.createElement("span"),f=document.createElement("a"),f.setAttribute("href","#"),f.innerText=" Recent  ",e.dataset.action=actionKind.Recently,
f.addEventListener("click",bind(function(a,e){stopEvent(e);doAction(a,e)},this,actionKind.Recently),!1),e.appendChild(f),attachDragHandlers(e,{type:"group",id:actionKind.Recently}),a.appendChild(e));e=document.createElement("span");f=document.createElement("input");f.id="filter";f.type="search";f.autofocus="autofocus";f.results="1";f.size="9";f.placeholder="filter...";f.addEventListener("input",actionFilter,!1);e.appendChild(f);a.appendChild(e);e=document.createElement("span");f=document.createElement("a");
f.addEventListener("click",function(a){stopEvent(a);var e="https://chrome.google.com/webstore/",f=$id("filter").value.trim();f&&(e+="search/"+encodeURIComponent(f));chrome.tabs.create({url:e,selected:selectTab(a)})},!1);f.setAttribute("href","#");f.innerText=" WebStore ";e.appendChild(f);a.appendChild(e);groupsLoad();actionShowGroups();a.style.visibility="visible";a.style.display="block";adjustListPos()}var prevBottom=0;
function adjustListPos(){var a=$id("actions"),e=$id("list"),a=0+a.getBoundingClientRect().bottom;settings.getValue("showGroupStatisticsMeter")&&(a+=4);prevBottom=a;e.style.top=""+a+"px";e.style.marginTop="0px"}function actionCheckNewGroup(a){a=a||!1;var e=groupGet(actionKind.Group);e&&(actionRemoveGroup(e),e.list&&0<e.list.length||a?(e.id=groupGetFreeId(),actionAddGroup(e)):groupRemove(actionKind.Group),groupSave());apiSendMessage({type:"onChanges"})}
function actionRemoveGroup(a){if(!a||!a.id)return null;(a=$id("group#"+a.id))&&removeWithChilds(a)}function actionRemoveGroups(){var a=$id("groups");a&&removeWithChilds(a)}function actionShowGroups(){settings.getValue("showGroups")&&(actionRemoveGroups(),groupStorage.forEach(function(a){actionAddGroup(a)}),apiSendMessage({type:"onChanges"}))}
function actionAddGroup(a){if(!a||!a.id||!a.name)return null;var e=a.id;a=a.name;if(e>actionKind.GroupEnd||e<actionKind.Group)return null;var f=document.getElementById("actions"),g=$id("groups");g||(g=document.createElement("div"),g.id="groups",g.classList.add("groups"),f.appendChild(g));var h="group#"+e,f=$id(h);f||(f=document.createElement("span"),f.id=h,f.classList.add("group"),f.classList.add("drop"),f.dataset.action=e,f.dataset.id=e,f.dataset.type=unitKind.group,h=document.createElement("a"),
h.setAttribute("href","#"),h.innerText=a,h.addEventListener("click",bind(function(a,e){stopEvent(e);doAction(a,e)},this,e),!1),h.addEventListener("dblclick",bind(function(a,e){stopEvent(e);groupEditName(a)},this,e),!1),f.appendChild(h),attachDropHandlers(f),attachDragHandlers(f,{type:"group",id:e}),g.appendChild(f),dfn(f,null,f.dataset.action));adjustListPos();apiSendMessage({type:"onChanges"});return f}
function groupDuplicateEnvelope(a,e){var f=groupGet(a),g=groupGet(e);confirm("Copy all displayed items from "+f.name+" to "+g.name+" ?")?extListIterator(a,bind(function(a,e,f){groupDuplicateFunc(a,e,f)},this,e)):actionCheckNewGroup()}function attachDropHandlers(a){a.addEventListener("dragenter",handleDragEnter,!1);a.addEventListener("dragover",handleDragOver,!1);a.addEventListener("dragleave",handleDragLeave,!1);a.addEventListener("drop",handleDrop,!1)}
function attachDragHandlers(a,e){a.draggable=!0;$eachChild(a,function(a){a.draggable=!0});a.addEventListener("dragstart",bind(handleDragStart,this,e),!1);a.addEventListener("dragend",bind(handleDragEnd,this,e),!1)}function $eachChild(a,e){if(a&&a.childNodes)for(var f=a.childNodes.length-1;0<=f;f--)e(a.childNodes[f]),$eachChild(a.childNodes[f],e)}
function prepareDragIcon(){dragImages||(dragImages=[],dragImages[dragKind.Link]=document.createElement("img"),dragImages[dragKind.Link].src=chrome.extension.getURL("icons/dragLink.png"),dragImages[dragKind.Move]=document.createElement("img"),dragImages[dragKind.Move].src=chrome.extension.getURL("icons/dragMove.png"))}function drawDragIcon(a){prepareDragIcon();return dragImages[a]}
function handleDragStart(a,e){a&&(a.type&&"group"===a.type)&&e.target.click();var f;e.ctrlKey||e.altKey||e.button?(e.dataTransfer.effectAllowed="move",e.dataTransfer.dropEffect="move",f=dragKind.Move,apiSendMessage({type:"moveGroup"})):(e.dataTransfer.effectAllowed="link",e.dataTransfer.dropEffect="link",apiSendMessage({type:"addNewGroup"}),f=dragKind.Link);e.dataTransfer.setData("text/plain",JSON.stringify(a));e.dataTransfer.setDragImage(drawDragIcon(f),-16,-16);return!0}
var fDropActiveAdd=function(a){a.classList.add("dropActive")},fDropActiveRemove=function(a){a.classList.remove("dropActive")};function setDropActive(a){a=void 0===a?!0:a;var e=document.getElementsByClassName("drop");e&&_forEach.call(e,a?fDropActiveAdd:fDropActiveRemove)}function handleDragOver(a){a.preventDefault&&a.preventDefault();return!1}function handleDragEnter(a){a.target.classList.remove("dropActive");a.target.classList.add("dropActiveOver")}
function handleDragLeave(a){a.target.classList.remove("dropActiveOver");setDropActive(!1);setDropActive(!0)}
function handleDrop(a){a.stopPropagation&&a.stopPropagation();var e;try{e=JSON.parse(a.dataTransfer.getData("text/plain"))}catch(f){e={}}var g=tryIntParse(a.currentTarget.dataset.action),h=groupGet(e.id),l=groupGet(g);g>=actionKind.Group&&g<=actionKind.GroupEnd&&(/extension/i.test(e.type)?(groupAddItem(g,e.id),l=getExtById(e.id),notifyExt(displayName(l)," have been attached to group "+h.name,l),actionCheckNewGroup()):/group/i.test(e.type)&&("move"===a.dataTransfer.effectAllowed?(e=l.ord,l.ord=h.ord,
h.ord=e,groupsOrder(),groupSave(),actionRemoveGroups(),actionShowGroups(),doAction(currentAction)):groupDuplicateEnvelope(e.id,g)),adjustListPos());a.target.classList.remove("dropActiveOver");setDropActive(!1);return!1}
function handleDragEnd(a,e){if(0>e.clientY||0>e.clientX||e.clientY>window.innerHeight||e.clientX>window.innerWidth)if(/extension/i.test(a.type))currentAction>=actionKind.Group&&currentAction<actionKind.GroupEnd&&(groupRemoveItem(currentAction,a.id),doAction(currentAction));else if(/group/i.test(a.type)){var f=a.id,g=groupGet(f),g=groupNext(g,!0);f>=actionKind.Group&&f<actionKind.GroupEnd&&groupDelete(f,e)&&(currentAction===f&&(currentAction=g?g.id:actionKind.All),doAction(currentAction))}"none"===
e.dataTransfer.dropEffect&&actionCheckNewGroup();setDropActive(!1);e.target.classList.remove("dropActiveOver")}
function doAction(a){currentAction=a;switch(a){case actionKind.All:loadExtInfo(init,function(a){return filterControl(a)});break;case actionKind.Extensions:loadExtInfo(init,function(a){return getUnitKind(a)===unitKind.extension&&filterControl(a)});break;case actionKind.Applications:loadExtInfo(init,function(a){return getUnitKind(a)===unitKind.app&&filterControl(a)});break;case actionKind.Themes:loadExtInfo(init,function(a){return getUnitKind(a)===unitKind.theme&&filterControl(a)});break;case actionKind.Enabled:loadExtInfo(init,
function(a){return a.enabled&&filterControl(a)});break;case actionKind.Disabled:loadExtInfo(init,function(a){return!a.enabled&&filterControl(a)});break;case actionKind.Outdated:loadExtInfo(init,function(a){return a.webstore&&a.webstore.version&&a.version!==a.webstore.version&&filterControl(a)});break;case actionKind.Recently:loadExtInfo(initRecently,function(a){return filterControl(a)});break;case actionKind.Favorites:break;default:if(a>=actionKind.Group&&a<actionKind.GroupEnd){var e=groupGet(a);
if(!e&&(e=groupNext(a),!e||e.id===actionKind.Group)){doAction(actionKind.All);return}var f=e?e.list.map(function(a){return a.id}):[];loadExtInfo(init,function(a){return 0<=f.indexOf(a.id)&&filterControl(a)})}}for(var e=document.querySelectorAll("span[data-action]"),g=e.length;0<=--g;)tryIntParse(e[g].dataset.action)===a?e[g].classList.add("actionSelected"):e[g].classList.remove("actionSelected");saveSettings()}function actualNode(a,e){for(;a.nodeName!==e&&a.parentNode;)a=a.parentNode;return a}
function actionGlobalSwitcher(){}function actionAll(){loadExtInfo(init,function(a){return filterControl(a)})}function actionExtensions(){loadExtInfo(init,function(a){return!a.isApp&&filterControl(a)})}function actionApplications(){loadExtInfo(init,function(a){return a.isApp&&filterControl(a)})}function actionEnabled(){loadExtInfo(init,function(a){return a.enabled&&filterControl(a)})}function actionDisabled(){loadExtInfo(init,function(a){return!a.enabled&&filterControl(a)})}
function actionFilter(a){doAction(currentAction);changedFilter(a.target.value)}function changedFilter(a){var e="";a.trim()&&(e="solid 2px -webkit-focus-ring-color ");$id("actions").style.outline=e}var refFilterControl=/\s*[\s.,;&|+]\s*/;function filterControl(a){var e=!0;a=a.name+" "+a.description;for(var f=document.getElementById("filter").value.split(refFilterControl),g=0;g<f.length;g++)f[g]&&(re=RegExp(f[g],"i"),e&=re.test(a));return e}
function initRecently(a,e){var f,g=new Date,h=settings.getValue("recentType"),l=settings.getValue("recentDepth");apiBackground.loadHistory();var k=JSON.parse(JSON.stringify(apiBackground.historyList));if(k){k.sort(historySort);if("all"===h)for(var j=k.length-1;0<=j;j--)if(0<j&&k[j].id===k[j-1].id&&864E5>=Math.abs((new Date(k[j-1].time)).getTime()-(new Date(k[j].time)).getTime())){var n=k[j-1].type,m=k[j].type;f=n%10;var n=Math.round(n/10),p=m%10,m=Math.round(m/10);if((0<n||0<m)&&!(0<n&&0<m)||0==n&&
0===m)k[j-1].type=p+10*f,k.splice(j,1)}for(j=k.length-1;0<=j;j--)filterHistoryByType(h,k[j].type)?0<l&&daysBetween(g,new Date(k[j].time))>l?k.splice(j,1):(f=getExtIndById(k[j].id,a),0>f&&"uninstall"!==h?k.splice(j,1):"uninstall"===h?0<=f?k.splice(j,1):(k[j].homepageUrl=defaulthomepageUrl+k[j].id,k[j].name=k[j].id,k[j].version="?"):(k[j].eventType=k[j].type,addObject(k[j],a[f]))):k.splice(j,1);init(k,e)}}
function filterHistoryByType(a,e){var f=!0;switch(a){case "install":f=e===historyEventKind.Installed||e===historyEventKind.Updated;break;case "toggle":f=e===historyEventKind.Enabled||e===historyEventKind.Disabled}return f}function getExtById(a,e){e||(e=apiBackground.extInfoStorage);for(var f=e.length-1;0<=f;f--)if(e[f].id===a)return e[f];return null}function getExtIndById(a,e){e||(e=apiBackground.extInfoStorage);for(var f=e.length-1;0<=f;f--)if(e[f].id===a)return f;return-1}
function init(a,e,f){var g=$id("list");g.setAttribute("style","visibility:hidden; display:none;");removeChilds(g);var h,l,k;if(a&&a.length){f||(f=ordinalSort);for(f=0;f<a.length;f++)if(!(void 0!==e&&e)||e(a[f])){h=document.createElement("div");h.setAttribute("class","item");h.dataset.id=a[f].id;h.dataset.type=unitKind.extensions;var j=document.createElement("img");j.src="icons/empty.png";getUnitKind(a[f])===unitKind.theme?(j.setAttribute("width","16"),j.setAttribute("height","16"),j.setAttribute("src",
a[f].icon)):(j.setAttribute("width","16"),j.setAttribute("src",getIconUrl(a[f].icons,16)));j.addEventListener("error",bind(function(a,e){a.src=e?e:"icons/empty.png"},this,j,a[f].icon),!1);var n=document.createElement("a");n.setAttribute("href","#");n.addEventListener("click",bind(function(a,e){stopEvent(e);a.isApp&&(a.appLaunchUrl?chrome.tabs.create({url:appLaunchUrl,selected:selectTab(e)}):chrome.management.launchApp(id));a.homepageUrl?chrome.tabs.create({url:a.homepageUrl,selected:selectTab(e)}):
notifyExt(displayName(a),"Homepage is not specified.",a)},this,a[f]),!1);n.appendChild(j);j=document.createElement("input");j.type="checkbox";j.checked=a[f].enabled;j.id="toggle#"+a[f].id;var m=bind(function(a,e,f){a.id!==thisExtensionId||confirm("Are you sure you want to disable "+a.name+" themselves?")?(a.enabled=!a.enabled,f.target.checked=a.enabled,chrome.management.setEnabled(a.id,f.target.checked)):f.target.checked=!f.target.checked},this,a[f],j);j.addEventListener("click",m,!1);m=document.createElement("a");
m.classList.add("actionButton");m.setAttribute("href","#");var p=document.createElement("img");p.setAttribute("width","16");p.setAttribute("src","icons/info.png");m.addEventListener("click",bind(function(a,e){stopEvent(e);showInfo(a,e)},this,a[f]),!1);m.appendChild(p);p=document.createElement("a");p.setAttribute("href","#");p.classList.add("actionButton");var q=document.createElement("img");q.classList.add("actionButton");q.setAttribute("width","16");q.setAttribute("src","icons/uninstall.png");p.addEventListener("click",
bind(function(a,e){stopEvent(e);settings.getValue("chromium")?apiSendMessage({type:"uninstall",extInfo:a}):window.confirm("Are you sure you want to uninstall "+displayName(a)+"?")&&chrome.management.uninstall(a.id)},this,a[f]),!1);p.appendChild(q);q=document.createElement("a");q.setAttribute("href","#");q.classList.add("actionButton");l=document.createElement("img");l.id="imageOptions#"+a[f].id;l.setAttribute("width","16");a[f].optionsUrl?(l.setAttribute("src",a[f].enabled?"icons/options.png":"icons/optionsOff.png"),
q.addEventListener("click",bind(function(a,e,f){stopEvent(f);a=bind(function(a,e){e.enabled&&chrome.tabs.create({url:a,selected:selectTab(f)})},this,a);chrome.management.get(e,a)},this,a[f].optionsUrl,a[f].id),!1)):l.setAttribute("src","icons/empty.png");q.appendChild(l);l=document.createElement("span");k=document.createElement("a");k.setAttribute("href","#");k.addEventListener("click",bind(function(a,e){stopEvent(e);a.isApp?chrome.tabs.create({url:a.appLaunchUrl,selected:selectTab(e)}):a.homepageUrl?
chrome.tabs.create({url:a.homepageUrl,selected:selectTab(e)}):notifyExt(displayName(a),"Homepage is missing.",a)},this,a[f]),!1);l.appendChild(k);k.appendChild(document.createTextNode(separator+a[f].name+separator));try{l.classList.add(a[f].isApp?"appName":"extName")}catch(u){}k=document.createElement("span");k.setAttribute("class","version");k.id="ver#"+a[f].id;k.appendChild(document.createTextNode(separator+("v."+a[f].version)));var s=document.createElement("span");s.setAttribute("class","history");
if(currentAction==actionKind.Recently&&void 0!==a[f].type){var r=new Date(a[f].time);s.appendChild(document.createTextNode(separator+historyTypeName(a[f].eventType)+" "+r.toLocaleDateString()+" "+r.toLocaleTimeString()))}if(settings.getValue("showDescribeInline")){var t=document.createElement("span");t.setAttribute("class","description");r=document.createTextNode(a[f].description);t.appendChild(r)}h.appendChild(dfn(n,a[f].homepageUrl?"Click to open the homepage.":"No homepage specified."));h.appendChild(dfn(p,
"Uninstall"));h.appendChild(dfn(q,a[f].optionsUrl?"Open the options page":"haven't the options page"));h.appendChild(dfn(m,"Info"));h.appendChild(dfn(j,"Enable/Disable"));currentAction===actionKind.Outdated&&h.appendChild(dfn(anchorUpdate,"Update"));h.appendChild(l);h.appendChild(k);currentAction===actionKind.Recently?h.appendChild(s):settings.getValue("showDescribeInline")&&h.appendChild(t);g.appendChild(h);attachDragHandlers(h,{type:"extension",id:a[f].id})}g.style.visibility="visible";g.style.display=
"block";adjustListPos()}}function dfn(a,e,f){!a&&void 0!==f&&(a=document.querySelector('[data-dfn="'+f+'"]'));a&&(f&&a.setAttribute("data-dfn",f),settings.getValue("showTips")&&(a.title=e));return a}function hideInfo(a){if(a&&(a=document.querySelector('div.item[data-id="'+a.id+'"]')))return a.nextSibling&&a.nextSibling.classList.contains("info")?(a.parentNode.removeChild(a.nextSibling),!0):!1}
function showInfo(a){if(a){var e=document.querySelector('div.item[data-id="'+a.id+'"]');if(e&&!hideInfo(a)){var f=document.createElement("div");f.classList.add("info");f.setAttribute("data-id",a.id);var g=$create("<dl>"+addInfoItem("id",a.id)+addInfoItem("name",a.name)+addInfoItem("description",a.description)+addInfoItem("version",a.version)+addInfoItem("may be disabled",a.mayDisable)+addInfoItem("disable reason",a.disabledReason)+addInfoItem("type",a.type)+addInfoItem("app launch url",a.appLaunchUrl)+
addInfoURL("homepage url",a.homepageUrl)+addInfoItem("update url",a.updateUrl)+addInfoItem("offline enabled",a.offlineEnabled)+addInfoURL("options url",a.optionsUrl)+addInfoItem("permissions",a.permissions)+addInfoItem("hosts permiswsions",a.hostPermissions)+addInfoItem("install type",a.installType)+"</dl>");f.appendChild(g);$insertAfter(f,e);f.addEventListener("click",function(e){stopEvent(e);e.target&&e.target.href?chrome.tabs.create({url:e.target.href,selected:selectTab(e)}):hideInfo(a)},!1);showInfoWebStoreAppend(a);
apiBackground.wsExtension(a,function(a){showInfoWebStoreAppend(a)})}}}
function showInfoWebStoreAppend(a,e){var f=document.querySelector('.info[data-id="'+a.id+'"]'),g=a.webstore;console.log("showInfoWebStoreAppend",a,g,e);if(f&&g&&g._valid){var h=document.querySelector('.info[data-id="'+a.id+'"] > .webstore');h&&f.removeChild(h);g=$create("<dl>"+addInfoItem("author",g.author)+addInfoItem("date ",g.date)+addInfoItem("users / votes / rating ",g.users+" /  "+g.votes+" /  "+g.rating)+addInfoURL("site",g.site)+addInfoURL("support",g.support)+addInfoURL("category",g.category)+
addInfoItem("permission",g.permission)+addInfoItem("web store description",g.descr)+addInfoImage("logo",getUnitKind(a)===unitKind.theme?[g.demoimage,g.logo,g.demoicon,g.icon].find(Array.prototype.findNotNull):[g.logo,g.demoicon,g.demoimage,g.icon].find(Array.prototype.findNotNull))+"</dl>");g.classList.add("webstore");f.appendChild(g)}}function addInfoItem(a,e){return a&&e?"<dt>"+a+":</dt><dd>"+e+"</dd>":""}
function addInfoURL(a,e){return a&&e?"<dt>"+a+':</dt><dd><a href="'+e+'">'+e+"</a></dd>":""}function addInfoImage(a,e){return a&&e?"<dt>"+a+':</dt><dd><img src="'+e+'"></dd>':""}function notifyExt(a,e,f){apiBackground.notify({title:a,message:e,extInfo:f})}function notify(a,e,f){apiBackground.notify({title:a,message:e,icon:f})}function removeWithChilds(a){removeChilds(a);a.parentNode.removeChild(a)}
function removeChilds(a){if(a&&a.childNodes)for(var e=a.childNodes.length-1;0<=e;e--)a.removeChild(a.childNodes[e])}function stopEvent(a){a.stopPropagation();a.preventDefault()}function selectTab(a){return a.button?!1:!0}
function extListIterator(a,e){switch(a){case actionKind.All:loadExtInfo(e,function(a){return filterControl(a)});break;case actionKind.Extensions:loadExtInfo(e,function(a){return getUnitKind(a)===unitKind.extension&&filterControl(a)});break;case actionKind.Applications:loadExtInfo(e,function(a){return getUnitKind(a)===unitKind.app&&filterControl(a)});break;case actionKind.Themes:loadExtInfo(e,function(a){return getUnitKind(a)===unitKind.theme&&filterControl(a)});break;case actionKind.Enabled:loadExtInfo(e,
function(a){return a.enabled&&filterControl(a)});break;case actionKind.Disabled:loadExtInfo(e,function(a){return!a.enabled&&filterControl(a)});break;case actionKind.Outdated:loadExtInfo(e,function(a){return a.webstore&&a.webstore.version&&a.version!==a.webstore.version&&filterControl(a)});break;case actionKind.Recently:loadExtInfo(e,function(a){return filterControl(a)});break;case actionKind.Favorites:break;default:if(a>=actionKind.Group&&a<actionKind.GroupEnd){var f=groupGet(a),g=f?f.list.map(function(a){return a.id}):
[];loadExtInfo(e,function(a){return 0<=g.indexOf(a.id)&&filterControl(a)})}}}function historyTrackStart(a,e){var f=historyTrack.push({id:historyTrack.length,name:a,action:e,stamp:(new Date).valueOf(),items:[]})-1;dfn(null,"UNDO switch "+(e?"ON":"OFF")+" group '"+a+"'","undoSwitch");return f}function historyTrackAdd(a,e,f,g){historyTrack.some(function(e){if(e.id===g)return e.items.push({id:a,current:f}),!0})}
function historyTrackRemove(a,e){historyTrack.some(function(f){if(f.id===e)return f.items.some(function(e,h){if(e.id===a)return f.items.splice(h,1),!0}),!0})}function switchedAction(a){return a!==actionKind.Recently}function checkTheme(a){return getUnitKind(a)===unitKind.theme}function switchItem(a,e,f,g){a!==thisExtensionId&&!checkTheme(a)&&(historyTrackAdd(a,e,f,g),apiBackground.skipNotify(a,e),chrome.management.setEnabled(a,e))}
function switchOn(){if(switchedAction(currentAction)){var a=groupGet(currentAction);if(a){var e=historyTrackStart(a.name,!0);extListIterator(currentAction,function(a,g){if(a&&a.length)for(var h=0;h<a.length;h++)(!(void 0!==g&&g)||g(a[h]))&&switchItem(a[h].id,!0,a[h].enabled,e)});settings.getValue("showSwitchNotification")&&notify("Group "+a.name,"switches on")}}}
function switchOff(){if(switchedAction(currentAction)){var a=groupGet(currentAction);if(a){var e=historyTrackStart(a.name,!1);extListIterator(currentAction,function(a,g){if(a&&a.length)for(var h=0;h<a.length;h++)(!(void 0!==g&&g)||g(a[h]))&&switchItem(a[h].id,!1,a[h].enabled,e)});settings.getValue("showSwitchNotification")&&notify("Group "+a.name,"switches off")}}}
function switchUndo(){if(historyTrack){var a=historyTrack.pop(),e=a?a.items:null,f;if(e)for(var g=e.length-1;0<=g;g--)f=e[g].id,f!==thisExtensionId&&(apiBackground.skipNotify(f,e[g].current),chrome.management.setEnabled(f,e[g].current));e=historyTrack.length-1;0<=e?dfn(null,"UNDO switch "+(historyTrack[e].action?"ON":"OFF")+" group '"+historyTrack[e].name+"'","undoSwitch"):dfn(null,"Nothing to UNDO","undoSwitch");settings.getValue("showSwitchNotification")&&notify("Group "+a.name,"UNDO switch "+(a.action?
"on":"off"))}}function createBorderImage(a,e,f,g){var h=document.createElement("canvas"),l=h.getContext("2d");if(void 0===g||!g)g=10;a=Math.ceil(100*a/g);h.width=100;h.height=4;l.clearRect(0,0,100,4);l.fillStyle="#eeeeee";l.fillRect(0,0,100,4);l.fillStyle=e?e:"#af2b26";l.fillRect(0,3,a,4);l.fillStyle=f?f:"#D9D9D9";l.fillRect(a,3,100-a,4);return h.toDataURL("image/png")}var powerBorder=null,powerBase=10;
function drawPower(a,e,f){if(a){if(!powerBorder){powerBorder=[];for(var g=0;g<=powerBase;g++)powerBorder.push(createBorderImage(g,null,null,powerBase))}e=0<f?Math.ceil(e*powerBase/f):0;e%=powerBase+1;a.style.borderImageSource="url("+powerBorder[e]+")";a.style.borderImageRepeat="stretch";a.style.borderImageSlice="0 0 4";a.style.borderWidth="0 0 4px 0"}}
function calcGroupStatistics(){var a=[actionKind.All,actionKind.Extensions,actionKind.Applications];groupStorage.forEach(function(e){a.push(e.id)});a.forEach(function(a){extListIterator(a,function(f,g){if(f&&f.length){for(var h=0,l=0,k=0;k<f.length;k++)if(!(void 0!==g&&g)||g(f[k]))l+=f[k].enabled,h++;settings.getValue("showGroupStatisticsTips")&&dfn(null,"Enabled "+l+" of "+h,a);settings.getValue("showGroupStatisticsMeter")&&a>=actionKind.Group&&drawPower(document.querySelector('span[data-action="'+
a+'"]'),l,h)}})})}$ready(initialize);