var actionKind={All:0,Extensions:1,Applications:2,Enabled:3,Disabled:4,Favorites:5,Outdated:6,Recently:7,Themes:8,Group:900,GroupEnd:999},historyEventKind={Installed:0,Updated:1,Enabled:2,Disabled:3,InstalledEnabled:20,InstalledDisabled:30,UpdatedEnabled:21,UpdatedDisabled:31},noneDate=new Date(70,1,1),defaulthomepageUrl="https://chrome.google.com/webstore/ajax/detail",webStoreDetailUrl="https://chrome.google.com/webstore/detail/",webStoreFormatVersion="1326836727",unitKind={extension:0,app:1,theme:2,
group:3,unknown:-1},thisExtensionId=chrome.runtime?chrome.runtime.id:chrome.i18n.getMessage("@@extension_id"),RESERVEDNAMES=["all"],apiExt=chrome.extension,apiRuntime=chrome.runtime,apiBackground=apiExt&&apiExt.getBackgroundPage?apiExt.getBackgroundPage():(function(){throw Error("getBackgroundPage method not implemented.");}(),{}),apiSendMessage=apiRuntime&&apiRuntime.sendMessage?apiRuntime.sendMessage:apiExt&&apiExt.sendMessage?apiExt.sendMessage:apiExt&&apiExt.sendRequest?apiExt.sendRequest:(function(){throw Error("SendMessage method not implemented.");
}(),function(){}),apiOnMessage=apiRuntime&&apiRuntime.onMessage?apiRuntime.onMessage:apiExt&&apiExt.onMessage?apiExt.onMessage:apiExt&&apiExt.onRequest?apiExt.onRequest:(function(){throw Error("onMessage method not implemented.");}(),{}),_xhrRequestOnline=0,_xhrRequestSuspend=0,_xhrRequestSuspendQueue=[];
function getUnitKind(a){if("string"===typeof a&&(a=chrome.extension.getBackgroundPage().getExtInfoItem(a),"object"!==typeof a||!("type"in a)))return unitKind.extension;var b=a.isApp?unitKind.app:unitKind.extension;switch(a.type){case "extension":b=unitKind.extension;break;case "hosted_app":case "packaged_app":case "legacy_packaged_app":b=unitKind.app;break;case "theme":b=unitKind.theme;break;default:b=unitKind.extension}return b}
function toUnitKind(a){var b=unitKind.extension;switch(a){case 0:b=unitKind.extension;break;case 4:b=unitKind.app;break;case 1:b=unitKind.theme;break;default:b=unitKind.extension}return b}var bind=function(a,b,c){if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};
function displayName(a){var b;if(a){switch(getUnitKind(a)){case unitKind.app:b=" application";break;case unitKind.theme:b=" theme";break;default:b=" extension"}return"'"+a.name+"'"+b}}function displayCurrentTime(){return(new Date).toLocaleTimeString()}function displayTime(a){a=new Date(1E3*a);return a.toLocaleDateString()+" "+a.toLocaleTimeString()}
function getIconUrl(a,b){var c=void 0===b?48:b,d=0,f,g="icons/empty.png";if(a)for(f=0;f<a.length;f++)if(!d||Math.abs(a[f].size-c)<=Math.abs(d-c))g=a[f].url,d=a[f].size;return g}
var ordinalSort=function(a,b){var c=a.name.toUpperCase(),d=b.name.toUpperCase();return c<d?-1:c>d?1:0},historySort=function(a,b){var c=a.time?a.time:noneDate,d=b.time?b.time:noneDate,c=(new Date(c)).getTime(),d=(new Date(d)).getTime();return(c<d)-(c>d)},historyTypeName=function(a){var b="";switch(a){case historyEventKind.Installed:b="installed";break;case historyEventKind.Updated:b="updated";break;case historyEventKind.Enabled:b="enabled";break;case historyEventKind.Disabled:b="disabled";break;case historyEventKind.InstalledEnabled:b=
"installed & enabled";break;case historyEventKind.InstalledDisabled:b="installed & disabled";break;case historyEventKind.UpdatedEnabled:b="updated & enabled";break;case historyEventKind.UpdatedDisabled:b="updated & disabled"}return b};function daysBetween(a,b){return Math.round(Math.abs(a.getTime()-b.getTime())/864E5)}function isImageLoaded(a){return!a.complete?!1:!0}
function xhrClearQueue(){for(var a=0;a<_xhrRequestSuspendQueue.length;a++)clearTimeout(_xhrRequestSuspendQueue[a]);_xhrRequestSuspend=0}
function xhrRequest(a,b,c,d,f,g){if(1<=_xhrRequestOnline||"active"===idleState&&!g)_xhrRequestSuspend++,_xhrRequestSuspendQueue.push(window.setTimeout(bind(function(a,b,c,d,e,f){_xhrRequestSuspend--;xhrRequest(a,b,c,d,e,f)},this,a,b,c,d,f,g),1200*_xhrRequestSuspend));else{0>=_xhrRequestSuspend&&xhrClearQueue();_xhrRequestOnline++;var e=new XMLHttpRequest;e.url=a;e.abortTimer=window.setTimeout(function(){_xhrRequestOnline--;e.abort()},requestTimeout);try{e.onreadystatechange=function(){4==e.readyState&&
(_xhrRequestOnline--,400>e.status&&(e.responseText&&"function"===typeof d)&&d(e),e.abortTimer&&clearTimeout(e.abortTimer),e.abortTimer=null,e.onerror=null)},e.onerror=function(){clearTimeout(e.abortTimer);e.abortTimer=null;_xhrRequestOnline--;f&&f(e)},e.open(b,a,!0),e.setRequestHeader("Content-type","application/x-www-form-urlencoded"),e.send(c)}catch(h){_xhrRequestOnline--,f(e)}}}function tryIntParse(a){a=parseInt(a);isNaN(a)&&(a=0);return a}
String.prototype.trim=String.prototype.trim||function(){return this.replace(/^\s\s*/,"").replace(/\s\s*$/,"")};function $parentFind(a,b,c){!c&&"undefined"!==typeof c&&(a=a.parentNode);if(a){do{if(b(a))return a;a=a.parentNode}while(a&&a!==a.parentNode)}return null}var _eventHandlers={};function addEvent(a,b,c,d){a in _eventHandlers||(_eventHandlers[a]={});b in _eventHandlers[a]||(_eventHandlers[a][b]=[]);_eventHandlers[a][b].push([c,d]);a.addEventListener(b,c,d)}
function removeAllEvents(a,b){if(a in _eventHandlers){var c=_eventHandlers[a];if(b in c)for(var c=c[b],d=c.length;d--;){var f=c[d];a.removeEventListener(b,f[0],f[1])}}}function versionNormalize(a){a=a.split(".");for(var b=Math.max(a.length,4),c=0,d=a.length;0<=--d;)c+=Math.pow(10,b-d)*tryIntParse(a[d]);return c}$id=function(a){return document.getElementById(a)};DOMContentLoaded=function(a){document.removeEventListener("DOMContentLoaded",DOMContentLoaded,!1);a()};
$ready=function(a){"complete"===document.readyState?a():document.addEventListener("DOMContentLoaded",bind(DOMContentLoaded,this,a),!1)};$insertAfter=function(a,b){var c=b.parentNode;c.lastchild===b?c.appendChild(a):c.insertBefore(a,b.nextSibling);return b};String.prototype.hashCode=function(){for(var a=0,b=0;b<this.length;b++)a=(a<<5)-a+this.charCodeAt(b),a&=a;return a};var _forEach=Array.prototype.forEach;$create=function(a,b){var c=document.createElement(b?b:"div");c.innerHTML=a;return c};
Array.prototype.find||(Array.prototype.find=function(a,b){var c=this.length;if("function"!=typeof a)throw new TypeError;for(var d=0;d<c;d++)if(d in this&&a.call(b,this[d],d,this))return this[d];return null});Array.prototype.findNotNull||(Array.prototype.findNotNull=function(a){return!!a});