var tabDataMap={},tabRegistry={},globalTabRegistry=[],windowFocusTabId={},windowRegistry=[],recentlyClosedURLs=[],recentlySelectedTabs=[],ENTRIES_PER_TAB=10,MAX_RECENT_TABS=12,MAX_RECENTLY_CLOSED=12,MAX_RECENTLY_SELECTED=12,MAJOR_VERSION=0.7;chrome.tabs.onUpdated.addListener(function(a,b){b.status=="complete"&&chrome.pageAction.show(a)});
chrome.tabs.onSelectionChanged.addListener(function(a){windowFocusTabId[tabDataMap[a].windowId]=a;for(i=0;i<recentlySelectedTabs.length;i++)if(recentlySelectedTabs[i]==a){recentlySelectedTabs.splice(i,1);break}recentlySelectedTabs.unshift(a);recentlySelectedTabs.length>MAX_RECENTLY_SELECTED&&recentlySelectedTabs.pop()});function tabData(a,b){this.id=a;this.windowId=b;this.favIconURL=this.title="";this.URL=[];this.popped=this.pinned=!1;this.parent=this.id;this.children=[]}
function urlData(a,b,c){this.URL=a;this.title=b;this.favIconURL=c}
chrome.tabs.onUpdated.addListener(function(a,b,c){if(c.title)tabDataMap[a].title=c.title;if(c.favIconUrl)tabDataMap[a].favIconURL=c.favIconUrl;if(b.url&&tabDataMap[a]){if(tabDataMap[a].URL)for(var d=0;d<tabDataMap[a].URL.length;d++)if(tabDataMap[a].URL[d]==b.url){tabDataMap[a].URL.splice(d,1);break}b=new urlData(b.url,c.title,c.favIconUrl);tabDataMap[a].URL.push(b);tabDataMap[a].URL.length>ENTRIES_PER_TAB&&tabDataMap[a].URL.shift();chrome.pageAction.show(c.id)}else if(tabDataMap[a])b=tabDataMap[a].URL.length-
1,tabDataMap[a].URL[b].title=c.title,tabDataMap[a].URL[b].favIconURL=c.favIconUrl});
chrome.tabs.onCreated.addListener(function(a){if(!tabDataMap[a.id]){tabDataMap[a.id]=new tabData(a.id,a.windowId);tabRegistry[a.windowId]||(tabRegistry[a.windowId]=[],windowRegistry.push(a.windowId));var b=!1;for(i=0;i<tabRegistry[a.windowId].length;i++)tabRegistry[a.windowId][i]==a.id&&(b=!0);b||(tabRegistry[a.windowId].push(a.id),globalTabRegistry.push(a.id))}if(windowFocusTabId[a.windowId]&&tabDataMap[a.id].URL.length==0&&a.url!="chrome://newtab/")tabDataMap[a.id].parent=windowFocusTabId[a.windowId],
tabDataMap[windowFocusTabId[a.windowId]].children.push(a.id);if(a.title)tabDataMap[a.id].title=a.title;b=new urlData(a.url,a.title,a.favIconUrl);tabDataMap[a.id].URL.push(b);tabDataMap[a.id].favIconURL=a.favIconUrl;chrome.pageAction.show(a.id)});
chrome.tabs.onAttached.addListener(function(a,b){tabRegistry[b.newWindowId]||(tabRegistry[b.newWindowId]=[],windowRegistry.push(b.newWindowId));for(i=0;i<tabRegistry[tabDataMap[a].windowId].length;i++)if(tabRegistry[tabDataMap[a].windowId][i]==a){tabRegistry[tabDataMap[a].windowId].splice(i,1);break}tabDataMap[a].windowId=b.newWindowId;tabRegistry[b.newWindowId].push(a)});
chrome.tabs.onRemoved.addListener(function(a){for(i=0;i<tabRegistry[tabDataMap[a].windowId].length;i++)if(tabRegistry[tabDataMap[a].windowId][i]==a){tabRegistry[tabDataMap[a].windowId].splice(i,1);break}for(i=0;i<globalTabRegistry.length;i++)if(globalTabRegistry[i]==a){globalTabRegistry.splice(i,1);break}for(i=0;i<recentlySelectedTabs.length;i++)if(recentlySelectedTabs[i]==a){recentlySelectedTabs.splice(i,1);break}var b=3;if(tabDataMap[a].URL.length<b)b=tabDataMap[a].URL.length;for(i=tabDataMap[a].URL.length-
b;i<tabDataMap[a].URL.length;i++)tabDataMap[a].URL[i].URL!="chrome://newtab/"&&tabDataMap[a].URL[i].URL!=""&&recentlyClosedURLs.unshift(tabDataMap[a].URL[i]);for(;recentlyClosedURLs.length>MAX_RECENTLY_CLOSED;)recentlyClosedURLs.pop();b=tabDataMap[a].parent;for(i=0;i<tabDataMap[b].children.length;i++)tabDataMap[b].children[i]==a&&tabDataMap[b].children.splice(i,1);b=tabDataMap[a].children;for(i=0;i<b.length;i++)tabDataMap[b[i]].parent=tabDataMap[b[i]].id;delete tabDataMap[a]});
function init(){chrome.windows.getAll({populate:!0},function(a){a.forEach(function(a){var b=a.id;window.focus();a.tabs.forEach(function(a){tabDataMap[a.id]=new tabData(a.id,b);tabRegistry[b]||(tabRegistry[b]=[],windowRegistry.push(b));tabRegistry[b].push(a.id);globalTabRegistry.push(a.id);tabDataMap[a.id].title=a.title;tabDataMap[a.id].favIconURL=a.favIconUrl;chrome.pageAction.show(a.id);if(a.url){var c=new urlData(a.url,a.title,a.favIconUrl);tabDataMap[a.id].URL.push(c);tabDataMap[a.id].URL.length>
ENTRIES_PER_TAB&&tabDataMap[a.id].URL.shift()}})})});chrome.tabs.getSelected(null,function(a){chrome.tabs.getAllInWindow(null,function(c){recentlySelectedTabs.push(a.id);for(var d=0;d<c.length;d++)c[d].id!=a.id&&Math.abs(c[d].index-a.index)<=3&&recentlySelectedTabs.push(c[d].id)})});try{if(!localStorage.updateread)localStorage.updateread=MAJOR_VERSION,chrome.tabs.create({url:"http://blog.visibotech.com/2010/04/thank-you-for-installing-tabjump.html"})}catch(a){}}init();
