var MAX_SHOW_TABS=10,background=chrome.extension.getBackgroundPage();function getMessage(a,b){try{var c=chrome.i18n.getMessage(a,b);if(c)return c}catch(e){console.err.log(e)}}
function init(){protectedIcon.onclick=changePageProtection;unprotectedIcon.onclick=changePageProtection;document.getElementById("tabbacktitle").innerHTML="Jump";document.getElementById("tabsimilartitle").innerHTML="Related";document.getElementById("tabundotitle").innerHTML="Undo";document.getElementById("tabbackdescription").innerHTML=getMessage("frequentlyUsedTabs");document.getElementById("tabundodescription").innerHTML=getMessage("recentlyClosedTabs");document.getElementById("tabClearRecentlyClosedTabsHistory").title=
getMessage("clearRecentlyClosedTabsHistory");document.getElementById("tabsimilardescription").innerHTML=getMessage("relatedTabs");document.getElementById("protectedIcon").title=getMessage("unlockPage");document.getElementById("unprotectedIcon").title=getMessage("lockPage");document.getElementById("protectedDisableIcon").title=getMessage("cannotLockPage");setTabTitle();document.getElementById("tabbackcolumn");document.getElementById("tabundocolumn");document.getElementById("tabsimilarcolumn");var a=
0;document.getElementById("tabClearRecentlyClosedTabsHistory").addEventListener("click",clearRecentlyClosedTabsHistory);checkAllowProtection();var b=background.recentlySelectedTabs.length;b>MAX_SHOW_TABS&&(b=MAX_SHOW_TABS);chrome.windows.getCurrent(function(e){var d=0;chrome.tabs.getSelected(null,function(c){for(a=0;a<background.recentlySelectedTabs.length;a++){var g=background.recentlySelectedTabs[a],h=background.tabDataMap[g];if(h&&(h.windowId==e.id&&g!=c.id&&(createTabbox(h,"back"),d+=1),d>=b))break}})});
var c=background.recentlyClosedURLs.length;c>MAX_SHOW_TABS&&(c=MAX_SHOW_TABS);for(a=0;a<c;a++)createTabbox(background.recentlyClosedURLs[a],"undo",a);chrome.tabs.getSelected(null,function(b){var b=background.tabDataMap[b.id],d=[];if(b)if(b.children.length>0)for(a=0;a<b.children.length;a++)d.push({tabId:background.tabDataMap[b.children[a]].id,score:1.5});else{var c=background.tabDataMap[b.parent];if(c.id!=b.id){d.push({tabId:c.id,score:1.5});for(a=0;a<c.children.length;a++){var g=background.tabDataMap[c.children[a]];
g.id!=b.id&&d.push({tabId:g.id,score:1.5})}}}getSameDomain(function(a){for(var b=[],c=[],f=0;f<a.length;f++)if(a[f].score>=2)b[a[f].tabId]=a[f].score;for(f=0;f<d.length;f++)b[d[f].tabId]!=null?b[d[f].tabId]+=parseFloat(d[f].score):b[d[f].tabId]=parseFloat(d[f].score);for(var f in b)c.push({tabId:f,score:b[f]});var c=c.sort(function(a,b){return b.score-a.score}),e=c.length;e>MAX_SHOW_TABS&&(e=MAX_SHOW_TABS);chrome.windows.getCurrent(function(a){var b=0;chrome.tabs.getSelected(null,function(d){for(f=
0;f<c.length;f++){var g=c[f].tabId,h=background.tabDataMap[g];h.windowId==a.id&&g!=d.id&&(createTabbox(h,"similar"),b+=1);if(b>=e)break}})})})});if(localStorage.updateread<background.MAJOR_VERSION)c=document.getElementById("updateNotifier"),c.style.display="block",c.onclick=function(){localStorage.updateread=background.MAJOR_VERSION;chrome.tabs.create({url:"http://www.visibotech.com/TabJump/update070.html"});window.close()}}
function createTabbox(a,b,c){var e=document.createElement("div"),d=document.createElement("img");d.src=a.favIconURL?a.favIconURL:"img/favicons.png";d.setAttribute("class","favicon");e.appendChild(d);d=document.createElement("div");d.textContent=a.title!=""?a.title:b=="undo"?a.URL:getMessage("loading");d.setAttribute("class","tabtitle");e.appendChild(d);e.setAttribute("class","tabbox");e.title=getMessage("clickToOpen",[d.textContent]);b=="undo"?e.setAttribute("tabid",b+"_"+c):e.setAttribute("tabid",
b+"_"+a.id);b=="back"?(a=document.getElementById("tabbackcolumn"),e.addEventListener("click",tabbackClickHandler),a.appendChild(e)):b=="similar"?(a=document.getElementById("tabsimilarcolumn"),e.addEventListener("click",tabsimilarClickHandler),a.appendChild(e)):b=="undo"&&(a=document.getElementById("tabundocolumn"),e.addEventListener("click",tabundoClickHandler),a.appendChild(e))}
function tabbackClickHandler(a){a=a.currentTarget.getAttribute("tabid").replace(/back_/,"");chrome.tabs.update(parseInt(a),{selected:!0});window.close()}function tabsimilarClickHandler(a){a=a.currentTarget.getAttribute("tabid").replace(/similar_/,"");chrome.tabs.update(parseInt(a),{selected:!0});window.close()}
function tabundoClickHandler(a){var b=a.button==1||a.metaKey==!0?!1:!0,a=a.currentTarget.getAttribute("tabid").replace(/undo_/,"");chrome.tabs.create({url:background.recentlyClosedURLs[a].URL,selected:b});background.recentlyClosedURLs.splice(a,1);if(b==!1){a=document.getElementById("tabundocolumn").getElementsByClassName("tabbox");for(b=a.length-1;b>=0;b--)a[b].parentNode.removeChild(a[b]);a=background.recentlyClosedURLs.length;a>MAX_SHOW_TABS&&(a=MAX_SHOW_TABS);for(b=0;b<a;b++)createTabbox(background.recentlyClosedURLs[b],
"undo",b)}}function getSameDomain(a){chrome.tabs.getSelected(null,function(b){var c=[];try{var e=/^([A-Za-z]+:\/+)*([^\:^\/]+):?(\d*)(\/.*)*/,d=b.url.match(e)[2].split(".")}catch(l){a([]);return}var g=background.tabDataMap,h;for(h in g)if(g[h].URL.length){var i=g[h].URL[g[h].URL.length-1].URL;try{if(h!=b.id){for(var j=i.match(e)[2].split("."),f=i=0,f=d.length>j.length?d.length:j.length,k=1;k<f+1;k++)if(d[d.length-k]==j[j.length-k])i+=1;else break;c.push({tabId:h,score:i})}}catch(m){}}a(c)})}
function setTabTitle(){chrome.tabs.getSelected(null,function(a){a=a.status=="complete"?a.title:getMessage("loading");document.getElementById("currentTitle").textContent=a})}function changePageProtection(){chrome.tabs.getSelected(null,function(a){chrome.tabs.sendMessage(a.id,{action:"changeProtection"},function(a){toggleProtectionIcon(a)})})}
function checkAllowProtection(){chrome.tabs.getSelected(null,function(a){if(a.url.indexOf("chrome")==0||a.url.indexOf("chrome.google.com/extensions")>=0||a.url.indexOf("mail.google.com")>=0){var a=document.getElementById("protectedIcon"),b=document.getElementById("unprotectedIcon"),c=document.getElementById("protectedDisableIcon");a.setAttribute("style","display:none");b.setAttribute("style","display:none");c.setAttribute("style","display:block")}else chrome.tabs.sendMessage(a.id,{action:"currentStatus"},
function(a){toggleProtectionIcon(a)})})}function toggleProtectionIcon(a){var b=document.getElementById("protectedIcon"),c=document.getElementById("unprotectedIcon");a==!0?(b.setAttribute("style","display:block"),c.setAttribute("style","display:none")):(c.setAttribute("style","display:block"),b.setAttribute("style","display:none"))}
function clearRecentlyClosedTabsHistory(){background.recentlyClosedURLs=[];for(var a=document.getElementById("tabundocolumn").getElementsByClassName("tabbox"),b=a.length-1;b>=0;b--)a[b].parentNode.removeChild(a[b])}window.onload=function(){console.log("onload");init()};
