//@ sourceMappingURL=share.map
// Generated by CoffeeScript 1.6.1
(function() {

  BH.Persistence.Share = (function() {

    function Share(remote) {
      this.remote = remote != null ? remote : $.ajax;
    }

    Share.prototype.send = function(sharedTag, callbacks) {
      var _this = this;
      return this.remote({
        url: "http://" + apiHost + "/share",
        data: JSON.stringify(sharedTag),
        type: 'POST',
        dataType: 'json',
        contentType: 'application/json',
        success: function(data) {
          return callbacks.success(data);
        },
        error: function() {
          return callbacks.error();
        }
      });
    };

    return Share;

  })();

}).call(this);
