//@ sourceMappingURL=auth_successful_view.map
// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Views.AuthSuccessfulView = (function(_super) {

    __extends(AuthSuccessfulView, _super);

    function AuthSuccessfulView() {
      return AuthSuccessfulView.__super__.constructor.apply(this, arguments);
    }

    AuthSuccessfulView.include(BH.Modules.I18n);

    AuthSuccessfulView.prototype.className = 'auth_success_view';

    AuthSuccessfulView.prototype.template = BH.Templates['auth_successful'];

    AuthSuccessfulView.prototype.events = {
      'click .done': 'doneClicked'
    };

    AuthSuccessfulView.prototype.initialize = function() {
      this.chromeAPI = chrome;
      this.tracker = this.options.tracker;
      return this.attachGeneralEvents();
    };

    AuthSuccessfulView.prototype.render = function() {
      this.$el.html(this.renderTemplate(this.getI18nValues()));
      return this;
    };

    AuthSuccessfulView.prototype.doneClicked = function(ev) {
      ev.preventDefault();
      return this.close();
    };

    AuthSuccessfulView.prototype.getI18nValues = function() {
      return this.t(['prompt_done_button', 'auth_success_title', 'auth_success_description']);
    };

    return AuthSuccessfulView;

  })(BH.Views.ModalView);

}).call(this);
