// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Views.MenuView = (function(_super) {

    __extends(MenuView, _super);

    function MenuView() {
      return MenuView.__super__.constructor.apply(this, arguments);
    }

    MenuView.prototype.template = BH.Templates['menu'];

    MenuView.prototype.events = {
      'click .menu > *': 'weekClicked'
    };

    MenuView.prototype.render = function() {
      var html;
      html = Mustache.to_html(this.template, this.collection.toTemplate());
      return this.$el.html(html);
    };

    MenuView.prototype.weekClicked = function(ev) {
      var $el;
      this.$('.menu > *').removeClass('selected');
      $el = $(ev.currentTarget);
      $el.addClass('selected');
      return analyticsTracker.weekView($el.data('week-id'), $el.index());
    };

    return MenuView;

  })(Backbone.View);

}).call(this);
