// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Views.ReadOnlyExplanationView = (function(_super) {

    __extends(ReadOnlyExplanationView, _super);

    function ReadOnlyExplanationView() {
      return ReadOnlyExplanationView.__super__.constructor.apply(this, arguments);
    }

    ReadOnlyExplanationView.include(BH.Modules.I18n);

    ReadOnlyExplanationView.prototype.className = 'read_only_explanation_view';

    ReadOnlyExplanationView.prototype.template = BH.Templates['read_only_explanation'];

    ReadOnlyExplanationView.prototype.events = {
      'click .okay': 'okayClicked'
    };

    ReadOnlyExplanationView.prototype.initialize = function() {
      this.chromeAPI = chrome;
      this.tracker = this.options.tracker;
      return this.attachGeneralEvents();
    };

    ReadOnlyExplanationView.prototype.render = function() {
      this.$el.html(this.renderTemplate(this.getI18nValues()));
      return this;
    };

    ReadOnlyExplanationView.prototype.okayClicked = function(ev) {
      ev.preventDefault();
      return this.close();
    };

    ReadOnlyExplanationView.prototype.getI18nValues = function() {
      return this.t(['prompt_okay_button', 'read_only_explanation_title', 'read_only_explanation_description']);
    };

    return ReadOnlyExplanationView;

  })(BH.Views.ModalView);

}).call(this);
