// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Views.TagsListView = (function(_super) {

    __extends(TagsListView, _super);

    function TagsListView() {
      return TagsListView.__super__.constructor.apply(this, arguments);
    }

    TagsListView.include(BH.Modules.I18n);

    TagsListView.prototype.className = 'tags_list_view';

    TagsListView.prototype.template = BH.Templates['tags_list'];

    TagsListView.prototype.initialize = function() {
      return this.chromeAPI = chrome;
    };

    TagsListView.prototype.render = function() {
      var html, presenter, properties;
      presenter = new BH.Presenters.TagsPresenter(this.collection);
      properties = _.extend(presenter.tagsSummary(), this.getI18nValues());
      html = Mustache.to_html(this.template, properties);
      this.$el.html(html);
      return this;
    };

    TagsListView.prototype.getI18nValues = function() {
      var properties;
      properties = this.t(['no_tags_found', 'about_tags_title']);
      properties.i18n_about_tags_instructions = this.t('about_tags_instructions', ['<a href="#" class="how_to_tag">', '</a>', '<a href="http://mad.ly/signups/84938/join">', '</a>']);
      properties.i18n_extra_tag_help = this.t('extra_tag_help', ['<a href="#" class="how_to_tag">', '</a>', '<a href="#" class="load_example_tags">', '</a>']);
      return properties;
    };

    return TagsListView;

  })(BH.Views.MainView);

}).call(this);
