// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Views.VisitView = (function(_super) {

    __extends(VisitView, _super);

    function VisitView() {
      return VisitView.__super__.constructor.apply(this, arguments);
    }

    VisitView.include(BH.Modules.I18n);

    VisitView.prototype.className = 'visit_view';

    VisitView.prototype.template = BH.Templates['visit'];

    VisitView.prototype.events = {
      'click .delete_visit': 'deleteClicked'
    };

    VisitView.prototype.render = function() {
      var html, properties;
      properties = _.extend(this.getI18nValues(), this.model.toTemplate());
      html = Mustache.to_html(this.template, properties);
      this.$el.html(html);
      return this;
    };

    VisitView.prototype.deleteClicked = function(ev) {
      var _this = this;
      ev.preventDefault();
      return this.model.destroy({
        success: function() {
          var method;
          method = _this._isGroupedAndEmpty() ? '_removeGroup' : '_remove';
          return _this[method]();
        }
      });
    };

    VisitView.prototype._remove = function() {
      return this.$el.slideUp('fast', function() {
        return $el.remove();
      });
    };

    VisitView.prototype._removeGroup = function() {
      return $(this._getGroup()).slideUp('fast', function() {
        return $el.remove();
      });
    };

    VisitView.prototype._isGroupedAndEmpty = function() {
      if (this.$el.parents('.expanded').children().length === 1) {
        return true;
      } else {
        return false;
      }
    };

    VisitView.prototype._getGroup = function() {
      return this.$el.parents('.grouped_visits_view');
    };

    VisitView.prototype.getI18nValues = function() {
      return this.t(['prompt_delete_button']);
    };

    return VisitView;

  })(Backbone.View);

}).call(this);
