//@ sourceMappingURL=search_history.map
// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Chrome.SearchHistory = (function(_super) {

    __extends(SearchHistory, _super);

    function SearchHistory(query) {
      this.query = query;
      this.historyQuery = new BH.Lib.HistoryQuery(chrome);
    }

    SearchHistory.prototype.fetch = function() {
      var options,
        _this = this;
      options = {
        text: this.query,
        searching: true
      };
      return this.historyQuery.run(options, function(history) {
        return _this.trigger('query:complete', [history]);
      });
    };

    SearchHistory.prototype.destroy = function() {
      this.fetch();
      return this.on('query:complete', function(history) {
        var visit, _i, _len;
        for (_i = 0, _len = history.length; _i < _len; _i++) {
          visit = history[_i];
          chrome.history.deleteUrl({
            url: visit.url
          });
        }
        return this.trigger('destroy:complete');
      });
    };

    return SearchHistory;

  })(EventEmitter);

}).call(this);
