//@ sourceMappingURL=weeks_history.map
// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Chrome.WeeksHistory = (function(_super) {

    __extends(WeeksHistory, _super);

    function WeeksHistory() {
      return WeeksHistory.__super__.constructor.apply(this, arguments);
    }

    WeeksHistory.prototype.fetch = function() {
      var historyQuery,
        _this = this;
      historyQuery = new BH.Lib.HistoryQuery();
      return historyQuery.run({
        startTime: 0,
        maxResults: 0,
        endTime: new Date().getTime(),
        text: ''
      }, function(history) {
        var options;
        options = {
          visits: history,
          config: {
            startingWeekDay: settings.get('startingWeekDay')
          }
        };
        return BH.Modules.Worker.worker('weekGrouper', options, function(history) {
          return _this.trigger('query:complete', [history]);
        });
      });
    };

    WeeksHistory.prototype.destroy = function() {
      var _this = this;
      return chrome.history.deleteAll(function() {
        return _this.trigger('destroy:complete');
      });
    };

    return WeeksHistory;

  })(EventEmitter);

}).call(this);
