// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Modals.LoginErrorModal = (function(_super) {

    __extends(LoginErrorModal, _super);

    function LoginErrorModal() {
      return LoginErrorModal.__super__.constructor.apply(this, arguments);
    }

    LoginErrorModal.include(BH.Modules.I18n);

    LoginErrorModal.prototype.className = 'login_error_view';

    LoginErrorModal.prototype.template = BH.Templates['login_error'];

    LoginErrorModal.prototype.events = {
      'click .okay': 'okayClicked'
    };

    LoginErrorModal.prototype.initialize = function() {
      this.chromeAPI = chrome;
      this.tracker = this.options.tracker;
      return this.attachGeneralEvents();
    };

    LoginErrorModal.prototype.render = function() {
      this.$el.html(this.renderTemplate(this.getI18nValues()));
      return this;
    };

    LoginErrorModal.prototype.okayClicked = function(ev) {
      ev.preventDefault();
      return this.close();
    };

    LoginErrorModal.prototype.getI18nValues = function() {
      return this.t(['prompt_okay_button', 'login_error_title', 'login_error_description']);
    };

    return LoginErrorModal;

  })(BH.Modals.Base);

}).call(this);
