// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Modals.ReadOnlyExplanationModal = (function(_super) {

    __extends(ReadOnlyExplanationModal, _super);

    function ReadOnlyExplanationModal() {
      return ReadOnlyExplanationModal.__super__.constructor.apply(this, arguments);
    }

    ReadOnlyExplanationModal.include(BH.Modules.I18n);

    ReadOnlyExplanationModal.prototype.className = 'read_only_explanation_view';

    ReadOnlyExplanationModal.prototype.template = BH.Templates['read_only_explanation'];

    ReadOnlyExplanationModal.prototype.events = {
      'click .okay': 'okayClicked'
    };

    ReadOnlyExplanationModal.prototype.initialize = function() {
      this.chromeAPI = chrome;
      this.tracker = this.options.tracker;
      return this.attachGeneralEvents();
    };

    ReadOnlyExplanationModal.prototype.render = function() {
      this.$el.html(this.renderTemplate(this.getI18nValues()));
      return this;
    };

    ReadOnlyExplanationModal.prototype.okayClicked = function(ev) {
      ev.preventDefault();
      return this.close();
    };

    ReadOnlyExplanationModal.prototype.getI18nValues = function() {
      return this.t(['prompt_okay_button', 'read_only_explanation_title', 'read_only_explanation_description']);
    };

    return ReadOnlyExplanationModal;

  })(BH.Modals.Base);

}).call(this);
