// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Modals.RenameTagModal = (function(_super) {

    __extends(RenameTagModal, _super);

    function RenameTagModal() {
      return RenameTagModal.__super__.constructor.apply(this, arguments);
    }

    RenameTagModal.include(BH.Modules.I18n);

    RenameTagModal.prototype.className = 'rename_tag_view';

    RenameTagModal.prototype.template = BH.Templates['rename_tag'];

    RenameTagModal.prototype.events = {
      'click .cancel': 'cancelClicked',
      'click .rename': 'renameClicked'
    };

    RenameTagModal.prototype.initialize = function() {
      this.chromeAPI = chrome;
      this.tracker = this.options.tracker;
      return this.attachGeneralEvents();
    };

    RenameTagModal.prototype.render = function() {
      this.$el.html(this.renderTemplate(this.getI18nValues()));
      return this;
    };

    RenameTagModal.prototype.cancelClicked = function(ev) {
      ev.preventDefault();
      return this.close();
    };

    RenameTagModal.prototype.renameClicked = function(ev) {
      var tag,
        _this = this;
      ev.preventDefault();
      tag = this.$('input.new_tag').val();
      tag = tag.replace(/^\s\s*/, '').replace(/\s\s*$/, '');
      if (tag.length === 0) {
        return false;
      }
      return this.model.renameTag(this.$('input.new_tag').val(), function() {
        _this.tracker.tagRenamed();
        return _this.close();
      });
    };

    RenameTagModal.prototype.getI18nValues = function() {
      var properties;
      properties = this.t(['rename_tag_button', 'prompt_cancel_button', 'new_tag_placeholder']);
      properties['i18n_rename_tag_title'] = this.t('rename_tag_title', [this.model.get('name')]);
      return properties;
    };

    return RenameTagModal;

  })(BH.Modals.Base);

}).call(this);
