// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Collections.Weeks = (function(_super) {

    __extends(Weeks, _super);

    function Weeks() {
      return Weeks.__super__.constructor.apply(this, arguments);
    }

    Weeks.prototype.reload = function(startingDay) {
      var date, i, _i, _len, _ref;
      this.reset();
      _ref = _.range(10);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        i = _ref[_i];
        date = moment(new Date()).past(startingDay, i);
        this.add({
          id: date.format("M-D-YY"),
          date: date
        });
      }
      return this.trigger('reloaded');
    };

    return Weeks;

  })(Backbone.Collection);

}).call(this);
