//@ sourceMappingURL=interval_presenter.map
// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Presenters.IntervalPresenter = (function(_super) {

    __extends(IntervalPresenter, _super);

    function IntervalPresenter(model) {
      this.model = model;
    }

    IntervalPresenter.prototype.interval = function() {
      var presenter, properties;
      properties = {
        amount: this.t('number_of_visits', [this.model.get('visits').length.toString(), '<span class="amount">', '</span>']),
        time: moment(this.model.get('datetime')).format('LT'),
        id: this.model.id
      };
      presenter = new BH.Presenters.VisitsPresenter(this.model.get('visits'));
      return _.extend(properties, presenter.visits());
    };

    return IntervalPresenter;

  })(BH.Presenters.Base);

}).call(this);
