// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Presenters.SearchPresenter = (function(_super) {

    __extends(SearchPresenter, _super);

    function SearchPresenter(search) {
      this.search = search;
    }

    SearchPresenter.prototype.searchInfo = function() {
      var i, joined, term, _i, _len, _ref;
      this.terms = [];
      if (this.search.query != null) {
        this.terms = this.search.query.split(' ');
      }
      joined = this.t('searching_title') + ' ';
      _ref = this.terms;
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        term = _ref[i];
        joined += "\"" + term + "\"";
        if (i !== this.terms.length - 1) {
          joined += " " + (this.t('and')) + " ";
        }
      }
      return _.extend(this.search, {
        title: joined
      });
    };

    return SearchPresenter;

  })(BH.Presenters.Base);

}).call(this);
