// Generated by CoffeeScript 1.6.1
(function() {

  BH.Presenters.SitePresenter = (function() {

    function SitePresenter(model) {
      this.model = model;
    }

    SitePresenter.prototype.site = function() {
      var domain, match, out;
      match = this.model.get('url').match(/\/\/(.*?)\//);
      domain = match === null ? null : match[1];
      if (domain) {
        domain = domain.replace('www.', '');
      }
      out = this.model.toJSON();
      out.domain = domain;
      return out;
    };

    return SitePresenter;

  })();

}).call(this);
