// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Presenters.WeekHistoryPresenter = (function(_super) {

    __extends(WeekHistoryPresenter, _super);

    function WeekHistoryPresenter(days) {
      this.days = days;
    }

    WeekHistoryPresenter.prototype.history = function() {
      var day, dayVisitPercentage, out,
        _this = this;
      dayVisitPercentage = function(day) {
        var largest;
        largest = Math.max.apply(Math, _this.dayVisits()) || 0;
        if (largest === 0) {
          return 0;
        }
        return day.visits.length / largest * 100;
      };
      return {
        total: this.totalVisits(),
        days: (function() {
          var _i, _len, _ref, _results;
          _ref = this.days;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            day = _ref[_i];
            _results.push(out = {
              count: day.visits.length,
              day: day.name,
              percentage: "" + (dayVisitPercentage(day)) + "%"
            });
          }
          return _results;
        }).call(this)
      };
    };

    WeekHistoryPresenter.prototype.dayVisits = function() {
      var day, _i, _len, _ref, _results;
      _ref = this.days;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        day = _ref[_i];
        _results.push(day.visits.length);
      }
      return _results;
    };

    WeekHistoryPresenter.prototype.totalVisits = function() {
      if (this.dayVisits().length === 0) {
        return 0;
      }
      return this.dayVisits().reduce(function(sum, num) {
        return sum + num;
      });
    };

    return WeekHistoryPresenter;

  })(BH.Presenters.Base);

}).call(this);
