// Extension for Chrome Browser - Magic Actions for YouTube™ - CHROMEACTIONS.COM - Copyright 2014 Vlad and Serge Strukoff - All Rights Reserved
(function(){function u(){"complete"==document.readyState?(w(),x(),y()):setTimeout(u,250)}function z(){var a=document.getElementById("j782677h"),b;a||(a=document.createElement("style"),a.setAttribute("type","text/css"),a.id="j782677h",document.documentElement.appendChild(a),b=a.sheet,b.disabled=e.a0&&e.a4&&e.ui?!1:!0,b.insertRule("body *{color:#909090!important}",0),b.insertRule("div,div > span{background-color:#1E1E1E!important;border-color:#333!important}",1),b.insertRule("a{color:#555!important}",
2),b.insertRule("a:hover,a > span{color:#6783ab!important}",3),b.insertRule("[aria-label='Posting options']{background:url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAAS0lEQVQ4y2NgGAWjYIiD////t//HDqZRYijj////l6AZuPH////MlLqW7f///3uhBp74//8/F7WCgf/////b/v//Lz2aKEbBKMADAMppT6HBpHJKAAAAAElFTkSuQmCC') center no-repeat!important}",4),b.insertRule("span[role=listitem] *{color:#fff!important;background-color:transparent!important}",5),b.insertRule("[role=checkbox],[role=tooltip] div,.Mga,.Jea{border:0!important}",
6),b.insertRule("[role=checkbox] > div{border:1px solid #333!important}",7),b.insertRule("[aria-checked=true] > div{box-shadow:inset 0 0 0 3px #101010!important;background:#4e4e4e!important}",8),b.insertRule("span.r0,.g-h-f-p-Ov{background:none!important}",9),b.insertRule(".MJa,.LJa{-webkit-filter:invert(100%)!important}",10));a.sheet.disabled=e.a0&&e.a4&&e.ui?!1:!0}function y(){document.documentElement.proc||(document.documentElement.proc=1,document.documentElement.addEventListener("click",function(a){setTimeout(w,
1E3);setTimeout(x,1E3);setTimeout(y,1E3)},!1))}function x(){if(e.c0&&(e.c2||e.c3))for(var a=document.querySelectorAll("a[oid]"),b=0,c=a.length;b<c;b++)a[b].proc||(a[b].proc=!0,a[b].addEventListener("mouseover",D,!1))}function D(a){2>this.proc&&(this.proc=2,E(this));a.stopPropagation()}function r(a,b){n("GET","//gdata.youtube.com/feeds/api/users/"+a+"?v=2&alt=json",null,"responseText",0,function(a){if(a){try{a=JSON.parse(a).entry}catch(f){return}var g,h,d=a.gd$feedLink;g=a.yt$location&&a.yt$location.$t?
a.yt$location.$t:"Earth";a.yt$statistics&&a.yt$statistics.subscriberCount&&(subscribers=a.yt$statistics.subscriberCount);a=0;for(var v=d.length;a<v;++a)d[a].rel.match(/uploads/)&&(h=d[a].countHint);if(e.c3){d=document.createElement("a");a=g;var v=g.length,A={AF:"Afghanistan",AX:"\u00c5land Islands",AL:"Albania",DZ:"Algeria",AS:"American Samoa",AD:"Andorra",AO:"Angola",AI:"Anguilla",AG:"Antigua and Barbuda",AR:"Argentina",AM:"Armenia",AW:"Aruba",AU:"Australia",AT:"Austria",AZ:"Azerbaijan",BS:"Bahamas",
BH:"Bahrain",BD:"Bangladesh",BB:"Barbados",BY:"Belarus",BE:"Belgium",BZ:"Belize",BJ:"Benin",BM:"Bermuda",BT:"Bhutan",BO:"Bolivia",BQ:"Bonaire",BA:"Bosnia and Herzegovina",BW:"Botswana",BR:"Brazil",IO:"British Indian Ocean Territory",BN:"Brunei Darussalam",BG:"Bulgaria",BF:"Burkina Faso",BI:"Burundi",KH:"Cambodia",CM:"Cameroon",CA:"Canada",CV:"Cape Verde",KY:"Cayman Islands",CF:"Central African Republic",TD:"Chad",CL:"Chile",ZH:"China",CN:"China",CX:"Christmas Island",CC:"Cocos Islands",CO:"Colombia",
KM:"Comoros",CG:"Congo",CD:"Congo",CK:"Cook Islands",CR:"Costa Rica",CI:"C\u00f4te d'Ivoire",HR:"Croatia",CU:"Cuba",CW:"Cura\u00e7ao",CY:"Cyprus",CZ:"Czech Republic",DK:"Denmark",DJ:"Djibouti",DM:"Dominica",DO:"Dominican Republic",EC:"Ecuador",EG:"Egypt",SV:"El Salvador",GQ:"Equatorial Guinea",ER:"Eritrea",EE:"Estonia",ET:"Ethiopia",FK:"Falkland Islands (Malvinas)",FO:"Faroe Islands",FJ:"Fiji",FI:"Finland",FR:"France",GF:"French Guiana",PF:"French Polynesia",TF:"French Southern Territories",GA:"Gabon",
GM:"Gambia",GE:"Georgia",DE:"Germany",GH:"Ghana",GI:"Gibraltar",GR:"Greece",GL:"Greenland",GD:"Grenada",GP:"Guadeloupe",GU:"Guam",GT:"Guatemala",GG:"Guernsey",GN:"Guinea",GW:"Guinea-Bissau",GY:"Guyana",HT:"Haiti",VA:"Vatican",HN:"Honduras",HK:"Hong Kong",HU:"Hungary",IS:"Iceland",IN:"India",ID:"Indonesia",IR:"Iran",IQ:"Iraq",IE:"Ireland",IM:"Isle of Man",IL:"Israel",IT:"Italy",JM:"Jamaica",JP:"Japan",JE:"Jersey",JO:"Jordan",KZ:"Kazakhstan",KE:"Kenya",KI:"Kiribati",KP:"North Korea",KR:"South Korea",
KW:"Kuwait",KG:"Kyrgyzstan",LA:"Laos",LV:"Latvia",LB:"Lebanon",LS:"Lesotho",LR:"Liberia",LY:"Libya",LI:"Liechtenstein",LT:"Lithuania",LU:"Luxembourg",MO:"Macao",MK:"Macedonia",MG:"Madagascar",MW:"Malawi",MY:"Malaysia",MV:"Maldives",ML:"Mali",MT:"Malta",MH:"Marshall Islands",MQ:"Martinique",MR:"Mauritania",MU:"Mauritius",YT:"Mayotte",MX:"Mexico",FM:"Micronesia",MD:"Moldova",MC:"Monaco",MN:"Mongolia",ME:"Montenegro",MS:"Montserrat",MA:"Morocco",MZ:"Mozambique",MM:"Myanmar",NA:"Namibia",NR:"Nauru",NP:"Nepal",
NL:"Netherlands",NC:"New Caledonia",NZ:"New Zealand",NI:"Nicaragua",NE:"Niger",NG:"Nigeria",NU:"Niue",NF:"Norfolk Island",MP:"Northern Mariana Islands",NO:"Norway",OM:"Oman",PK:"Pakistan",PW:"Palau",PS:"Palestinian Territory",PA:"Panama",PG:"Papua New Guinea",PY:"Paraguay",PE:"Peru",PH:"Philippines",PN:"Pitcairn",PL:"Poland",PT:"Portugal",PR:"Puerto Rico",QA:"Qatar",RE:"R\u00e9union",RO:"Romania",RU:"Russia",RW:"Rwanda",BL:"Saint Barth\u00e9lemy",SH:"Saint Helena",KN:"Saint Kitts and Nevis",LC:"Saint Lucia",
MF:"Saint Martin",PM:"Saint Pierre and Miquelon",VC:"Saint Vincent and the Grenadines",WS:"Samoa",SM:"San Marino",ST:"Sao Tome and Principe",SA:"Saudi Arabia",SN:"Senegal",RS:"Serbia",SC:"Seychelles",SL:"Sierra Leone",SG:"Singapore",SX:"Sint Maarten",SK:"Slovakia",SI:"Slovenia",SB:"Solomon Islands",SO:"Somalia",ZA:"South Africa",GS:"South Georgia and the South Sandwich Islands",SS:"South Sudan",ES:"Spain",LK:"Sri Lanka",SD:"Sudan",SR:"Suriname",SZ:"Swaziland",SE:"Sweden",CH:"Switzerland",SY:"Syria",
TW:"Taiwan",TJ:"Tajikistan",TZ:"Tanzania",TH:"Thailand",TL:"Timor-Leste",TG:"Togo",TK:"Tokelau",TO:"Tonga",TT:"Trinidad and Tobago",TN:"Tunisia",TR:"Turkey",TM:"Turkmenistan",TC:"Turks and Caicos Islands",TV:"Tuvalu",UG:"Uganda",UA:"Ukraine",AE:"United Arab Emirates",GB:"United Kingdom",US:"United States",UM:"U.S. Minor Outlying Islands",UY:"Uruguay",UZ:"Uzbekistan",VU:"Vanuatu",VE:"Venezuela",VN:"Viet Nam",VG:"Virgin Islands, British",VI:"Virgin Islands, U.S.",WF:"Wallis and Futuna",EH:"Western Sahara",
YE:"Yemen",ZM:"Zambia",ZW:"Zimbabwe",EA:"Earth"};2<v&&(a="Earth"==g?"EA":g.slice(v-2));d.href="http://www.fastsatfinder.com/country-flags-geo-location.html?cc="+a;d.target="_blank";A[a]&&(d.title=A[a]);d.className="maFlag";d.style.setProperty("width","16px",k);d.style.setProperty("height","11px",k);d.style.setProperty("display","inline-block",k);d.style.setProperty("margin-left","5px",k);d.style.setProperty("cursor","pointer",k);d.style.setProperty("background","url("+F+"i/f/"+a+".png) no-repeat",
k);g=b.parentElement;"h3"===g.localName&&(g=g.parentElement);g.appendChild(d)}e.c2&&(g=subscribers,d=b.parentElement,a=document.createElement("span"),a.style.setProperty("color","#2793e6",k),a.style.setProperty("margin-left","7px",k),a.style.setProperty("cursor","default",k),a.title="This user uploaded "+h+" videos and have "+g+" subscribers",a.innerHTML=h+" / "+g,"h3"===d.localName&&(d=d.parentElement),d.appendChild(a))}})}function B(a){var b=a.getAttribute("oid"),c,f;b&&(0==b.indexOf("UC")?r(oid.slice(2),
a):n("GET","//www.youtube.com/profile_redirector/"+b,null,"response",1,function(b){b&&b.documentElement&&(f=b.documentElement.querySelector("meta[itemprop=channelId]"))&&(c=f.getAttribute("content"))&&r(c.slice(2),a)}))}function E(a){for(var b=a.parentElement,c=0;3>c;c++)b=b.parentElement;if(b=b.querySelector("span")){var f=b.getAttribute("data-update-id");G();f&&m?n("GET","//gdata.youtube.com/feeds/api/videos/"+m+"/comments/"+f+"?v=2&alt=json",null,"responseText",0,function(b){if(b){try{b=JSON.parse(b).entry}catch(c){return}(f=
b.author&&b.author[0]&&b.author[0].yt$userId&&b.author[0].yt$userId.$t)&&"__NO_YOUTUBE_ACCOUNT__"!=f&&r(f,a)}}):B(a)}else B(a)}function w(){if(e.c0&&e.c1)for(var a=document.images,b,c=0,f=a.length;c<f;c++)b=a[c],b.prc||(b.prc=1,b.addEventListener("mouseover",H,!1),b.addEventListener("mouseout",I,!1))}function H(a){l&&(l=clearTimeout(l));var b=this,c=J(b),f=c[0],g=c[1],e=this.offsetWidth,d=this.offsetHeight;b.removeAttribute("title");l=setTimeout(function(){var a,c,l,p,m=b.src.replace(/s\d+-c-k/,"s256-c-k");
300>f?(a=f+e+20,l="magic-tip-left"):(a=f-256-20,l="magic-tip-right");c=g-parseInt((256-d)/2)-5;p=128;0>c&&(p+=c,c=0);p+="px";var m="url("+m+") center center/100% auto no-repeat",q,s;if(h)q=h.firstElementChild,s=h.lastElementChild;else{h=document.createElement("div");q=document.createElement("div");s=document.createElement("iframe");h.className="magic-tip";for(var r=s,n=["scrolling","no","frameborder",0],t=0,u=n.length;t<u;t+=2)r.setAttribute(n[t],n[t+1]);h.appendChild(q);h.appendChild(s);document.body.appendChild(h)}C(h,
["top",c+"px","left",a+"px","height","256px"],1);C(s,["width","256px","height","256px","background",m,"display","block"],1);l?(q.style.setProperty("display",""),q.className=l,p&&q.style.setProperty("top",p,k)):q.style.setProperty("display","none",k);h.style.setProperty("display","block",k)},500);a.stopPropagation()}function I(a){l&&(l=clearTimeout(l));h&&h.style.setProperty("display","none",k)}function G(){if(m)return m;var a=document.URL,b=document.URL.indexOf("substream_id="),c;-1<b&&(b+=13,c=a.indexOf("&",
b),-1<c&&(m=a.slice(b,c)));return m}function n(a,b,c,f,g,e){var d=new XMLHttpRequest;d.onload=function(a){200==this.status?e(this[f]):e()};d.onerror=e;d.onabort=e;d.open(a,b,!0);g&&(d.responseType="document");d.send(c)}function C(a,b,c){if(a){var f=0,e=b.length;for(c=c?k:null;f<e;f+=2)a.style.setProperty(b[f],b[f+1],c)}}function J(a){if(!a||void 0==a)return[0,0];var b=0,c=0;if(a.offsetParent){do b+=a.offsetLeft,c+=a.offsetTop;while(a=a.offsetParent)}return[b,c]}var e,F=chrome.runtime.getURL(""),m,
h,l,k="important";chrome.runtime.sendMessage('{"id":0}',function(a){a&&a.ver&&(e=a,z(),a=document.getElementById("s773549"),a||(a=document.createElement("style"),a.setAttribute("type","text/css"),a.id="s773549",document.documentElement.appendChild(a),a=a.sheet,a.insertRule(".magic-tip{z-index:2147483648;position:absolute;background-color:#333;border:7px solid #333;border-radius:7px}",0),a.insertRule(".magic-tip-right{position:absolute;top:50%;right:-17px;margin-top:-10px;width:0;height:0;border-style:solid;border-width:10px 0 10px 10px;border-color:transparent #333!important}",
1),a.insertRule(".magic-tip-left{position:absolute;top:50%;left:-17px;margin-top:-10px;width:0;height:0;border-style:solid;border-width:10px 10px 10px 0;border-color:transparent #333!important}",2)),u())});window.addEventListener("message",function(a){var b=0;try{b=JSON.parse(a.data)}catch(c){return}680==b.id&&(e=b.opt,z())},!1)})();
