// Extension for Chrome Browser - Magic Actions for YouTube™ - CHROMEACTIONS.COM - Copyright 2014 Vlad and Serge Strukoff - All Rights Reserved
window.addEventListener("load",ccMenu,!1);
function ccMenu(){function u(){var a=this.id;l!=a&&(l&&(e(l).className="nav"),l=a,this.className="nav act",t(a))}function t(a){var c,b=e("box");if("menu0"==a)c=[3,"orange","report.png",0,7,0,"help1.png",1,3,"blue","options.png",2,3,"violet","plugins.png",3,3,"violet","history.png",4,3,"violet","extensions.png",5,3,"violet","security.png",6,0,"fb","facebook32.png",7,0,"yt","youtube32.png",8,0,"gp","gplus32.png",9,0,"rt","rate32.png",10];else if("menu1"==a){c=e("donate");if(!c.hasAttribute("init")){for(var d=
chrome.i18n.getMessage(a).split(";"),f=c.innerHTML,r=0,h;h=d[r];r++)f=f.replace("t"+(10+r),h);c.innerHTML=f;c.setAttribute("init",!0);v()}b.style.display="none";c.style.display="block";return}r=0;a=chrome.i18n.getMessage(a).split(";");for(var l=document.createDocumentFragment(),m,g,k,p,q,s,n=0;n<c.length;n+=4)p=n/4,m=c[n],k=c[n+1],q=c[n+2],2==m?(g=new Uint8Array(1),crypto.getRandomValues(g),g=g[0]%k.length,p="i"+(p+g),k=k[g],q="i/menu/"+q[g],s=a[c[n+3]+g]):(p="i"+p,q="i/menu/"+q,s=a[c[n+3]]),7>m?
(h=0,d=document.createElement("div"),f=document.createElement("div"),g=new Image,k="btn "+k,2<m&&(k+=" wide"),d.id=p,d.className=k,g.className="icn",f.className="txt0",g.dataset.url=g.src=q,f.textContent=s,d.appendChild(g),d.appendChild(f),l.appendChild(d)):(m=document.createElement("div"),k=document.createElement("div"),g=new Image,g.src=q,m.id=p,m.className="adt a"+h,g.className="icnm",k.className="txt1",k.textContent=s,m.appendChild(g),d.insertBefore(m,f),d.insertBefore(k,f),h++),r++;b.innerHTML=
"";b.appendChild(l);b.style.display="";e("donate").style.display=""}function w(a){var c=a.target.id?a.target:a.target.parentElement,b=c.id;"menu0"==l&&(b=parseInt(c.id.slice(1)),0==b?h("http://www.chromeactions.com/magic-actions-for-youtube-support.html"):1==b?h("http://www.chromeactions.com/magic-actions-for-youtube-help-and-tips.html"):2==b?chrome.runtime.sendMessage('{"id":7}'):3==b?h("chrome://plugins"):4==b?h("http://www.youtube.com/my_history"):5==b?h("chrome://extensions"):6==b?h("http://www.hotcleaner.com/clickclean-app.html"):
7==b?h("https://www.facebook.com/magicactions"):8==b?h("http://www.youtube.com/user/StrukoffBrothers/feed"):9==b?h("https://plus.google.com/110367533603365326399/posts"):10==b&&h("https://chrome.google.com/webstore/detail/magic-actions-for-youtube/abjcfabbhafbcdfjoecdgepllmpfceif/reviews"));a.stopPropagation()}function v(){var a=e("rng"),c=e("amnt"),b=e("paypal"),d=e("bitpay"),f=e("ppPrice");e_price2=e("bpPrice");b.setAttribute("action","https://www.paypal.com/cgi-bin/webscr");d.setAttribute("action",
"https://bitpay.com/checkout");e("ppItemName").value=e("bpItemDesc").value="Donation for Magic Actions App";e("ppBusiness").value="webmaster@mixesoft.com";e("bpData").value="QssHQDbRWfw8q4ZrIXbQo39IRne2n99dmkMZHZ5U30pSjGO7mKX1oewbiLiSkZZ/mGmWzLvaYuMrDax7AZNkZg/3mLE2npzjwC0mUH+rwp+cScWvicGSP0ZnXXiAsFjClAJtBZ5C3Y5NgMS3TM4AUP+5v7WRXGDnMsNdxjuPIYao/vi8ici0swhr4lXPpmZAehzTcDKd5jqiCm1cx0Fjd/orQchtC44wHDamnN/JVpLQrLuZahb8NP10wkQXo7sefDInqAmVgSjNpaOGjcpd2g==";c.textContent="$ "+a.value;a.addEventListener("change",
function(b){c.textContent="$ "+a.value;f.value=e_price2.value=a.value;b.stopPropagation()},!1);b.addEventListener("submit",function(){var a=f.value;return isNaN(a)||2>a||30<a?!1:!0},!1);d.addEventListener("submit",function(){var a=e_price2.value;return isNaN(a)||2>a||30<a?!1:!0},!1)}function h(a){chrome.tabs.create({url:a})}function e(a){return document.getElementById(a)}var l="menu1";(function(){var a=chrome.i18n.getMessage("menu").split(";"),c=document.createDocumentFragment(),b=e("menu"),d;b.id=
"menu";for(var f=0;f<a.length;f++)d=document.createElement("div"),d.className="nav",d.id="menu"+f,d.textContent=a[f],d.addEventListener("click",u,!1),c.appendChild(d);b.appendChild(c);e(l).className="nav act";t(l);e("box").addEventListener("click",w,!1);chrome.runtime.sendMessage('{"id":1,"ea":"menu"}')})()};
