// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Modals.ConnectionRequiredModal = (function(_super) {

    __extends(ConnectionRequiredModal, _super);

    function ConnectionRequiredModal() {
      return ConnectionRequiredModal.__super__.constructor.apply(this, arguments);
    }

    ConnectionRequiredModal.include(BH.Modules.I18n);

    ConnectionRequiredModal.prototype.className = 'connection_required_view';

    ConnectionRequiredModal.prototype.template = BH.Templates['connection_required'];

    ConnectionRequiredModal.prototype.events = {
      'click .okay': 'okayClicked'
    };

    ConnectionRequiredModal.prototype.initialize = function() {
      this.chromeAPI = chrome;
      this.tracker = this.options.tracker;
      return this.attachGeneralEvents();
    };

    ConnectionRequiredModal.prototype.render = function() {
      this.$el.html(this.renderTemplate(this.getI18nValues()));
      return this;
    };

    ConnectionRequiredModal.prototype.okayClicked = function(ev) {
      ev.preventDefault();
      return this.close();
    };

    ConnectionRequiredModal.prototype.getI18nValues = function() {
      return this.t(['prompt_okay_button', 'connection_required_title', 'connection_required_description']);
    };

    return ConnectionRequiredModal;

  })(BH.Modals.Base);

}).call(this);
