/*
 Copyright 2010 Google Inc.  All Rights Reserved.
 Your use of this software is subject to the Terms of Service located
 at https://chrome.google.com/extensions/intl/en/gallery_tos.html.
*/
var e;var l=function(a,b,c){return a.call.apply(a.bind,arguments)},n=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},p=function(a,b,c){p=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?l:n;return p.apply(null,arguments)},q=function(a,b){function c(){}
c.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(a,c,g){var h=Array.prototype.slice.call(arguments,2);return b.prototype[c].apply(a,h)}};Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return p.apply(null,c)}return p(this,a)};
Function.prototype.partial=function(a){var b=Array.prototype.slice.call(arguments);b.unshift(this,null);return p.apply(null,b)};Function.prototype.inherits=function(a){q(this,a)};Function.prototype.mixin=function(a){var b=this.prototype,c;for(c in a)b[c]=a[c]};var r=RegExp("https?://(?:.+\\.)?google\\.[a-z]{2,3}(?:\\.[a-z]{2})?(?:\\:[0-9]+)?/(?:advanced_)?search.*(([?&]q=)([^&]+))"),s=RegExp("https?://(?:.+\\.)?google\\.[a-z]{2,3}(?:\\.[a-z]{2})?(?:\\:[0-9]+)?/(?:webhp[^#]*)?(#((?:.+&)?q=)([^&]+)(.*)&fp=[^&]+)"),t=/&/g,u=/</g,v=/>/g,w=/\"/g;function x(a){return a?a.replace(t,"&amp;").replace(u,"&lt;").replace(v,"&gt;").replace(w,"&quot;"):""}function y(a){return r.test(a)||s.test(a)}function z(a){return y(a)&&/[?&#](qscrl|espv)=/.test(a)}
function A(a,b,c,d,f,g,h,m){return p.apply(null,arguments)}Array.prototype.peek=function(){return this[this.length-1]};function B(a,b,c){if("true"==window.localStorage.enableGen204Logging&&null!=a&&null!=b){b=["atyp=i","oi=findy","ct="+b];a.ei&&b.push("ei="+a.ei);a.ved&&b.push("ved="+a.ved);a=c||{};a.seq=(new Date).getTime();c=[];for(var d in a)c.push(d+":"+encodeURIComponent(a[d]));d="http://www.google.com/gen_204?"+b.join("&")+"&cad="+c.join(";");try{var f=new XMLHttpRequest;f.open("GET",d,!0);f.send()}catch(g){}}};var C="StopIteration"in this?this.StopIteration:Error("StopIteration"),D=function(){};D.prototype.next=function(){throw C;};D.prototype.__iterator__=function(){return this};var E=function(a,b){this.map_={};this.keys_=[];this.version_=this.count_=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){var f;if(a instanceof E)f=a.getKeys(),d=a.getValues();else{var c=[],g=0;for(f in a)c[g++]=f;f=c;c=[];g=0;for(d in a)c[g++]=a[d];d=c}for(c=0;c<f.length;c++)this.set(f[c],d[c])}};e=E.prototype;e.getCount=function(){return this.count_};
e.getValues=function(){F(this);for(var a=[],b=0;b<this.keys_.length;b++)a.push(this.map_[this.keys_[b]]);return a};e.getKeys=function(){F(this);return this.keys_.concat()};e.containsKey=function(a){return G(this.map_,a)};e.containsValue=function(a){for(var b=0;b<this.keys_.length;b++){var c=this.keys_[b];if(G(this.map_,c)&&this.map_[c]==a)return!0}return!1};
e.equals=function(a,b){if(this===a)return!0;if(this.count_!=a.getCount())return!1;var c=b||H;F(this);for(var d,f=0;d=this.keys_[f];f++)if(!c(this.get(d),a.get(d)))return!1;return!0};var H=function(a,b){return a===b};E.prototype.isEmpty=function(){return 0==this.count_};E.prototype.clear=function(){this.map_={};this.version_=this.count_=this.keys_.length=0};
E.prototype.remove=function(a){return G(this.map_,a)?(delete this.map_[a],this.count_--,this.version_++,this.keys_.length>2*this.count_&&F(this),!0):!1};var F=function(a){if(a.count_!=a.keys_.length){for(var b=0,c=0;b<a.keys_.length;){var d=a.keys_[b];G(a.map_,d)&&(a.keys_[c++]=d);b++}a.keys_.length=c}if(a.count_!=a.keys_.length){for(var f={},c=b=0;b<a.keys_.length;)d=a.keys_[b],G(f,d)||(a.keys_[c++]=d,f[d]=1),b++;a.keys_.length=c}};e=E.prototype;
e.get=function(a,b){return G(this.map_,a)?this.map_[a]:b};e.set=function(a,b){G(this.map_,a)||(this.count_++,this.keys_.push(a),this.version_++);this.map_[a]=b};e.forEach=function(a,b){for(var c=this.getKeys(),d=0;d<c.length;d++){var f=c[d],g=this.get(f);a.call(b,g,f,this)}};e.clone=function(){return new E(this)};e.transpose=function(){for(var a=new E,b=0;b<this.keys_.length;b++){var c=this.keys_[b];a.set(this.map_[c],c)}return a};
e.toObject=function(){F(this);for(var a={},b=0;b<this.keys_.length;b++){var c=this.keys_[b];a[c]=this.map_[c]}return a};e.getKeyIterator=function(){return this.__iterator__(!0)};e.getValueIterator=function(){return this.__iterator__(!1)};e.__iterator__=function(a){F(this);var b=0,c=this.keys_,d=this.map_,f=this.version_,g=this,h=new D;h.next=function(){for(;;){if(f!=g.version_)throw Error("The map has changed since the iterator was created");if(b>=c.length)throw C;var h=c[b++];return a?h:d[h]}};return h};
var G=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var J=function(a,b){this.maxCount_=a||null;this.cache_=!!b;this.map_=new E;this.head_=new I("",void 0);this.head_.next=this.head_.prev=this.head_},L=function(a,b){var c=a.map_.get(b);c&&a.cache_&&(c.remove(),K(a,c));return c};e=J.prototype;e.get=function(a,b){var c=L(this,a);return c?c.value:b};e.peekValue=function(a,b){var c=this.map_.get(a);return c?c.value:b};e.set=function(a,b){var c=L(this,a);c?c.value=b:(c=new I(a,b),this.map_.set(a,c),K(this,c))};e.peek=function(){return this.head_.next.value};
e.peekLast=function(){return this.head_.prev.value};e.shift=function(){return M(this,this.head_.next)};e.pop=function(){return M(this,this.head_.prev)};e.remove=function(a){return(a=this.map_.get(a))?(this.removeNode(a),!0):!1};e.removeNode=function(a){a.remove();this.map_.remove(a.key)};e.getCount=function(){return this.map_.getCount()};e.isEmpty=function(){return this.map_.isEmpty()};e.setMaxCount=function(a){this.maxCount_=a||null;null!=this.maxCount_&&N(this,this.maxCount_)};
e.getKeys=function(){return this.map(function(a,b){return b})};e.getValues=function(){return this.map(function(a){return a})};e.contains=function(a){return this.some(function(b){return b==a})};e.containsKey=function(a){return this.map_.containsKey(a)};e.clear=function(){N(this,0)};e.forEach=function(a,b){for(var c=this.head_.next;c!=this.head_;c=c.next)a.call(b,c.value,c.key,this)};e.map=function(a,b){for(var c=[],d=this.head_.next;d!=this.head_;d=d.next)c.push(a.call(b,d.value,d.key,this));return c};
e.some=function(a,b){for(var c=this.head_.next;c!=this.head_;c=c.next)if(a.call(b,c.value,c.key,this))return!0;return!1};e.every=function(a,b){for(var c=this.head_.next;c!=this.head_;c=c.next)if(!a.call(b,c.value,c.key,this))return!1;return!0};
var K=function(a,b){a.cache_?(b.next=a.head_.next,b.prev=a.head_,a.head_.next=b,b.next.prev=b):(b.prev=a.head_.prev,b.next=a.head_,a.head_.prev=b,b.prev.next=b);null!=a.maxCount_&&N(a,a.maxCount_)},N=function(a,b){for(var c=a.map_.getCount();c>b;c--)a.removeNode(a.cache_?a.head_.prev:a.head_.next)},M=function(a,b){a.head_!=b&&a.removeNode(b);return b.value},I=function(a,b){this.key=a;this.value=b};I.prototype.remove=function(){this.prev.next=this.next;this.next.prev=this.prev;delete this.prev;delete this.next};var O=function(){this.map_=new J(100,!0)};O.prototype.hasResultsFor=function(a){return null!=this.map_.get(a)};var Q=function(a,b){var c=P.map_.get(a);if(!c||null==b)return null;for(var d=null,f=0;f<c.length&&(d=c[f],d.query!=b&&d.ei!=b);f++);return d};O.prototype.getNumResultsForUrl=function(a){return this.map_.get(a,[]).length};chrome.extension.getVersion=function(){if(!chrome.extension.version_){var a=new XMLHttpRequest;a.open("GET",chrome.extension.getURL("manifest.json"),!1);a.onreadystatechange=function(){if(4==this.readyState){var a=JSON.parse(this.responseText);chrome.extension.version_=a.version}};a.send()}return chrome.extension.version_};var R=function(){this.lastInterval_=null};R.prototype.setImage_=function(a){chrome.pageAction.setIcon({tabId:a,path:"images/page-action-animated_"+this.step_+".png"});this.step_=(this.step_+1)%8};R.prototype.stop=function(){this.lastInterval_&&window.clearInterval(this.lastInterval_)};var T={"search-results":S,"landing-page":aa,"found-tidbits":ba,"log-event":ca,"minimized-state":da,"open-link":ea,"get-more-tidbits":fa},P=new O,U=new R;
function S(a,b){for(var c=b.results,d=P,f=0;f<c.length;f++){var g=c[f];if(g.href)t:{var h=d,m=h.map_.get(g.href);if(m){for(h=0;h<m.length;h++){var k=m[h];if(k.query==g.query||k.ei==g.ei){k.ei=g.ei;k.fromVisualSnippet=g.fromVisualSnippet;k.vsClickedTidbitIndex=g.vsClickedTidbitIndex;k.query=g.query;k.searchUrl=g.searchUrl;k.tidbits=g.tidbits;k.htmlTidbits=g.htmlTidbits;k.hasEbmTidbits=g.hasEbmTidbits;m.splice(h,1);m.push(k);break t}}m.push(g)}else h.map_.set(g.href,[g])}}}
function aa(a,b){var c=a.sender.tab.id,d=Q(b.href,b.subkey);if(d&&0<d.tidbits.length)d.debug=d.debug||{},d.debug.version=chrome.extension.getVersion(),d.hasEbmTidbits?V(c,{title:"running",active:!0}):V(c,{active:!0}),chrome.tabs.executeScript(c,{code:"window.qs_result = "+JSON.stringify(d)},function(){W(c,"in-document_content_script.js",function(){d.seen=!0})});else{var f;d?f=chrome.i18n.getMessage("qs_info_non_annotated_result",x(d.query)):y(b.href)&&z(b.href)&&(f=chrome.i18n.getMessage("qs_info_on_search"));
f&&(V(c,{active:!1}),X(c,f))}}function ba(a,b){var c=a.sender.tab.id;b.foundTidbits?(V(c,{active:!0}),B(b.result,b.result.hasEbmTidbits?"found-tidbits":"found-nft-tidbits",b.logParams)):(V(c,{active:!1}),X(c,chrome.i18n.getMessage("qs_info_no_tidbits_found",x(b.result.query))),B(b.result,"no-tidbits-found"))}function ca(a,b){var c=b.params||{};c.ver=chrome.extension.getVersion();B(b.result,b.action,c)}function da(a,b){b.result&&(Q(b.result.href,b.result.query).minimized=b.minimized)}
function ea(a,b){Y(b.url)}function Y(a){chrome.tabs.getAllInWindow(null,function(b){for(var c=0;c<b.length;c++)if(b[c].url==a){chrome.tabs.update(b[c].id,{selected:!0});return}chrome.tabs.create({url:a,selected:!0})})}function fa(a,b){try{var c=new XMLHttpRequest;c.open("GET",b.url,!0);c.onreadystatechange=function(){4==this.readyState&&a.postMessage({content:this.responseText})};c.send()}catch(d){a.postMessage({content:""})}}
function V(a,b){if("running"==b.title){var c=U;c.stop();c.step_=1;c.lastInterval_=window.setInterval(A(c.setImage_,c,a),300)}else U.stop(),chrome.pageAction.setIcon({tabId:a,path:"images/page-action-"+((b.active?"active":"inactive")+".png")});c=chrome.i18n.getMessage("qs_page_action_"+(b.title||(b.active?"active":"inactive")));chrome.pageAction.setTitle({tabId:a,title:c});chrome.pageAction.show(a)}
function W(a,b,c){var d=chrome.i18n.getMessage("direction");Z(a,"jquery_do_not_compile.js",function(){chrome.tabs.insertCSS(a,{file:"in-document_"+d+"_css.css"},function(){Z(a,b,c)})})}function Z(a,b,c){chrome.tabs.executeScript(a,{file:b},function(){c()})}function X(a,b){W(a,"in-document-message_content_script.js",function(){chrome.tabs.sendRequest(a,{text:b})})}chrome.extension.onConnect.addListener(function(a){a.onMessage.addListener(function(b){if(T[a.name])T[a.name](a,b)})});
chrome.pageAction.onClicked.addListener(function(a){var b=chrome.extension.getURL("about.html");0!=a.url.indexOf("chrome")&&-1==a.url.indexOf("chrome.google.com/extensions")||a.url==b?chrome.tabs.sendRequest(a.id,{toggle:!0}):Y(b)});
chrome.webRequest.onBeforeRequest.addListener(function(a){a=a.url;return y(a)&&!z(a)?{redirectUrl:a+"&qscrl=1"}:{}},{urls:"*://www.google.com/search* *://www.google.ae/search* *://www.google.at/search* *://www.google.au/search* *://www.google.be/search* *://www.google.bg/search* *://www.google.ca/search* *://www.google.ch/search* *://www.google.cl/search* *://www.google.cn/search* *://www.google.co.id/search* *://www.google.co.il/search* *://www.google.co.in/search* *://www.google.co.kr/search* *://www.google.co.nz/search* *://www.google.co.jp/search* *://www.google.co.th/search* *://www.google.co.uk/search* *://www.google.co.ve/search* *://www.google.co.za/search* *://www.google.com.ar/search* *://www.google.com.au/search* *://www.google.com.br/search* *://www.google.com.co/search* *://www.google.com.eg/search* *://www.google.com.hk/search* *://www.google.com.mx/search* *://www.google.com.my/search* *://www.google.com.ng/search* *://www.google.com.pe/search* *://www.google.com.ph/search* *://www.google.com.pk/search* *://www.google.com.sa/search* *://www.google.com.sg/search* *://www.google.com.tr/search* *://www.google.com.tw/search* *://www.google.com.ua/search* *://www.google.com.vn/search* *://www.google.cz/search* *://www.google.de/search* *://www.google.dk/search* *://www.google.ee/search* *://www.google.es/search* *://www.google.fi/search* *://www.google.fr/search* *://www.google.gr/search* *://www.google.hr/search* *://www.google.hu/search* *://www.google.ie/search* *://www.google.it/search* *://www.google.lt/search* *://www.google.lv/search* *://www.google.nl/search* *://www.google.no/search* *://www.google.pl/search* *://www.google.pt/search* *://www.google.ro/search* *://www.google.rs/search* *://www.google.ru/search* *://www.google.se/search* *://www.google.si/search* *://www.google.sk/search*".split(" "),types:["main_frame"]},
["blocking"]);
