Function.prototype.bind=function(){var a=this,b=Array.prototype.slice.call(arguments),c=b.shift();return function(){return a.apply(c,b.concat(Array.prototype.slice.call(arguments)))}};function getMessage(a,b){try{var c=chrome.i18n.getMessage(a,b);if(c)return c}catch(d){}}
var isFilling=!1,bookmarkBarId,otherBookmarkId,rootBookmarkId,background=chrome.extension.getBackgroundPage(),inNotepadBox=!1,popupNode,bmNode,wpData={},columnInBookmark=localStorage.columnInBookmark=="true",selectedAlbum,multiNotes,lastSelectedNote=0,typingTimer,doneTypingInterval=5E3,MAJOR_VERSION=1.6;
function renderSelectedNote(a){a||(a=localStorage.lastNoteIndex);if(isNaN(a)||a<0||a>3)a=0;var b=[chrome.i18n.getMessage("defaultNotepadText"),"Yup, you got another notepad in blue.","A notepad in green","And a notepad in pink!"],c=[],d=localStorage.multiNotes;if(d)try{c=JSON.parse(d)}catch(e){console.error(e)}if(c[a])if(c=c[a].text){if(c==""||c=="__NULL__")c=" "}else c=b[a];else c=getMessage("defaultNotepadText");lastSelectedNote=a;localStorage.lastNoteIndex=a;$("#notepad").val(c).css("background-color",
["ffff60","ccffff","ccffcc","ffccee"][a])}
function updateNote(){var a=$("#notepad").val();console.log("Update note",lastSelectedNote,a);if(!a||a=="")a="__NULL__";var b=[];if(localStorage.multiNotes)try{b=JSON.parse(localStorage.multiNotes)}catch(c){console.error("updateNote",c)}b[lastSelectedNote]||(b[lastSelectedNote]={});if(b[lastSelectedNote].text!=a){b[lastSelectedNote].text=a;a=JSON.stringify(b);localStorage.multiNotes=a;try{var d=chrome.extension.getViews({type:"tab"});d.length>0&&$.each(d,function(a,b){b!=window&&(console.log("refreshNote"),
b.renderSelectedNote(lastSelectedNote))})}catch(e){console.error("updateAllViews",e)}if(localStorage.syncNotepad=="true")try{background.onNoteChanged()}catch(f){console.error("background error:onNoteChanged")}}$("#notepad").blur();inNotepadBox=!1}
function init(){background=chrome.extension.getBackgroundPage();if(localStorage.updateread<MAJOR_VERSION){var a=$("#updateNotifier");a.text("Incredible StartPage updated to version "+MAJOR_VERSION+".0, click here to see new features!");a.show();a.click(function(){localStorage.updateread=MAJOR_VERSION;chrome.tabs.create({url:"http://blog.visibotech.com/search/label/IncredibleStartpage"});$("#updateNotifier").hide()})}resize();localStorage.themeColor&&changeBackgroundColor(parseInt(localStorage.themeColor));
var a=chrome.i18n.getMessage("@@ui_locale"),b={ca:1,cs:1,da:1,de:1,es:1,es_419:1,et:1,fi:1,fil:1,fr:1,hr:1,hu:1,it:1,lt:1,lv:1,nb:1,pl:1,pt:1,pt_BR:1,pt_PT:1,ro:1,sk:1,sl:1,sv:1,tr:1,vi:1};a in b&&($("#toggleOptionsBtn").css("font","16px Tahoma, Arial, sans-serif"),$("#advancedOptionsBtn").css("font","16px Tahoma, Arial, sans-serif"),$("#optionsCloseBtn").css("font","16px Tahoma, Arial, sans-serif"),$(".photoTheme").css("font","18px Tahoma, Arial, sans-serif"),$("#notepad").css("font","18px Tahoma, Arial, sans-serif"),
$("#share").css("font","18px Tahoma, Arial, sans-serif"));for(var c=["recentlyClosedTitle","bookmarkBrowserTitle","clearClosedText","backToParentText","toggleOptionsBtn","advancedOptionsBtn","bookmarkBarHelpContent","bookmarkBarHelpDismiss","bookmarkBrowserPin","bookmarkBrowserTop","bookmarkControlsHelpMsg","bookmarkControlsHelpDismiss","backgroundColorOptionTitle","backgroundColorSelectionTips","backgroundColorCustomTips","fontColorOptionTitle","fontColorSelectionTips","wallpaperOptionTitle","wallpaperThemeSelectionTips",
"wallpaperThemeCustomTips","message","closeBtn","saveBtn","noteUpdatedAtOtherPlacesText","uninstallApp","useLocalLabel"],d=0;d<c.length;++d)getMessage(c[d])&&$("#"+c[d]).text(getMessage(c[d]));localStorage.showTopSites=="false"&&($("#topSelector").hide(),localStorage["last.tab"]=="tops"&&delete localStorage["last.tab"]);if(!localStorage.hasNewPermission){console.log("check permission again");try{chrome.permissions.contains({permissions:["topSites"],origins:["chrome://favicon/"]},function(a){localStorage.hasNewPermission=
a})}catch(e){localStorage.hasNewPermission=!1}}getAppList();renderRecentlyClosed();$("#notepad").keyup(function(){clearTimeout(typingTimer);typingTimer=setTimeout(updateNote,doneTypingInterval)});$("#notepad").bind("paste cut",function(){clearTimeout(typingTimer);typingTimer=setTimeout(updateNote,doneTypingInterval)});$("#notepad").focus(function(){inNotepadBox=!0});$("#notepad").blur(function(){inNotepadBox=!1});$("#bookmarkSelector").click(function(){toggleView("bm")});$("#appSelector").click(function(){toggleView("apps")});
$("#topSelector").click(function(){checkTopsites()});$("#backgroundColorSelection .colorbutton").click(function(){changeBackgroundColor(parseInt($(this).attr("bg")))});$("#backgroundColorCustom input[type=button]").click(function(){customBackgroundColor()});$("#fontColorSelection .colorbutton").click(function(){changeFontColor(parseInt($(this).attr("fc")))});$("#wallpaperThemeSelection .photoTheme").click(function(){var a={clouds:1,sunset:1,nature:0,"Star Trails":0},b=$(this).attr("album");b&&showAlbum(b,
a[b],this)});$("#wallpaperThemeCustom input[type=button]").click(function(){saveWallpaper("gradient")});$("#optionsCloseBtn").click(function(){toggleOptionsBox()});$("#pencilHoverCatcher").click(function(){chrome.tabs.create({url:"/v162/options.html"})}).hover(function(){$("#pencil").css("background","url(/img/pencil_hover.png)")},function(){$("#pencil").css("background","url(/img/pencil.png)")});$("#toggleOptionsBtn").click(function(){toggleOptionsBox()});$("#advancedOptionsBtn").click(function(){chrome.tabs.create({url:"/v162/options.html"})});
$("#customWallpaperURL").click(function(){$("#useURL").attr("checked",!0)});$("#nextPhotos").click(function(){getPhotos(1)});$("#prevPhotos").click(function(){getPhotos(-1)});$("#closeBtn").click(function(){undo()});$("#saveBtn").click(function(){saveWallpaper("custom")});$(".multinote").click(function(){updateNoteBeforeTimeout();renderSelectedNote($(this).attr("index"))});$("#shareToMail").click(function(){var a=$("#notepad").val()+"\n\n---\n\nReminder from Incredible StartPage for Chrome\n\n",b=
"https://mail.google.com/mail/";localStorage.shareNotepadSetting&&localStorage.shareNotepadSetting=="googleApps"&&localStorage.googleAppsDomain&&(b="https://mail.google.com/a/"+localStorage.googleAppsDomain+"/");a=b+"?view=cm&tf=0&to=&su="+encodeURIComponent("Notes")+"&body="+encodeURIComponent(a);chrome.tabs.create({url:a})});$("#shareToCalendar").click(function(){var a=$("#notepad").val(),b="https://www.google.com/calendar/";b+=localStorage.shareNotepadSetting&&localStorage.shareNotepadSetting==
"googleApps"&&localStorage.googleAppsDomain?"a/"+localStorage.googleAppsDomain+"/":"b/0/";var c=new Date,d=c.getMonth()+1,e=c.getDate();d<10&&(d="0"+d);var n=""+c.getFullYear()+d+(e<10?"0"+e:e),c=""+c.getFullYear()+d+(e+1<10?"0"+(e+1):e+1),a=b+"render?action=TEMPLATE&text="+encodeURIComponent(a.split("\n")[0])+"&dates="+n+"/"+c+"&details="+encodeURIComponent(a)+"&sprop;=name:";chrome.tabs.create({url:a})});c=localStorage.notepadFont;if(!c)c=a in b?"Verdana":"Handwritten",localStorage.notepadFont=
c;$("#notepad").css("font-family",c);$("#background-img").load(function(){$(".loading-gif").hide();resizeBackground()});$("#background-img").error(function(){var a=$(this);a.attr("base")&&saveWallpaper("flickr",a.attr("base")+"_o.jpg",a.attr("fid"))});$(window).resize(function(){resizeBackground();resize()});localStorage.hideBookmarkControlsHelp||($("#bookmarkControlsHelp").show(),$("#bookmarkControlsHelpDismiss").click(function(){localStorage.hideBookmarkControlsHelp=!0;$("#bookmarkControlsHelp").hide("fast")}));
localStorage.hideBookmarkHelp||($("#bookmarkBar").hover(function(){localStorage.hideBookmarkHelp||$("#bookmarkBarHelp").stop().show().animate({opacity:1},"fast")},function(){$("#bookmarkBarHelp").stop().animate({opacity:0},"fast",function(){$("#bookmarkBarHelp").hide()})}),$("#bookmarkBarHelpDismiss").click(function(){localStorage.hideBookmarkHelp=!0;$("#bookmarkBarHelp").hide("slow")}));$("#files").change(handleFileSelect);chrome.bookmarks.getChildren("0",function(a){for(var b=["bookmarkBarList",
"bookmarkBrowserList"],c=0;c<b.length;c++)setupList(b[c]);try{rootBookmarkId="0",bookmarkBarId=localStorage.bookmarkBarId||a[0].id,otherBookmarkId=a[1].id,fillBoxWithBookmarkId(localStorage.bookmarkBrowserId||rootBookmarkId,"bookmarkBrowser",!1),fillBoxWithBookmarkId(bookmarkBarId,"bookmarkBar",!0)}catch(d){fillBoxWithBookmarkId("0","bookmarkBrowser",!1),fillBoxWithBookmarkId("1","bookmarkBar",!0)}$(".list").disableSelection();$("#backToParentDiv").click(function(){var a=$("#bookmarkBrowserList").attr("bookmarkId");
chrome.bookmarks.get(a,function(a){a?a[0].parentId&&fillBoxWithBookmarkId(a[0].parentId,"bookmarkBrowser"):fillBoxWithBookmarkId(rootBookmarkId,"bookmarkBrowser")})});$("#bookmarkBrowserPin").click(function(){if($(this).attr("disabled")!="true"){var a=$("#bookmarkBrowserList").attr("bookmarkId");chrome.bookmarks.get(a,function(b){b?(bookmarkBarId=a,localStorage.bookmarkBarId=a,fillBoxWithBookmarkId(a,"bookmarkBar",!0)):alert("FAIL")})}});$("#bookmarkBrowserTop").click(function(){$(this).attr("disabled")!=
"true"&&fillBoxWithBookmarkId(rootBookmarkId,"bookmarkBrowser")});loadWallPaper()});$("#uninstallApp").click(function(){popupNode&&(confirm(getMessage("confirm_uninstall",[popupNode.app.name]))?chrome.management.uninstall(popupNode.app.id,function(){popupNode.node.remove();popupNode=null;$("#appContextmenu").hide()}):(popupNode=null,$("#appContextmenu").hide()))});$("#deleteBm").click(function(){bmNode&&chrome.bookmarks.remove(bmNode[0].bookmarkId,function(){bmNode.remove();bmNode=null;$("#appContextmenu").hide()})});
$("#renameBm").click(function(){if(bmNode){var a=bmNode.attr("title"),b=prompt(getMessage("promptRename"),a);b&&b!=a?chrome.bookmarks.update(bmNode[0].bookmarkId,{title:b},function(){bmNode.attr("title",b);bmNode.find(".label").text(b);bmNode=null;$("#appContextmenu").hide()}):(bmNode=null,$("#appContextmenu").hide())}});$("#menuCancel").click(function(){$("#appContextmenu").hide()});(lastTab=localStorage["last.tab"])&&lastTab!="bm"&&toggleView(lastTab);$("#custom").click(function(){$(".photoTheme").removeAttr("selected");
$("#custom").attr("selected",!0);wpData.source=="customURL"?($("#customWallpaperURL")[0].value=wpData.url,$("#useURL").attr("checked",!0),$("#customWallpaperURL")[0].focus(),$("#customWallpaperURL")[0].select()):wpData.source=="local"&&$("#useLocal").attr("checked",!0);$("#customDialog").fadeIn();$("#albumRow").hide()});$("#default").click(function(){saveWallpaper("default")});renderSelectedNote();window.onbeforeunload=updateNoteBeforeTimeout;minibarArea.onselectstart=function(){return!1}}
function updateNoteBeforeTimeout(){typingTimer&&(clearTimeout(typingTimer),updateNote())}function checkTopsites(){localStorage.hasNewPermission=="true"?toggleView("tops"):(console.log("ask for permission"),chrome.permissions.request({permissions:["topSites"],origins:["chrome://favicon/"]},function(a){if(a)console.log("granted permission"),localStorage.hasNewPermission=!0,localStorage["last.tab"]="tops",window.location.reload()}))}
function loadWallPaper(){try{wpData=JSON.parse(localStorage.wpData||"{}"),wpData.source=="default"?$("#background-img").attr("src","/img/default_background.jpg"):wpData.source=="local"?($("#background-img").show(),$("#background-img").attr("src",localStorage["local-file"]||"/img/default_background.jpg")):wpData.url?($("#background-img").show(),$("#background-img").attr("src",wpData.url||"/img/default_background.jpg")):wpData.source=="gradient"&&($("#background-img").hide(),$("#background-imgBlock").css("background",
"-webkit-gradient(linear, left top, right bottom, from("+wpData.from+"),to("+wpData.to+"))"))}catch(a){console.error("Wallpaper too large too load",a),$("#background-img").attr("src","/img/default_background.jpg")}}
function setupList(a){$("#"+a).click(function(a){openBookmark(a)});$("#"+a).sortable({scroll:!0,opacity:0.6,tolerance:"pointer",connectWith:".connected",appendTo:"body",helper:"clone",distance:5,cancel:"#bookmarkBrowserHelp",items:"a",start:function(a,c){c.item.css("z-index","99999")},stop:function(a,c){c.item.css("z-index","")},deactivate:function(){},receive:function(a,c){($(this).attr("bookmarkId")==c.item.attr("parentId")||c.item.attr("isFolder")=="true")&&$(c.sender).sortable("cancel")},remove:function(){},
update:function(b,c){$(this).attr("updated",!0);var d=0;if(this.id!=c.item.parent().attr("id"))d=1;else if(c.item.hasClass(this.id.replace("List","Item")))d=2;else{d=3;c.item.attr("style","");for(var e=c.item.attr("class").split(" "),f=0;f<e.length;f++)e[f].match(/Item$/)&&(c.item.removeClass(e[f]),c.item.find(".label").removeClass(e[f].replace("Item","Label")),c.item.find(".favicon").removeClass(e[f].replace("Item","Favicon")));c.item.addClass(this.id.replace("List","Item"));c.item.find(".label").addClass(this.id.replace("List",
"Label"));c.item.find(".favicon").addClass(this.id.replace("List","Favicon"))}c.item.attr("parentId",$(this).attr("bookmarkId"));for(var e=$(this).sortable("toArray"),k=$(this).attr("bookmarkId"),g=c.item.attr("id"),j=0,f=0;f<e.length;f++)if(e[f]==g){j=f;break}chrome.bookmarks.getChildren(k,function(b){for(var e=!1,f=0,l=0,h=0;h<b.length;h++)if(b[h].url==null&&a=="bookmarkBarList"?f+=1:l+=1,b[h].id==g&&(e=!0),l>j)break;e==!0&&(j+=1);j+=f;d!=2&&c.item.attr("isFolder")=="true"||chrome.bookmarks.move(g,
{parentId:k,index:j},function(a){if(a==null)for(var a=$(".connected"),b=1;b<a.length;b++)fillBoxWithBookmarkId($(a[b]).attr("bookmarkId"),$(a[b]).parent().attr("id"),$(a[b]).attr("singleDirectoryMode"))})});e=$(".connected");for(f=0;f<e.length;f++)$(this).attr("bookmarkId")==$(e[f]).attr("bookmarkId")&&this!=e[f]&&fillBoxWithBookmarkId($(e[f]).attr("bookmarkId"),$(e[f]).parent().attr("id"),$(e[f]).attr("singleDirectoryMode"))}}).disableSelection()}
function renderRecentlyClosed(){$("#recentlyClosedList").empty();var a=[],b=localStorage.hasNewPermission=="true";try{a=background&&background.rcTabs&&background.rcTabs.length>0?background.rcTabs:JSON.parse(localStorage.recentlyClosedTabs)}catch(c){console.error("cannot load recently closed tabs")}for(var d=$("#recentlyClosedList"),e=a.length-1;e>=0;e--){var f=$("<a/>",{"class":"recentlyClosedItem item",style:"color:white",title:a[e].title,pinned:a[e].pinned,id:a[e].id,href:a[e].URL}).appendTo(d),
k=$("<img/>",{"class":"favicon recentlyClosedFavicon"}).appendTo(f);setFavicon(k,a[e].URL,a[e].favIconURL,b);$("<div/>",{"class":"label recentlyClosedLabel",title:a[e].title,text:a[e].title}).appendTo(f)}$("#recentlyClosed").click(function(a){openBookmark(a)});$("#clearClosedDiv").click(function(){if($(".recentlyClosedItem").length>0&&confirm("Clear closed tabs history?")&&($("#recentlyClosedList").empty(),localStorage.recentlyClosedTabs=[],background))background.rcTabs=[]})}
function fillBoxWithBookmarkId(a,b,c){(a==bookmarkBarId||a==rootBookmarkId)&&b=="bookmarkBrowser"?$(".connected").sortable("option","connectWith",""):$(".connected").sortable("option","connectWith",".connected");chrome.bookmarks.getChildren(a,function(d){d?(b=="bookmarkBrowser"?fillBoxWithData(d,b,c,a,!0):fillBoxWithData(d,b,c,a),b=="bookmarkBrowser"&&(localStorage.bookmarkBrowserId=a)):b=="bookmarkBrowser"?fillBoxWithBookmarkId("0","bookmarkBrowser",!1):b=="bookmarkBar"&&fillBoxWithBookmarkId("1",
"bookmarkBar",!0)});chrome.bookmarks.get(a,function(a){b=="bookmarkBrowser"&&(a&&a[0]&&a[0].parentId?($("#backToParentDiv").show(),$("#bookmarkBrowserPin").attr("disabled","false"),$("#bookmarkBrowserTop").attr("disabled","false")):($("#backToParentDiv").hide(),$("#bookmarkBrowserPin").attr("disabled","true"),$("#bookmarkBrowserTop").attr("disabled","true")))})}
function setFavicon(a,b,c,d){d?a.attr("src","chrome://favicon/"+b):c?a.attr("src",c):window.setTimeout(function(){a.attr("src","http://www.google.com/s2/favicons?domain_url="+encodeURIComponent(b))},200)}
function fillBoxWithData(a,b,c,d,e){if(isFilling)setTimeout(function(){fillBoxWithData(a,b,c)},Math.floor(Math.random()*100)+20);else{isFilling=!0;var f=b+"Item",k=b+"Label",g,j=b+"Favicon",m=$("#"+(b+"List"));m.empty();if(!(a==null||b==null)){for(var n=localStorage.hasNewPermission=="true",i=0;i<a.length;i++)if(!c||a[i].url){g="fontColor1";if(localStorage.fontColor){var l=localStorage.fontColor;l==2&&!e&&(g="fontColor2")}var h=$("<a/>",{id:a[i].id,"class":f+" item "+g,title:a[i].title}).appendTo(m);
h[0].parentId=d;h[0].bookmarkId=a[i].id;g=$("<img/>",{"class":j+" favicon"}).appendTo(h);a[i].url?(setFavicon(g,a[i].url,null,n),h.attr("href",a[i].url)):(g.attr("src","/img/folder.png"),h.attr("isFolder","true"));var o=$("<div/>",{"class":k+" label",title:a[i].title,text:a[i].title}).appendTo(h);if(b=="bookmarkBar"){g="fontColor1";if(localStorage.fontColor)l=localStorage.fontColor,l==2&&(g="fontColor2");o.addClass(g);$("<img/>",{src:"/img/wrench.png","class":"appWrench",align:"right",width:16,height:16,
click:editBookmark}).appendTo(h)}columnInBookmark&&f=="bookmarkBarItem"&&h.css("width","30%")}m.attr("bookmarkId",d);c&&m.attr("singleDirectoryMode","true");isFilling=!1;d=="0"&&$("<div/>",{id:"bookmarkBrowserHelp",html:getMessage("bookmarkBrowserHelp")}).appendTo(m)}}}
function editBookmark(a){a.stopPropagation();var a=$(a.target).closest("a"),b=a.attr("title");$("#appContextmenu").show();$("#appMenuTitle").text('Edit bookmark "'+b+'"?');$("#uninstallApp").hide();$("#appContextmenu > .bmMenu").show();bmNode=a;return!1}
function openBookmark(a){var b=$(a.target).closest(".item");if(b&&b.length>0){var c=b[0].href;if(c){if(c.indexOf("file://")==0||c.indexOf("chrome://")==0)return a.stopPropagation(),a.button==0?chrome.tabs.getSelected(null,function(a){chrome.tabs.update(a.id,{url:c})}):chrome.tabs.create({url:c}),!1}else a.button==0&&fillBoxWithBookmarkId(b[0].bookmarkId,b[0].parentNode.parentNode.id)}}
function resize(){if(background){var a=$("#fixedArea"),b=$("#base"),a=document.defaultView.getComputedStyle(a[0],null).width,b=document.defaultView.getComputedStyle(b[0],null).width,a=parseInt(a.replace("px","")),b=parseInt(b.replace("px",""));$("#variableArea").css("width",b-a-50)}}chrome.bookmarks.onMoved.addListener(function(a,b){refreshBookmarkFolder(b.parentId);b.parentId!=b.oldParentId&&refreshBookmarkFolder(b.oldParentId)});chrome.bookmarks.onCreated.addListener(function(a,b){refreshBookmarkFolder(b.parentId)});
chrome.bookmarks.onRemoved.addListener(function(a,b){refreshBookmarkFolder(b.parentId)});function refreshBookmarkFolder(a){[bookmarkBarList,bookmarkBrowserList].forEach(function(b){a==$(b).attr("bookmarkid")&&(b=$(b),b.attr("updated")!="true"?fillBoxWithBookmarkId(b.attr("bookmarkId"),b.parent().attr("id"),b.attr("singleDirectoryMode")):b.attr("updated",!1))})}
function changeBackgroundColor(a){switch(a){case 0:document.body.setAttribute("class","colorTheme0");break;case 1:document.body.setAttribute("class","colorTheme1");break;case 2:document.body.setAttribute("class","colorTheme2");break;case 3:document.body.setAttribute("class","colorTheme3");break;case 4:document.body.setAttribute("class","colorTheme4");break;case 5:if(document.body.setAttribute("class","colorThemeCustom"),localStorage.backgroundColor1&&localStorage.backgroundColor2){var b=localStorage.backgroundColor1,
c=localStorage.backgroundColor2;$(".colorThemeCustom").css("background","-webkit-gradient(linear, left top, right bottom, from("+b+"),to("+c+"))")}else $(".colorThemeCustom").css("background","-webkit-gradient(linear, left top, right bottom, from(#aaa),to(#aaa))")}localStorage.themeColor=a}function customBackgroundColor(){var a=$("#backgroundColor1")[0].value,b=$("#backgroundColor2")[0].value;localStorage.backgroundColor1=a;localStorage.backgroundColor2=b;changeBackgroundColor(5)}
function changeFontColor(a){a=="1"?($(".bookmarkBarLabel").removeClass("fontColor2"),$(".bookmarkBarLabel").addClass("fontColor1"),$(".appItemLabel").removeClass("fontColor2"),$(".appItemLabel").addClass("fontColor1"),$(".appItem").removeClass("fontColor2"),$(".appItem").addClass("fontColor1"),$(".bookmarkBarItem").removeClass("fontColor2"),$(".bookmarkBarItem").addClass("fontColor1")):a=="2"&&($(".bookmarkBarLabel").removeClass("fontColor1"),$(".bookmarkBarLabel").addClass("fontColor2"),$(".appItemLabel").removeClass("fontColor1"),
$(".appItemLabel").addClass("fontColor2"),$(".appItem").removeClass("fontColor1"),$(".appItem").addClass("fontColor2"),$(".bookmarkBarItem").removeClass("fontColor1"),$(".bookmarkBarItem").addClass("fontColor2"));localStorage.fontColor=a}
function toggleOptionsBox(){$(".photoTheme").removeAttr("selected");$("#optionsArea").css("display")=="none"?($("#optionsArea").css("display","block"),$("#optionsArea").animate({top:"+=700"},300,"linear"),wpData=JSON.parse(localStorage.wpData||"{}"),wpData.source=="custom"||wpData.source=="local"?$("#custom").attr("selected",!0):wpData.source=="gradient"?($("#wallpaperColor1")[0].color.fromString(wpData.from),$("#wallpaperColor2")[0].color.fromString(wpData.to)):wpData.source=="default"&&$("#default").attr("selected",
!0),localStorage.backgroundColor1&&localStorage.backgroundColor2&&($("#backgroundColor1")[0].color.fromString(localStorage.backgroundColor1),$("#backgroundColor2")[0].color.fromString(localStorage.backgroundColor2))):($("#optionsArea").animate({top:"-=700"},300,"linear",function(){$("#optionsArea").css("display","none")}),cleanupAlbums());$("#customDialog").hide();$("#albumRow").hide();$("#reset").hide()}
function resizeBackground(){var a=$("#background-img")[0],b=$("#background-imgBlock")[0],a=a.naturalWidth/a.naturalHeight,c=b.offsetWidth,b=b.offsetHeight;if(a>c/b)var d=b,e=b*a;else e=c,d=c/a;$("#background-img").css({width:e,height:d,top:(b-d)/2,left:(c-e)/2})}
function renderPage(a){if(a){var b=$("#albumRow");b.empty();$.each(a,function(a,d){$("<img/>",{src:d.url+"_m.jpg",id:d.id,index:a,"class":"wpThumb",click:function(){$(".loading-gif").show();$("#background-img").attr("base",d.url);$("#background-img").attr("fid",d.id);saveWallpaper("flickr",d.url+"_b.jpg",d.id)}}).appendTo(b)});$("#albumRow").show();$(".loading-gif").hide()}else alert("Fail to load more photos")}
function getPhotos(a){selectedAlbum?a==1?selectedAlbum.getNextPage(renderPage):(a=selectedAlbum.getPreviousPage(),renderPage(a)):showAlbum("clouds",1,document.getElementById("clouds"))}function showAlbum(a,b,c){$(".photoTheme").removeAttr("selected");$(c).attr("selected",!0);$(".loading-gif").show();selectedAlbum=getAlbum(a,b);selectedAlbum.getPage(0,function(a){$("#albumRow").empty();renderPage(a)})}
function showCustomWallpaperBox(){wpData.source=="customURL"?($("#customWallpaperURL")[0].value=wpData.url,$("#useURL").attr("checked",!0),$("#customWallpaperURL")[0].focus(),$("#customWallpaperURL")[0].select()):wpData.source=="local"&&$("#useLocal").attr("checked",!0);$("#customDialog").fadeIn();$("#albumRow").hide()}function undo(){$("#customDialog").fadeOut();loadWallPaper()}
function saveWallpaper(a,b,c){$(".photoTheme").removeAttr("selected");if(a=="default")wpData={source:"default",url:"/img/default_background.jpg"},$("#default").attr("selected",!0);else if(a=="gradient")wpData={source:a,from:$("#wallpaperColor1")[0].value,to:$("#wallpaperColor2")[0].value};else if($("#useLocal").attr("checked"))try{wpData={source:"local",filename:$("#thumb").attr("title")},localStorage["local-file"]=$("#background-img").attr("src"),$("#custom").attr("selected",!0)}catch(d){alert("Image size is too large, please use a smaller one")}else $("#useURL").attr("checked")?
(wpData={source:"customURL",url:$("#customWallpaperURL")[0].value},$("#custom").attr("selected",!0)):a=="flickr"&&(wpData={source:"flickr",url:b,id:c});wpData.source!="gradient"&&($("#wallpaperColor1")[0].color.fromString("FFFFFF"),$("#wallpaperColor2")[0].color.fromString("FFFFFF"));localStorage.wpData=JSON.stringify(wpData);loadWallPaper();$("#customDialog").fadeOut()}
function toggleView(a){a&&($(".tabSelector").css("background","rgba(255,255,255,0.1)"),$("#appContextmenu").hide(),bmNode=popupNode=null,a=="apps"?($("#bookmarkBarList").hide(),$("#appList").show(),$("#topList").hide(),$("#appSelector").css("background","white")):a=="tops"?($("#topList").children().length==0&&(console.log("render top sites"),showTopsites()),$("#bookmarkBarList").hide(),$("#appList").hide(),$("#topList").show(),$("#topSelector").css("background","white")):($("#bookmarkBarList").show(),
$("#appList").hide(),$("#topList").hide(),$("#bookmarkSelector").css("background","white")),localStorage["last.tab"]=a)}function orderApp(a){var b={};a.forEach(function(a){a.isApp&&a.enabled&&(b[a.id]=a)});var c=localStorage.appOrder,d;if(c)try{d=JSON.parse(c),$.each(d,function(a,c){if(b[c])b[c].order=a})}catch(e){}return a=a.sort(function(a,b){return a.order&&b.order?a.order>b.order?1:-1:a.order||b.order?a.order?1:-1:a.name>b.name?1:-1})}
function getIcon(a){if(a.icons){var b={};a.icons.forEach(function(a){b[a.size]=a});if((a=b[48]||b[128])&&a.url)return a.url}return"/img/IBChrome48.png"}var appSorting=!1;
function getAppList(){chrome.management.getAll(function(a){var b="fontColor1";localStorage.fontColor&&localStorage.fontColor==2&&(b="fontColor2");var a=orderApp(a),c=$("<a/>",{"class":"appItem "+b,id:"gallery",href:"https://chrome.google.com/webstore"});$("<div/>",{text:"Chrome Web Store","class":"appItemLabel "+b}).appendTo(c);$("<img/>",{src:"/img/google_chrome_web_store.png",align:"left",width:48,height:48}).appendTo(c);c.appendTo($("#appList"));a.forEach(function(a){if(a.isApp&&a.enabled){var c=
$("<div/>",{"class":"appItem",id:a.id});$("<img/>",{src:getIcon(a),align:"left",width:48,height:48}).appendTo(c);$("<div/>",{text:a.name,"class":"appItemLabel "+b}).appendTo(c);$("<img/>",{src:"/img/wrench.png","class":"appWrench",align:"right",width:16,height:16,click:function(){$("#appContextmenu").show();$("#appMenuTitle").text("Actions for "+a.name);$("#uninstallApp").show();$("#appContextmenu > .bmMenu").hide();popupNode={app:a,node:c};return!1}}).appendTo(c);c.appendTo($("#appList"))}});localStorage.columnInApp==
"true"&&$("#appList").find(".appItem").css("width","30%")});$("#appList").sortable({items:".appItem:not(.ui-state-disabled)",start:function(a,b){appSorting=!0;b.item.css("z-index","99999")},update:function(){var a=$("#appList").sortable("toArray");localStorage.appOrder=JSON.stringify(a)},stop:function(a,b){appSorting=!1;b.item.css("z-index","")},containment:"#appList",cancel:".appWrench",delay:30});$("#appList").mouseup(function(a){if(appSorting)return!0;var b=$(a.target).closest(".appItem");if(b[0].id==
"gallery")return!1;if($(a.target).hasClass("appWrench"))return!1;a.button==0?(chrome.management.launchApp(b[0].id),window.close()):a.button==1&&chrome.management.launchApp(b[0].id)})}
function handleFileSelect(a){for(var a=a.target.files,b=0,c;c=a[b];b++){if(c.fileSize>512E3){alert(getMessage("fileWarning"));$("#reset").click();break}if(c.type.match("image.*")){var d=new FileReader;d.onload=function(a){return function(b){$("#thumb").attr("src",b.target.result).attr("title",a.name);$("#useLocal").attr("checked",!0);$("#background-img").attr("src",b.target.result)}}(c);d.readAsDataURL(c)}}}
chrome.extension.onRequest.addListener(function(a){switch(a.type){case "wallpaperChanged":$("#background-img").attr("src",a.url)}});
function showTopsites(){if(localStorage.showTopSites!="false"){var a="fontColor1";localStorage.fontColor&&localStorage.fontColor==2&&(a="fontColor2");chrome.topSites.get(function(b){b.forEach(function(b){var d=$("<a/>",{"class":"appItem",href:b.url,title:b.title});$("<img/>",{src:"chrome://favicon/"+b.url,align:"left","class":"bookmarkBarFavicon favicon"}).appendTo(d);$("<div/>",{text:b.title,"class":"appItemLabel "+a}).appendTo(d);d.appendTo($("#topList"))});localStorage.columnInTop=="true"&&$("#topList").find(".appItem").css("width",
"30%")})}}var albums={};function cleanupAlbums(){albums={}}function getAlbum(a,b){var c=albums[a];c||(c=new Album(a,b),albums[a]=c);return c}function Album(a,b){this.tag=a;this.pages=[];this.selected=0;this.sort=b==0?"interestingness-desc":"relevance"}
Album.prototype={addPhotos:function(a,b){var c=[];$.each(a.photos.photo,function(a,b){c.push({url:"http://farm"+b.farm+".static.flickr.com/"+b.server+"/"+b.id+"_"+b.secret,id:b.id})});this.pages[b]=c},getPage:function(a,b){var c=this;this.pages[a]?b(this.pages[a]):fetchPhotos({tag:this.tag,sort:this.sort,page:a+1},function(d,e){d?(c.addPhotos(e,a),b(c.pages[a])):b(null)})},getNextPage:function(a){this.selected++;this.getPage(this.selected,a)},getPreviousPage:function(){this.selected>0&&this.selected--;
return this.pages[this.selected]}};function fetchPhotos(a,b){console.log("fetchPhotos",a);$.ajax({url:"http://api.flickr.com/services/rest/",type:"GET",dataType:"json",data:{method:"flickr.photos.search",api_key:"90485e931f687a9b9c2a66bf58a3861a",text:a.tag,safe_search:1,content_type:1,sort:a.sort,per_page:20,page:a.page,format:"json",nojsoncallback:1},success:function(a){a.stat=="ok"?b&&b(!0,a):b&&b(!1,null)},error:function(a,d,e){console.log("ajax FAIL",a,d,e);b(!1,null)}})}$(document).ready(function(){init()});
