var background=chrome.extension.getBackgroundPage();
function init(){$("title").html(chrome.i18n.getMessage("pagetitle"));for(var a=["pagetitle","incredibleStartPage","incredibleStartPageDescription","optionsTitle","notepadFont","maximumRecentlyClosedTabs","notRememberClosedTabs","notepadSync","notepadSyncDescription","notepadSyncDescription2","shareNotepadTo","gmailAccount","googleAppsAccount","googleAppsAccountDescription","save","optionsSaved","optionsEffect","contactUs","columnInBookmarkLabel","columnInAppLabel","noColumnsLabel","existingBMLabel",
"topSitesLabel","addLinkMenu"],b=0;b<a.length;++b)try{var c=chrome.i18n.getMessage(a[b]);c&&$("#"+a[b]).html(c)}catch(d){}$("#syncNotepad").click(function(){checkSyncAvailable()});$("#save").click(function(){save()})}
function restoreSetting(){var a=localStorage.notepadFont;a&&$("#fontFamily").val(a);(a=localStorage.maxRecentlyClosed)&&$("#maxRecentlyClosed").val(a);localStorage.syncNotepad=="true"&&$("#syncNotepad").attr("checked",!0);localStorage.googleAppsDomain&&$("#googleAppsDomain").attr("value",localStorage.googleAppsDomain);localStorage.shareNotepadSetting&&(localStorage.shareNotepadSetting=="googleApps"?$(".shareNotepadSetting[value='googleApps']").attr("checked","checked"):$(".shareNotepadSetting[value='gmail']").attr("checked",
"checked"));localStorage.columnInBookmark=="true"&&$("#columnInBookmark").attr("checked",!0);localStorage.columnInApp=="true"&&$("#columnInApp").attr("checked",!0);localStorage.columnInTop=="true"&&$("#columnInTop").attr("checked",!0);localStorage.showTopSites!="false"&&$("#showTopSites").attr("checked",!0);localStorage.enableAddLink=="true"&&$("#enableAddLink").attr("checked",!0)}
function checkSyncAvailable(){isChecked("#syncNotepad")?background.hasBookmark(function(a){console.log("hasBookmark",a);a?(a=decodeURIComponent(a.url.replace("javascript:","")),localStorage.multiNotes!=a?$("#useExisting").show():console.log("Content is in sync")):($("#useExisting").hide(),console.log("No exisiting"))}):($("#useExisting").hide(),console.log("No sync"))}
function saveMaxRecentlyClosed(){var a=$("#maxRecentlyClosed")[0].value;localStorage.maxRecentlyClosed=a;if(background.rcTabs){for(;background.rcTabs.length>a;)background.rcTabs.shift();localStorage.recentlyClosedTabs=JSON.stringify(background.rcTabs)}}function isChecked(a){return $(a).attr("checked")=="checked"}function saveSyncNotepad(){var a=chrome.extension.getBackgroundPage(),b=isChecked("#syncNotepad");localStorage.syncNotepad=b;a.setUpSyncBookmark(b,isChecked("#existingBm"))}
function save(){saveMaxRecentlyClosed();saveSyncNotepad();localStorage.notepadFont=$("#fontFamily")[0].value;var a=$("#googleAppsDomain")[0].value;localStorage.googleAppsDomain=a;localStorage.shareNotepadSetting=$(".shareNotepadSetting:checked").val();localStorage.columnInBookmark=isChecked("#columnInBookmark");localStorage.columnInApp=isChecked("#columnInApp");localStorage.columnInTop=isChecked("#columnInTop");isChecked("#showTopSites")?delete localStorage.showTopSites:localStorage.showTopSites=
!1;isChecked("#enableAddLink")?localStorage.enableAddLink=!0:delete localStorage.enableAddLink;background.toggleMenu();$("#optionsSaved").show().delay(3E3).fadeOut()}$(document).ready(function(){init();restoreSetting()});
