/*
 Copyright 2010 Google Inc.  All Rights Reserved.
 Your use of this software is subject to the Terms of Service located
 at https://chrome.google.com/extensions/intl/en/gallery_tos.html.
*/
var e;var l=function(a,b,c){return a.call.apply(a.bind,arguments)},n=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},p=function(a,b,c){p=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?l:n;return p.apply(null,arguments)},q=function(a,b){function c(){}
c.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new c;a.prototype.constructor=a};Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return p.apply(null,c)}return p(this,a)};Function.prototype.partial=function(a){var b=Array.prototype.slice.call(arguments);b.unshift(this,null);return p.apply(null,b)};Function.prototype.inherits=function(a){q(this,a)};
Function.prototype.mixin=function(a){var b=this.prototype,c;for(c in a)b[c]=a[c]};var r=RegExp("https?://(?:.+\\.)?google\\.[a-z]{2,3}(?:\\.[a-z]{2})?(?:\\:[0-9]+)?/(?:advanced_)?search.*(([?&]q=)([^&]+))"),s=RegExp("https?://(?:.+\\.)?google\\.[a-z]{2,3}(?:\\.[a-z]{2})?(?:\\:[0-9]+)?/(?:webhp[^#]*)?(#((?:.+&)?q=)([^&]+)(.*)&fp=[^&]+)"),t=/&/g,u=/</g,v=/>/g,w=/\"/g;function x(a){return a?a.replace(t,"&amp;").replace(u,"&lt;").replace(v,"&gt;").replace(w,"&quot;"):""}function y(a,b,c,d,f,g,h,m){return p.apply(null,arguments)}
Array.prototype.peek=function(){return this[this.length-1]};function z(a,b,c){if("true"==window.localStorage.enableGen204Logging&&null!=a&&null!=b){b=["atyp=i","oi=findy","ct="+b];a.ei&&b.push("ei="+a.ei);a.ved&&b.push("ved="+a.ved);a=c||{};a.seq=(new Date).getTime();c=[];for(var d in a)c.push(d+":"+encodeURIComponent(a[d]));d="http://www.google.com/gen_204?"+b.join("&")+"&cad="+c.join(";");try{var f=new XMLHttpRequest;f.open("GET",d,!0);f.send()}catch(g){}}};var A="StopIteration"in this?this.StopIteration:Error("StopIteration"),B=function(){};B.prototype.next=function(){throw A;};B.prototype.__iterator__=function(){return this};var C=function(a,b){this.map_={};this.keys_=[];var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){var f;if(a instanceof C)f=a.getKeys(),d=a.getValues();else{var c=[],g=0;for(f in a)c[g++]=f;f=c;c=[];g=0;for(d in a)c[g++]=a[d];d=c}for(c=0;c<f.length;c++)this.set(f[c],d[c])}};e=C.prototype;e.count_=0;e.version_=0;e.getCount=function(){return this.count_};
e.getValues=function(){D(this);for(var a=[],b=0;b<this.keys_.length;b++)a.push(this.map_[this.keys_[b]]);return a};e.getKeys=function(){D(this);return this.keys_.concat()};e.containsKey=function(a){return E(this.map_,a)};e.containsValue=function(a){for(var b=0;b<this.keys_.length;b++){var c=this.keys_[b];if(E(this.map_,c)&&this.map_[c]==a)return!0}return!1};
e.equals=function(a,b){if(this===a)return!0;if(this.count_!=a.getCount())return!1;var c=b||F;D(this);for(var d,f=0;d=this.keys_[f];f++)if(!c(this.get(d),a.get(d)))return!1;return!0};var F=function(a,b){return a===b};C.prototype.isEmpty=function(){return 0==this.count_};C.prototype.clear=function(){this.map_={};this.version_=this.count_=this.keys_.length=0};
C.prototype.remove=function(a){return E(this.map_,a)?(delete this.map_[a],this.count_--,this.version_++,this.keys_.length>2*this.count_&&D(this),!0):!1};var D=function(a){if(a.count_!=a.keys_.length){for(var b=0,c=0;b<a.keys_.length;){var d=a.keys_[b];E(a.map_,d)&&(a.keys_[c++]=d);b++}a.keys_.length=c}if(a.count_!=a.keys_.length){for(var f={},c=b=0;b<a.keys_.length;)d=a.keys_[b],E(f,d)||(a.keys_[c++]=d,f[d]=1),b++;a.keys_.length=c}};e=C.prototype;
e.get=function(a,b){return E(this.map_,a)?this.map_[a]:b};e.set=function(a,b){E(this.map_,a)||(this.count_++,this.keys_.push(a),this.version_++);this.map_[a]=b};e.clone=function(){return new C(this)};e.transpose=function(){for(var a=new C,b=0;b<this.keys_.length;b++){var c=this.keys_[b];a.set(this.map_[c],c)}return a};e.toObject=function(){D(this);for(var a={},b=0;b<this.keys_.length;b++){var c=this.keys_[b];a[c]=this.map_[c]}return a};e.getKeyIterator=function(){return this.__iterator__(!0)};
e.getValueIterator=function(){return this.__iterator__(!1)};e.__iterator__=function(a){D(this);var b=0,c=this.keys_,d=this.map_,f=this.version_,g=this,h=new B;h.next=function(){for(;;){if(f!=g.version_)throw Error("The map has changed since the iterator was created");if(b>=c.length)throw A;var h=c[b++];return a?h:d[h]}};return h};var E=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var H=function(a,b){this.maxCount_=a||null;this.cache_=!!b;this.map_=new C;this.head_=new G("",void 0);this.head_.next=this.head_.prev=this.head_},J=function(a,b){var c=a.map_.get(b);c&&a.cache_&&(c.remove(),I(a,c));return c};e=H.prototype;e.get=function(a,b){var c=J(this,a);return c?c.value:b};e.peekValue=function(a,b){var c=this.map_.get(a);return c?c.value:b};e.set=function(a,b){var c=J(this,a);c?c.value=b:(c=new G(a,b),this.map_.set(a,c),I(this,c))};e.peek=function(){return this.head_.next.value};
e.peekLast=function(){return this.head_.prev.value};e.shift=function(){return K(this,this.head_.next)};e.pop=function(){return K(this,this.head_.prev)};e.remove=function(a){return(a=this.map_.get(a))?(this.removeNode(a),!0):!1};e.removeNode=function(a){a.remove();this.map_.remove(a.key)};e.getCount=function(){return this.map_.getCount()};e.isEmpty=function(){return this.map_.isEmpty()};e.setMaxCount=function(a){this.maxCount_=a||null;null!=this.maxCount_&&L(this,this.maxCount_)};
e.getKeys=function(){return this.map(function(a,b){return b})};e.getValues=function(){return this.map(function(a){return a})};e.contains=function(a){return this.some(function(b){return b==a})};e.containsKey=function(a){return this.map_.containsKey(a)};e.clear=function(){L(this,0)};e.forEach=function(a,b){for(var c=this.head_.next;c!=this.head_;c=c.next)a.call(b,c.value,c.key,this)};e.map=function(a,b){for(var c=[],d=this.head_.next;d!=this.head_;d=d.next)c.push(a.call(b,d.value,d.key,this));return c};
e.some=function(a,b){for(var c=this.head_.next;c!=this.head_;c=c.next)if(a.call(b,c.value,c.key,this))return!0;return!1};e.every=function(a,b){for(var c=this.head_.next;c!=this.head_;c=c.next)if(!a.call(b,c.value,c.key,this))return!1;return!0};
var I=function(a,b){a.cache_?(b.next=a.head_.next,b.prev=a.head_,a.head_.next=b,b.next.prev=b):(b.prev=a.head_.prev,b.next=a.head_,a.head_.prev=b,b.prev.next=b);null!=a.maxCount_&&L(a,a.maxCount_)},L=function(a,b){for(var c=a.map_.getCount();c>b;c--)a.removeNode(a.cache_?a.head_.prev:a.head_.next)},K=function(a,b){a.head_!=b&&a.removeNode(b);return b.value},G=function(a,b){this.key=a;this.value=b};G.prototype.remove=function(){this.prev.next=this.next;this.next.prev=this.prev;delete this.prev;delete this.next};var M=function(){this.map_=new H(100,!0)};M.prototype.hasResultsFor=function(a){return null!=this.map_.get(a)};var O=function(a,b){var c=N.map_.get(a);if(!c||null==b)return null;for(var d=null,f=0;f<c.length&&(d=c[f],d.query!=b&&d.ei!=b);f++);return d};M.prototype.getNumResultsForUrl=function(a){return this.map_.get(a,[]).length};chrome.extension.getVersion=function(){if(!chrome.extension.version_){var a=new XMLHttpRequest;a.open("GET",chrome.extension.getURL("manifest.json"),!1);a.onreadystatechange=function(){if(4==this.readyState){var a=JSON.parse(this.responseText);chrome.extension.version_=a.version}};a.send()}return chrome.extension.version_};var P=function(){this.lastInterval_=null};P.prototype.setImage_=function(a){chrome.pageAction.setIcon({tabId:a,path:"images/page-action-animated_"+this.step_+".png"});this.step_=(this.step_+1)%8};P.prototype.stop=function(){this.lastInterval_&&window.clearInterval(this.lastInterval_)};var T={"search-results":Q,"landing-page":R,"found-tidbits":S,"log-event":aa,"minimized-state":ba,"open-link":ca,"get-more-tidbits":da},N=new M,U=new P;
function Q(a,b){for(var c=b.results,d=N,f=0;f<c.length;f++){var g=c[f];if(g.href)t:{var h=d,m=h.map_.get(g.href);if(m){for(h=0;h<m.length;h++){var k=m[h];if(k.query==g.query||k.ei==g.ei){k.ei=g.ei;k.fromVisualSnippet=g.fromVisualSnippet;k.vsClickedTidbitIndex=g.vsClickedTidbitIndex;k.query=g.query;k.searchUrl=g.searchUrl;k.tidbits=g.tidbits;k.htmlTidbits=g.htmlTidbits;k.hasEbmTidbits=g.hasEbmTidbits;m.splice(h,1);m.push(k);break t}}m.push(g)}else h.map_.set(g.href,[g])}}}
function R(a,b){var c=a.sender.tab.id,d=O(b.href,b.subkey);if(d&&0<d.tidbits.length)d.debug=d.debug||{},d.debug.version=chrome.extension.getVersion(),d.hasEbmTidbits?V(c,{title:"running",active:!0}):V(c,{active:!0}),chrome.tabs.executeScript(c,{code:"window.qs_result = "+JSON.stringify(d)},function(){W(c,"in-document_content_script.js",function(){d.seen=!0})});else{var f;d?f=chrome.i18n.getMessage("qs_info_non_annotated_result",x(d.query)):(r.test(b.href)||s.test(b.href))&&((r.test(b.href)||s.test(b.href))&&
/[?&#](qscrl|espv)=/.test(b.href))&&(f=chrome.i18n.getMessage("qs_info_on_search"));f&&(V(c,{active:!1}),X(c,f))}}function S(a,b){var c=a.sender.tab.id;b.foundTidbits?(V(c,{active:!0}),z(b.result,b.result.hasEbmTidbits?"found-tidbits":"found-nft-tidbits",b.logParams)):(V(c,{active:!1}),X(c,chrome.i18n.getMessage("qs_info_no_tidbits_found",x(b.result.query))),z(b.result,"no-tidbits-found"))}function aa(a,b){var c=b.params||{};c.ver=chrome.extension.getVersion();z(b.result,b.action,c)}
function ba(a,b){b.result&&(O(b.result.href,b.result.query).minimized=b.minimized)}function ca(a,b){Y(b.url)}function Y(a){chrome.tabs.getAllInWindow(null,function(b){for(var c=0;c<b.length;c++)if(b[c].url==a){chrome.tabs.update(b[c].id,{selected:!0});return}chrome.tabs.create({url:a,selected:!0})})}
function da(a,b){try{var c=new XMLHttpRequest;c.open("GET",b.url,!0);c.onreadystatechange=function(){4==this.readyState&&a.postMessage({content:this.responseText})};c.send()}catch(d){a.postMessage({content:""})}}
function V(a,b){if("running"==b.title){var c=U;c.stop();c.step_=1;c.lastInterval_=window.setInterval(y(c.setImage_,c,a),300)}else U.stop(),chrome.pageAction.setIcon({tabId:a,path:"images/page-action-"+((b.active?"active":"inactive")+".png")});c=chrome.i18n.getMessage("qs_page_action_"+(b.title||(b.active?"active":"inactive")));chrome.pageAction.setTitle({tabId:a,title:c});chrome.pageAction.show(a)}
function W(a,b,c){var d=chrome.i18n.getMessage("direction");Z(a,"jquery_do_not_compile.js",function(){chrome.tabs.insertCSS(a,{file:"in-document_"+d+"_css.css"},function(){Z(a,b,c)})})}function Z(a,b,c){chrome.tabs.executeScript(a,{file:b},function(){c()})}function X(a,b){W(a,"in-document-message_content_script.js",function(){chrome.tabs.sendRequest(a,{text:b})})}chrome.extension.onConnect.addListener(function(a){a.onMessage.addListener(function(b){if(T[a.name])T[a.name](a,b)})});
chrome.pageAction.onClicked.addListener(function(a){var b=chrome.extension.getURL("about.html");0!=a.url.indexOf("chrome")&&-1==a.url.indexOf("chrome.google.com/extensions")||a.url==b?chrome.tabs.sendRequest(a.id,{toggle:!0}):Y(b)});window.localStorage&&!window.localStorage.welcome&&(window.localStorage.enableGen204Logging="false",chrome.tabs.getSelected(null,function(a){chrome.tabs.update(a.id,{url:chrome.extension.getURL("about.html")})}));
window.setInterval(function(){window.localStorage&&!window.localStorage.welcome&&(window.localStorage.welcome="true")},6E5);
