//@ sourceMappingURL=error_tracker.map
// Generated by CoffeeScript 1.6.1
(function() {

  BH.Lib.ErrorTracker = (function() {

    ErrorTracker.prototype.key = "$ERROR_TRACKER_ID$";

    function ErrorTracker(tracker) {
      tracker.configure({
        api_key: this.key,
        onerror: true
      });
    }

    return ErrorTracker;

  })();

}).call(this);
