// Generated by CoffeeScript 1.6.1
(function() {

  BH.Lib.GoogleUserInfo = (function() {

    function GoogleUserInfo() {}

    GoogleUserInfo.prototype.fetch = function(callbacks) {
      return chrome.identity.getAuthToken({
        'interactive': true
      }, function(token) {
        if (token != null) {
          return $.ajax({
            url: "https://www.googleapis.com/oauth2/v3/userinfo",
            dataType: 'json',
            headers: {
              "Authorization": "OAuth " + token
            },
            success: function(data) {
              if (data.sub != null) {
                return callbacks.success(data);
              } else {
                return callbacks.error();
              }
            },
            error: function(data) {
              if (callbacks.errors) {
                return callbacks.error();
              }
            }
          });
        } else {
          $('.login_spinner').hide();
          return alert('Please sign into Chrome before continuing');
        }
      });
    };

    GoogleUserInfo.prototype.revoke = function() {
      return chrome.identity.getAuthToken(function(token) {
        $.get("https://accounts.google.com/o/oauth2/revoke?token=" + token);
        return chrome.identity.removeCachedAuthToken({
          token: token
        }, function() {});
      });
    };

    return GoogleUserInfo;

  })();

}).call(this);
