// Generated by CoffeeScript 1.6.1
(function() {

  BH.Lib.ImageData = {
    base64: function(url, callback) {
      var img,
        _this = this;
      img = new Image();
      img.src = url;
      return img.onload = function() {
        var canvas, ctx, dataURL;
        canvas = document.createElement("canvas");
        ctx = canvas.getContext("2d");
        ctx.drawImage(img, 16, 16);
        dataURL = canvas.toDataURL("image/png");
        return callback(dataURL);
      };
    }
  };

}).call(this);
