// Generated by CoffeeScript 1.6.1
(function() {

  BH.Init.MailingList = (function() {

    function MailingList(options) {
      this.syncStore = options.syncStore;
    }

    MailingList.prototype.prompt = function(callback) {
      var _this = this;
      return this.syncStore.get(['mailingListPromptTimer', 'mailingListPromptSeen'], function(data) {
        var mailingListPromptSeen, mailingListPromptTimer;
        mailingListPromptTimer = data.mailingListPromptTimer || 5;
        mailingListPromptSeen = data.mailingListPromptSeen;
        if (mailingListPromptSeen == null) {
          if (mailingListPromptTimer === 1) {
            callback();
            _this.syncStore.remove('mailingListPromptTimer');
            return _this.syncStore.set({
              mailingListPromptSeen: true
            });
          } else {
            return _this.syncStore.set({
              mailingListPromptTimer: mailingListPromptTimer - 1
            });
          }
        }
      });
    };

    return MailingList;

  })();

}).call(this);
