// Generated by CoffeeScript 1.6.1
(function() {

  BH.Init.Persistence = (function() {

    function Persistence(config) {
      this.config = config != null ? config : {};
    }

    Persistence.prototype.tag = function() {
      if (this.config.localStore == null) {
        throw "localStore requied";
      }
      return this.tagPersistence || (this.tagPersistence = new BH.Persistence.Tag({
        localStore: this.config.localStore
      }));
    };

    Persistence.prototype.remote = function(authId) {
      if (this.config.ajax == null) {
        throw "Ajax requied";
      }
      if (this.config.state == null) {
        throw "State required";
      }
      authId = authId || user.get('authId');
      this.remotePersistence || (this.remotePersistence = new BH.Persistence.Remote(authId, this.config.ajax, this.config.state));
      if (authId != null) {
        this.remotePersistence.updateAuthId(authId);
      }
      return this.remotePersistence;
    };

    return Persistence;

  })();

}).call(this);
