// Generated by CoffeeScript 1.6.1
(function() {

  BH.Init.TagFeature = (function() {

    function TagFeature(options) {
      this.syncStore = options.syncStore;
    }

    TagFeature.prototype.announce = function(callback) {
      if (callback == null) {
        callback = function() {};
      }
      return this.syncStore.get('tagInstructionsDismissed', function(data) {
        var tagInstructionsDismissed;
        tagInstructionsDismissed = data.tagInstructionsDismissed || false;
        if (!tagInstructionsDismissed) {
          return callback();
        }
      });
    };

    TagFeature.prototype.prepopulate = function(callback) {
      var _this = this;
      return this.syncStore.get('tagInstructionsDismissed', function(data) {
        var tagInstructionsDismissed;
        tagInstructionsDismissed = data.tagInstructionsDismissed || false;
        return persistence.tag().fetchTags(function(tags) {
          if (!tagInstructionsDismissed && tags.length === 0) {
            return callback();
          }
        });
      });
    };

    return TagFeature;

  })();

}).call(this);
