function setScreenshotUrl(){if(window.localStorage.theme!=1&&window.localStorage.theme!=2)window.localStorage.theme=2,document.body.background="bgM.bmp",document.body.style.backgroundAttachment="fixed";else if(window.localStorage.theme==1)document.body.background="bg.bmp",document.body.style.backgroundAttachment="";else if(window.localStorage.theme==2)document.body.background="bgM.bmp",document.body.style.backgroundAttachment="fixed";var m=null;chrome.tabs.getSelected(null,function(a){m=a.id});var o=
document.getElementsByTagName("body")[0],i=document.createElement("table"),n=document.createElement("tbody"),p=parseInt(148),k=0;chrome.windows.getAll({populate:!0},function(a){for(var b=0;b<a.length;b++){for(var c=0;c<a[b].tabs.length;c++){if(k%3==0)var i=document.createElement("tr");var l=document.createElement("td");l.className+="specialBorder";l.id=a[b].tabs[c].id+"cell";var g=document.createElement("div");g.style.position="relative";g.style.overflow="hidden";g.style.height=p+"px";g.style.width=
"215px";g.id=a[b].tabs[c].id+"div";var h=document.createElement("div");h.style.overflow="hidden";h.style.width="206px";h.style.height="17px";h.style.backgroundColor="transparent";if(window.localStorage.theme!=1&&window.localStorage.theme!=2)window.localStorage.theme=2,h.style.color="#606060";else if(window.localStorage.theme==1)h.style.color="black";else if(window.localStorage.theme==2)h.style.color="#606060";h.className+="fixedfont";var e=a[b].tabs[c].favIconUrl,d=document.createElement("img");d.src=
e?e:"favicon.png";d.width=12;d.height=12;e=a[b].tabs[c].url.search("exposeDisplay.html")>0?document.createTextNode("  Tab Expose Tab Selection Window"):document.createTextNode("  "+a[b].tabs[c].title);h.appendChild(d);h.appendChild(e);d=document.createElement("img");d.className+="myss";if(chrome.extension.getBackgroundPage().getSs(a[b].tabs[c].id))a[b].tabs[c].url.search("youtube.com/watch")>0?(e=a[b].tabs[c].url.match("[\\?&]v=([^&#]*)"),d.src="http://img.youtube.com/vi/"+e[1]+"/0.jpg"):d.src=a[b].tabs[c].url.search("exposeDisplay.html")>
0?"tabExpose.png":chrome.extension.getBackgroundPage().getSs(a[b].tabs[c].id);else if(a[b].tabs[c].url.search("youtube.com")>0){if(d.src="youtube.png",a[b].tabs[c].url.search("youtube.com/watch")>0)e=a[b].tabs[c].url.match("[\\?&]v=([^&#]*)"),d.src="http://img.youtube.com/vi/"+e[1]+"/0.jpg"}else if(a[b].tabs[c].url.search("chrome.google.com/extensions")>0){if(d.src="chromeExtension.png",a[b].tabs[c].url.search("chrome.google.com/extensions/detail")>0)d.src="galleryDetail.png"}else if(a[b].tabs[c].url==
"chrome://extensions/")d.src="extension.png";else if(a[b].tabs[c].url.search("exposeDisplay.html")>0)d.src="tabExpose.png";else if(a[b].tabs[c].url.search("chrome.google.com/webstore")>0){if(d.src="webStore.png",a[b].tabs[c].url.search("chrome.google.com/webstore/detail")>0)d.src="storeDetail.png"}else d.src=a[b].tabs[c].url.search("google.com/search?")>0?"googleSearch.png":a[b].tabs[c].url.search("://newtab")>0?"newtab.png":"http://open.thumbshots.org/image.aspx?url="+a[b].tabs[c].url;d.width=209;
d.height=122;d.style.zIndex="-1";e=document.createElement("div");e.style.position="absolute";e.style.top="0";e.style.left="0";e.style.height="100%";e.style.width="100%";e.style.zIndex="50";var j=document.createElement("div");j.style.position="absolute";j.style.top="1";j.style.right="1";j.style.height=12;j.style.width=12;j.style.zIndex="100";j.style.backgroundColor="transparent";var f=document.createElement("img");f.id=a[b].tabs[c].id;f.src="close.png";f.width=13;f.height=13;f.style.zIndex="100";f.style.cssFloat=
"right";j.appendChild(f);f.onmouseover=function(){this.src="close2.png"};f.onmouseout=function(){this.src="close.png"};f.onclick=function(){chrome.tabs.remove(parseInt(this.id));var a=document.getElementById(this.id+"cell");a.parentNode.removeChild(a)};e.id=a[b].tabs[c].id;e.onclick=function(){chrome.tabs.update(parseInt(this.id),{selected:!0})};if(a[b].tabs[c].id==m)myHereDiv=document.createElement("div"),myHereDiv.style.position="absolute",myHereDiv.style.bottom="5%",myHereDiv.style.left="50%",
myHereDiv.style.marginLeft="-69px",myHereDiv.style.height=30,f=document.createElement("img"),f.src="here.png",f.height=30,myHereDiv.appendChild(f);g.appendChild(h);g.appendChild(d);g.appendChild(e);g.appendChild(j);a[b].tabs[c].id==m&&g.appendChild(myHereDiv);l.appendChild(g);i.appendChild(l);k++;k%3==0&&n.appendChild(i)}k%3!=0&&n.appendChild(i)}});i.appendChild(n);o.appendChild(i);i.setAttribute("border","0");i.setAttribute("align","left");i.style.marginRight="15px";i.setAttribute("cellSpacing",
"10")}function bgSet(){if(document.body)if(window.localStorage.theme!=1&&window.localStorage.theme!=2)window.localStorage.theme=2,document.body.background="bgrd.jpg";else if(window.localStorage.theme==1)document.body.background="bg.bmp";else if(window.localStorage.theme==2)document.body.background="bgrd.jpg"};