// Generated by CoffeeScript 1.3.3
var ToggleCommand;

TabState.prototype.send = function(message, data) {
  if (data == null) {
    data = {};
  }
  return chrome.tabs.sendRequest(this.tab, [message, data]);
};

TabState.prototype.bundledScriptURI = function() {
  return chrome.extension.getURL('livereload.js');
};

LiveReloadGlobal.isAvailable = function(tab) {
  return true;
};

LiveReloadGlobal.initialize();

ToggleCommand = {
  invoke: function() {},
  update: function(tabId) {
    var status;
    status = LiveReloadGlobal.tabStatus(tabId);
    chrome.browserAction.setTitle({
      tabId: tabId,
      title: status.buttonToolTip
    });
    return chrome.browserAction.setIcon({
      tabId: tabId,
      path: status.buttonIcon
    });
  }
};

chrome.browserAction.onClicked.addListener(function(tab) {
  LiveReloadGlobal.toggle(tab.id);
  return ToggleCommand.update(tab.id);
});

chrome.tabs.onSelectionChanged.addListener(function(tabId, selectInfo) {
  return ToggleCommand.update(tabId);
});

chrome.tabs.onRemoved.addListener(function(tabId) {
  return LiveReloadGlobal.killZombieTab(tabId);
});

chrome.extension.onRequest.addListener(function(_arg, sender, sendResponse) {
  var data, eventName;
  eventName = _arg[0], data = _arg[1];
  switch (eventName) {
    case 'status':
      LiveReloadGlobal.updateStatus(sender.tab.id, data);
      return ToggleCommand.update(sender.tab.id);
    default:
      return LiveReloadGlobal.received(eventName, data);
  }
});
