// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Collections.Visits = (function(_super) {

    __extends(Visits, _super);

    function Visits() {
      return Visits.__super__.constructor.apply(this, arguments);
    }

    Visits.prototype.destroyAll = function(options) {
      while (this.length > 0) {
        if (this.at(0)) {
          this.at(0).destroy();
        }
      }
      if (options != null) {
        return options.success();
      }
    };

    Visits.prototype.toTemplate = function(start, end) {
      var i, model, visits, _i, _j, _len, _ref;
      visits = [];
      if ((start != null) && (end != null)) {
        for (i = _i = start; start <= end ? _i < end : _i > end; i = start <= end ? ++_i : --_i) {
          if (this.models[i] != null) {
            visits.push(this.models[i].toTemplate());
          }
        }
      } else {
        _ref = this.models;
        for (_j = 0, _len = _ref.length; _j < _len; _j++) {
          model = _ref[_j];
          visits.push(model.toTemplate());
        }
      }
      return {
        visits: visits
      };
    };

    return Visits;

  })(Backbone.Collection);

}).call(this);
