// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Collections.Weeks = (function(_super) {

    __extends(Weeks, _super);

    function Weeks() {
      return Weeks.__super__.constructor.apply(this, arguments);
    }

    Weeks.include(BH.Modules.I18n);

    Weeks.prototype.model = BH.Models.Week;

    Weeks.prototype.initialize = function(attrs, options) {
      this.chromeAPI = chrome;
      return this.settings = options.settings;
    };

    Weeks.prototype.toTemplate = function() {
      var model, weeks;
      weeks = (function() {
        var _i, _len, _ref, _results;
        _ref = this.models;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          model = _ref[_i];
          _results.push(model.toTemplate());
        }
        return _results;
      }).call(this);
      return {
        weeks: weeks
      };
    };

    Weeks.prototype.reload = function(startingDay) {
      var i, _i, _len, _ref;
      this.reset();
      _ref = _.range(10);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        i = _ref[_i];
        this.add({
          date: moment(new Date()).past(startingDay, i)
        }, {
          settings: this.settings
        });
      }
      return this.trigger('reloaded');
    };

    return Weeks;

  })(Backbone.Collection);

}).call(this);
