/* Copyright (C) Sergey Barbushin, 2013. All Rights Reserved.
 * This file can be used only within Google Chrome extension "PHP Console" installed from https://chrome.google.com/webstore/detail/php-console/nfhmhhlpfleoednkpnnnkolmclajemef
 * Unauthorized copying and using of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Sergey Barbushin <barbushin@gmail.com>, June 2013
 */
window.app=new function(){function k(a,e,c){p.getServer(e,function(b){var v={"php-console-client":p.protocol};(b=n.j(b))&&(b=b.o())&&(v.auth=b);d[0]!=l[2][0]&&(a=1);var f=g.f[e]||!1,q=(f?"https":"http")+"://"+e,h=btoa(JSON.stringify(v));chrome.cookies.get({url:q,name:t},function(e){!e||e.value!=h||f&&e.secure!=f?chrome.cookies.set({url:q,name:t,secure:f,value:h},function(){c?c(!0):chrome.tabs.reload(a,{bypassCache:!0})}):c()})})}function m(a,e,c){var l=w[e];p.getServer(g.a(l),function(b){r.l(l,{__PHP_Console:{eval:{data:a,
signature:n.j(b).p(a)},getBackData:{tabId:e}}},c,c)})}function x(a,e,c,l){d[2]!=b[0]&&(e=a);c!=p.protocol&&g.m({tabId:a,protocol:c});w[a]=e;e=g.a(e);var f=!1;u[e]||(u[e]=!0,r.addListener(e),f=!0);k(a,e,function(e){id=v++;h.e[a]=id;l(id,f||e)})}var h=this,w={},u={},y=!1,p=null,n=null,d=chrome.runtime,f=d.getManifest(),g=null,r=null,t="php-console-client",b="history",a=null,e=/^https:\/\//i,c=d.getURL("manifest.json"),l=["eval","console","notify"],v=0;this.e={};this.getOptions=function(){return p};
this.k=function(a,e){e._id=h.e[a];chrome.tabs.sendMessage(a,e)};this.getActiveTab=function(a){chrome.tabs.query({currentWindow:!0,active:!0},function(e){var c=e[0].id;a(c,g.a(g.h[c]?g.h[c]:e[0].url))})};chrome.extension.onMessage.addListener(function(a,c,l){if(a._getConsolePack){c=a.id;var b=g.i[c];if(b&&g.i[c])return delete g.i[c],l({pack:b}),!0}else{if(a._registerTab){var v=a.url;x(c.tab.id,v,a.protocol,function(a,c){l({id:a,url:g.f[g.a(v)]&&!e.exec(v)?v.replace("http://","https://"):c?v:""})});
return!0}if(a._setPassword)h.getActiveTab(function(e,c){n.s(c,a.password);k(e,c);chrome.tabs.reload(e)});else if(a._logout)h.getActiveTab(function(a,e){n.n(e);k(a,e);chrome.tabs.reload(a)});else if(a._evalCode)return p.evalClearConsole&&h.k(a.tabId,{_clearConsole:!0}),m(a.code,a.tabId,l),!0}});p=new B(function(e){d=d.id;n=new C(e);a=new D(e);g=new E(e,n,a,h);r=new F(g);c=c.substr(19);var l=parseFloat(/^\d+\.\d+/.exec(f.version)[0]);chrome.extension.inIncognitoContext||e.version==l||(e.version?2.9>=
e.version?(y=!0,chrome.tabs.onRemoved.addListener(function(){y&&(y=!1,e.version=l,a.d({type:"update",subject:"PHP Console MEGA Update",permanent:!0,data:"\u271a Dump any type variable\n\u271a Execute PHP code remotely\n\u271a Protect access by password\n\u271a Group console logs by request\n\u271a New communication protocol\n\u271a Jump to error file:line in your text editor",openUrlOnClose:"https://github.com/barbushin/php-console/wiki/PHP-Console-v3-Release-(November-2013)",buttons:[{title:"IMPORTANT: PHP Console server library must be updated",
url:"https://github.com/barbushin/php-console/wiki/PHP-Console-v3-Release-(November-2013)"},{title:"Changelog & server library update instructions",url:"https://github.com/barbushin/php-console/wiki/PHP-Console-v3-Release-(November-2013)",icon:"img/right.png"}]}))})):e.version=l:(a.d({type:"update",subject:f.name+" installed",permanent:!0,data:"To use PHP Console on your server you need to install PHP Console server library.",openUrlOnClose:"https://github.com/barbushin/php-console#php-console-server-library",
buttons:[{title:"PHP Console server library Installation & Usage Guide",url:"https://github.com/barbushin/php-console#php-console-server-library",icon:"img/right.png"}]}),e.version=l),c[1]!="force"[0]&&(e={}))})};document.addEventListener("DOMContentLoaded",window.app,!1);
function C(k){function m(x,h){k.updateServer(x,{auth:h},null,!0)}this.r=function(k){var h=k.auth;h&&m(k.domain,{publicKey:h.publicKey,isSuccess:h.isSuccess})};this.j=function(k){var h=k.auth;if(h.publicKey&&h.hash)return new G(k.domain,h.publicKey,h.hash)};this.s=function(k,h){m(k,{hash:window.CryptoJS.SHA256(h+"NeverChangeIt:)").toString()})};this.n=function(k){m(k,{hash:null})}}
function G(k,m,x){this.domain=k;this.b=m;this.hash=x;this.getAuthToken=function(){if(this.hash&&this.b)return window.CryptoJS.SHA256(this.hash+this.b).toString()};this.p=function(k){if(this.hash&&this.b)return window.CryptoJS.SHA256(this.hash+this.b+k).toString()};this.o=function(){var k=this.getAuthToken();if(k&&this.b)return{publicKey:this.b,token:k}}}
function F(k){function m(b,a){for(var e in b)if(b[e].name==a)return b[e].value;return null}function x(b,a,e,c,l){var v=b||!1;v||(b={tabId:0>=c?null:c,redirectUrl:u(e,l),url:e,domain:k.a(e)});if(a){n[b.domain]=b.url;a=JSON.parse(a);if(a.isPostponed){t.push(b);h(a.id,b);return}for(var d in a)b[d]=a[d];a.getBackData&&a.getBackData.tabId&&(b.tabId=+a.getBackData.tabId);b.sourcesBasePath&&(b.sourcesBasePath=k.c(b.sourcesBasePath));if(b.messages&&b.messages.length)for(d in b.messages)a=b.messages[d],a.redirectUrl=
b.redirectUrl,a.url=b.url,a.tabId=b.tabId,a.basePath=b.sourcesBasePath,a.isLocal=b.isLocal,a["class"]?a.tags=[a["class"]]:"debug"!=a.type||a.tags||(a.tags=["debug"]),a.file&&f.exec(a.file)&&(a.file="terminal")}b.tabId&&chrome.tabs.get(b.tabId,function(a){b.tabUrl=a.url;v||t.push(b);b.redirectUrl||(a=t.slice(0),t=[],k.q(a))})}function h(b,a){p.l(a.url,{__PHP_Console:{getPostponedResponse:b}},function(e){x(a,e)})}function w(b){var a=k.a(b.url),e=m(b.responseHeaders,d);(n[a]==b.url||e)&&x(null,e,b.url,
b.tabId,m(b.responseHeaders,"Location"))}function u(b,a){a&&!g.exec(a)&&(a=(r.exec(b)||[b])[0]+a);return a}function y(b,a){var e=[],c;for(c in b){var l=a?a+"["+c+"]":c,v=b[c];e.push("object"==typeof v?y(v,l):encodeURIComponent(l)+"="+encodeURIComponent(v))}return e.join("&")}var p=this,n={},d="PHP-Console",f=/EvalProvider.php.*?eval/i,g=/^http/i,r=/^(.+[/\\])/,t=[];this.l=function(b,a,e,c){try{var l=new XMLHttpRequest;l.open("POST",b,!0);l.setRequestHeader("Content-type","application/x-www-form-urlencoded");
l.onreadystatechange=function(){4==l.readyState&&200==l.status&&e&&e(l.responseText)};l.send(y(a))}catch(v){c&&c()}};this.addListener=function(b){chrome.webRequest.onHeadersReceived.addListener(w,{urls:["*://"+b+"/*"],types:["main_frame","sub_frame","xmlhttprequest","other"]},["responseHeaders"])}}
function E(k,m,x,h){function w(a,c){var l=!1,b=setInterval(function(){chrome.tabs.get(a,function(d){"complete"==d.status&&!l&&h.e[a]&&(l=!0,clearInterval(b),c())})},100)}function u(a,c){var l=c.ignoreErrors,b=c.ignoreDebug,d={},f=[],g;for(g in a){var h=!1,s=a[g];if("debug"==s.type){if("object"==typeof s.tags)for(var n in s.tags){var q=s.tags[n];if("undefined"!=typeof b[q]){if(b[q]){h=!0;break}}else d[q]||(d[q]=!0)}}else"error"==s.type&&l[s["class"]]&&(h=!0);h||f.push(s)}l=Object.keys(d);if(l.length){l.sort();
d={};h=[];s=[];for(q in b)b[q]?h.push(q):s.push(q);for(g=0;20>g;g++)if(q=h.shift())d[q]=!0;else if(q=l.shift()||s.shift())d[q]=!1;else break;k.updateServer(c.domain,{ignoreDebug:d})}return f}function y(a){if("eval_result"==a.type){var c=[];a.output&&c.push(["%c output ","color: white; background: black",a.output]);c.push(["%c return ","color: white; background: black",a["return"]]);a.time&&k.evalShowTime&&c.push(["%c time ","color: white; background: black",a.time])}else if(c=["%c "+a.tags.join(".")+
" ","color: white; background: "+("debug"==a.type?"blue":"red"),a.data],a.path||a.trace)c.push("-"),a.path&&c.push(a.path+(a.line?":"+a.line:"")),a.trace&&c.push("\n"+a.trace);a.args=c}function p(a){if(a.trace){var c=[],l;for(l in a.trace){var b="#"+(+l+1)+" ",d=a.trace[l];d.file?(b+=n(a.basePath,d.file),d.line&&(b+=":"+d.line)):b+="[internal call]";d.call&&(b+=" - "+d.call);c.unshift(b)}a.trace=c.join("\n")}a.file&&(a.path=n(a.basePath,a.file))}function n(e,c){c=a.c(c);return e&&c.substr(0,e.length)==
e?c.substr(e.length):c}this.f={};this.h={};var d={},f={},g={},r=RegExp("\\\\","g"),t=/:\/\/([^:/]+)/,b=/^\w+:\/\/.*?(\/.*\.(js|htm|html))($|\?)/,a=this;this.c=function(a){return a.replace(r,"/")};this.m=function(a){var c=a.tabId;if(a.protocol){var b="logo_16.png",d="options/layout.html",f="PHP Console is active on server.";a.protocol!=k.protocol?(b="logo_16_fail.png",d="wrong_protocol.html",f="Wrong version of PHP Console server. Click on this icon to get update instructions."):a.auth&&(a.isEvalEnabled?
(b="terminal_16.png",f="PHP Console eval is enabled on server. Click on this icon to access eval & options form.",d="terminal/popup.html"):a.auth.isSuccess?(f="PHP Console is active on server protected by password. Click on this icon to see options.",d="logout/popup.html"):(b="key_16.png",f="PHP Console authorization required. Click on this icon to see authorization form.",d="auth/popup.html"));w(c,function(){chrome.pageAction.setTitle({tabId:c,title:f});chrome.pageAction.setIcon({tabId:c,path:"img/"+
b});chrome.pageAction.setPopup({tabId:c,popup:d});chrome.pageAction.show(c)})}else chrome.pageAction.hide(c)};a.q=function(e){var c=[],b=e[e.length-1];"undefined"!=typeof b.isSslOnlyMode&&(a.f[b.domain]=b.isSslOnlyMode);a.h[b.tabId]=b.url;a.m(b);b.protocol==k.protocol&&(m.r(b),b.docRoot&&(d[b.domain]=a.c(b.docRoot)),b.sourcesBasePath&&(f[b.domain]=a.c(b.sourcesBasePath)),b.isLocal&&(g[b.domain]=b.isLocal),k.getServer(b.domain,function(a){for(var d in e){var f=e[d];if(f.messages){var g=u(f.messages,
a),n=[],s=[],t=!1,q=!1,r;for(r in g){var m=g[r];p(m);var z="eval_result"==m.type,z=z|(k.consoleErrors&&"error"==m.type);if(z|=k.consoleDebug&&"debug"==m.type)"error"==m.type?t=!0:"eval_result"==m.type&&(q=!0),y(m),n.push(m);z=!1;z|=k.notifyErrors&&"error"==m.type;z|=k.notifyDebug&&"debug"==m.type;(z|="protocol_error"==m.type)&&s.push(m)}if(n.length){g=[];if(q)for(r in m=["debug","eval_result","error"],m)for(var A in n)n[A].type==m[r]&&g.push(n[A]);c.push({url:f.url,redirectUrl:f.redirectUrl,groupName:f.redirectUrl?
f.url+" --\x3e "+f.redirectUrl:f.url,collapse:!q&&!t&&(f.redirectUrl||k.consoleCollapseNoErrors),messages:g.length?g:n})}if(s.length&&!q){g=[];for(r in s)"error"==s[r].type&&(g.push(s[r]),delete s[r]);for(r in s)"error"!=s[r].type&&g.push(s[r]);x.g(g)}}}c.length&&w(b.tabId,function(){h.k(b.tabId,{_handleConsolePacks:!0,packs:c})})}))};chrome.extension.onMessage.addListener(function(e,c){if(e._handleJavascriptError){var l=e.text,h=e.url,m=e.line,r=c.tab.id;if(k.notifyJavaScriptErrors){if(l){var l=
l.replace(/^Uncaught /g,""),t=/(.+): *(.+)/.exec(l);if(t)var p="JavaScript "+t[1],l=t[2];else p="JavaScript error"}else l="... see details in JavaScript Console",p="JavaScript unknown error";var s=!1,u=h;if(u){var q=a.a(h);(t=b.exec(h))&&d[q]&&(h=d[q]+t[1],s=g[q],f[q]&&(u=n(f[q],h)))}x.d({tabId:r,type:"js_error",subject:p,data:l,file:h,line:m,path:u,isLocal:s},!0)}}});this.a=function(a){return t.exec(a)[1]}}
function D(k){function m(a,b){b=b||"";if("object"==typeof a&&null!==a){var c="",d;for(d in a){var f="";f="object"==typeof a[d]&&null!==a[d]?(f=m(a[d],b+"  "))?"\n"+f:-1!=d.indexOf(":")?"{}":"[]":a[d]+"\n";c=c+b+d+": "+f}return c}return b+a+"\n"}function x(a,b){if("debug"==b.type)return a.message;var c=a.title+": "+a.message;b.path&&(c+=" - "+b.path+(b.line?":"+b.line:""));b.trace&&(c+="\n"+b.trace);return c}function h(a,b){r++;var c="n"+r,d={type:"basic",buttons:[],priority:"error"==a.type?2:0,iconUrl:t[a.type]?
"img/"+t[a.type]:null,title:a.subject?a.subject:"debug"==a.type?a.tags.join("."):a["class"],message:m(a.data).trim()},f={isPermanent:a.permanent||!1,openUrlOnClose:a.openUrlOnClose||null,buttons:[]};if(a.path){var h=k.notifyJumpToFile&&a.isLocal&&"eval_result"!=a.type&&a.line,p=a.path+(a.line?" "+a.line:"");d.buttons.push({title:50>=p.length?p:"..."+p.substr(-47),iconUrl:h?"img/jump.png":"img/file.png"});f.buttons.push({type:"source",open:h,file:a.file,line:a.line,tabId:a.tabId})}!k.notifyCopyToClipboard||
"error"!=a.type&&"js_error"!=a.type&&"debug"!=a.type||(d.buttons.push({title:"Copy to clipboard",iconUrl:"img/clipboard.png"}),f.buttons.push({type:"copy",text:x(d,a)}));if(a.buttons)for(var w in a.buttons)h=a.buttons[w],d.buttons.push({title:h.title,iconUrl:h.icon||null}),f.buttons.push({type:"link",url:h.url});g[c]=f;f.isPermanent&&setTimeout(function(){g[c]&&(n(c),u(c,!0))},3E4);chrome.notifications.create(c,d,b)}function w(){!f&&k.notifyLifeTime&&(f=setTimeout(function(){u();f=null;Object.keys(g).length&&
w()},1E3*k.notifyLifeTime))}function u(a,b){if(!a)for(var c in g){a=c;break}!a||g[a].permanent&&!b||(delete g[a],chrome.notifications.clear(a,function(){}))}function y(a){var b=a.shift();b&&h(b,function(){y(a)})}function p(){var a=Object.keys(g);if(500<(new Date).getTime()-d)for(var b in a)u(a[b]);d=(new Date).getTime();f&&(clearTimeout(f),f=null)}function n(a){g[a].openUrlOnClose&&chrome.tabs.create({url:g[a].openUrlOnClose,active:!0})}var d=null,f=null,g={},r=1,t={update:"ok.png",js_error:"js_error.png",
error:"error.png",ahtung:"ahtung.png",debug:"info.png"},b=this;chrome.extension.onRequest.addListener(function(a){a.showNotifications?b.g(a.showNotifications):a.showNotification&&b.d(a.message)});b.g=function(a,b){b||p();y(a);w()};b.d=function(a,d){b.g([a],d)};chrome.notifications.onClosed.addListener(function(a,b){g[a]&&n(a);b&&p()});chrome.notifications.onClicked.addListener(function(a){g[a]&&(n(a),delete g[a])});chrome.notifications.onButtonClicked.addListener(function(a,b){if(g[a]){var c=g[a].buttons[b];
if("link"==c.type)chrome.tabs.create({url:c.url,active:!0});else if("source"==c.type)/:\/\//.exec(c.file)?chrome.tabs.create({url:"view-source:"+c.file,active:!0}):c.open&&document.getElementById("debug").setAttribute("src","editor://open/?file="+encodeURIComponent(c.file)+"&line="+encodeURIComponent(c.line));else if("copy"==c.type){var d=document.getElementById("textarea");d.value=c.text;d.select();document.execCommand("Copy",!1,null)}delete g[a]}})}
function B(k){function m(d,f){localStorage[d]="object"==typeof f?JSON.stringify(f):f}function x(d){return function(){return u[d]}}function h(d){return function(f){u[d]=f;m(d,f)}}var w=this;this.protocol=5;var u={version:null,consoleDebug:!0,consoleErrors:!0,consoleCollapseNoErrors:!1,notifyDebug:!0,notifyErrors:!0,notifyJavaScriptErrors:!0,notifyLifeTime:"",notifyCopyToClipboard:!1,notifyJumpToFile:!1,evalClearConsole:!0,evalShowTime:!0},y={auth:{},ignoreErrors:{},ignoreDebug:{}},p=null;this.getServer=
function(d,f,g){(g||p.transaction("servers","readwrite").objectStore("servers")).index("domain").get(d).onsuccess=function(g){g=g.target.result||{};g.domain=d;for(var h in y)"undefined"==typeof g[h]&&(g[h]=y[h]);f(g)}};this.updateServer=function(d,f,g,h){var k=p.transaction("servers","readwrite").objectStore("servers");w.getServer(d,function(b){for(var a in f)if(h&&b[a]&&"object"==typeof f[a])for(var d in f[a])b[a][d]=f[a][d];else b[a]=f[a];b=k.put(b);g&&(b.onsuccess=g)},k)};var n=indexedDB.open("php-console");
n.onupgradeneeded=function(){p=n.result;p.createObjectStore("servers",{keyPath:"domain",autoIncrement:!1}).createIndex("domain","domain",{unique:!0})};n.onsuccess=function(){p=n.result;if("undefined"==typeof localStorage.evalShowTime)for(var d in localStorage)"version"!=d&&delete localStorage[d];for(var f in u)d=localStorage.getItem(f),d="true"==d?!0:"false"==d?!1:null!==d&&"{"==d.charAt(0)&&"}"==d.charAt(d.length-1)?JSON.parse(d):d,null===d?(d=u[f],m(f,d)):u[f]=d,w.__defineGetter__(f,x(f)),w.__defineSetter__(f,
h(f));k(w)}};