// Generated by CoffeeScript 1.6.1
(function() {

  BH.Modules.Url = {
    urlFor: function(key, id, opts) {
      var base, buildBase, route;
      base = 'chrome://history/';
      if (key == null) {
        return base;
      }
      buildBase = function(opts) {
        if (opts != null ? opts.absolute : void 0) {
          return base;
        } else {
          return '';
        }
      };
      route = (function() {
        switch (key) {
          case 'search':
            return "#search/" + id;
          case 'week':
            return "#weeks/" + id;
          case 'day':
            return "#days/" + id;
          case 'tag':
            return "#tags/" + id;
        }
      })();
      return "" + (buildBase(opts)) + route;
    }
  };

}).call(this);
