//@ sourceMappingURL=add_view.map
// Generated by CoffeeScript 1.6.1
(function() {
  var body, container;

  body = document.getElementsByTagName('body')[0];

  container = document.createElement('div');

  container.className = 'chrome-bootstrap';

  container.innerHTML = "<div id=\"BH-add-to-collection\" class=\"overlay transparent\">\n  <div class=\"page\">\n    <h1>Add to Collections</h1>\n    <div class=\"content-area\">\n      <div style=\"width: 300px; overflow: scroll-x;\">\n        " + document.title + "</br>\n        " + window.location.href + "\n      </div>\n      <select id=\"BH-collection-selector\">\n        <option value=\"recipes\">Recipes</option>\n        <option value=\"auto\">Auto</option>\n        <option value=\"technology\">Technology</option>\n        <option value=\"read later\">Read later</option>\n      </select>\n    </div>\n    <div class=\"action-area\">\n      <div class=\"action-area-right\">\n        <div class=\"button-strip\">y\n          <button id=\"BH-cancel\">Cancel</button>\n          <button id=\"BH-add\">Add to Collections(s)</button>\n        </div>\n      </div>\n    </div>\n  </div>\n</div>";

  body.appendChild(container);

  setTimeout(function() {
    document.getElementById("BH-add-to-collection").className = "overlay";
    console.log(localStorage);
    document.getElementById('BH-cancel').addEventListener('click', function() {
      return body.removeChild(container);
    }, false);
    return document.getElementById('BH-add').addEventListener('click', function() {
      body.removeChild(container);
      return chrome.runtime.sendMessage({
        url: window.location.href,
        title: document.title,
        timestamp: new Date().getTime(),
        collection: document.getElementById('BH-collection-selector').value
      });
    }, false);
  }, 0);

}).call(this);
