// Generated by CoffeeScript 1.6.1
(function() {

  BH.Views.Cache = (function() {

    function Cache(options) {
      this.options = options;
      this.settings = this.options.settings;
      this.state = this.options.state;
      this.expire();
    }

    Cache.prototype.expire = function() {
      return this.cache = {
        weeks: {},
        days: {},
        tags: {}
      };
    };

    Cache.prototype.tagsView = function() {
      var tags;
      if (!this.cache.allTags) {
        tags = new BH.Collections.Tags([]);
        this.cache.allTags = new BH.Views.TagsView({
          collection: tags,
          state: this.state
        });
        this.insert(this.cache.allTags.render().el);
      }
      return this.cache.allTags;
    };

    Cache.prototype.tagView = function(id) {
      var tag;
      if (!this.cache.tags[id]) {
        tag = new BH.Models.Tag({
          name: id
        });
        this.cache.tags[id] = new BH.Views.TagView({
          name: id,
          model: tag,
          state: this.state
        });
        this.insert(this.cache.tags[id].render().el);
      }
      return this.cache.tags[id];
    };

    Cache.prototype.weeksView = function() {
      if (this.cache.allWeeks) {
        return this.cache.allWeeks;
      }
      this.cache.allWeeks = new BH.Views.WeeksView({
        collection: new Backbone.Collection()
      });
      this.insert(this.cache.allWeeks.render().el);
      return this.cache.allWeeks;
    };

    Cache.prototype.weekView = function(id) {
      if (this.cache.weeks[id]) {
        return this.cache.weeks[id];
      }
      this.cache.weeks[id] = new BH.Views.WeekView({
        model: new Backbone.Model({
          id: id,
          date: new Date(id)
        }),
        collection: new Backbone.Collection()
      });
      this.insert(this.cache.weeks[id].render().el);
      return this.cache.weeks[id];
    };

    Cache.prototype.dayView = function(id) {
      if (this.cache.days[id]) {
        return this.cache.days[id];
      }
      this.cache.days[id] = new BH.Views.DayView({
        model: new Backbone.Model({
          id: id,
          date: new Date(id)
        }),
        collection: new Backbone.Collection()
      });
      this.insert(this.cache.days[id].render().el);
      return this.cache.days[id];
    };

    Cache.prototype.searchView = function(options) {
      if (this.cache.search || options.expired === true) {
        return this.cache.search;
      }
      this.cache.search = new BH.Views.SearchView({
        model: new Backbone.Model(),
        collection: new Backbone.Collection()
      });
      this.insert(this.cache.search.render().el);
      return this.cache.search;
    };

    Cache.prototype.settingsView = function() {
      if (!this.cache.settings) {
        this.cache.settings = new BH.Views.SettingsView({
          model: this.settings,
          state: this.state
        });
        this.insert(this.cache.settings.render().el);
      }
      return this.cache.settings;
    };

    Cache.prototype.insert = function(html) {
      return $('.mainview').append(html);
    };

    return Cache;

  })();

}).call(this);
