//@ sourceMappingURL=connection_restored_view.map
// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Views.ConnectionRestoredView = (function(_super) {

    __extends(ConnectionRestoredView, _super);

    function ConnectionRestoredView() {
      return ConnectionRestoredView.__super__.constructor.apply(this, arguments);
    }

    ConnectionRestoredView.include(BH.Modules.I18n);

    ConnectionRestoredView.prototype.className = 'connection_restored_view';

    ConnectionRestoredView.prototype.template = BH.Templates['connection_restored'];

    ConnectionRestoredView.prototype.events = {
      'click .okay': 'okayClicked'
    };

    ConnectionRestoredView.prototype.initialize = function() {
      this.chromeAPI = chrome;
      this.tracker = this.options.tracker;
      return this.attachGeneralEvents();
    };

    ConnectionRestoredView.prototype.render = function() {
      this.$el.html(this.renderTemplate(this.getI18nValues()));
      return this;
    };

    ConnectionRestoredView.prototype.okayClicked = function(ev) {
      ev.preventDefault();
      return this.close();
    };

    ConnectionRestoredView.prototype.getI18nValues = function() {
      return this.t(['prompt_okay_button', 'connection_restored_title', 'connection_restored_description']);
    };

    return ConnectionRestoredView;

  })(BH.Views.ModalView);

}).call(this);
