//@ sourceMappingURL=devices_view.map
// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Views.DevicesView = (function(_super) {

    __extends(DevicesView, _super);

    function DevicesView() {
      return DevicesView.__super__.constructor.apply(this, arguments);
    }

    DevicesView.include(BH.Modules.I18n);

    DevicesView.prototype.className = 'devices_view';

    DevicesView.prototype.template = BH.Templates['devices'];

    DevicesView.prototype.initialize = function() {
      this.chromeAPI = chrome;
      return this.tracker = analyticsTracker;
    };

    DevicesView.prototype.pageTitle = function() {
      return this.t('devices_title');
    };

    DevicesView.prototype.render = function() {
      var html, properties;
      properties = _.extend(this.getI18nValues(), {});
      html = Mustache.to_html(this.template, properties);
      this.$el.append(html);
      return this;
    };

    DevicesView.prototype.getI18nValues = function() {
      var properties;
      properties = this.t(['devices_title', 'search_input_placeholder_text']);
      return properties;
    };

    return DevicesView;

  })(BH.Views.MainView);

}).call(this);
