//@ sourceMappingURL=how_to_tag_view.map
// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Views.HowToTagView = (function(_super) {

    __extends(HowToTagView, _super);

    function HowToTagView() {
      return HowToTagView.__super__.constructor.apply(this, arguments);
    }

    HowToTagView.include(BH.Modules.I18n);

    HowToTagView.prototype.className = 'how_to_tag_view';

    HowToTagView.prototype.template = BH.Templates['how_to_tag'];

    HowToTagView.prototype.events = {
      'click .done': 'doneClicked'
    };

    HowToTagView.prototype.initialize = function() {
      this.chromeAPI = chrome;
      return this.attachGeneralEvents();
    };

    HowToTagView.prototype.render = function() {
      this.$el.html(this.renderTemplate(this.getI18nValues()));
      this.on('open', function() {
        return !(function() {
          var n;
          n = function() {
            var e, t, _i, _len, _results;
            n = document.getElementsByName('quickcast');
            _results = [];
            for (_i = 0, _len = n.length; _i < _len; _i++) {
              e = n[_i];
              t = e.offsetWidth;
              _results.push(e.height = t / 0.91 + 'px');
            }
            return _results;
          };
          n();
          window.onresize = n;
          return window.addEventListener('message', function(n) {
            if (n.data.indexOf('//quick.as/') !== -1) {
              return window.location.href = n.data;
            }
          }, !1);
        })();
      }, this);
      return this;
    };

    HowToTagView.prototype.doneClicked = function(ev) {
      ev.preventDefault();
      return this.close();
    };

    HowToTagView.prototype.getI18nValues = function() {
      return this.t(['how_to_tag_title', 'prompt_done_button']);
    };

    return HowToTagView;

  })(BH.Views.ModalView);

}).call(this);
