//@ sourceMappingURL=sign_up_view.map
// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BH.Views.SignUpView = (function(_super) {

    __extends(SignUpView, _super);

    function SignUpView() {
      return SignUpView.__super__.constructor.apply(this, arguments);
    }

    SignUpView.include(BH.Modules.I18n);

    SignUpView.prototype.className = 'sign_up_view';

    SignUpView.prototype.template = BH.Templates['sign_up'];

    SignUpView.prototype.events = {
      'click .close': 'closeClicked'
    };

    SignUpView.prototype.initialize = function() {
      this.chromeAPI = chrome;
      return this.attachGeneralEvents();
    };

    SignUpView.prototype.render = function() {
      this.$el.html(this.renderTemplate(this.getI18nValues()));
      return this;
    };

    SignUpView.prototype.closeClicked = function(ev) {
      ev.preventDefault();
      return this.close();
    };

    SignUpView.prototype.openClicked = function(ev) {
      ev.preventDefault();
      return this.open();
    };

    SignUpView.prototype.getI18nValues = function() {
      return this.t(['close_button']);
    };

    return SignUpView;

  })(BH.Views.ModalView);

}).call(this);
