// Generated by CoffeeScript 1.6.1
(function() {

  BH.Modules.Worker = {
    worker: function(name, options, callback) {
      var basePath, path, worker;
      basePath = 'scripts/workers';
      path = (function() {
        switch (name) {
          case 'searchSanitizer':
            return "" + basePath + "/search_sanitizer.js";
          case 'rangeSanitizer':
            return "" + basePath + "/range_sanitizer.js";
          case 'domainGrouper':
            return "" + basePath + "/domain_grouper.js";
          case 'timeGrouper':
            return "" + basePath + "/time_grouper.js";
          case 'dayGrouper':
            return "" + basePath + "/day_grouper.js";
          case 'weekGrouper':
            return "" + basePath + "/week_grouper.js";
        }
      })();
      worker = new Worker(path);
      worker.onmessage = function(e) {
        if (e.data.log) {
          return console.log(e.data.log);
        } else {
          callback(e.data);
          return worker.terminate();
        }
      };
      return worker.postMessage(options);
    }
  };

}).call(this);
