//@ sourceMappingURL=tag_announcement.map
// Generated by CoffeeScript 1.6.1
(function() {

  BH.Init.TagAnnouncement = function(callback) {
    return syncStore.get('tagInstructionsDismissed', function(data) {
      var tagInstructionsDismissed;
      tagInstructionsDismissed = data.tagInstructionsDismissed || false;
      if (!tagInstructionsDismissed) {
        return callback();
      }
    });
  };

}).call(this);
